(function (lib, img, cjs, ss) {

var p; // shortcut to reference prototypes
lib.webFontTxtFilters = {}; 

// library properties:
lib.properties = {
	width: 120,
	height: 600,
	fps: 18,
	color: "#CCCCCC",
	opacity: 1.00,
	webfonts: {},
	manifest: [
		{src:"images/_336x280gardener.jpg", id:"_336x280gardener"}
	]
};



lib.ssMetadata = [];


lib.webfontAvailable = function(family) { 
	lib.properties.webfonts[family] = true;
	var txtFilters = lib.webFontTxtFilters && lib.webFontTxtFilters[family] || [];
	for(var f = 0; f < txtFilters.length; ++f) {
		txtFilters[f].updateCache();
	}
};
// symbols:



(lib._336x280gardener = function() {
	this.initialize(img._336x280gardener);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,515,200);


(lib.TEC_logostackrev = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgaA2IAAhpIAPAAIAAAWQALgZAZABIABAAIAAAPIgBAAQgPgBgKAKQgLALAAARIAAA3g");
	this.shape.setTransform(-86.9,100.2,1.483,1.483);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAZA1IgZhVIgYBVIgPAAIgjhpIAQAAIAaBWIAZhWIAOAAIAaBWIAahWIAQAAIgjBpg");
	this.shape_1.setTransform(-5,100.3,1.483,1.483);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgCBAQgFgGAAgNIAAhGIgTAAIAAgMIATAAIAAggIAMAAIAAAgIAWAAIAAAMIgWAAIAABEQAAAHACADQACADAGAAIAMAAIAAANIgNABQgNgBgDgFg");
	this.shape_2.setTransform(-67.5,98.1,1.483,1.483);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AAdBJIAAhCQAAgdgaAAQgMAAgJAJQgJAKAAAOIAAA+IgPAAIAAiRIAPAAIAAA4QAEgIAJgGQAJgFAJAAQAUAAAKAKQAJAKAAAUIAABEg");
	this.shape_3.setTransform(-52.3,97.3,1.483,1.483);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AghApQgNgPAAgaQAAgVALgPQANgTAWAAQAVAAALANQAPAPAAAbIAAAEIhPAAQABAQAIALQAJANAOAAQAaAAAGgbIABAAIAOAAIAAABQgJAmgmAAQgUAAgNgPgAAhgHQgCgOgHgLQgJgLgPABQgMgBgKALQgHALgDAOIBBAAIAAAAg");
	this.shape_4.setTransform(-35.4,100.3,1.483,1.483);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAcBJIAAhCQAAgdgaAAQgMAAgIAJQgJAKgBAOIAAA+IgOAAIAAiRIAOAAIAAA4QAKgTAWAAQAUAAAKAKQAJAKAAAUIAABEg");
	this.shape_5.setTransform(15.8,97.3,1.483,1.483);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AglAmQgMgQAAgWQAAgWAMgPQAOgSAXAAQAYAAAOASQAMAPAAAWQAAAWgMAQQgOASgYAAQgXAAgOgSgAgagdQgJANAAAQQAAARAJAMQAKAPAQAAQAQAAAKgPQAJgMAAgRQAAgQgJgNQgKgOgQABQgQgBgKAOg");
	this.shape_6.setTransform(32.7,100.3,1.483,1.483);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgqAOIAAhEIAPAAIAABEQAAAcAbAAQANAAAIgNQAHgMAAgQIAAg3IAPAAIAABpIgOAAIAAgRQgLAUgWABQgmAAAAgpg");
	this.shape_7.setTransform(115.7,100.5,1.483,1.483);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AghApQgNgPgBgaQAAgVALgPQANgTAXAAQAUAAAMANQAQAPAAAbIAAAEIhPAAQAAAQAIALQAJANAOAAQAZAAAHgbIAAAAIAPAAIAAABQgJAmgmAAQgVAAgMgPgAAggHQAAgOgJgLQgJgLgOABQgMgBgJALQgJALgBAOIA/AAIAAAAg");
	this.shape_8.setTransform(56.1,100.3,1.483,1.483);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgbBJIgIgCIgBAAIAAgNIAKABQAHAAAEgDQACgDAEgJIAFgMIgrhoIAQAAIAgBWIAghWIAPAAIgvB5QgEAOgFAFQgFAEgMABg");
	this.shape_9.setTransform(82.3,103.2,1.483,1.483);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AglAmQgMgQAAgWQAAgWAMgPQAOgSAXAAQAYAAAOASQAMAPAAAWQAAAWgMAQQgOASgYAAQgXAAgOgSgAgagdQgJANAAAQQAAARAJAMQAKAPAQAAQARAAAKgPQAIgMAAgRQAAgQgIgNQgKgOgRABQgQgBgKAOg");
	this.shape_10.setTransform(98.4,100.3,1.483,1.483);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AglAmQgMgQAAgWQAAgWAMgPQAOgSAXAAQAYAAAOASQAMAPAAAWQAAAWgMAQQgOASgYAAQgXAAgOgSgAgagdQgIANAAAQQAAARAIAMQAKAPAQAAQARAAAKgPQAJgMAAgRQAAgQgJgNQgKgOgRABQgQgBgKAOg");
	this.shape_11.setTransform(-102.5,100.3,1.483,1.483);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("ATYBtIAAgjIAcAAIAAAjgAGoBtIAAjZIAVAAIAADZgAzzBtIAAjZICLAAIAAAVIh1AAIAABKIBpAAIAAATIhpAAIAABng");
	this.shape_12.setTransform(1.1,97.3);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgnBzQgZgKgPgTQgOgRgHgXQgGgVAAgYQgBgZAKgYQAKgZAQgPQAQgRAZgKQAagJAaAAQAdAAATAGQAVAHARAKQgIALgEANIgEALIgHAAQgJgPgOgIQgQgKgSAAIgBAAQgcAAgPAbQgPAbAAAvQAAAsATAZQARAYAkAAQAPAAAPgHQAOgIAHgIIAGAEIgGAPIgFAPQgKAIgRAGQgSAFgWABQgiAAgZgLg");
	this.shape_13.setTransform(106.4,56.1,1.483,1.483);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AggB3IAAjtIAPACIARABQAOAAATgDIAADtg");
	this.shape_14.setTransform(80,56.1,1.483,1.483);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AggB3IAAjtIAOACIASABQANAAAUgDIAADtg");
	this.shape_15.setTransform(24.5,56.1,1.483,1.483);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AASC6IgxABIAAl1IAOACIARABIASgBIAOgCIAAF1g");
	this.shape_16.setTransform(7.3,46,1.483,1.483);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgpCzQgjgOgXgXQgXgXgNgjQgNgiAAglQABg1AQgoQAPgnAcgZQAbgZAkgLQAggLAoAAQAPAAANACIAbAFQARAFAJAEQALAEAJAGIgHAbQgCANgCAPIgHAAQgRgZgWgMQgSgLgcAAQgVAAgTAJQgSAKgRAVQgPASgLAgQgKAgAAApQAAApAKAeQALAeAQASQARATATAJQAWAIAUAAQANAAAMgDQANgEALgEQALgFALgIQALgHAIgKIAGAFIgGAWQgDAOgBAKQgpAWg8AAQgqAAghgNg");
	this.shape_17.setTransform(-27.2,46.3,1.483,1.483);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("ABaB5IgjAAIgPABIAAiNIgCgaQgBgLgEgGQgLgPgUAAQgTAAgLATQgKAUAAAiIAAB+IgQgBIgzABIAAjtIAQACIAQABIATgBIAQgCIAAAlIABABQANgVARgLQASgMAXAAQAgAAAUAWQAUAVAAAvIAACZIgQgBg");
	this.shape_18.setTransform(52.6,55.6,1.483,1.483);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgYAbQgLgMAAgPQAAgOALgLQALgMANAAQAPAAAKAMQALALAAAOQAAAQgLALQgKALgPAAQgNAAgLgLg");
	this.shape_19.setTransform(80.2,25.7,1.483,1.483);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgYAbQgLgMAAgPQAAgOALgLQAKgMAOAAQAPAAAKAMQALALAAAOQAAAPgLAMQgKALgPAAQgOAAgKgLg");
	this.shape_20.setTransform(24.4,25.7,1.483,1.483);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AhBBcIAAjjIAJgDIAYgKQAUgKAKgIIADADIAABbIAvgCIABAbIgwgBIAACaQAAAJAGAGQAIAIAOgDQAQgDAPgPIAGACIAAABIgFAXIAAAAQAAADgMAKQgOAMgOAEQgMAEgKAAQhAAAAAhLg");
	this.shape_21.setTransform(114,-19.7,1.483,1.483);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("Ag+BcIAAiMIguAAIAAgaIAuACIAAg/IAJgDIAXgKQAVgKAJgIIAEADIAABbIBpAAIgBAYIhoAAIAACaQAAAJAGAGQAIAIANgDQARgDAPgPIAGACIAAABIgFAXIAAAAQgBADgLAKQgOAMgOAEQgMAEgMAAQg+AAAAhLg");
	this.shape_22.setTransform(89.4,-19.7,1.483,1.483);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AhUB5IAAjsIBHAAIgBAuIABABQAIgUASgQQAWgQAWAAQANAAAPAEIgBABQgVAVgLAgIgCADIgDgBQgHgCgHAAQgWAAgMAPQgMAOAAAUIAACGg");
	this.shape_23.setTransform(29.7,-13.9,1.483,1.483);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AggB2QgXgHgPgOQgQgPgKgZQgKgYAAggQAAgeAJgYQAIgXAQgRQAOgPAWgIQAUgJAYABQAxAAAZAcQAaAcAAA1IAAAPIiMAAQAAATAEASQAEAQAIAPQAIANALAHQANAHARAAQAhAAAkgdIAGACIAAABIgEAXQgQASgdAKQgSAFgcABQgVAAgXgIgAApgVQgBglgIgVQgIgXgTAAQgJAAgIAHQgHAIgEALQgEALgDAPIgDAdIBKAAIAAAAg");
	this.shape_24.setTransform(56,-13.5,1.483,1.483);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AggB2QgXgHgPgOQgSgQgIgYQgKgYAAggQAAgeAJgYQAHgXAQgRQAPgPAVgIQAVgJAXABQAyAAAaAcQAaAdAAA0IAAAPIiNAAQAAATAEASQADAQAJAPQAIANALAHQANAHAQAAQAiAAAkgdIAGACIAAABIgEAXQgQASgdAKQgSAFgcABQgVAAgXgIgAAogVQAAglgJgVQgHgXgUAAQgJAAgHAHQgHAIgEALQgEALgDAPIgDAdIBJAAIAAAAg");
	this.shape_25.setTransform(-3.7,-13.5,1.483,1.483);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AgPB2IgOAAIhEi8IgSgvIAUABIA4gBIA1CrIACAAIAehVIAdhWIAUACIAVgCIgTAsIgYA4IgaBAQgQAsgJAbg");
	this.shape_26.setTransform(-35.6,-13.5,1.483,1.483);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AheC7IAAl1IBXADIBAgBIAmgCQgCALAAAKIACAXIgggCIgggCIgdgCIgUgBIAABmIBWgEIAPApQg8gDgpAAIAACkIA5gBQAfgCAZgDIgBAWIAAAMIABAIg");
	this.shape_27.setTransform(-68.9,-23.6,1.483,1.483);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AggB2QgXgHgQgOQgQgPgKgZQgJgYgBggQABgeAIgYQAJgXAPgRQAOgPAWgIQAVgJAXABQAyAAAZAcQAaAdAAA0IAAAPIiMAAQAAATAEASQAFASAHANQAIANALAHQANAHARAAQAgAAAlgdIAGACIAAABIgEAXQgQASgdAKQgSAFgcABQgWAAgWgIgAApgVQgBglgIgVQgJgXgSAAQgJAAgIAHQgHAIgEALQgEALgDAPIgDAdIBKAAIAAAAg");
	this.shape_28.setTransform(107.6,-76.1,1.483,1.483);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("ABeC6IgnAAIgQABIAAiPIAAgaQgCgLgFgGQgKgNgTAAQgVAAgKARQgKAUAAAiIAACAIgQgBIg3ABIAAl1IAQACIATABIAUgBIAQgCIAACtIABABQANgVASgLQAQgMAXAAQAlAAAUAWQAUAVAAAtIAACbIgQgBg");
	this.shape_29.setTransform(71.6,-86.3,1.483,1.483);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("AgjC6IAAlNIhbAGIAAgsIBZADICkgDIAAAWIAAAWIhYgGIAAFNg");
	this.shape_30.setTransform(32.7,-86.4,1.483,1.483);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-125.7,-114,253.7,228.1);


(lib.sub1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// type
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#6B8A21").s().p("AAAAGQgFAAAAgGIAAAAQAAgFAFAAIAAAAQAGAAAAAFIAAAAQAAAGgGAAg");
	this.shape.setTransform(56.9,99.1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#6B8A21").s().p("AAeApQgEAAAAgEIAAgoQAAgHgCgFQgBgGgDgDQgDgEgFgCQgFgCgFAAQgDAAgFABQgEABgEADIgGAGQgDADgCAEIAAAzQAAAEgDAAIgBAAQgEAAAAgEIAAhLIADgBQAAAAABAAQAAAAABABQAAAAABAAQAAAAAAABQACACAAAEIAAAIQACgEADgDIAGgFIAIgEIAIgBQAIAAAGADQAGACAEAFQAEAFACAGQACAHAAAIIAAApQAAAEgDAAg");
	this.shape_1.setTransform(50.8,95.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#6B8A21").s().p("AgPAmQgHgDgGgGQgFgFgEgIQgDgIAAgIQAAgHADgIQAEgIAFgFQAGgGAHgDQAIgDAHAAQAIAAAIADQAHADAGAGQAGAFADAIQACAIAAAHQAAAJgCAHQgDAIgGAGQgGAFgHADQgIADgIAAQgHAAgIgDgAgMgfQgFADgFAFQgEAEgDAHQgDAGABAGQgBAHADAGQADAGAEAFQAFAFAFADQAHACAFAAQAHAAAFgCQAGgDAFgFQAEgEADgGQADgHgBgHQABgFgDgHQgDgGgEgFQgFgFgGgDQgFgCgHAAQgFAAgHACg");
	this.shape_2.setTransform(41.5,95.6);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#6B8A21").s().p("AAAA4QgCAAgBgDIAAhIQABgEACAAIAAAAQAEAAAAAEIAABIQAAADgEAAgAgEgyQAAgFAEAAQAFAAAAAFQAAAGgFAAQgEAAAAgGg");
	this.shape_3.setTransform(35.1,94);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#6B8A21").s().p("AgQAnQgGgDgEgEQgFgEAAgDQAAgDAFgBQAEAGAHAEIAIADIAHABQAGAAAEgCIAIgDQADgCABgDQACgDAAgDQAAgEgCgDQgBgCgEgCQgEgCgNgDQgNgDgFgBQgFgDgCgDQgDgEAAgGQAAgFADgEQABgFAFgDQAEgDAFgCQAGgBAEAAQAJAAAHACQAHADAEADQACAEAAACQAAABAAAAQAAABAAAAQAAABgBAAQAAABgBAAIgCABQgEgGgFgDQgHgEgJAAQgDAAgEACIgHADQgDACgBADQgCACAAAEQAAADACADIAEAEQAFADALADIAKACIAKACQAEACADAEQACAEAAAGQAAAFgCAEQgCAFgDADQgFADgGACQgFABgIAAQgIAAgIgCg");
	this.shape_4.setTransform(29.6,95.6);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#6B8A21").s().p("AgPAnQgHgDgFgEQgEgEAAgDQABgDAEgBQAEAGAHAEIAIADIAIABQAFAAAFgCIAHgDQACgCACgDQACgDgBgDQABgEgCgDQgCgCgDgCQgFgCgMgDQgNgDgGgBQgEgDgCgDQgDgEAAgGQAAgFADgEQACgFADgDQAFgDAFgCQAFgBAGAAQAIAAAHACQAGADAFADQADAEAAACQAAABgBAAQAAABAAAAQAAABgBAAQAAABgBAAIgCABQgDgGgHgDQgHgEgHAAQgEAAgEACIgHADQgDACgCADQgBACAAAEQAAADABADIAGAEQAEADALADIAKACIAKACQAEACADAEQADAEgBAGQAAAFgBAEQgCAFgFADQgEADgGACQgFABgHAAQgJAAgHgCg");
	this.shape_5.setTransform(22.1,95.6);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#6B8A21").s().p("AgNAmQgIgDgFgFQgFgGgDgHQgDgIAAgJQAAgHADgIQADgHAFgGQAFgGAIgDQAIgDAGAAQAIAAAHACQAGADAGAFQAFAGACAHQADAHAAAJIAAABQAAAAAAAAQgBAAAAAAQgBAAAAABQgBAAgBAAIg/AAQAAAHACAGQADAGAEAFQAFAEAFADQAHACAFAAQAGAAAFgBQAEgBAEgDQAGgEAEgHIACABQABAAAAABQABAAAAAAQAAABAAABQABAAAAABQgBADgEAFQgFAFgGACQgJADgJAAQgHAAgIgDgAAegEQgBgHgCgFQgCgFgEgEQgDgEgGgCQgFgCgGAAQgEAAgGACIgKAGQgEAEgCAFQgDAFgBAHIA7AAIAAAAg");
	this.shape_6.setTransform(14,95.6);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#6B8A21").s().p("AgQAnQgGgDgFgEQgDgEAAgDQgBgDAFgBQAEAGAHAEIAHADIAIABQAGAAAFgCIAGgDQAEgCABgDQABgDAAgDQAAgEgBgDQgCgCgDgCQgFgCgMgDQgNgDgGgBQgEgDgCgDQgDgEAAgGQAAgFACgEQACgFAEgDQAEgDAGgCQAGgBAEAAQAJAAAHACQAGADAEADQAEAEAAACQAAABgBAAQAAABAAAAQAAABgBAAQAAABgBAAIgCABQgEgGgGgDQgGgEgJAAQgDAAgEACIgHADQgDACgCADQgBACAAAEQAAADABADIAGAEQAEADALADIALACIAJACQAFACACAEQACAEABAGQAAAFgCAEQgCAFgFADQgEADgFACQgHABgHAAQgIAAgIgCg");
	this.shape_7.setTransform(5.7,95.6);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#6B8A21").s().p("AgPAmQgHgDgGgGQgGgFgDgIQgCgIAAgIQAAgHACgIQADgIAGgFQAGgGAHgDQAIgDAHAAQAIAAAIADQAHADAGAGQAFAFAEAIQACAIAAAHQAAAJgCAHQgEAIgFAGQgGAFgHADQgIADgIAAQgHAAgIgDgAgLgfQgGADgFAFQgEAEgDAHQgDAGABAGQgBAHADAGQADAGAEAFQAFAFAGADQAFACAGAAQAGAAAHgCQAFgDAFgFQAEgEADgGQADgHgBgHQABgFgDgHQgDgGgEgFQgFgFgFgDQgHgCgGAAQgGAAgFACg");
	this.shape_8.setTransform(67.5,74.6);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#6B8A21").s().p("AgFA6QgEAAAAgEIAAhDIgNAAQgEAAAAgEIAAAAQAAgEAEAAIANAAIAAgIQAAgHACgFQABgGADgDQADgEACgBQAEgCAGAAQAEAAAEABIAFADQABABAAAAQABABAAAAQAAABAAAAQAAABAAAAQAAABAAAAQAAABAAAAQAAAAgBABQAAAAAAAAIgBABIgGgDQgEgCgDAAQgEAAgDABQgCABgCADQgBADAAAEIgBAJIAAAIIAQAAQAEAAAAAEIAAAAQAAAEgEAAIgQAAIAABDQAAAEgDAAg");
	this.shape_9.setTransform(60.4,72.8);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#6B8A21").s().p("AAeApQgEAAAAgEIAAgoQAAgHgCgFQgBgGgDgDQgDgEgFgCQgFgCgFAAQgDAAgFABQgEABgEADIgGAGQgDADgCAEIAAAzQAAAEgDAAIgBAAQgEAAAAgEIAAhLIADgBQAAAAABAAQAAAAABABQAAAAABAAQAAAAAAABQACACAAAEIAAAIQACgEADgDIAGgFIAIgEIAIgBQAIAAAGADQAGACAEAFQAEAFACAGQACAHAAAIIAAApQAAAEgDAAg");
	this.shape_10.setTransform(52.9,74.5);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#6B8A21").s().p("AAAA5QgCAAAAgFIAAhHQAAgEACAAIAAAAQAEAAAAAEIAABHQAAAFgEAAgAgEgxQAAgHAEAAQAFAAAAAHQAAAFgFAAQgEAAAAgFg");
	this.shape_11.setTransform(46.7,73);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#6B8A21").s().p("AgNAmQgHgDgGgFQgFgGgEgHQgCgIAAgJQAAgHADgIQADgHAFgGQAGgGAHgDQAHgDAHAAQAIAAAHACQAGADAFAFQAGAGACAHQADAHAAAJIAAABQAAAAAAAAQgBAAAAAAQAAAAgBABQgBAAgBAAIg/AAQAAAHACAGQADAGAEAFQAFAEAFADQAHACAFAAQAGAAAFgBQAFgBADgDQAGgEAEgHIACABQABAAAAABQABAAAAAAQAAABAAABQAAAAAAABQAAADgEAFQgFAFgGACQgIADgKAAQgHAAgIgDgAAegEQgBgHgCgFQgCgFgEgEQgDgEgGgCQgFgCgGAAQgEAAgGACIgKAGQgDAEgDAFQgDAFgBAHIA7AAIAAAAg");
	this.shape_12.setTransform(37.7,74.6);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#6B8A21").s().p("AgNAmQgIgDgFgFQgGgGgDgHQgCgIAAgJQAAgHADgIQADgHAFgGQAFgGAIgDQAHgDAHAAQAIAAAHACQAGADAGAFQAFAGACAHQADAHAAAJIAAABQAAAAAAAAQgBAAAAAAQgBAAAAABQgBAAgBAAIg/AAQAAAHACAGQADAGAEAFQAFAEAFADQAHACAFAAQAGAAAFgBQAFgBADgDQAGgEAEgHIACABQABAAAAABQABAAAAAAQAAABAAABQAAAAAAABQAAADgEAFQgFAFgGACQgJADgJAAQgHAAgIgDgAAegEQgBgHgCgFQgCgFgEgEQgDgEgGgCQgFgCgGAAQgEAAgGACIgKAGQgEAEgCAFQgDAFgBAHIA7AAIAAAAg");
	this.shape_13.setTransform(28.8,74.6);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#6B8A21").s().p("AgPApQgEAAAAgEIAAhLIADgBQAAAAABAAQAAAAABABQAAAAABAAQAAAAAAABQACACAAAEIAAALIADgJIAFgGQADgDACgBIAHgBQAFAAADACQADACAAADIgBADIgBABQgEgDgGAAQgFAAgDADQgDACgDAFQgCAEgCAHIgBANIAAAjQAAAEgDAAg");
	this.shape_14.setTransform(21.9,74.5);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#6B8A21").s().p("AgFA6QgEAAAAgEIAAhDIgNAAQgEAAAAgEIAAAAQAAgEAEAAIANAAIAAgIQAAgHACgFQABgGADgDQADgEACgBQAEgCAGAAQAEAAAEABIAFADQABABAAAAQABABAAAAQAAABAAAAQAAABAAAAQAAABAAAAQAAABAAAAQAAAAgBABQAAAAAAAAIgBABIgGgDQgEgCgDAAQgEAAgDABQgCABgCADQgBADAAAEIgBAJIAAAIIAQAAQAEAAAAAEIAAAAQAAAEgEAAIgQAAIAABDQAAAEgDAAg");
	this.shape_15.setTransform(16.4,72.8);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#6B8A21").s().p("AgQAoQgFgCgEgDQgEgDgCgEQgBgEAAgFQAAgGADgFQADgFAHgDQAHgBAMgCQAIgCAQAAIABAAIAAgEQAAgGgBgEQgCgFgDgDQgDgDgFgBQgFgCgFAAIgIABQgEABgEADQgGAEgEAGQgEAAAAgEQAAgEAEgEQAFgFAGgCQAIgDAHAAQAIAAAGACQAGACAEAEQAEAEACAGQACAGAAAHIAAAwIgDABQAAAAgBAAQAAAAgBAAQAAAAAAgBQgBAAAAAAQgCgCAAgFIAAgIIgFAHQgDADgEACQgEADgFABQgEABgFAAQgGAAgFgBgAABABQgIABgGADQgFACgDAEQgDADAAAFQAAAEABADIAEAFQADACAEABIAIABQAFAAAFgCQAGgCAEgEQAFgEACgFQACgFAAgGIAAgHIgCAAIgWABg");
	this.shape_16.setTransform(6,74.6);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#6B8A21").s().p("AgPApQgEAAAAgEIAAhLIADgBQAAAAABAAQAAAAABABQAAAAABAAQAAAAAAABQACACAAAEIAAALIADgJIAFgGQADgDACgBIAHgBQAFAAADACQADACAAADIgBADIgBABQgEgDgGAAQgFAAgDADQgDACgDAFQgCAEgCAHIgBANIAAAjQAAAEgDAAg");
	this.shape_17.setTransform(93.8,53.5);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#6B8A21").s().p("AgPAmQgHgDgGgGQgFgFgDgIQgEgIAAgIQAAgHAEgIQADgIAFgFQAGgGAHgDQAHgDAIAAQAIAAAIADQAHADAGAGQAFAFADAIQADAIAAAHQAAAJgDAHQgDAIgFAGQgGAFgHADQgIADgIAAQgIAAgHgDgAgMgfQgGADgEAFQgFAEgCAHQgCAGgBAGQABAHACAGQACAGAFAFQAEAFAGADQAGACAGAAQAGAAAGgCQAHgDAEgFQAEgEADgGQADgHAAgHQAAgFgDgHQgDgGgEgFQgEgFgHgDQgGgCgGAAQgGAAgGACg");
	this.shape_18.setTransform(85.9,53.6);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#6B8A21").s().p("AgFA6QgEAAAAgEIAAhDIgNAAQgEAAAAgEIAAAAQAAgEAEAAIANAAIAAgIQAAgHACgFQABgGADgDQADgEACgBQAEgCAGAAQAEAAAEABIAFADQABABAAAAQAAABABAAQAAABAAAAQAAABAAAAQAAABAAAAQAAABAAAAQAAAAgBABQAAAAAAAAIgBABIgGgDQgEgCgDAAQgEAAgDABIgEAEQgBADAAAEIgBAJIAAAIIAQAAQAEAAAAAEIAAAAQAAAEgEAAIgQAAIAABDQAAAEgDAAg");
	this.shape_19.setTransform(78.8,51.8);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#6B8A21").s().p("AgPApQgEAAAAgEIAAhLIADgBQAAAAABAAQAAAAABABQAAAAABAAQAAAAAAABQACACAAAEIAAALIADgJIAFgGQADgDACgBIAHgBQAFAAADACQADACAAADIgBADIgBABQgEgDgGAAQgFAAgDADQgDACgDAFQgCAEgCAHIgBANIAAAjQAAAEgDAAg");
	this.shape_20.setTransform(70.6,53.5);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#6B8A21").s().p("AgNAmQgIgDgFgFQgGgGgDgHQgCgIAAgJQAAgHADgIQADgHAFgGQAFgGAIgDQAHgDAHAAQAIAAAHACQAGADAGAFQAFAGACAHQADAHAAAJIAAABQAAABgEAAIg/AAQAAAHACAGQADAGAEAFQAFAEAFADQAHACAFAAQAGAAAFgBQAFgBADgDQAGgEAEgHIACABQABAAAAABQABAAAAABQAAAAAAABQAAAAAAABQAAADgEAFQgFAFgGACQgJADgJAAQgHAAgIgDgAAegEQgBgHgCgFQgCgFgEgEQgDgEgGgCQgFgCgGAAQgEAAgGACIgKAGQgEAEgCAFQgDAFgBAHIA7AAIAAAAg");
	this.shape_21.setTransform(63,53.6);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#6B8A21").s().p("AAAAxQgCgCgDgDQgDgDgBgEQgBgFAAgHIAAgvIgKAAQgEAAAAgEIAAAAQAAgEAEAAIAKAAIAAgPQAAgEADAAIABAAQABAAABAAQAAAAABABQAAAAAAABQAAABAAABIAAAPIAWAAQAEAAAAAEIAAAAQAAAEgEAAIgWAAIAAAvQAAAKADAEQACAFAHAAQAFAAADgCQADgCACgDIACAAQAAABAAAAQAAAAABABQAAAAAAABQAAAAAAABQAAACgDADIgFADIgIABQgGAAgDgBg");
	this.shape_22.setTransform(55.7,52.7);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#6B8A21").s().p("AgQAnQgGgDgEgEQgEgEgBgDQAAgDAFgBQAEAGAHAEIAHADIAIABQAGAAAEgCIAHgDQADgCACgDQACgDAAgDQAAgEgCgDQgBgCgEgCQgEgCgNgDQgNgDgFgBQgFgDgCgDQgDgEAAgGQAAgFACgEQACgFAFgDQAEgDAFgCQAGgBAEAAQAJAAAHACQAHADAEADQACAEAAACQAAABAAAAQAAABAAAAQAAABgBAAQAAABgBAAIgCABQgEgGgFgDQgIgEgIAAQgDAAgEACIgHADQgDACgBADQgCACAAAEQAAADACADIAEAEQAFADALADIAKACIAKACQAFACACAEQADAEAAAGQgBAFgCAEQgCAFgDADQgFADgFACQgGABgIAAQgIAAgIgCg");
	this.shape_23.setTransform(49.1,53.6);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#6B8A21").s().p("AAAA5QgCgBgBgEIAAhHQABgEACAAIAAAAQAEAAAAAEIAABHQAAAEgEABgAgEgxQAAgHAEABQAFgBAAAHQAAAFgFAAQgEAAAAgFg");
	this.shape_24.setTransform(43.7,52);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#6B8A21").s().p("AgQA9QgHgBgFgDQgFgDgCgEQgCgEAAgFQAAgFACgEQACgEAEgDIAJgFIAKgDIgEgDQgCgCAAgDQAAgFAFgEIgIgCQgEgCgDgEIgEgHQgBgEAAgFQAAgGACgFQACgGAFgEQAEgEAGgCQAGgCAGAAQAEAAAFABQAGACAEADIAHgKQADgFAEABQABAAABABQAAAAABAAQAAABAAAAQAAABAAABIgNAOQAEAEACAEQACAFAAAFQAAAGgDAGQgCAFgFAEQgEAEgGAAQgGACgFAAIgFAAQgDACAAADQAAAEAGACIAPAFIAJACIAIAFQAEACACAEQACADAAAFQAAAGgCAEQgDAEgFADQgFADgIACQgHABgIAAIgQgBgAgLAYIgJAEIgHAFQgCAEAAAEQAAADACADIAFAFIAKADIAMABIAMgBQAGgBAEgCIAGgGQACgDAAgEQAAgDgBgCQgCgDgDgBQgFgDgJgCIgKgDIgLACgAgJgtQgEACgDADQgEADgBAEQgCAEAAAFQAAAFACAEQABAEAEADQADADAEABQAEACAFAAQAEAAAEgCQAEgBADgDQAEgDABgEQACgEAAgFQAAgFgCgEQgBgEgDgDQgEgDgEgCQgEgCgEAAQgFAAgEACg");
	this.shape_25.setTransform(38.3,54.9);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#6B8A21").s().p("AgNAmQgHgDgGgFQgFgGgEgHQgCgIAAgJQAAgHADgIQADgHAFgGQAGgGAHgDQAHgDAHAAQAIAAAHACQAGADAFAFQAGAGACAHQADAHAAAJIAAABQAAABgEAAIg/AAQAAAHACAGQADAGAEAFQAFAEAFADQAHACAFAAQAGAAAFgBQAFgBADgDQAGgEAEgHIACABQABAAAAABQABAAAAABQAAAAAAABQAAAAAAABQAAADgEAFQgFAFgGACQgIADgKAAQgHAAgIgDgAAegEQgBgHgCgFQgCgFgEgEQgDgEgGgCQgFgCgGAAQgEAAgGACIgKAGQgDAEgDAFQgDAFgBAHIA7AAIAAAAg");
	this.shape_26.setTransform(30,53.6);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#6B8A21").s().p("AgPApQgEAAAAgEIAAhLIADgBQAAAAABAAQAAAAABABQAAAAABAAQAAAAAAABQACACAAAEIAAALIADgJIAFgGQADgDACgBIAHgBQAFAAADACQADACAAADIgBADIgBABQgEgDgGAAQgFAAgDADQgDACgDAFQgCAEgCAHIgBANIAAAjQAAAEgDAAg");
	this.shape_27.setTransform(23.2,53.5);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#6B8A21").s().p("AgPApQgEAAAAgEIAAhLIADgBQAAAAABAAQAAAAABABQAAAAABAAQAAAAAAABQACACAAAEIAAALIADgJIAFgGQADgDACgBIAHgBQAFAAADACQADACAAADIgBADIgBABQgEgDgGAAQgFAAgDADQgDACgDAFQgCAEgCAHIgBANIAAAjQAAAEgDAAg");
	this.shape_28.setTransform(14.7,53.5);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#6B8A21").s().p("AgPAmQgHgDgGgGQgFgFgDgIQgDgIgBgIQABgHADgIQADgIAFgFQAGgGAHgDQAHgDAIAAQAIAAAIADQAHADAGAGQAFAFADAIQADAIABAHQgBAJgDAHQgDAIgFAGQgGAFgHADQgIADgIAAQgIAAgHgDgAgLgfQgHADgEAFQgEAEgDAHQgDAGAAAGQAAAHADAGQADAGAEAFQAEAFAHADQAFACAGAAQAHAAAFgCQAHgDAEgFQAEgEADgGQADgHAAgHQAAgFgDgHQgDgGgEgFQgEgFgHgDQgFgCgHAAQgGAAgFACg");
	this.shape_29.setTransform(6.8,53.6);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#6B8A21").s().p("AgNAmQgHgDgGgFQgFgGgDgHQgDgIAAgJQAAgHADgIQADgHAFgGQAGgGAHgDQAIgDAGAAQAIAAAHACQAGADAGAFQAEAGADAHQADAHAAAJIAAABQAAAAAAAAQgBAAAAAAQgBAAAAABQgBAAgBAAIg/AAQAAAHADAGQACAGAEAFQAEAEAGADQAHACAFAAQAGAAAFgBQAEgBAEgDQAGgEADgHIADABQABAAAAABQABAAAAAAQAAABAAABQABAAAAABQgBADgFAFQgEAFgGACQgJADgJAAQgHAAgIgDgAAegEQgBgHgCgFQgCgFgEgEQgEgEgFgCQgFgCgGAAQgEAAgFACIgLAGQgEAEgCAFQgDAFgBAHIA7AAIAAAAg");
	this.shape_30.setTransform(92.4,32.6);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#6B8A21").s().p("AgPApQgEAAAAgEIAAhLIADgBQAAAAABAAQAAAAABABQAAAAABAAQAAAAAAABQACACAAAEIAAALIADgJIAFgGQADgDACgBIAHgBQAFAAADACQADACAAADIgBADIgBABQgEgDgGAAQgFAAgDADQgDACgDAFQgCAEgCAHIgBANIAAAjQAAAEgDAAg");
	this.shape_31.setTransform(85.6,32.5);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#6B8A21").s().p("AgPAmQgIgDgFgGQgFgFgDgIQgEgIAAgIQAAgHAEgIQADgIAFgFQAFgGAIgDQAHgDAIAAQAIAAAIADQAIADAFAGQAGAFACAIQADAIAAAHQAAAJgDAHQgCAIgGAGQgFAFgIADQgIADgIAAQgIAAgHgDgAgMgfQgFADgFAFQgFAEgCAHQgCAGgBAGQABAHACAGQACAGAFAFQAFAFAFADQAGACAGAAQAGAAAGgCQAHgDAEgFQAEgEADgGQACgHAAgHQAAgFgCgHQgDgGgEgFQgEgFgHgDQgGgCgGAAQgGAAgGACg");
	this.shape_32.setTransform(77.7,32.6);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#6B8A21").s().p("AA5ApQgEAAAAgEIAAgqQAAgGgCgFQgBgGgDgDQgDgEgEgBQgFgCgFAAIgIABQgEABgEADIgGAGIgEAHIAAAzQgBAEgDAAIAAAAQgCAAgBgEIAAgsQAAgGgBgEQgBgFgEgDQgCgEgEgBQgFgCgGAAIgHABQgFABgDADIgGAGQgDADgBAEIAAAzQAAAEgEAAIgBAAQgEAAAAgEIAAhLIADgBQABAAAAAAQABAAAAABQABAAAAAAQAAAAAAABQACACABAEIAAAHQABgDADgDIAHgFQADgDAEgBIAIgBIAKABIAIAEIAGAGIACAIQABgEADgEIAHgGIAJgEIAJgBQAIAAAFACQAGADAEAEQAEAFACAGQACAGAAAJIAAAqQAAAEgDAAg");
	this.shape_33.setTransform(65.7,32.5);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#6B8A21").s().p("AAeApQgEAAAAgEIAAgoQAAgHgCgFQgBgGgDgDQgDgEgFgCQgFgCgFAAQgDAAgFABQgEABgEADIgGAGQgDADgCAEIAAAzQAAAEgDAAIgBAAQgEAAAAgEIAAhLIADgBQAAAAABAAQAAAAABABQAAAAABAAQAAAAAAABQACACAAAEIAAAIQACgEADgDIAGgFIAIgEIAIgBQAIAAAGADQAGACAEAFQAEAFACAGQACAHAAAIIAAApQAAAEgDAAg");
	this.shape_34.setTransform(50.9,32.5);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#6B8A21").s().p("AgPApQgEAAAAgEIAAhLIADgBQAAAAABAAQAAAAABABQAAAAABAAQAAAAAAABQACACAAAEIAAALIADgJIAFgGQADgDACgBIAHgBQAFAAADACQADACAAADIgBADIgBABQgEgDgGAAQgFAAgDADQgDACgDAFQgCAEgCAHIgBANIAAAjQAAAEgDAAg");
	this.shape_35.setTransform(43.9,32.5);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#6B8A21").s().p("AgQAoQgFgCgEgDQgEgDgCgEQgBgEAAgFQAAgGADgFQADgFAHgDQAHgBAMgCQAIgCAQAAIABAAIAAgEQAAgGgBgEQgCgFgDgDQgDgDgFgBQgFgCgFAAIgIABQgEABgEADQgGAEgEAGQgEAAAAgEQAAgEAEgEQAFgFAGgCQAIgDAHAAQAIAAAGACQAGACAEAEQAEAEACAGQACAGAAAHIAAAwIgDABQAAAAgBAAQAAAAgBAAQAAAAAAgBQgBAAAAAAQgCgCAAgFIAAgIIgFAHQgDADgEACQgEADgFABQgEABgFAAQgGAAgFgBgAABABQgIABgGADQgFACgDAEQgDADAAAFQAAAEABADIAEAFQADACAEABIAIABQAFAAAFgCQAGgCAEgEQAFgEACgFQACgFAAgGIAAgHIgCAAIgWABg");
	this.shape_36.setTransform(36.2,32.6);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#6B8A21").s().p("AgNAmQgHgDgGgFQgFgGgDgHQgDgIAAgJQAAgHADgIQADgHAFgGQAGgGAHgDQAHgDAHAAQAIAAAHACQAHADAFAFQAEAGADAHQADAHAAAJIAAABQAAABgEAAIg/AAQAAAHADAGQACAGAEAFQAEAEAHADQAGACAFAAQAGAAAFgBQAFgBADgDQAGgEADgHIADABQABAAAAABQABAAAAAAQAAABAAABQABAAAAABQAAADgGAFQgEAFgHACQgHADgKAAQgHAAgIgDgAAdgEQAAgHgCgFQgCgFgEgEQgDgEgGgCQgFgCgGAAQgEAAgFACIgKAGQgEAEgDAFQgDAFAAAHIA5AAIAAAAg");
	this.shape_37.setTransform(27.8,32.6);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#6B8A21").s().p("AAAA5QgDAAAAgDIAAhuIADgBQAAAAAAABQAAAAAAAAQABAAAAABQAAAAABABQACABAAAFIAABmQAAADgEAAg");
	this.shape_38.setTransform(21.7,30.9);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#6B8A21").s().p("AgPAmQgIgDgFgGQgGgFgCgIQgDgIAAgIQAAgHADgIQACgIAGgFQAFgGAIgDQAIgDAHAAQAIAAAIADQAIADAFAGQAFAFADAIQAEAIAAAHQAAAJgEAHQgDAIgFAGQgFAFgIADQgIADgIAAQgHAAgIgDgAgLgfQgHADgEAFQgEAEgDAHQgCAGAAAGQAAAHACAGQADAGAEAFQAEAFAHADQAGACAFAAQAGAAAHgCQAFgDAFgFQAFgEACgGQACgHABgHQgBgFgCgHQgCgGgFgFQgFgFgFgDQgHgCgGAAQgFAAgGACg");
	this.shape_39.setTransform(12.4,32.6);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#6B8A21").s().p("AAAAxQgCgCgDgDQgDgDgBgEQgBgFAAgHIAAgvIgKAAQgEAAAAgEIAAAAQAAgEAEAAIAKAAIAAgPQAAgEADAAIABAAQABAAABAAQAAAAABABQAAAAAAABQAAABAAABIAAAPIAWAAQAEAAAAAEIAAAAQAAAEgEAAIgWAAIAAAvQAAAKADAEQACAFAHAAQAFAAADgCQADgCACgDIACAAQAAABAAAAQAAAAABABQAAAAAAABQAAAAAAABQAAACgDADIgFADIgIABQgGAAgDgBg");
	this.shape_40.setTransform(4.9,31.7);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#6B8A21").s().p("AgfA2QgFAAgBgEIAAhiQABgGAFAAIA/AAQABAAABABQABAAAAAAQABABAAAAQAAABAAABIAAABQAAAAAAABQAAABgBAAQAAABgBAAQgBAAgBAAIg9AAIAAArIAvAAQAEAAAAACIAAABQAAACgEAAIgvAAIAAAtIA/AAQABAAABAAQAAAAABABQAAAAAAABQABAAAAABIAAABQAAABgBABQAAAAAAABQgBAAAAAAQgBAAgBAAg");
	this.shape_41.setTransform(84.2,10.1);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#6B8A21").s().p("AAaA0IgogtIgNAAIAAAsQAAAEgEAAIgBAAQgEAAABgEIAAhkQAAgFAEAAIAeAAQAIAAAHACQAIACAFAEQAEAEADAGQACAGAAAIQAAAHgCAGQgDAGgEADQgFADgHACQgHACgIAAIgDAAIAnAsIgBACQAAABgBAAQAAAAgBAAQAAABgBAAQAAAAgBAAQgCAAgDgDgAgbAAIAbAAQAFAAAGAAQAFgBAEgEQAEgDACgEQACgFAAgFQAAgGgCgEQgCgFgEgDQgEgDgFgCQgGgBgFAAIgbAAg");
	this.shape_42.setTransform(74.6,10.1);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#6B8A21").s().p("AggA2QgEAAAAgEIAAhiQAAgGAEAAIBBAAQAAAAABABQABAAAAAAQABABAAAAQAAABAAABIAAABQAAAAAAABQAAABgBAAQAAABgBAAQgBAAAAAAIg9AAIAAArIAuAAQAEAAAAACIAAABQAAACgEAAIguAAIAAAtIA+AAQABAAABAAQAAAAABABQAAAAAAABQAAAAAAABIAAABQAAABAAABQAAAAAAABQgBAAAAAAQgBAAgBAAg");
	this.shape_43.setTransform(65.2,10.1);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#6B8A21").s().p("AAmA3QgDAAAAgEIAAgvIhFAAIAAAvQAAAEgEAAIgBAAQgDAAAAgEIAAhlQAAgEADAAIABAAQAEAAAAAEIAAAwIBFAAIAAgwQAAgEADAAIABAAQAEAAAAAEIAABlQAAAEgEAAg");
	this.shape_44.setTransform(54.3,10.1);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#6B8A21").s().p("AgfA3QgDAAAAgEIAAhlQAAgEADAAIABAAQAEAAAAAEIAAAxIAygzQAEgDADABQABABABAAQAAAAAAABQABAAAAABQAAABAAABIgyAxIAzAzQAAACgDABQgDACgDgDIg0g1IAAAzQAAAEgEAAg");
	this.shape_45.setTransform(41.6,10.1);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#6B8A21").s().p("AgEA3IgLgDIgJgFIgIgGIgGgJIgFgJIgDgLIgBgMIABgKIADgLIAFgKIAGgIIAIgHIAJgFIALgDIAKgBQAIAAANAEQAIADAGAFQAFAHAAAEQAAABAAAAQAAABAAABQgBAAAAABQAAAAgBAAIgCABIgGgIIgIgHQgFgDgGgBIgMgCIgIABIgIADQgJADgGAHQgGAGgDAJQgDAOAAAFQABANACAGQADAJAGAHIAHAGIAIAEIAJADIAIABQAHAAAGgCQAGgCAFgDQAFgDADgFQADgEACgFQAFABAAAEQgCAJgFAEQgGAGgIADQgNAEgJAAIgJgBg");
	this.shape_46.setTransform(31.2,10.1);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("#6B8A21").s().p("AAAA3QgDAAAAgEIAAhlQAAgEADAAIAAAAQAEAAAAAEIAABlQAAAEgEAAg");
	this.shape_47.setTransform(23.6,10.1);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("#6B8A21").s().p("AgaA3QgGAAAAgFIAAhkQABgEADAAIABAAQADAAABAEIAABhIA0AAQADAAAAAEIAAAAQAAABAAABQAAAAAAABQgBAAAAABQgBAAgBAAg");
	this.shape_48.setTransform(17.8,10.1);

	this.shape_49 = new cjs.Shape();
	this.shape_49.graphics.f("#6B8A21").s().p("AgEA3IgLgDIgJgFIgIgGIgGgJIgFgJIgDgLIgBgMIABgKIADgLIAFgKIAGgIIAIgHIAJgFIALgDIAKgBQAIAAANAEQAIADAGAFQAFAHAAAEQAAABAAAAQAAABAAABQgBAAAAABQAAAAgBAAIgCABIgGgIIgIgHQgFgDgGgBIgMgCIgIABIgIADQgJADgGAHQgGAGgDAJQgDAOAAAFQABANACAGQADAJAGAHIAHAGIAIAEIAJADIAIABQAHAAAGgCQAGgCAFgDQAFgDADgFQADgEACgFQAFABAAAEQgCAJgFAEQgGAGgIADQgNAEgJAAIgJgBg");
	this.shape_49.setTransform(7.7,10.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_49},{t:this.shape_48},{t:this.shape_47},{t:this.shape_46},{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,104,105);


(lib.replaybtn = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#666666").s().p("Ak9BwIAAjgIJ6AAIAADgg");
	this.shape.setTransform(9.1,9.8,0.438,1.268,0,0,0,-0.2,0);
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(3).to({_off:false},0).wait(1));

	// Layer 2
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#BFBFBF").s().p("AgEBGQghgDgWgXQgXgZAAgfQAAgQAGgQQAOggAfgNQARgGAOgBQAiAAAYAZQAZAYAAAjIgUAAQAAgbgTgSQgSgTgaAAQgZAAgSATQgTATAAAaQAAAXARASQAQASAZACIgNgcIBVAnIhWAlg");
	this.shape_1.setTransform(8.4,9.7);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#666666").s().p("AgEBGQghgDgWgXQgXgZAAgfQAAgQAGgQQAOggAfgNQARgGAOgBQAiAAAYAZQAZAYAAAjIgUAAQAAgbgTgSQgSgTgaAAQgZAAgSATQgTATAAAaQAAAXARASQAQASAZACIgNgcIBVAnIhWAlg");
	this.shape_2.setTransform(8.4,9.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AgEBGQghgDgWgXQgXgZAAgfQAAgQAGgQQAOggAfgNQARgGAOgBQAiAAAYAZQAZAYAAAjIgUAAQAAgbgTgSQgSgTgaAAQgZAAgSATQgTATAAAaQAAAXARASQAQASAZACIgNgcIBVAnIhWAlg");
	this.shape_3.setTransform(8.4,9.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1}]}).to({state:[{t:this.shape_2}]},1).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_3}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,16.7,19.4);


(lib.pic = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib._336x280gardener();

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,515,200);


(lib.head1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#193670").s().p("AAAAHQgHAAABgHIAAAAQgBgGAHgBIABAAQAGABABAGIAAAAQgBAHgGAAg");
	this.shape.setTransform(70.8,118.1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#193670").s().p("AgUAwQgIgDgFgFQgFgFAAgDQAAgFAFgBQAGAIAIAEIAKAEIAJABQAHAAAGgCQAFgBAEgDQAEgCABgEQACgDAAgEQAAgFgCgEQgCgDgEgCQgGgDgPgDQgRgEgHgCQgFgDgDgEQgDgFAAgHQAAgHACgFQADgFAFgEQAFgEAHgCQAHgCAGAAQALAAAJADQAIADAFAFQADAEAAADQAAABAAAAQAAABgBAAQAAABAAAAQgBABAAAAIgDABQgFgGgIgEQgHgFgLAAQgEAAgFACQgFABgEADQgDACgDAEQgCADAAAEQAAAFACADQADADAEACQAFADAPAEIAMADIAMACQAGAEACAEQAEAFAAAHQAAAHgDAFQgCAFgGAEQgEAEgIACQgHACgJAAQgKAAgKgDg");
	this.shape_1.setTransform(64.1,113.8);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#193670").s().p("AAlAzQgFAAAAgFIAAgzQAAgHgCgHQgCgHgEgFQgEgEgFgCQgGgDgHAAQgEAAgGABIgKAFIgIAIIgFAJIAAA/QAAAFgFAAIgBAAQgEAAAAgFIAAhdIADgBQABAAABAAQAAAAABABQAAAAABAAQAAAAABABQACADAAAFIAAAJIAGgIQADgEAFgCQAEgDAGgCQAFgBAEgBQAKABAIADQAHADAFAGQAFAGADAHQACAJAAAKIAAAzQAAAFgEAAg");
	this.shape_2.setTransform(53.9,113.8);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#193670").s().p("AgTAvQgJgDgHgHQgHgIgEgJQgDgKAAgKQAAgJADgKQAEgJAHgHQAHgHAJgEQAJgEAKAAQAKAAAKAEQAJAEAHAHQAGAHAFAJQADAKAAAJQAAALgDAJQgFAKgGAHQgHAHgJADQgKAEgKAAQgKAAgJgEgAgOgmQgIADgGAGQgFAGgDAHQgDAIAAAIQAAAJADAHQADAIAFAGQAGAGAIADQAHADAHAAQAIAAAIgDQAHgDAGgGQAFgFADgIQADgIAAgJQAAgHgDgIQgDgIgFgGQgGgGgHgDQgIgDgIAAQgHAAgHADg");
	this.shape_3.setTransform(42.4,113.8);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#193670").s().p("AAABGQgEAAABgFIAAhZQgBgFAEAAIAAAAQAEAAABAFIAABZQgBAFgEAAgAgFg+QgBgHAGAAQAGAAAAAHQABAHgHAAQgFAAAAgHg");
	this.shape_4.setTransform(34.5,111.8);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#193670").s().p("AAAA8QgDgBgEgEQgDgEgBgGQgCgGAAgIIAAg7IgMAAQgFAAAAgEIAAgBQAAgEAFAAIAMAAIAAgTQAAgFAEAAIACAAQAEAAAAAFIAAATIAbAAQAFAAAAAEIAAABQAAAEgFAAIgbAAIAAA6QAAANADAFQACAGAKAAQAFAAAEgDQAEgCACgEIADABQAAABAAAAQAAABABAAQAAABAAAAQAAABAAAAQAAADgEADQgCADgEACQgEABgGAAQgGAAgFgCg");
	this.shape_5.setTransform(29,112.7);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#193670").s().p("AgqBGQgFABAAgGIAAiEIAEgBQABAAAAAAQABAAAAABQABAAAAAAQABAAAAABQACADAAAFIAAALIAHgJIAJgHIALgFQAGgBAFgBQAJAAAJAFQAJADAGAHQAHAGADAKQAEAKAAALQAAALgEAIQgDAJgHAHQgGAIgJADQgJAEgKAAQgFAAgHgCQgGgBgFgEIgIgHIgGgIIAAA3QAAAGgEgBgAgMg7QgGACgEAEQgFAEgEAFIgGAKIAAAYQAAAGADAFQADAHAFAFQAFAFAHACQAHADAHAAQAIAAAHgDQAHgDAFgGQAFgGADgFQADgJAAgJQAAgJgDgIQgDgIgFgFQgFgGgHgDQgHgEgIAAQgFAAgHACg");
	this.shape_6.setTransform(19.9,115.8);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#193670").s().p("AgTAvQgJgDgHgHQgHgIgEgJQgDgKAAgKQAAgJADgKQAEgJAHgHQAHgHAJgEQAJgEAKAAQAKAAAKAEQAJAEAHAHQAGAHAEAJQAEAKAAAJQAAALgEAJQgEAKgGAHQgHAHgJADQgKAEgKAAQgKAAgJgEgAgPgmQgHADgGAGQgFAGgDAHQgDAIAAAIQAAAJADAHQADAIAFAGQAGAGAHADQAIADAHAAQAIAAAIgDQAHgDAFgGQAGgFADgIQADgIAAgJQAAgHgDgIQgDgIgGgGQgFgGgHgDQgHgDgJAAQgHAAgIADg");
	this.shape_7.setTransform(7.9,113.8);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#193670").s().p("AgQAwQgKgEgGgHQgHgHgEgJQgDgKAAgLQAAgJADgKQAEgJAHgHQAHgHAIgEQAKgEAJAAQAJAAAJADQAJAEAFAGQAHAHACAJQAEAJAAAKIAAABQAAACgFAAIhPAAQABAJADAIQADAHAFAGQAGAFAHAEQAIACAHAAQAHAAAGgBQAFgCAFgDQAHgFAFgJIADABQADACAAADQAAAFgGAGQgGAFgIADQgKAEgLAAQgJAAgKgDgAAkgGQAAgIgDgGQgCgHgFgEQgFgFgGgDQgGgCgHAAQgGAAgHACQgGADgGAFQgFAFgDAGQgEAHgBAHIBIAAIAAAAg");
	this.shape_8.setTransform(90.3,88.8);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#193670").s().p("AgUBLQgJgCgGgDQgGgDgDgFQgCgFAAgHQAAgGACgFQADgEAFgEQAEgEAHgCIAMgEQgDgCgCgCQgCgDAAgEQAAgGAFgEIgKgDQgEgDgEgEQgCgEgCgGQgCgFAAgFQAAgIADgHQADgGAFgFQAGgFAGgDQAIgDAIAAQAFAAAGACQAHACAFAEIAKgMQADgGAFABQAEABAAAEIgQARQAEAFACAGQADAGAAAGQAAAHgDAHQgDAGgGAFQgFAFgHABQgHADgHAAIgHgBQgEACABAFQgBAFAIACIATAFIALAEIAKAFQAFADACAEQADAFAAAGQABAHgEAFQgDAGgGADQgHAEgKACQgJACgJAAQgMAAgIgCgAgOAdQgGACgFADIgJAHQgCAEAAAFQAAAEACAEQACADAFADQAFACAGABQAHACAJAAQAHAAAIgCIAMgEQAFgCADgEQACgEAAgFQAAgEgCgDQgCgDgDgCQgGgDgMgDIgMgDQgHAAgHACgAgLg4QgGACgEADQgDAEgCAFQgDAFAAAGQAAAGADAFQACAFADAEQAEAEAGACQAFACAGAAQAEAAAGgCQAFgCAEgEQAEgEACgFQADgFgBgGQABgGgDgFQgCgFgEgDQgEgEgFgCQgGgCgEAAQgGAAgFACg");
	this.shape_9.setTransform(80.1,90.5);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#193670").s().p("AgUAxQgHgCgEgDQgFgEgCgFQgCgFAAgGQAAgIAEgGQAEgGAJgEQAIgCAOgCQALgCATAAIACAAIAAgGQAAgGgCgGQgCgFgEgEQgEgEgFgCQgGgCgHAAQgEAAgGACQgFABgEADQgIAEgFAJQgFgBAAgFQAAgEAFgGQAGgFAHgDQAKgEAKAAQAJAAAHADQAIACAFAFQAFAFADAHQACAHAAAJIAAA9IgDABQgBAAgBAAQAAAAgBgBQAAAAgBAAQAAgBgBAAQgCgDAAgFIAAgLQgCAFgEAEIgJAHQgFADgGACQgFABgGAAQgIAAgGgCgAABABQgKACgHADQgHADgEAEQgDAFAAAGQAAAEACAEQABADAEADQADACAEACIALABQAGAAAHgDQAHgCAFgFQAGgEACgGQADgHAAgHIAAgJIgCAAQgRAAgLABg");
	this.shape_10.setTransform(69.8,88.8);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#193670").s().p("AAAA8QgEgBgCgEQgDgEgDgGQgBgGAAgIIAAg7IgMAAQgFAAAAgEIAAgBQAAgEAFAAIAMAAIAAgTQAAgFAFAAIABAAQAEAAAAAFIAAATIAbAAQAFAAAAAEIAAABQAAAEgFAAIgbAAIAAA6QAAANADAFQACAGAJAAQAGAAAEgDQAEgCADgEIABABQABABAAAAQAAABABAAQAAABAAAAQAAABAAAAQAAADgDADQgDADgEACQgEABgGAAQgGAAgFgCg");
	this.shape_11.setTransform(61.4,87.7);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#193670").s().p("AAlAzQgFgBAAgEIAAgzQAAgIgCgGQgCgHgEgEQgEgFgFgCQgGgDgHAAQgEAAgGACIgKAEIgIAHIgFAKIAAA/QAAAEgFABIgBAAQgEgBAAgEIAAhdIADgBQABAAABAAQAAAAABAAQAAABABAAQAAAAABABQACADAAAFIAAAJIAGgIQADgEAFgDQAEgDAGgBQAFgCAEAAQAKAAAIAEQAHADAFAGQAFAGADAHQACAJAAAKIAAAzQAAAEgEABg");
	this.shape_12.setTransform(52.2,88.8);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#193670").s().p("AgUAxQgHgCgEgDQgFgEgCgFQgCgFAAgGQAAgIAEgGQAEgGAJgEQAIgCAOgCQALgCATAAIACAAIAAgGQAAgGgCgGQgCgFgEgEQgEgEgFgCQgGgCgHAAQgEAAgGACQgFABgEADQgIAEgFAJQgFgBAAgFQAAgEAFgGQAGgFAHgDQAKgEAKAAQAJAAAHADQAIACAFAFQAFAFADAHQACAHAAAJIAAA9IgDABQgBAAgBAAQAAAAgBgBQAAAAgBAAQAAgBgBAAQgCgDAAgFIAAgLQgCAFgEAEIgJAHQgFADgGACQgFABgGAAQgIAAgGgCgAABABQgKACgHADQgHADgEAEQgDAFAAAGQAAAEACAEQABADAEADQADACAEACIALABQAGAAAHgDQAHgCAFgFQAGgEACgGQADgHAAgHIAAgJIgCAAQgRAAgLABg");
	this.shape_13.setTransform(41,88.8);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#193670").s().p("AgFAuIgnhcQAJgHAEALIAfBSIAhhSQAEgMAIAIIgmBcQgCAEgFAAQgEAAgBgEg");
	this.shape_14.setTransform(31.2,88.9);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#193670").s().p("AgSBEQgJgEgGgGQgHgHgDgKQgEgKAAgLQAAgLAEgJQADgIAHgHQAGgHAJgEQAJgEAJAAQAGAAAGACQAGACAFADQAFADAEAEIAGAIIAAg+IADgBQADAAACACQACADAAAFIAAB/QAAAEgFAAIgBAAQgEAAAAgEIAAgQIgHAJIgJAHQgFADgGABQgGACgFAAQgKAAgIgEgAgOgSQgHADgFAGQgFAGgDAGQgDAHAAAKQAAAJADAIQADAIAFAGQAFAGAHADQAHADAHAAQAHAAAHgDQAHgCAFgFQAGgFADgHQADgGAAgIIAAgXQgDgEgDgFIgIgIQgFgEgGgCQgGgCgHAAQgHAAgHADg");
	this.shape_15.setTransform(20.1,86.8);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#193670").s().p("AAvA/IgRgrIg7AAIgRArQgEAJgIgHIA0iBQABgDAFAAQAGAAACADIAzCBQgEADgDAAQgDAAgCgFgAAbALIgbhDIgZBDIA0AAg");
	this.shape_16.setTransform(8.3,87);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#193670").s().p("AgQAwQgJgEgIgHQgGgHgEgJQgDgKAAgLQAAgJADgKQAEgJAHgHQAGgHAJgEQAKgEAIAAQAKAAAJADQAJAEAFAGQAGAHADAJQAEAJAAAKIAAABQAAACgEAAIhPAAQAAAJADAIQADAHAFAGQAGAFAHAEQAIACAGAAQAIAAAGgBQAFgCAFgDQAIgFAEgJIADABQADACAAADQAAAFgHAGQgEAFgJADQgKAEgMAAQgIAAgKgDgAAkgGQAAgIgCgGQgDgHgFgEQgFgFgFgDQgHgCgIAAQgFAAgHACQgGADgGAFQgFAFgDAGQgDAHgCAHIBIAAIAAAAg");
	this.shape_17.setTransform(78,63.8);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#193670").s().p("AgUAyQgEAAAAgEIAAhdIADgBQABAAABAAQABAAAAAAQABABAAAAQABABAAAAQACADAAAFIAAAMIAEgKQACgEAEgEQADgDADgBQAEgBAFAAQAGAAAEACQAEACAAAEIgBAEIgCABQgEgEgHAAQgIAAgDADQgEAEgDAFQgDAGgDAJQgBAHAAAJIAAArQAAAEgEAAg");
	this.shape_18.setTransform(69.6,63.8);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#193670").s().p("AgUAxQgHgCgEgDQgFgEgCgFQgCgFAAgGQAAgIAEgGQAEgGAJgEQAIgCAOgCQALgCATAAIACAAIAAgGQAAgGgCgGQgCgFgEgEQgEgEgFgCQgGgCgHAAQgEAAgGACQgFABgEADQgIAEgFAJQgFgBAAgFQAAgEAFgGQAGgFAHgDQAKgEAKAAQAJAAAHADQAIACAFAFQAFAFADAHQACAHAAAJIAAA9IgDABQgBAAgBAAQAAAAgBgBQAAAAgBAAQAAgBgBAAQgCgDAAgFIAAgLQgCAFgEAEIgJAHQgFADgGACQgFABgGAAQgIAAgGgCgAABABQgKACgHADQgHADgEAEQgDAFAAAGQAAAEACAEQABADAEADQADACAEACIALABQAGAAAHgDQAHgCAFgFQAGgEACgGQADgHAAgHIAAgJIgCAAQgRAAgLABg");
	this.shape_19.setTransform(60,63.8);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#193670").s().p("AgPAvQgJgDgHgHQgHgIgDgJQgEgKAAgKQAAgJAEgKQADgJAHgHQAHgHAJgEQAKgEAJAAQALAAAKAEQAHADAGAGQAIAHAAAHQAAADgDABIgEABIgEgJIgIgHQgEgEgGgBQgGgCgHAAQgHAAgIADQgHADgGAGQgFAGgDAHQgDAIAAAIQAAAJADAHQADAIAFAGQAGAGAHADQAIADAHAAQAHAAAGgBIAKgFQAGgFAGgMQAHABAAAEQgDAJgFAGQgGAFgIAEQgJADgLAAQgJAAgKgEg");
	this.shape_20.setTransform(49.7,63.8);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#193670").s().p("AAABGQgEAAAAgFIAAhZQAAgFAEAAIAAAAQAFAAAAAFIAABZQAAAFgFAAgAgGg+QAAgHAGAAQAGAAABAHQAAAHgHAAQgGAAAAgHg");
	this.shape_21.setTransform(42.3,61.8);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#193670").s().p("AgSBEQgJgEgGgGQgHgHgDgKQgEgKAAgLQAAgLAEgJQADgIAHgHQAGgHAJgEQAJgEAJAAQAGAAAGACQAGACAFADQAFADAEAEIAGAIIAAg+IADgBQADAAACACQACADAAAFIAAB/QAAAEgFAAIgBAAQgEAAAAgEIAAgQIgHAJIgJAHQgFADgGABQgGACgFAAQgKAAgIgEgAgOgSQgHADgFAGQgFAGgDAGQgDAHAAAKQAAAJADAIQADAIAFAGQAFAGAHADQAHADAHAAQAHAAAHgDQAHgCAFgFQAGgFADgHQADgGAAgIIAAgXQgDgEgDgFIgIgIQgFgEgGgCQgGgCgHAAQgHAAgHADg");
	this.shape_22.setTransform(34,61.8);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#193670").s().p("AgQAwQgJgEgIgHQgGgHgEgJQgDgKAAgLQAAgJADgKQAEgJAHgHQAGgHAJgEQAKgEAIAAQAKAAAJADQAIAEAHAGQAFAHAEAJQADAJAAAKIAAABQAAACgEAAIhPAAQAAAJADAIQADAHAFAGQAGAFAHAEQAIACAGAAQAIAAAGgBQAGgCAEgDQAHgFAFgJIADABQADACAAADQAAAFgHAGQgEAFgJADQgKAEgMAAQgIAAgKgDgAAkgGQAAgIgCgGQgDgHgFgEQgFgFgFgDQgHgCgIAAQgFAAgHACQgGADgGAFQgFAFgDAGQgDAHgBAHIBHAAIAAAAg");
	this.shape_23.setTransform(23,63.8);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#193670").s().p("AA3BEQgFAAAAgEIAAh3IgpBPQgDAHgGAAQgFAAgCgHIgqhPIAAB3QAAAEgEAAIgCAAQgEAAAAgEIAAh9QAAgGAIAAIACAAQAEAAACACIADAGIAoBQIAphQIAEgGQACgCADAAIADAAQAHAAAAAGIAAB9QAAAEgEAAg");
	this.shape_24.setTransform(9.7,62);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#193670").s().p("AgUAyQgEABAAgFIAAhdIADgBQABAAABAAQABAAAAABQABAAAAAAQABABAAAAQACACAAAGIAAANIAEgLQACgEAEgDQAEgEACgBQAEgCAFABQAGgBAEADQAEACAAAEIgBAEIgCABQgFgEgGAAQgIAAgDADQgEAEgDAFQgEAGgBAJQgCAHAAAJIAAArQAAAFgFgBg");
	this.shape_25.setTransform(94.6,38.8);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#193670").s().p("AgTAwQgHgEgFgFQgFgGgDgJQgCgIAAgKIAAgzQAAgEAEAAIACAAQAEAAAAAEIAAAzQAAAIACAHQACAGAEAFQAEAEAFADQAGACAHAAQAEAAAGgBQAFgCAFgDQAEgDAEgFIAFgJIAAg/QAAgEAFAAIABAAQAEAAAAAEIAABdIgDABQgBAAgBAAQAAAAgBgBQAAAAgBAAQAAgBgBAAQgCgCAAgGIAAgJIgGAIQgDAEgFACQgEADgGACQgFABgEABQgKAAgIgDg");
	this.shape_26.setTransform(84.8,38.9);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#193670").s().p("AgTAvQgJgDgHgHQgHgIgEgJQgDgKAAgKQAAgJADgKQAEgJAHgHQAHgHAJgEQAJgEAKAAQAKAAAKAEQAJAEAHAHQAGAHAFAJQADAKAAAJQAAALgDAJQgFAKgGAHQgHAHgJADQgKAEgKAAQgKAAgJgEgAgOgmQgIADgGAGQgFAGgDAHQgDAIAAAIQAAAJADAHQADAIAFAGQAGAGAIADQAHADAHAAQAIAAAIgDQAHgDAGgGQAFgFADgIQADgIAAgJQAAgHgDgIQgDgIgFgGQgGgGgHgDQgIgDgIAAQgHAAgHADg");
	this.shape_27.setTransform(73.4,38.8);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#193670").s().p("AgPBFIgCgCIARgrQgEAAgCgEIgmhWQAIgHAFALIAgBQIAfhQQAEgLAJAHIgyCBQgCAHgFAAg");
	this.shape_28.setTransform(62.8,40.8);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#193670").s().p("AAAA8QgDgBgEgEQgCgEgCgGQgCgGAAgIIAAg7IgMAAQgFAAAAgEIAAgBQAAgEAFAAIAMAAIAAgTQAAgFAFAAIABAAQAEAAAAAFIAAATIAbAAQAFAAAAAEIAAABQAAAEgFAAIgbAAIAAA6QAAANADAFQADAGAIAAQAGAAAEgDQAEgCACgEIACABQABABAAAAQAAAAABABQAAAAAAABQAAABAAAAQAAADgEADQgCADgEACQgEABgGAAQgHAAgEgCg");
	this.shape_29.setTransform(50.9,37.7);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#193670").s().p("AgTAwQgHgEgFgFQgFgGgDgJQgCgIAAgKIAAgzQAAgEAEAAIACAAQAEAAAAAEIAAAzQAAAIACAHQACAGAEAFQAEAEAFADQAGACAHAAQAEAAAGgBQAFgCAFgDQAEgDAEgFIAFgJIAAg/QAAgEAFAAIABAAQAEAAAAAEIAABdIgDABQgBAAgBAAQAAAAgBgBQAAAAgBAAQAAgBgBAAQgCgCAAgGIAAgJIgGAIQgDAEgFACQgEADgGACQgFABgEABQgKAAgIgDg");
	this.shape_30.setTransform(41.6,38.9);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#193670").s().p("AgTAvQgJgDgHgHQgHgIgEgJQgDgKAAgKQAAgJADgKQAEgJAHgHQAHgHAJgEQAJgEAKAAQAKAAAKAEQAJAEAHAHQAGAHAFAJQADAKAAAJQAAALgDAJQgFAKgGAHQgHAHgJADQgKAEgKAAQgKAAgJgEgAgOgmQgIADgGAGQgFAGgDAHQgDAIAAAIQAAAJADAHQADAIAFAGQAGAGAIADQAHADAHAAQAIAAAIgDQAHgDAGgGQAFgFADgIQADgIAAgJQAAgHgDgIQgDgIgFgGQgGgGgHgDQgIgDgIAAQgHAAgHADg");
	this.shape_31.setTransform(30.2,38.8);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#193670").s().p("AgMBGQgGgCgFgDIgJgHIgFgIIAAAQQAAAEgEAAIgBAAQgFAAAAgEIAAiIIAEgBQABAAAAAAQABAAAAABQABAAAAAAQABABAAAAQACADAAAFIAAA2IAHgJQAEgFAFgDIALgEQAGgCAFAAQAJAAAJAEQAJAEAGAHQAHAGADAJQAEAJAAALQAAALgEAKQgDAJgHAHQgGAHgJAEQgJAEgKAAQgFAAgHgCgAgMgTQgGACgEAEQgFADgEAFIgGAJIAAAXQAAAHADAHQADAHAFAFQAFAFAHACQAHADAHAAQAIAAAHgDQAHgDAFgGQAFgGADgIQADgIAAgJQAAgJgDgIQgDgGgFgGQgFgFgHgEQgHgDgIAAQgFAAgHACg");
	this.shape_32.setTransform(18.8,36.8);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#193670").s().p("AgUAxQgHgCgEgDQgFgEgCgFQgCgFAAgGQAAgIAEgGQAEgGAJgEQAIgCAOgCQALgCATAAIACAAIAAgGQAAgGgCgGQgCgFgEgEQgEgEgFgCQgGgCgHAAQgEAAgGACQgFABgEADQgIAEgFAJQgFgBAAgFQAAgEAFgGQAGgFAHgDQAKgEAKAAQAJAAAHADQAIACAFAFQAFAFADAHQACAHAAAJIAAA9IgDABQgBAAgBAAQAAgBgBAAQAAAAgBAAQAAgBgBAAQgCgDAAgFIAAgLQgCAFgEAEIgJAHQgFADgGACQgFABgGAAQgIAAgGgCgAABABQgKACgHADQgHADgEAEQgDAFAAAGQAAAEACAEQABADAEADQADACAEACIALABQAGAAAHgDQAHgCAFgFQAGgEACgGQADgHAAgHIAAgJIgCAAQgRAAgLABg");
	this.shape_33.setTransform(7,38.8);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#193670").s().p("AAlAyQgFABAAgFIAAgzQAAgHgCgIQgCgGgEgFQgEgEgFgDQgGgCgHAAQgEAAgGABIgKAGIgIAHIgFAJIAAA/QAAAFgFgBIgBAAQgEABAAgFIAAhdIADgBQABAAABAAQAAAAABABQAAAAABAAQAAABABAAQACACAAAGIAAAJIAGgIQADgEAFgCQAEgDAGgCQAFgBAEgBQAKABAIADQAHADAFAFQAFAGADAIQACAJAAAKIAAAzQAAAFgEgBg");
	this.shape_34.setTransform(46.6,13.8);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#193670").s().p("AgTAyQgFABAAgFIAAhdIAEgBQAAAAABAAQABAAAAABQABAAAAAAQABABAAAAQACACAAAGIAAANIAEgLQADgEADgDQADgDADgCQAEgBAFgBQAGABAEACQAEACAAAEIgBAEIgBABQgGgEgHAAQgHAAgDAEQgEACgEAHQgCAFgCAIQgCAIAAAIIAAAsQAAAFgFgBg");
	this.shape_35.setTransform(38,13.8);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#193670").s().p("AgUAxQgHgCgEgDQgFgEgCgFQgCgFAAgGQAAgIAEgGQAEgGAJgEQAIgCAOgCQALgCATAAIACAAIAAgGQAAgGgCgGQgCgFgEgEQgEgEgFgCQgGgCgHAAQgEAAgGACQgFABgEADQgIAEgFAJQgFgBAAgFQAAgEAFgGQAGgFAHgDQAKgEAKAAQAJAAAHADQAIACAFAFQAFAFADAHQACAHAAAJIAAA9IgDABQgBAAgBAAQAAgBgBAAQAAAAgBAAQAAgBgBAAQgCgDAAgFIAAgLQgCAFgEAEIgJAHQgFADgGACQgFABgGAAQgIAAgGgCgAABABQgKACgHADQgHADgEAEQgDAFAAAGQAAAEACAEQABADAEADQADACAEACIALABQAGAAAHgDQAHgCAFgFQAGgEACgGQADgHAAgHIAAgJIgCAAQgRAAgLABg");
	this.shape_36.setTransform(28.5,13.8);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#193670").s().p("AgQAwQgKgEgGgHQgHgHgDgJQgEgKAAgLQAAgJAEgKQADgJAHgHQAHgHAJgEQAJgEAJAAQAKAAAIADQAJAEAFAGQAHAHACAJQAEAJAAAKIAAABQAAACgFAAIhPAAQABAJADAIQADAHAGAGQAFAFAHAEQAIACAHAAQAHAAAGgBQAFgCAFgDQAIgFAEgJIADABQADACAAADQAAAFgGAGQgGAFgIADQgKAEgLAAQgJAAgKgDgAAlgGQgBgIgDgGQgCgHgFgEQgEgFgHgDQgGgCgHAAQgHAAgGACQgGADgGAFQgFAFgDAGQgDAHgCAHIBJAAIAAAAg");
	this.shape_37.setTransform(18.1,13.8);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#193670").s().p("AgiBEQgFAAAAgHIAAh7QgBgFAFAAIABAAQAFAAAAAFIAAB4IBAAAQAFAAABAFIAAAAQgBAFgFAAg");
	this.shape_38.setTransform(7.8,12);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,107,125);


(lib.CTA_btn = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#00FFFF").s().p("A6PV3MAAAgruMA0eAAAMAAAArug");
	this.shape.setTransform(168,140);
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(3).to({_off:false},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = null;


(lib.border336x280 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,0,3).p("EgMaguyIY1AAMAAABdlI41AAg");
	this.shape.setTransform(-20,0,0.748,1);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-80.5,-300.5,121,601);


(lib.blocks = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#005A8C").s().p("AjyDwIAAnfIHlAAIAAHfg");
	this.shape.setTransform(6,87.3);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#557C6B").s().p("AjyDqIAAnTIHlAAIAAHTg");
	this.shape_1.setTransform(6,39.7);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#92AF2B").s().p("AjyDzIAAnlIHlAAIAAHlg");
	this.shape_2.setTransform(6,-8.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-18.3,-32.4,48.7,143.8);


(lib.LogoLockkup120x600 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.blocks();
	this.instance.setTransform(147.5,283.9,1,1,90,0,0,150,12.5);

	this.instance_1 = new lib.TEC_logostackrev("synched",0);
	this.instance_1.setTransform(200.6,48.3,0.576,0.576,0,0,0,181.3,32.2);

	this.shape = new cjs.Shape();
	this.shape.graphics.f("#193670").s().p("AxCRYIAAk6IgEAAIAA7ZQAAiRCIgJIAAgBId5AAIAAABQCIAJAACRIAAENQADAUAAAaIAAbYg");
	this.shape.setTransform(109.5,54.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape},{t:this.instance_1},{t:this.instance}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,-57,219,222.4);


// stage content:
(lib.TEC201609_Garden_120x600_AdR = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.clickthru_btn.on("click", function(evt){
		  window.open(clickTag, "_blank");
		});
	}
	this.frame_125 = function() {
		this.stop();
		 
		this.replay_btn.addEventListener("click", fl_ClickToGoToAndPlayFromFrame.bind(this));
		function fl_ClickToGoToAndPlayFromFrame() 
		{
		this.gotoAndPlay(1);
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(125).call(this.frame_125).wait(1));

	// replay btn
	this.replay_btn = new lib.replaybtn();
	this.replay_btn.setTransform(101,443,0.75,0.75);
	this.replay_btn._off = true;
	new cjs.ButtonHelper(this.replay_btn, 0, 1, 2, false, new lib.replaybtn(), 3);

	this.timeline.addTween(cjs.Tween.get(this.replay_btn).wait(125).to({_off:false},0).wait(1));

	// cta btn
	this.clickthru_btn = new lib.CTA_btn();
	this.clickthru_btn.setTransform(0,-0.2,0.357,2.143,0,0,0,-0.1,-0.1);
	new cjs.ButtonHelper(this.clickthru_btn, 0, 1, 2, false, new lib.CTA_btn(), 3);

	this.timeline.addTween(cjs.Tween.get(this.clickthru_btn).wait(126));

	// border
	this.instance = new lib.border336x280();
	this.instance.setTransform(80,300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(126));

	// head1
	this.instance_1 = new lib.head1("synched",0);
	this.instance_1.setTransform(12,189);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(126));

	// sub1
	this.instance_2 = new lib.sub1("synched",0);
	this.instance_2.setTransform(657,1261.5,5,5,0,0,0,131.4,220.7);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(66).to({_off:false},0).to({scaleX:1,scaleY:1,x:143.4,y:549.7},5).wait(55));

	// logo block
	this.instance_3 = new lib.LogoLockkup120x600();
	this.instance_3.setTransform(93.4,665.8,0.616,0.616,0,0,0,150,50);
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(118).to({_off:false},0).to({y:528.8},5).wait(3));

	// pic
	this.instance_4 = new lib.pic();
	this.instance_4.setTransform(-241,0,0.85,0.85);

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(126));

	// bkgd
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("EgJXAu4MAAAhdvISuAAMAAABdvg");
	this.shape.setTransform(60,300);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(126));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-181,300,437.9,600);

})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{});
var lib, images, createjs, ss;