(function (lib, img, cjs, ss) {

var p; // shortcut to reference prototypes
lib.webFontTxtFilters = {}; 

// library properties:
lib.properties = {
	width: 728,
	height: 90,
	fps: 18,
	color: "#CCCCCC",
	opacity: 1.00,
	webfonts: {},
	manifest: [
		{src:"images/_336x280gardener.jpg", id:"_336x280gardener"}
	]
};



lib.ssMetadata = [];


lib.webfontAvailable = function(family) { 
	lib.properties.webfonts[family] = true;
	var txtFilters = lib.webFontTxtFilters && lib.webFontTxtFilters[family] || [];
	for(var f = 0; f < txtFilters.length; ++f) {
		txtFilters[f].updateCache();
	}
};
// symbols:



(lib._336x280gardener = function() {
	this.initialize(img._336x280gardener);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,515,200);


(lib.TEC_logorev = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// TEC_logo-rev.ai
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AhBBcIAAjjIAJgDIAYgKQAUgKAKgIIADADIAABbIAvgCIABAbIgwgBIAACaQAAAJAGAGQAIAIAOgDQAQgDAPgPIAGACIAAABIgFAXIAAAAQAAADgMAKQgOAMgOAEQgMAEgKAAQhAAAAAhLg");
	this.shape.setTransform(42.1,-10.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("Ag+BcIAAiMIguAAIAAgaIAuACIAAg/IAJgDIAXgKQAVgKAJgIIAEADIAABbIBpAAIgBAYIhoAAIAACaQAAAJAGAGQAIAIANgDQARgDAPgPIAGACIAAABIgFAXIAAAAQgBADgLAKQgOAMgOAEQgMAEgMAAQg+AAAAhLg");
	this.shape_1.setTransform(25.5,-10.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AhUB5IAAjsIBHAAIgBAuIABABQAIgUASgQQAWgQAWAAQANAAAPAEIgBABQgVAVgLAgIgCADIgDgBQgHgCgHAAQgWAAgMAPQgMAOAAAUIAACGg");
	this.shape_2.setTransform(-14.8,-6.5);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgnBzQgZgKgPgTQgOgRgHgXQgGgVAAgYQgBgZAKgYQAKgZAQgPQAQgRAZgKQAagJAaAAQAdAAATAGQAVAHARAKQgIALgEANIgEALIgHAAQgJgPgOgIQgQgKgSAAIgBAAQgcAAgPAbQgPAbAAAvQAAAsATAZQARAYAkAAQAPAAAPgHQAOgIAHgIIAGAEIgGAPIgFAPQgKAIgRAGQgSAFgWABQgiAAgZgLg");
	this.shape_3.setTransform(166.8,-6.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AggB2QgXgHgPgOQgQgPgKgZQgKgYAAggQAAgeAJgYQAIgXAQgRQAOgPAWgIQAUgJAYABQAxAAAZAcQAaAcAAA1IAAAPIiMAAQAAATAEASQAEAQAIAPQAIANALAHQANAHARAAQAhAAAkgdIAGACIAAABIgEAXQgQASgdAKQgSAFgcABQgVAAgXgIgAApgVQgBglgIgVQgIgXgTAAQgJAAgIAHQgHAIgEALQgEALgDAPIgDAdIBKAAIAAAAg");
	this.shape_4.setTransform(3,-6.3);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AggB2QgXgHgPgOQgSgQgIgYQgKgYAAggQAAgeAJgYQAHgXAQgRQAPgPAVgIQAVgJAXABQAyAAAaAcQAaAdAAA0IAAAPIiNAAQAAATAEASQADAQAJAPQAIANALAHQANAHAQAAQAiAAAkgdIAGACIAAABIgEAXQgQASgdAKQgSAFgcABQgVAAgXgIgAAogVQAAglgJgVQgHgXgUAAQgJAAgHAHQgHAIgEALQgEALgDAPIgDAdIBJAAIAAAAg");
	this.shape_5.setTransform(-37.3,-6.3);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AggB2QgXgHgQgOQgQgPgKgZQgJgYgBggQABgeAIgYQAJgXAPgRQAOgPAWgIQAVgJAXABQAyAAAZAcQAaAdAAA0IAAAPIiMAAQAAATAEASQAFASAHANQAIANALAHQANAHARAAQAgAAAlgdIAGACIAAABIgEAXQgQASgdAKQgSAFgcABQgWAAgWgIgAApgVQgBglgIgVQgJgXgSAAQgJAAgIAHQgHAIgEALQgEALgDAPIgDAdIBKAAIAAAAg");
	this.shape_6.setTransform(-118.1,-6.3);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgPB2IgOAAIhEi8IgSgvIAUABIA4gBIA1CrIACAAIAehVIAdhWIAUACIAVgCIgTAsIgYA4IgaBAQgQAsgJAbg");
	this.shape_7.setTransform(-58.8,-6.3);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AheC7IAAl1IBXADIBAgBIAmgCQgCALAAAKIACAXIgggCIgggCIgdgCIgUgBIAABmIBWgEIAPApQg8gDgpAAIAACkIA5gBQAfgCAZgDIgBAWIAAAMIABAIg");
	this.shape_8.setTransform(-81.2,-13.1);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AggB3IAAjtIAPACIARABQAOAAATgDIAADtg");
	this.shape_9.setTransform(149,-6.3);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AggB3IAAjtIAOACIASABQANAAAUgDIAADtg");
	this.shape_10.setTransform(111.6,-6.3);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AASC6IgxABIAAl1IAOACIARABIASgBIAOgCIAAF1g");
	this.shape_11.setTransform(100,-13.1);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgaA2IAAhpIAPAAIAAAWQALgZAZABIABAAIAAAPIgBAAQgPgBgKAKQgLALAAARIAAA3g");
	this.shape_12.setTransform(36.7,22.9);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AAZA1IgZhVIgYBVIgPAAIgjhpIAQAAIAaBWIAZhWIAOAAIAaBWIAahWIAQAAIgjBpg");
	this.shape_13.setTransform(91.8,23);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgCBAQgFgGAAgNIAAhGIgTAAIAAgMIATAAIAAggIAMAAIAAAgIAWAAIAAAMIgWAAIAABEQAAAHACADQACADAGAAIAMAAIAAANIgNABQgNgBgDgFg");
	this.shape_14.setTransform(49.7,21.5);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AAdBJIAAhCQAAgdgaAAQgMAAgJAJQgJAKAAAOIAAA+IgPAAIAAiRIAPAAIAAA4QAEgIAJgGQAJgFAJAAQAUAAAKAKQAJAKAAAUIAABEg");
	this.shape_15.setTransform(60,20.9);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgpCzQgjgOgXgXQgXgXgNgjQgNgiAAglQABg1AQgoQAPgnAcgZQAbgZAkgLQAggLAoAAQAPAAANACIAbAFQARAFAJAEQALAEAJAGIgHAbQgCANgCAPIgHAAQgRgZgWgMQgSgLgcAAQgVAAgTAJQgSAKgRAVQgPASgLAgQgKAgAAApQAAApAKAeQALAeAQASQARATATAJQAWAIAUAAQANAAAMgDQANgEALgEQALgFALgIQALgHAIgKIAGAFIgGAWQgDAOgBAKQgpAWg8AAQgqAAghgNg");
	this.shape_16.setTransform(76.7,-12.9);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AghApQgNgPAAgaQAAgVALgPQANgTAWAAQAVAAALANQAPAPAAAbIAAAEIhPAAQABAQAIALQAJANAOAAQAaAAAGgbIABAAIAOAAIAAABQgJAmgmAAQgUAAgNgPgAAhgHQgCgOgHgLQgJgLgPABQgMgBgKALQgHALgDAOIBBAAIAAAAg");
	this.shape_17.setTransform(71.4,23);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AAcBJIAAhCQAAgdgaAAQgMAAgIAJQgJAKgBAOIAAA+IgOAAIAAiRIAOAAIAAA4QAKgTAWAAQAUAAAKAKQAJAKAAAUIAABEg");
	this.shape_18.setTransform(105.9,20.9);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AglAmQgMgQAAgWQAAgWAMgPQAOgSAXAAQAYAAAOASQAMAPAAAWQAAAWgMAQQgOASgYAAQgXAAgOgSgAgagdQgJANAAAQQAAARAJAMQAKAPAQAAQAQAAAKgPQAJgMAAgRQAAgQgJgNQgKgOgQABQgQgBgKAOg");
	this.shape_19.setTransform(117.2,23);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgIALIAAgVIARAAIAAAVg");
	this.shape_20.setTransform(180.5,27.1);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgqAOIAAhEIAPAAIAABEQAAAcAbAAQANAAAIgNQAHgMAAgQIAAg3IAPAAIAABpIgOAAIAAgRQgLAUgWABQgmAAAAgpg");
	this.shape_21.setTransform(173.2,23.1);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgGBJIAAiRIANAAIAACRg");
	this.shape_22.setTransform(125.3,20.9);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AghApQgNgPgBgaQAAgVALgPQANgTAXAAQAUAAAMANQAQAPAAAbIAAAEIhPAAQAAAQAIALQAJANAOAAQAZAAAHgbIAAAAIAPAAIAAABQgJAmgmAAQgVAAgMgPgAAggHQAAgOgJgLQgJgLgOABQgMgBgJALQgJALgBAOIA/AAIAAAAg");
	this.shape_23.setTransform(133.1,23);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AgbBJIgIgCIgBAAIAAgNIAKABQAHAAAEgDQACgDAEgJIAFgMIgrhoIAQAAIAgBWIAghWIAPAAIgvB5QgEAOgFAFQgFAEgMABg");
	this.shape_24.setTransform(150.7,24.9);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AglAmQgMgQAAgWQAAgWAMgPQAOgSAXAAQAYAAAOASQAMAPAAAWQAAAWgMAQQgOASgYAAQgXAAgOgSgAgagdQgJANAAAQQAAARAJAMQAKAPAQAAQARAAAKgPQAIgMAAgRQAAgQgIgNQgKgOgRABQgQgBgKAOg");
	this.shape_25.setTransform(161.6,23);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("ABaB5IgjAAIgPABIAAiNIgCgaQgBgLgEgGQgLgPgUAAQgTAAgLATQgKAUAAAiIAAB+IgQgBIgzABIAAjtIAQACIAQABIATgBIAQgCIAAAlIABABQANgVARgLQASgMAXAAQAgAAAUAWQAUAVAAAvIAACZIgQgBg");
	this.shape_26.setTransform(130.5,-6.6);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("ABeC6IgnAAIgQABIAAiPIAAgaQgCgLgFgGQgKgNgTAAQgVAAgKARQgKAUAAAiIAACAIgQgBIg3ABIAAl1IAQACIATABIAUgBIAQgCIAACtIABABQANgVASgLQAQgMAXAAQAlAAAUAWQAUAVAAAtIAACbIgQgBg");
	this.shape_27.setTransform(-142.5,-13.1);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AgjC6IAAlNIhbAGIAAgsIBZADICkgDIAAAWIAAAWIhYgGIAAFNg");
	this.shape_28.setTransform(-168.7,-13.2);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AgtBJIAAiRIBbAAIAAAOIhMAAIAAAyIBEAAIAAAMIhEAAIAABFg");
	this.shape_29.setTransform(15.1,20.9);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("AglAmQgMgQAAgWQAAgWAMgPQAOgSAXAAQAYAAAOASQAMAPAAAWQAAAWgMAQQgOASgYAAQgXAAgOgSgAgagdQgIANAAAQQAAARAIAMQAKAPAQAAQARAAAKgPQAJgMAAgRQAAgQgJgNQgKgOgRABQgQgBgKAOg");
	this.shape_30.setTransform(26.1,23);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("AgYAbQgLgMAAgPQAAgOALgLQALgMANAAQAPAAAKAMQALALAAAOQAAAQgLALQgKALgPAAQgNAAgLgLg");
	this.shape_31.setTransform(149.1,-26.8);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FFFFFF").s().p("AgYAbQgLgMAAgPQAAgOALgLQAKgMAOAAQAPAAAKAMQALALAAAOQAAAPgLAMQgKALgPAAQgOAAgKgLg");
	this.shape_32.setTransform(111.5,-26.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-181.4,-32.2,362.9,64.4);


(lib.sub1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// type
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#6B8A21").s().p("AAAAHQgGAAAAgHIAAAAQAAgGAGAAIAAAAQAHAAAAAGIAAAAQAAAHgHAAg");
	this.shape.setTransform(463.2,16.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#6B8A21").s().p("AAhAuQgEAAAAgFIAAgtQAAgHgCgGQgCgGgDgEQgDgFgGgCQgFgCgGAAQgEAAgFACIgJAEQgEACgDAEIgFAJIAAA4QAAAFgEAAIgBAAQgEAAAAgFIAAhTIADgBQABAAAAAAQABAAAAAAQABABAAAAQABAAAAABQACACAAAFIAAAIIAFgHQADgEAFgCIAJgEQAFgCADAAQAJAAAHADQAGADAFAFQAFAGACAHQACAHAAAKIAAAtQAAAFgEAAg");
	this.shape_1.setTransform(456.3,12.6);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#6B8A21").s().p("AgRArQgJgDgFgHQgHgHgDgIQgEgIAAgKQAAgJAEgIQADgJAHgGQAFgGAJgEQAJgDAIAAQAJAAAJADQAIAEAGAGQAGAGAEAJQAEAJAAAIQAAAKgEAIQgEAJgGAGQgGAHgIADQgJAEgJgBQgIABgJgEgAgNgjQgHADgFAGQgFAFgCAHQgEAIAAAGQAAAIAEAHQACAHAFAFQAFAFAHADQAHADAGAAQAHAAAHgDQAHgCAEgGQAGgFACgHQADgHAAgIQAAgGgDgIQgDgGgEgGQgFgGgHgDQgHgCgHAAQgGAAgHACg");
	this.shape_2.setTransform(445.9,12.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#6B8A21").s().p("AAAA/QgDAAAAgEIAAhQQAAgFADAAIAAAAQAEAAAAAFIAABQQAAAEgEAAgAgFg4QAAgGAFAAQAGAAAAAGQAAAHgGgBQgFABAAgHg");
	this.shape_3.setTransform(438.8,10.9);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#6B8A21").s().p("AgSArQgHgDgFgEQgEgEAAgEQAAgDAFgBQAEAGAHAEIAJADQAFACAEAAQAGAAAFgCIAIgDQAEgCABgEQACgDAAgDQAAgFgCgDQgCgDgEgCQgEgDgOgDQgPgDgGgBQgFgDgDgFQgDgEAAgGQAAgGADgFQACgFAFgDQAEgEAGgCQAGgBAGAAQAKAAAIACQAHADAEAFQADADAAAEQAAAAAAAAQAAABAAAAQAAABgBAAQAAABgBAAIgCABQgEgGgHgEQgIgDgJAAIgJABIgHADQgEADgBADQgCACAAAFQAAADACADIAFAFQAFADANADIAMADQAGAAAEACQAFADADAEQADAEAAAHQAAAGgCAFQgDAFgEADQgFADgGACQgHACgIAAQgJABgJgEg");
	this.shape_4.setTransform(432.7,12.7);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#6B8A21").s().p("AgSArQgHgDgFgEQgEgEAAgEQAAgDAFgBQAEAGAHAEIAJADQAFACAEAAQAGAAAFgCIAIgDQAEgCABgEQACgDAAgDQAAgFgCgDQgCgDgEgCQgEgDgOgDQgPgDgGgBQgFgDgDgFQgDgEAAgGQAAgGADgFQACgFAFgDQAEgEAGgCQAGgBAGAAQAKAAAIACQAHADAEAFQADADAAAEQAAAAAAAAQAAABAAAAQgBABAAAAQAAABgBAAIgCABQgEgGgHgEQgIgDgJAAIgJABIgHADQgEADgBADQgCACAAAFQAAADACADIAFAFQAFADANADIAMADQAGAAAEACQAFADADAEQADAEAAAHQAAAGgCAFQgDAFgEADQgFADgGACQgHACgIAAQgJABgJgEg");
	this.shape_5.setTransform(424.3,12.7);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#6B8A21").s().p("AgPArQgIgEgGgFQgGgHgDgJQgDgIAAgKQAAgIADgJQADgJAGgGQAGgGAIgEQAJgDAIAAQAJAAAHADQAIADAFAGQAFAFADAJQADAIABAKIAAABQgBABgEAAIhGAAQgBAIADAHQADAHAFAFQAFAFAGACQAHADAGAAQAHAAAGgBQAFgBAEgDQAGgFAFgIIACABQADACAAADQAAADgGAGQgFAFgHADQgJAEgLgBQgIABgJgEgAAhgFQAAgHgDgGQgCgGgEgEQgFgFgFgCQgGgDgGABQgGgBgFADQgGADgGAEQgEAEgDAGQgDAGgBAHIBBAAIAAAAg");
	this.shape_6.setTransform(415.2,12.7);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#6B8A21").s().p("AgSArQgHgDgFgEQgEgEAAgEQAAgDAFgBQAEAGAHAEIAJADQAFACAEAAQAGAAAFgCIAIgDQAEgCABgEQACgDAAgDQAAgFgCgDQgCgDgEgCQgEgDgOgDQgPgDgGgBQgFgDgDgFQgDgEAAgGQAAgGADgFQACgFAFgDQAEgEAGgCQAGgBAGAAQAKAAAIACQAHADAEAFQADADAAAEQAAAAAAAAQAAABAAAAQAAABgBAAQAAABgBAAIgCABQgEgGgHgEQgIgDgJAAIgJABIgHADQgEADgBADQgCACAAAFQAAADACADIAFAFQAFADANADIAMADQAGAAAEACQAFADADAEQADAEAAAHQAAAGgCAFQgDAFgEADQgFADgGACQgHACgIAAQgJABgJgEg");
	this.shape_7.setTransform(405.9,12.7);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#6B8A21").s().p("AgRArQgIgDgHgHQgGgHgDgIQgEgIABgKQgBgJAEgIQADgJAGgGQAHgGAIgEQAIgDAJAAQAKAAAIADQAIAEAHAGQAGAGADAJQADAJAAAIQAAAKgDAIQgDAJgGAGQgHAHgIADQgIAEgKgBQgJABgIgEgAgNgjQgHADgFAGQgFAFgDAHQgCAIAAAGQAAAIACAHQADAHAFAFQAFAFAHADQAGADAHAAQAHAAAHgDQAHgCAFgGQAEgFAEgHQACgHAAgIQAAgGgCgIQgEgGgEgGQgFgGgHgDQgHgCgHAAQgHAAgGACg");
	this.shape_8.setTransform(393.2,12.7);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#6B8A21").s().p("AgGBBQgEAAAAgEIAAhMIgPAAQgEAAAAgEIAAgBQAAgDAEgBIAPAAIAAgJQAAgIACgFQABgGADgFIAGgFQAFgCAGAAIAJABIAGADQACADAAADIgBADIgBABQgDgDgEgBQgEgCgEAAIgHABQgDABgCADIgBAIIgBAKIAAAJIASAAQAEABAAADIAAABQAAAEgEAAIgSAAIAABMQAAAEgEAAg");
	this.shape_9.setTransform(385.3,10.7);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#6B8A21").s().p("AAhAuQgEAAAAgFIAAgtQAAgHgCgGQgCgGgDgEQgDgFgGgCQgFgCgGAAQgEAAgFACIgJAEQgEACgDAEIgFAJIAAA4QAAAFgEAAIgBAAQgEAAAAgFIAAhTIADgBQAAAAABAAQABAAAAAAQABABAAAAQABAAAAABQACACAAAFIAAAIIAFgHQADgEAFgCIAJgEQAFgCADAAQAJAAAHADQAGADAFAFQAFAGACAHQACAHAAAKIAAAtQAAAFgEAAg");
	this.shape_10.setTransform(376.9,12.6);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#6B8A21").s().p("AAAA/QgDAAAAgEIAAhQQAAgFADAAIAAAAQAEAAAAAFIAABQQAAAEgEAAgAgFg4QAAgGAFAAQAGAAAAAGQAAAHgGgBQgFABAAgHg");
	this.shape_11.setTransform(369.9,10.9);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#6B8A21").s().p("AgPArQgIgEgGgFQgGgHgDgJQgDgIgBgKQABgIADgJQADgJAGgGQAGgGAIgEQAJgDAHAAQAKAAAHADQAIADAFAGQAFAFADAJQADAIABAKIAAABQgBABgEAAIhHAAQABAIACAHQADAHAFAFQAFAFAGACQAIADAFAAQAHAAAGgBQAFgBAEgDQAGgFAFgIIADABQACACAAADQAAADgGAGQgFAFgHADQgJAEgLgBQgIABgJgEgAAhgFQAAgHgDgGQgCgGgEgEQgFgFgFgCQgGgDgHABQgFgBgFADQgGADgGAEQgEAEgDAGQgDAGgBAHIBBAAIAAAAg");
	this.shape_12.setTransform(359.8,12.7);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#6B8A21").s().p("AgPArQgHgEgHgFQgGgHgDgJQgEgIAAgKQAAgIAEgJQADgJAHgGQAFgGAIgEQAJgDAHAAQAJAAAIADQAIADAFAGQAFAFAEAJQACAIAAAKIAAABQAAABgDAAIhIAAQABAIADAHQACAHAFAFQAFAFAHACQAGADAHAAQAGAAAGgBQAFgBAEgDQAHgFADgIIADABQADACAAADQAAADgGAGQgFAFgHADQgJAEgKgBQgIABgKgEgAAhgFQAAgHgCgGQgDgGgEgEQgEgFgGgCQgGgDgHABQgFgBgGADQgFADgFAEQgFAEgDAGQgDAGgBAHIBBAAIAAAAg");
	this.shape_13.setTransform(349.9,12.7);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#6B8A21").s().p("AgRAuQgFAAAAgFIAAhTIADgBQABAAABAAQAAAAABAAQAAABABAAQAAAAABABQABACAAAFIAAALIAEgKQACgEAEgCIAFgEQADgCAFAAQAFAAAEADQAEACAAADIgBAEIgCABQgEgEgHAAQgGAAgDADQgEADgDAFQgDAFgBAIIgBAOIAAAnQAAAFgEAAg");
	this.shape_14.setTransform(342.3,12.6);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#6B8A21").s().p("AgGBBQgEAAAAgEIAAhMIgPAAQgEAAAAgEIAAgBQAAgDAEgBIAPAAIAAgJQAAgIACgFQABgGADgFIAGgFQAFgCAGAAIAJABIAGADQACADAAADIgBADIgBABQgDgDgEgBQgEgCgEAAIgHABQgDABgCADIgBAIIgBAKIAAAJIASAAQAEABAAADIAAABQAAAEgEAAIgSAAIAABMQAAAEgEAAg");
	this.shape_15.setTransform(336,10.7);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#6B8A21").s().p("AgSAtQgGgCgEgDQgEgDgCgFQgCgFAAgFQAAgIADgFQAEgGAIgDQAIgCANgBQAKgCAQAAIACAAIAAgFQAAgGgCgFQgCgFgDgEQgDgDgGgCQgFgCgGAAQgEAAgFACQgFABgEACQgHAFgDAHQgGAAAAgFQAAgEAGgFQAEgFAHgCQAJgEAIAAQAJAAAHACQAGADAFAEQAEAFADAGQADAHgBAIIAAA2IgDABQgBAAAAAAQgBAAAAAAQgBAAAAgBQgBAAAAAAQgBgDgBgFIAAgJIgFAIIgIAGIgKAEIgLABQgGAAgGgBgAABABQgIACgIACQgGADgDAEQgDAEAAAGQAAAEACADQABADADACQADADAEABQAEABAFAAQAGAAAGgCQAGgDAFgEQAFgEADgFQACgGAAgGIAAgJIgCAAIgZABg");
	this.shape_16.setTransform(324.5,12.7);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#6B8A21").s().p("AgRAuQgFAAAAgFIAAhTIADgBQABAAABAAQAAAAABAAQAAABABAAQAAAAABABQABACAAAFIAAALIAEgKQACgEAEgCIAFgEQADgCAFAAQAFAAAEADQAEACAAADIgBAEIgCABQgEgEgHAAQgGAAgDADQgEADgDAFQgDAFgBAIIgBAOIAAAnQAAAFgEAAg");
	this.shape_17.setTransform(314.1,12.6);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#6B8A21").s().p("AgRArQgIgDgHgHQgGgHgDgIQgDgIAAgKQAAgJADgIQADgJAGgGQAHgGAIgEQAIgDAJAAQAKAAAIADQAIAEAHAGQAFAGAEAJQAEAJgBAIQABAKgEAIQgEAJgFAGQgHAHgIADQgIAEgKgBQgJABgIgEgAgNgjQgHADgFAGQgFAFgDAHQgDAIAAAGQAAAIADAHQADAHAFAFQAFAFAHADQAGADAHAAQAIAAAGgDQAHgCAEgGQAFgFAEgHQACgHAAgIQAAgGgCgIQgDgGgFgGQgFgGgHgDQgGgCgIAAQgHAAgGACg");
	this.shape_18.setTransform(305.2,12.7);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#6B8A21").s().p("AgGBBQgEAAAAgEIAAhMIgPAAQgEAAAAgEIAAgBQAAgDAEgBIAPAAIAAgJQAAgIACgFQABgGADgFIAGgFQAFgCAGAAIAJABIAGADQACADAAADIgBADIgBABQgDgDgEgBQgEgCgEAAIgHABQgDABgCADIgBAIIgBAKIAAAJIASAAQAEABAAADIAAABQAAAEgEAAIgSAAIAABMQAAAEgEAAg");
	this.shape_19.setTransform(297.3,10.7);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#6B8A21").s().p("AgRAuQgFAAAAgFIAAhTIADgBQABAAABAAQAAAAABAAQAAABABAAQAAAAABABQABACAAAFIAAALIAEgKQACgEAEgCIAFgEQADgCAFAAQAFAAAEADQAEACAAADIgBAEIgCABQgEgEgHAAQgGAAgDADQgEADgDAFQgDAFgBAIIgBAOIAAAnQAAAFgEAAg");
	this.shape_20.setTransform(288.1,12.6);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#6B8A21").s().p("AgPArQgHgEgHgFQgGgHgDgJQgEgIAAgKQAAgIAEgJQADgJAHgGQAGgGAHgEQAJgDAHAAQAJAAAIADQAIADAFAGQAGAFADAJQADAIAAAKIAAABQAAABgFAAIhHAAQAAAIAEAHQACAHAFAFQAFAFAHACQAGADAGAAQAHAAAGgBQAFgBAEgDQAHgFADgIIADABQADACAAADQAAADgGAGQgEAFgIADQgJAEgLgBQgHABgKgEgAAhgFQAAgHgCgGQgDgGgEgEQgEgFgGgCQgGgDgHABQgFgBgFADQgHADgEAEQgFAEgDAGQgDAGgBAHIBBAAIAAAAg");
	this.shape_21.setTransform(279.6,12.7);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#6B8A21").s().p("AAAA2QgDgBgCgDQgDgEgCgFQgBgFgBgIIAAg1IgKAAQgFAAAAgEIAAgBQAAgDAFgBIAKAAIAAgRQAAgFAFABIABAAQADgBAAAFIAAARIAZAAQAEABAAADIAAABQAAAEgEAAIgZAAIAAA0QABAMACAFQACAEAJAAQAEAAAEgCQADgCADgDIACABIABADQAAADgDADQgCADgDABQgFABgFAAQgGAAgEgCg");
	this.shape_22.setTransform(271.4,11.7);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#6B8A21").s().p("AgSArQgHgDgFgEQgEgEAAgEQAAgDAFgBQAEAGAHAEIAJADQAFACAEAAQAGAAAFgCIAIgDQAEgCABgEQACgDAAgDQAAgFgCgDQgCgDgEgCQgEgDgOgDQgPgDgGgBQgFgDgDgFQgDgEAAgGQAAgGADgFQACgFAFgDQAEgEAGgCQAGgBAGAAQAKAAAIACQAHADAEAFQADADAAAEQAAAAAAAAQAAABAAAAQAAABgBAAQAAABgBAAIgCABQgEgGgHgEQgIgDgJAAIgJABIgHADQgEADgBADQgCACAAAFQAAADACADIAFAFQAFADANADIAMADQAGAAAEACQAFADADAEQADAEAAAHQAAAGgCAFQgDAFgEADQgFADgGACQgHACgIAAQgJABgJgEg");
	this.shape_23.setTransform(264,12.7);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#6B8A21").s().p("AAAA/QgDAAAAgEIAAhQQAAgFADAAIAAAAQAEAAAAAFIAABQQAAAEgEAAgAgFg4QAAgGAFAAQAGAAAAAGQAAAHgGgBQgFABAAgHg");
	this.shape_24.setTransform(258,10.9);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#6B8A21").s().p("AgTBEQgHgBgFgDQgGgEgCgEQgDgFAAgGQAAgFADgEQACgEAEgEIAKgGIAMgDQgEgCgBgCQgCgCAAgEQAAgFAFgEQgFAAgEgCIgHgHQgDgEgBgEQgDgFAAgFQAAgHAEgGQACgGAFgEQAFgFAGgCQAHgDAHAAQAEAAAHACQAFACAFADIAIgLQADgGAFACQADABAAADIgOAQQAEAEACAFQACAFAAAGQAAAHgDAGQgCAGgFAEQgFAEgGABQgIACgFAAIgGAAQgDACgBAEQAAAEAIADIAQAEIAKAEIAJAEQAFADACAEQADAEAAAFQAAAHgDAFQgDAEgGAEQgGADgIACQgIACgJAAQgKAAgJgCgAgMAaIgLAFIgHAGQgDAEAAAEQAAAEACAEQACADAFACIAKADIAOABIANgBQAGgBAFgDQAFgCACgDQADgEgBgEQABgEgCgCIgFgFQgFgDgKgDIgMgDIgMACgAgLgzQgEACgEAEQgDADgCAEQgCAFAAAFQAAAGACAEQACAFADADQAEAEAEABQAFACAGAAQAEAAAFgCQAEgBAEgEQAEgDACgFQABgEAAgGQAAgFgBgFQgCgEgEgDQgEgEgEgCQgFgBgEAAQgGAAgFABg");
	this.shape_25.setTransform(252,14.2);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#6B8A21").s().p("AgPArQgHgEgHgFQgGgHgDgJQgEgIAAgKQAAgIAEgJQADgJAHgGQAGgGAHgEQAJgDAHAAQAJAAAIADQAIADAFAGQAGAFADAJQADAIAAAKIAAABQAAABgFAAIhHAAQAAAIAEAHQACAHAFAFQAFAFAHACQAGADAGAAQAHAAAGgBQAFgBAEgDQAHgFADgIIADABQADACAAADQAAADgGAGQgEAFgIADQgJAEgLgBQgHABgKgEgAAhgFQAAgHgCgGQgDgGgEgEQgEgFgGgCQgGgDgHABQgFgBgFADQgHADgEAEQgFAEgDAGQgDAGgBAHIBBAAIAAAAg");
	this.shape_26.setTransform(242.7,12.7);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#6B8A21").s().p("AgRAuQgFAAAAgFIAAhTIADgBQABAAABAAQAAAAABAAQAAABABAAQAAAAABABQABACAAAFIAAALIAEgKQACgEAEgCIAFgEQADgCAFAAQAFAAAEADQAEACAAADIgBAEIgCABQgEgEgHAAQgGAAgDADQgEADgDAFQgDAFgBAIIgBAOIAAAnQAAAFgEAAg");
	this.shape_27.setTransform(235.1,12.6);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#6B8A21").s().p("AgRAuQgFAAAAgFIAAhTIADgBQABAAABAAQAAAAABAAQAAABABAAQAAAAABABQABACAAAFIAAALIAEgKQACgEAEgCIAFgEQADgCAFAAQAFAAAEADQAEACAAADIgBAEIgCABQgEgEgHAAQgGAAgDADQgEADgDAFQgDAFgBAIIgBAOIAAAnQAAAFgEAAg");
	this.shape_28.setTransform(225.6,12.6);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#6B8A21").s().p("AgRArQgIgDgHgHQgGgHgDgIQgEgIABgKQgBgJAEgIQADgJAGgGQAHgGAIgEQAJgDAIAAQAKAAAIADQAIAEAGAGQAHAGADAJQADAJABAIQgBAKgDAIQgDAJgHAGQgGAHgIADQgIAEgKgBQgIABgJgEgAgNgjQgHADgFAGQgFAFgCAHQgDAIAAAGQAAAIADAHQACAHAFAFQAFAFAHADQAGADAHAAQAHAAAHgDQAHgCAFgGQAEgFAEgHQACgHAAgIQAAgGgCgIQgDgGgFgGQgFgGgHgDQgHgCgHAAQgHAAgGACg");
	this.shape_29.setTransform(216.7,12.7);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#6B8A21").s().p("AgPArQgHgEgHgFQgGgHgDgJQgEgIAAgKQAAgIAEgJQADgJAHgGQAFgGAIgEQAJgDAHAAQAJAAAIADQAIADAFAGQAFAFAEAJQACAIAAAKIAAABQABABgEAAIhIAAQABAIADAHQACAHAFAFQAFAFAHACQAGADAHAAQAGAAAGgBQAFgBAEgDQAHgFADgIIADABQADACAAADQAAADgGAGQgFAFgHADQgJAEgKgBQgIABgKgEgAAhgFQAAgHgCgGQgDgGgEgEQgEgFgGgCQgGgDgHABQgFgBgFADQgGADgFAEQgFAEgDAGQgDAGgBAHIBBAAIAAAAg");
	this.shape_30.setTransform(203.2,12.7);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#6B8A21").s().p("AgRAuQgFAAAAgFIAAhTIADgBQABAAABAAQAAAAABAAQAAABABAAQAAAAABABQABACAAAFIAAALIAEgKQACgEAEgCIAFgEQADgCAFAAQAFAAAEADQAEACAAADIgBAEIgCABQgEgEgHAAQgGAAgDADQgEADgDAFQgDAFgBAIIgBAOIAAAnQAAAFgEAAg");
	this.shape_31.setTransform(195.6,12.6);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#6B8A21").s().p("AgRArQgJgDgFgHQgHgHgDgIQgEgIAAgKQAAgJAEgIQADgJAHgGQAFgGAJgEQAJgDAIAAQAJAAAJADQAIAEAGAGQAGAGAEAJQAEAJAAAIQAAAKgEAIQgEAJgGAGQgGAHgIADQgJAEgJgBQgIABgJgEgAgNgjQgHADgFAGQgFAFgCAHQgEAIAAAGQAAAIAEAHQACAHAFAFQAFAFAHADQAHADAGAAQAHAAAHgDQAHgCAEgGQAGgFACgHQADgHAAgIQAAgGgDgIQgDgGgEgGQgFgGgHgDQgHgCgHAAQgGAAgHACg");
	this.shape_32.setTransform(186.7,12.7);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#6B8A21").s().p("AA/AuQgEAAAAgFIAAguQAAgIgCgFQgBgGgEgEQgDgEgFgCQgFgCgGAAIgJABIgIAFQgEACgDAEQgDAEgCAFIAAA4QAAAFgEAAIAAAAQgDAAAAgFIAAgwQAAgHgCgFQgBgGgEgDQgDgEgFgCQgFgCgGAAIgJABQgEACgEADQgEACgDAEQgDAEgCAFIAAA4QAAAFgEAAIgBAAQgEAAAAgFIAAhTIADgBQABAAAAAAQABAAAAAAQABABAAAAQABAAAAABQACACAAAFIAAAIQACgEADgEQADgDAEgCIAJgEQAEgCAFAAQAGAAAFACQAFABAEADIAGAHQACAEABAFQACgFADgEIAHgHQAFgDAFgBQAFgCAFAAQAJAAAGADQAHADAEAFQAEAFADAHQACAHAAAJIAAAvQAAAFgEAAg");
	this.shape_33.setTransform(173.3,12.6);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#6B8A21").s().p("AAhAuQgEAAAAgFIAAgtQAAgHgCgGQgCgGgDgEQgDgFgGgCQgFgCgGAAQgEAAgFACIgJAEQgEACgDAEIgFAJIAAA4QAAAFgEAAIgBAAQgEAAAAgFIAAhTIADgBQAAAAABAAQABAAAAAAQABABAAAAQABAAAAABQACACAAAFIAAAIIAFgHQADgEAFgCIAJgEQAFgCADAAQAJAAAHADQAGADAFAFQAFAGACAHQACAHAAAKIAAAtQAAAFgEAAg");
	this.shape_34.setTransform(156.8,12.6);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#6B8A21").s().p("AgRAuQgFAAAAgFIAAhTIADgBQABAAABAAQAAAAABAAQAAABABAAQAAAAABABQABACAAAFIAAALIAEgKQACgEAEgCIAFgEQADgCAFAAQAFAAAEADQAEACAAADIgBAEIgCABQgEgEgHAAQgGAAgDADQgEADgDAFQgDAFgBAIIgBAOIAAAnQAAAFgEAAg");
	this.shape_35.setTransform(149,12.6);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#6B8A21").s().p("AgSAtQgGgCgEgDQgEgDgCgFQgCgFAAgFQAAgIADgFQAEgGAIgDQAIgCANgBQAKgCAQAAIACAAIAAgFQAAgGgCgFQgCgFgDgEQgDgDgGgCQgFgCgGAAQgEAAgFACQgFABgEACQgHAFgDAHQgGAAAAgFQAAgEAGgFQAEgFAHgCQAJgEAIAAQAJAAAHACQAGADAFAEQAEAFADAGQADAHgBAIIAAA2IgDABQgBAAAAAAQgBAAAAAAQgBAAAAgBQgBAAAAAAQgBgDgBgFIAAgJIgFAIIgIAGIgKAEIgLABQgGAAgGgBgAABABQgIACgIACQgGADgDAEQgDAEAAAGQAAAEABADQACADADACQADADAEABQAEABAFAAQAGAAAGgCQAGgDAFgEQAFgEADgFQACgGAAgGIAAgJIgCAAIgZABg");
	this.shape_36.setTransform(140.4,12.7);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#6B8A21").s().p("AgPArQgHgEgHgFQgGgHgDgJQgDgIgBgKQABgIADgJQADgJAHgGQAGgGAHgEQAJgDAHAAQAKAAAHADQAIADAFAGQAFAFADAJQAEAIAAAKIAAABQAAABgFAAIhHAAQAAAIAEAHQACAHAFAFQAFAFAHACQAHADAFAAQAHAAAGgBQAFgBAEgDQAHgFAEgIIACABQADACAAADQAAADgGAGQgEAFgIADQgJAEgLgBQgHABgKgEgAAhgFQAAgHgDgGQgCgGgEgEQgEgFgGgCQgGgDgHABQgEgBgGADQgHADgEAEQgFAEgDAGQgDAGgBAHIBBAAIAAAAg");
	this.shape_37.setTransform(131,12.7);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#6B8A21").s().p("AAABAQgDAAAAgEIAAh6IADgBQAAAAAAAAQAAAAABAAQAAABABAAQAAAAAAABQACACAAAFIAAByQAAAEgEAAg");
	this.shape_38.setTransform(124.1,10.8);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#6B8A21").s().p("AgRArQgJgDgFgHQgHgHgDgIQgDgIgBgKQABgJADgIQADgJAHgGQAFgGAJgEQAJgDAIAAQAJAAAJADQAIAEAHAGQAFAGAEAJQADAJAAAIQAAAKgDAIQgEAJgFAGQgHAHgIADQgJAEgJgBQgIABgJgEgAgNgjQgHADgFAGQgFAFgCAHQgEAIAAAGQAAAIAEAHQACAHAFAFQAFAFAHADQAHADAGAAQAIAAAGgDQAHgCAEgGQAGgFACgHQADgHAAgIQAAgGgDgIQgDgGgEgGQgFgGgHgDQgGgCgIAAQgGAAgHACg");
	this.shape_39.setTransform(113.7,12.7);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#6B8A21").s().p("AAAA2QgCgBgDgDQgEgEgBgFQgBgFgBgIIAAg1IgKAAQgFAAAAgEIAAgBQAAgDAFgBIAKAAIAAgRQAAgFAEABIACAAQADgBAAAFIAAARIAZAAQAEABAAADIAAABQAAAEgEAAIgZAAIAAA0QABAMACAFQACAEAJAAQAFAAADgCQADgCADgDIACABIABADQAAADgDADQgCADgDABQgEABgGAAQgGAAgEgCg");
	this.shape_40.setTransform(105.3,11.7);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#6B8A21").s().p("AgkA9QgFAAAAgGIAAhtQAAgGAFAAIBIAAQAEAAAAAEIAAABQAAADgEABIhEAAIAAAuIA0AAQAFAAAAAFIAAAAQAAACgFAAIg0AAIAAAzIBGAAQAEgBAAAEIAAABQAAAEgEAAg");
	this.shape_41.setTransform(93.9,11.1);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#6B8A21").s().p("AAdA6IgtgyIgPAAIAAAxQABAEgFAAIgBAAQgEAAAAgEIAAhwQAAgFAGAAIAhAAQAJAAAIACQAIACAFAFQAGAEADAHQADAGAAAJQAAAIgDAHQgDAGgFAEQgGADgHADQgIACgJAAIgDAAIArAxQABAAAAAAQAAABgBAAQAAAAAAABQAAAAgBAAQAAABgBAAQAAABgBAAQAAAAgBAAQAAAAgBAAQgDAAgDgDgAgfAAIAfAAQAGAAAGAAQAHgCAEgDQAEgEACgFQACgFAAgGQAAgGgCgFQgCgFgFgEQgEgDgGgCQgHgCgGAAIgeAAg");
	this.shape_42.setTransform(83.2,11.1);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#6B8A21").s().p("AgkA9QgFAAAAgGIAAhtQAAgGAFAAIBIAAQAEAAAAAEIAAABQAAADgEABIhEAAIAAAuIA0AAQAFAAAAAFIAAAAQAAACgFAAIg0AAIAAAzIBGAAQAEgBAAAEIAAABQAAAEgEAAg");
	this.shape_43.setTransform(72.6,11.1);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#6B8A21").s().p("AArA+QgEAAAAgFIAAg1IhNAAIAAA1QAAAFgEAAIgBAAQgEAAAAgFIAAhxQAAgEAEAAIABAAQAEAAAAAEIAAA1IBNAAIAAg1QAAgEAEAAIABAAQAEAAAAAEIAABxQAAAFgEAAg");
	this.shape_44.setTransform(60.5,11.1);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#6B8A21").s().p("AAdA7Ig6g7IAAA5QAAAEgEAAIgCAAQgEAAAAgEIAAhxQAAgFAEAAIACAAQAEAAAAAFIAAA3IA4g5QAEgEAEACQADABgBADIg4A4IA6A4QABAEgEABIgCABQgDAAgCgDg");
	this.shape_45.setTransform(46.2,11.1);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#6B8A21").s().p("AgFA+QgHgBgFgDQgGgCgFgDIgIgIIgIgJIgEgLIgEgMIgBgNQAAgFACgHIADgLIAFgLIAHgKIAJgHQAFgEAFgCQAGgCAGgBIALgCQAJAAAQAEQAJAFAGAFQAGAHAAAFQAAADgDACIgCABQgDgFgEgFQgEgEgFgDQgFgDgHgCIgNgBIgJABIgKACQgJAEgHAIQgHAIgDAJQgEAOAAAHQACAPACAGQADAKAHAIIAIAHIAJAEIAKAEIAIABQAIAAAIgCQAGgCAGgEQAFgEADgFQAEgFACgFQAGABAAAFQgCAJgGAFQgHAHgJADQgPAFgJAAQgGAAgFgBg");
	this.shape_46.setTransform(34.6,11.1);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("#6B8A21").s().p("AAAA+QgDAAAAgFIAAhxQAAgEADAAIAAAAQAEAAAAAEIAABxQAAAFgEAAg");
	this.shape_47.setTransform(26.1,11.1);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("#6B8A21").s().p("AgeA9QgFAAgBgFIAAhwQAAgEAFAAIABAAQAEAAAAAEIAABtIA6AAQAFAAgBAEIAAAAQABAEgFAAg");
	this.shape_48.setTransform(19.7,11);

	this.shape_49 = new cjs.Shape();
	this.shape_49.graphics.f("#6B8A21").s().p("AgFA+QgGgBgGgDQgFgCgFgDIgJgIIgHgJIgGgLIgDgMIgBgNQAAgFACgHIACgLIAGgLIAHgKIAJgHQAFgEAGgCQAFgCAGgBIALgCQAKAAAOAEQAJAFAHAFQAGAHAAAFQAAADgDACIgCABQgDgFgEgFQgEgEgGgDQgEgDgHgCIgNgBIgJABIgKACQgJAEgHAIQgGAIgFAJQgDAOAAAHQABAPACAGQAFAKAGAIIAHAHIAJAEIAKAEIAKABQAIAAAGgCQAIgCAFgEQAFgEAEgFQADgFABgFQAHABAAAFQgDAJgFAFQgHAHgJADQgPAFgJAAQgGAAgFgBg");
	this.shape_49.setTransform(8.4,11.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_49},{t:this.shape_48},{t:this.shape_47},{t:this.shape_46},{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,533,23);


(lib.replaybtn = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#666666").s().p("Ak9BwIAAjgIJ6AAIAADgg");
	this.shape.setTransform(9.1,9.8,0.438,1.268,0,0,0,-0.2,0);
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(3).to({_off:false},0).wait(1));

	// Layer 2
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#BFBFBF").s().p("AgEBGQghgDgWgXQgXgZAAgfQAAgQAGgQQAOggAfgNQARgGAOgBQAiAAAYAZQAZAYAAAjIgUAAQAAgbgTgSQgSgTgaAAQgZAAgSATQgTATAAAaQAAAXARASQAQASAZACIgNgcIBVAnIhWAlg");
	this.shape_1.setTransform(8.4,9.7);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#666666").s().p("AgEBGQghgDgWgXQgXgZAAgfQAAgQAGgQQAOggAfgNQARgGAOgBQAiAAAYAZQAZAYAAAjIgUAAQAAgbgTgSQgSgTgaAAQgZAAgSATQgTATAAAaQAAAXARASQAQASAZACIgNgcIBVAnIhWAlg");
	this.shape_2.setTransform(8.4,9.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AgEBGQghgDgWgXQgXgZAAgfQAAgQAGgQQAOggAfgNQARgGAOgBQAiAAAYAZQAZAYAAAjIgUAAQAAgbgTgSQgSgTgaAAQgZAAgSATQgTATAAAaQAAAXARASQAQASAZACIgNgcIBVAnIhWAlg");
	this.shape_3.setTransform(8.4,9.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1}]}).to({state:[{t:this.shape_2}]},1).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_3}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,16.7,19.4);


(lib.pic = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib._336x280gardener();

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,515,200);


(lib.head1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#193670").s().p("AAAAJQgIgBAAgHIAAgBQAAgHAIAAIABAAQAIAAAAAHIAAABQAAAHgIABg");
	this.shape.setTransform(464.1,20.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#193670").s().p("AgXA3QgJgEgGgGQgGgFABgEQAAgFAFgBQAHAJAIAEQAGADAGACQAGABAGAAQAIAAAFgCQAHgBAEgDQAEgDACgEQACgEAAgFQAAgGgCgDQgDgEgFgDQgGgDgRgEQgTgEgIgCQgGgEgEgFQgDgGAAgIQAAgHADgGQADgGAFgFQAGgEAIgCQAIgDAIAAQAMAAAKAEQAIADAGAGQAFAEgBAEQAAADgCACIgEABQgEgHgKgFQgJgFgLAAQgGAAgGACQgGABgEADQgEADgCAEQgCAEAAAFQAAAFADADQABAEAFACQAGAEARAEIAPADQAIABAFADQAHADADAFQAEAGAAAIQAAAIgEAGQgDAGgFAEQgGAFgIACQgIADgKAAQgNAAgLgEg");
	this.shape_1.setTransform(456.5,15.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#193670").s().p("AAqA6QgFAAAAgGIAAg5QAAgKgDgHQgCgIgEgFQgEgFgHgDQgGgDgJAAQgFAAgGACQgGACgFADQgGAEgDAFQgFAFgCAGIAABHQAAAGgFAAIgCAAQgEAAAAgGIAAhqIADgBQAEAAACACQACADAAAGIAAALQACgFAFgEIAJgIQAFgDAGgCQAHgCAFAAQALAAAJAEQAIAEAGAGQAFAHADAJQAEAJAAAMIAAA6QAAAGgGAAg");
	this.shape_2.setTransform(444.8,15.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#193670").s().p("AgWA2QgLgEgHgIQgIgIgEgLQgFgLAAgMQAAgLAFgLQAEgLAIgIQAHgIALgEQALgFALAAQAMAAAKAFQALAEAIAIQAIAIAEALQAEALAAALQAAAMgEALQgEALgIAIQgIAIgLAEQgKAFgMAAQgLAAgLgFgAgRgsQgJAEgGAGQgGAHgDAJQgEAJAAAJQAAAKAEAJQADAJAGAGQAGAHAJAEQAJAEAIAAQAJAAAJgEQAJgEAFgGQAHgHADgJQAEgJAAgKQAAgIgEgKQgDgJgHgGQgFgHgJgEQgJgEgJAAQgIAAgJAEg");
	this.shape_3.setTransform(431.6,15.5);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#193670").s().p("AAABQQgEAAAAgGIAAhlQAAgGAEAAIAAAAQAGAAgBAGIAABlQABAGgGAAgAgGhHQgBgIAHAAQAIAAgBAIQAAAIgHAAQgGAAAAgIg");
	this.shape_4.setTransform(422.6,13.2);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#193670").s().p("AAABFQgEgCgDgEQgEgEgCgHQgCgHAAgJIAAhEIgOAAQgGAAABgFIAAgBQgBgFAGAAIAOAAIAAgVQAAgGAFgBIABAAQAGABgBAGIAAAVIAfAAQAGAAAAAFIAAABQAAAFgGAAIgfAAIAABDQABAOADAHQADAFAKAAQAGABAFgDQAEgDADgEIADABQAAAAABABQAAAAAAABQAAAAAAABQABABAAABQgBADgEAEQgCADgFABQgFACgGAAQgIAAgFgCg");
	this.shape_5.setTransform(416.3,14.3);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#193670").s().p("AgwBRQgGAAAAgGIAAiYIAEgBQAEAAABACQADADAAAGIAAANIAHgLIALgIQAFgDAHgCQAHgCAGAAQALAAAKAFQAKAEAHAIQAHAHAFALQAEALAAANQAAANgEAJQgEALgIAIQgHAIgKAEQgKAFgMAAQgGAAgIgDQgHgCgGgDIgJgIIgGgKIAABAQAAAGgFAAgAgOhDQgGACgGAEQgFAEgFAGQgEAFgCAHIAAAbQAAAIADAGQADAHAGAGQAGAFAIADQAIAEAIAAQAJAAAIgEQAIgEAGgGQAGgHADgHQADgJAAgLQAAgKgDgJQgDgJgGgHQgGgGgIgEQgIgEgJAAQgGAAgIADg");
	this.shape_6.setTransform(405.9,17.7);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#193670").s().p("AgWA2QgKgEgJgIQgHgIgEgLQgFgLAAgMQAAgLAFgLQAEgLAHgIQAJgIAKgEQALgFALAAQAMAAAKAFQALAEAIAIQAIAIAEALQAEALAAALQAAAMgEALQgEALgIAIQgIAIgLAEQgKAFgMAAQgLAAgLgFgAgRgsQgJAEgGAGQgGAHgDAJQgEAJAAAJQAAAKAEAJQADAJAGAGQAGAHAJAEQAJAEAIAAQAJAAAJgEQAJgEAFgGQAHgHADgJQAEgJAAgKQAAgIgEgKQgDgJgHgGQgFgHgJgEQgJgEgJAAQgIAAgJAEg");
	this.shape_7.setTransform(392.1,15.5);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#193670").s().p("AgTA2QgKgEgIgIQgIgIgEgLQgEgKAAgNQAAgLAEgLQAFgKAHgJQAIgIAKgEQALgFAKAAQALAAAKAEQAKAEAGAIQAHAHAEAKQAEAKAAANIAAABQAAACgFAAIhbAAQABAKADAJQAEAJAGAGQAGAHAJADQAIAEAIAAQAJAAAHgCQAGgCAFgEQAJgFAFgKIADABQAEACAAADQAAAFgIAIQgGAFgJAEQgMAFgNAAQgLAAgLgFgAAqgHQgBgJgDgHQgCgIgGgFQgFgGgHgDQgIgDgIAAQgHAAgIADQgHADgGAGQgGAFgEAIQgEAHgBAJIBTAAIAAAAg");
	this.shape_8.setTransform(375,15.5);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#193670").s().p("AgXBWQgKgCgHgEQgHgDgDgGQgDgGAAgIQAAgGADgGQADgFAFgEQAGgFAHgDIAPgEQgEgCgDgDQgCgDAAgEQAAgHAGgEIgLgEQgFgEgEgFQgEgEgCgGQgCgGAAgHQAAgIAEgIQADgHAGgGQAGgGAIgDQAJgDAJAAQAGAAAIACQAHADAGAEIAKgPQAEgGAGABQAFACAAADIgTAVQAFAFADAGQACAHAAAHQAAAJgDAHQgDAIgHAFQgGAGgIABQgJADgHAAIgIAAQgEACAAAFQAAAGAJADIAVAGIANAEQAHACAFAEQAFADADAFQADAGAAAGQAAAIgDAGQgEAGgIAEQgHAFgKACQgLACgLAAQgOAAgJgCgAgQAiQgHACgGADQgGAEgDAEQgEAFAAAFQAAAGADAEQACAEAGACQAFADAIABQAIACAKAAQAIAAAJgCQAIgBAGgDQAGgDADgEQADgFAAgFQAAgFgDgDQgCgEgEgCQgGgEgNgDIgPgEQgIAAgIADgAgNhAQgGACgFAEQgEAEgDAGQgCAGAAAHQAAAHACAFQADAGAEAEQAFAEAGADQAGACAHAAQAFAAAGgCQAHgDAEgEQAFgEACgGQACgFAAgHQAAgHgCgGQgCgFgFgFQgEgEgGgCQgHgDgFAAQgHAAgGADg");
	this.shape_9.setTransform(363.3,17.4);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#193670").s().p("AgXA5QgIgDgFgDQgFgFgDgFQgCgHAAgHQAAgJAEgHQAFgHAKgEQAKgDAQgCQANgCAWgBIACAAIAAgFQAAgIgCgHQgDgFgEgFQgFgFgGgCQgHgCgIAAQgFAAgGACQgGABgFAEQgJAFgFAJQgHAAAAgGQAAgFAHgGQAGgGAJgEQALgFALABQALAAAIACQAIAEAGAGQAGAFADAIQADAJAAAKIAABFIgEABQgDAAgCgCQgCgDAAgHIAAgLQgDAFgEAFIgKAIIgNAFQgGABgHABQgJAAgHgCgAABABQgLADgIADQgJADgEAGQgEAEAAAHQAAAGACADQACAFAEACQAEADAFACQAFABAHABQAHAAAIgEQAIgDAGgFQAGgFAEgHQADgHAAgIIAAgLIgDAAIggABg");
	this.shape_10.setTransform(351.5,15.5);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#193670").s().p("AAABFQgEgCgDgEQgEgEgCgHQgCgHAAgJIAAhEIgOAAQgFAAAAgFIAAgBQAAgFAFAAIAOAAIAAgVQAAgGAFgBIACAAQAEABAAAGIAAAVIAfAAQAGAAAAAFIAAABQAAAFgGAAIgfAAIAABDQAAAOAEAHQADAFAKAAQAHABAEgDQAEgDADgEIADABQAAAAABABQAAAAAAABQAAAAAAABQABABAAABQAAADgFAEQgCADgEABQgGACgGAAQgIAAgFgCg");
	this.shape_11.setTransform(341.9,14.3);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#193670").s().p("AAqA6QgFAAAAgGIAAg5QAAgKgDgHQgCgIgEgFQgEgFgHgDQgHgDgIAAQgFAAgGACQgGACgFADQgFAEgEAFQgEAFgDAGIAABHQAAAGgFAAIgCAAQgEAAAAgGIAAhqIADgBQAEAAACACQACADAAAGIAAALQADgFAEgEIAJgIQAFgDAGgCQAHgCAFAAQALAAAJAEQAIAEAGAGQAFAHADAJQAEAJAAAMIAAA6QgBAGgFAAg");
	this.shape_12.setTransform(331.5,15.4);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#193670").s().p("AgXA5QgIgDgFgDQgFgFgDgFQgCgHAAgHQAAgJAEgHQAFgHAKgEQAKgDAQgCQANgCAWgBIACAAIAAgFQAAgIgCgHQgDgFgEgFQgFgFgGgCQgHgCgIAAQgFAAgGACQgGABgFAEQgJAFgFAJQgHAAAAgGQAAgFAHgGQAGgGAJgEQALgFALABQALAAAIACQAIAEAGAGQAGAFADAIQADAJAAAKIAABFIgEABQgDAAgCgCQgCgDAAgHIAAgLQgDAFgEAFIgKAIIgNAFQgGABgHABQgJAAgHgCgAABABQgLADgIADQgJADgEAGQgEAEAAAHQAAAGACADQACAFAEACQAEADAFACQAFABAHABQAHAAAIgEQAIgDAGgFQAGgFAEgHQADgHAAgIIAAgLIgDAAIggABg");
	this.shape_13.setTransform(318.6,15.5);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#193670").s().p("AgHA1IgrhqQAJgIAFANIAkBeIAmheQAEgNAJAIIgrBqQgCAEgGAAQgFAAgCgEg");
	this.shape_14.setTransform(307.4,15.5);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#193670").s().p("AgVBOQgKgEgHgIQgIgIgEgLQgEgLAAgNQAAgNAEgKQAEgKAIgIQAHgIAKgEQAKgEALAAQAHAAAHACQAHACAGADIAKAIIAGAJIAAhGQABAAAAAAQAAgBABAAQAAAAABAAQAAAAABAAQADAAACACQADADAAAGIAACRQAAAFgGAAIgBAAQgFAAAAgFIAAgSIgHAKIgKAIQgGAEgHABQgHACgGAAQgLAAgKgEgAgQgUQgIADgGAHQgGAGgDAHQgDAJAAALQAAAKADAJQADAKAGAGQAGAHAIADQAIAEAIAAQAIAAAIgDQAIgDAGgGQAGgGAEgHQADgHAAgJIAAgaIgHgLQgEgGgFgEQgGgEgGgCQgHgCgIAAQgIAAgIAEg");
	this.shape_15.setTransform(294.8,13.2);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#193670").s().p("AhCBKIA6iTQADgEAFAAQAHAAABAEIA8CTQgLAIgEgKIgTgxIhDAAIgUAxQgCAGgEAAQgDAAgEgEgAAeANIgehNIgdBNIA7AAg");
	this.shape_16.setTransform(281.2,13.4);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#193670").s().p("AgTA2QgKgEgIgIQgIgIgEgLQgEgKAAgNQAAgLAEgLQAFgKAHgJQAIgIAKgEQALgFAKAAQALAAAKAEQAKAEAGAIQAHAHAEAKQAEAKAAANIAAABQAAACgFAAIhbAAQABAKADAJQAEAJAGAGQAGAHAJADQAIAEAIAAQAJAAAHgCQAGgCAFgEQAJgFAFgKIADABQAEACAAADQAAAFgIAIQgGAFgJAEQgMAFgNAAQgLAAgLgFgAAqgHQgBgJgDgHQgCgIgGgFQgFgGgHgDQgIgDgIAAQgHAAgIADQgHADgGAGQgGAFgEAIQgEAHgBAJIBTAAIAAAAg");
	this.shape_17.setTransform(263.6,15.5);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#193670").s().p("AgWA6QgGAAAAgGIAAhqIAEgBQAEAAABACQADADAAAGIAAAPQABgHADgGQADgFAEgDIAHgFQAFgCAGAAQAHAAAEADQAFADAAAEQAAADgCACIgCABQgFgFgIAAQgIAAgEAEQgFAEgEAGQgDAHgCAJQgCAKAAAJIAAAxQAAAGgFAAg");
	this.shape_18.setTransform(254,15.4);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#193670").s().p("AgXA5QgIgDgFgDQgFgFgDgFQgCgHAAgHQAAgJAEgHQAFgHAKgEQAKgDAQgCQANgCAWgBIACAAIAAgFQAAgIgCgHQgDgFgEgFQgFgFgGgCQgHgCgIAAQgFAAgGACQgGABgFAEQgJAFgFAJQgHAAAAgGQAAgFAHgGQAGgGAJgEQALgFALABQALAAAIACQAIAEAGAGQAGAFADAIQADAJAAAKIAABFIgEABQgDAAgCgCQgCgDAAgHIAAgLQgDAFgEAFIgKAIIgNAFQgGABgHABQgJAAgHgCgAABABQgLADgIADQgJADgEAGQgEAEAAAHQAAAGACADQACAFAEACQAEADAFACQAFABAHABQAHAAAIgEQAIgDAGgFQAGgFAEgHQADgHAAgIIAAgLIgDAAIggABg");
	this.shape_19.setTransform(243.1,15.5);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#193670").s().p("AgRA2QgKgEgIgIQgIgIgEgLQgEgLAAgMQAAgLAEgLQAEgLAIgIQAIgIAKgEQALgFAKAAQAOAAAKAFQAJADAHAHQAIAJAAAHQAAADgDACIgEABIgFgKIgIgIQgGgEgGgCQgHgDgJAAQgIAAgIAEQgJAEgGAGQgGAHgDAJQgEAJAAAJQAAAKAEAJQADAJAGAGQAGAHAJAEQAIAEAIAAQAJAAAHgDQAGgCAGgDQAGgFAHgOQAHABAAAFQgCAKgHAGQgGAHgJADQgKAFgOAAQgKAAgLgFg");
	this.shape_20.setTransform(231.4,15.5);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#193670").s().p("AAABQQgEAAAAgGIAAhlQAAgGAEAAIAAAAQAGAAgBAGIAABlQABAGgGAAgAgGhHQAAgIAGAAQAIAAAAAIQgBAIgHAAQgHAAABgIg");
	this.shape_21.setTransform(222.9,13.2);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#193670").s().p("AgVBOQgKgEgHgIQgIgIgEgLQgEgLAAgNQAAgNAEgKQAEgKAIgIQAHgIAKgEQAKgEALAAQAHAAAHACQAHACAGADIAKAIIAGAJIAAhGQABAAAAAAQAAgBABAAQAAAAABAAQAAAAABAAQADAAACACQADADAAAGIAACRQAAAFgGAAIgBAAQgFAAAAgFIAAgSIgHAKIgKAIQgGAEgHABQgHACgGAAQgLAAgKgEgAgQgUQgIADgGAHQgGAGgDAHQgDAJAAALQAAAKADAJQADAKAGAGQAGAHAIADQAIAEAIAAQAIAAAIgDQAIgDAGgGQAGgGAEgHQADgHAAgJIAAgaIgHgLQgEgGgFgEQgGgEgGgCQgHgCgIAAQgIAAgIAEg");
	this.shape_22.setTransform(213.4,13.2);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#193670").s().p("AgTA2QgKgEgIgIQgIgIgEgLQgEgKAAgNQAAgLAEgLQAFgKAHgJQAIgIAKgEQALgFAKAAQALAAAKAEQAKAEAGAIQAHAHAEAKQAEAKAAANIAAABQAAACgFAAIhbAAQABAKADAJQAEAJAGAGQAGAHAJADQAIAEAIAAQAJAAAHgCQAGgCAFgEQAJgFAFgKIADABQAEACAAADQAAAFgIAIQgGAFgJAEQgMAFgNAAQgLAAgLgFgAAqgHQgBgJgDgHQgCgIgGgFQgFgGgHgDQgIgDgIAAQgHAAgIADQgHADgGAGQgGAFgEAIQgEAHgBAJIBTAAIAAAAg");
	this.shape_23.setTransform(200.8,15.5);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#193670").s().p("AA+BOQgFAAAAgGIAAiHIgvBbQgDAHgHAAQgGAAgDgHIgwhbIAACHQAAAGgEAAIgCAAQgFAAAAgGIAAiNQAAgIAJAAIACAAQAFAAACACIAEAHIAuBcIAvhcIAEgHQACgCAFAAIACAAQAJAAAAAIIAACNQAAAGgFAAg");
	this.shape_24.setTransform(185.7,13.4);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#193670").s().p("AgWA6QgGAAAAgGIAAhqIAEgBQAEAAABACQADADAAAGIAAAPQABgHADgGQADgFAEgDIAHgFQAFgCAGAAQAHAAAEADQAFADAAAEQAAADgCACIgCABQgFgFgIAAQgIAAgEAEQgFAEgEAGQgDAHgCAJQgCAKAAAJIAAAxQAAAGgFAAg");
	this.shape_25.setTransform(169.4,15.4);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#193670").s().p("AgWA2QgIgDgGgHQgFgHgDgJQgDgJgBgMIAAg6QABgGAEAAIACAAQAFAAAAAGIAAA5QAAAKADAIQACAHAEAFQAFAFAGADQAHADAIAAQAEAAAHgCQAGgBAFgEQAGgEADgEIAGgLIAAhIQABgGAFAAIACAAQAEAAAAAGIAABqIgEABQgDAAgCgCQgCgDAAgHIAAgKIgHAKIgJAHQgGAEgFABQgHACgFAAQgLAAgJgEg");
	this.shape_26.setTransform(158.3,15.6);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#193670").s().p("AgWA2QgLgEgHgIQgIgIgFgLQgDgLAAgMQAAgLADgLQAFgLAIgIQAHgIALgEQALgFALAAQAMAAALAFQAKAEAIAIQAIAIAEALQAEALABALQgBAMgEALQgEALgIAIQgIAIgKAEQgLAFgMAAQgLAAgLgFgAgRgsQgIAEgHAGQgGAHgDAJQgEAJAAAJQAAAKAEAJQADAJAGAGQAHAHAIAEQAJAEAIAAQAJAAAJgEQAJgEAGgGQAGgHADgJQAEgJAAgKQAAgIgEgKQgDgJgGgGQgGgHgJgEQgJgEgJAAQgIAAgJAEg");
	this.shape_27.setTransform(145.2,15.5);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#193670").s().p("AgSBOIgCgCIAUgxQgFAAgCgFIgrhiQAJgIAFAMIAmBcIAjhbQAFgNAJAIIg4CUQgDAIgGAAg");
	this.shape_28.setTransform(133.1,17.8);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#193670").s().p("AAABFQgEgCgDgEQgFgEgBgHQgCgHAAgJIAAhEIgOAAQgGAAABgFIAAgBQgBgFAGAAIAOAAIAAgVQAAgGAFgBIACAAQAEABAAAGIAAAVIAfAAQAGAAAAAFIAAABQAAAFgGAAIgfAAIAABDQABAOADAHQADAFAKAAQAHABAEgDQAEgDADgEIADABQAAAAABABQAAAAAAABQAAAAAAABQABABAAABQAAADgFAEQgCADgFABQgFACgGAAQgIAAgFgCg");
	this.shape_29.setTransform(119.4,14.3);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#193670").s().p("AgWA2QgIgDgGgHQgFgHgDgJQgDgJAAgMIAAg6QAAgGAEAAIACAAQAFAAAAAGIAAA5QAAAKACAIQACAHAFAFQAFAFAGADQAGADAJAAQAEAAAHgCQAGgBAFgEQAGgEADgEIAGgLIAAhIQABgGAFAAIACAAQAEAAAAAGIAABqIgEABQgDAAgCgCQgCgDAAgHIAAgKIgHAKIgJAHQgGAEgGABQgGACgFAAQgLAAgJgEg");
	this.shape_30.setTransform(108.9,15.6);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#193670").s().p("AgWA2QgKgEgIgIQgIgIgFgLQgDgLAAgMQAAgLADgLQAFgLAIgIQAIgIAKgEQALgFALAAQAMAAAKAFQALAEAIAIQAIAIAEALQAEALABALQgBAMgEALQgEALgIAIQgIAIgLAEQgKAFgMAAQgLAAgLgFgAgRgsQgIAEgHAGQgGAHgDAJQgEAJAAAJQAAAKAEAJQADAJAGAGQAHAHAIAEQAJAEAIAAQAJAAAJgEQAJgEAFgGQAHgHADgJQAEgJAAgKQAAgIgEgKQgDgJgHgGQgFgHgJgEQgJgEgJAAQgIAAgJAEg");
	this.shape_31.setTransform(95.8,15.5);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#193670").s().p("AgOBQQgHgCgGgEQgFgDgEgFQgEgEgCgFIAAASQAAAFgFAAIgBAAQgGAAAAgFIAAibIAEgBQAEAAACACQACADAAAGIAAA+IAIgLIAKgIQAFgEAHgBQAHgCAGAAQALAAAKAEQAKAEAHAIQAHAIAFAKQAEAKAAANQAAANgEALQgEALgIAIQgHAIgKAEQgKAEgMAAQgGAAgIgCgAgOgWQgGACgGAEQgFAEgFAGQgEAGgCAFIAAAaQAAAIADAIQADAHAGAGQAGAGAIADQAIADAIAAQAJAAAIgDQAIgEAGgHQAGgGADgJQADgKAAgKQAAgLgDgJQgDgHgGgGQgGgHgIgDQgIgEgJAAQgGAAgIACg");
	this.shape_32.setTransform(82.7,13.2);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#193670").s().p("AgXA5QgIgDgFgDQgFgFgDgFQgCgHAAgHQAAgJAEgHQAFgHAKgEQAKgDAQgCQANgCAWgBIACAAIAAgFQAAgIgCgHQgDgFgEgFQgFgFgGgCQgHgCgIAAQgFAAgGACQgGABgFAEQgJAFgFAJQgHAAAAgGQAAgFAHgGQAGgGAJgEQALgFALABQALAAAIACQAIAEAGAGQAGAFADAIQADAJAAAKIAABFIgEABQgDAAgCgCQgCgDAAgHIAAgLQgDAFgEAFIgKAIIgNAFQgGABgHABQgJAAgHgCgAABABQgLADgIADQgJADgEAGQgEAEAAAHQAAAGACADQACAFAEACQAEADAFACQAFABAHABQAHAAAIgEQAIgDAGgFQAGgFAEgHQADgHAAgIIAAgLIgDAAIggABg");
	this.shape_33.setTransform(69.2,15.5);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#193670").s().p("AAqA6QgFAAAAgGIAAg5QAAgKgDgHQgCgIgEgFQgFgFgGgDQgHgDgIAAQgFAAgGACQgGACgFADQgFAEgEAFQgEAFgDAGIAABHQAAAGgFAAIgCAAQgEAAAAgGIAAhqIADgBQAEAAACACQACADAAAGIAAALQADgFAEgEIAJgIQAFgDAGgCQAHgCAFAAQALAAAJAEQAIAEAGAGQAFAHADAJQAEAJAAAMIAAA6QgBAGgFAAg");
	this.shape_34.setTransform(53,15.4);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#193670").s().p("AgWA6QgGAAAAgGIAAhqIAEgBQAEAAABACQADADAAAGIAAAPQABgHADgGQADgFAEgDIAHgFQAFgCAGAAQAHAAAEADQAFADAAAEQAAADgCACIgCABQgFgFgIAAQgIAAgEAEQgFAEgEAGQgDAHgCAJQgCAKAAAJIAAAxQAAAGgFAAg");
	this.shape_35.setTransform(43.1,15.4);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#193670").s().p("AgXA5QgIgDgFgDQgFgFgDgFQgCgHAAgHQAAgJAEgHQAFgHAKgEQAKgDAQgCQANgCAWgBIACAAIAAgFQAAgIgCgHQgDgFgEgFQgFgFgGgCQgHgCgIAAQgFAAgGACQgGABgFAEQgJAFgFAJQgHAAAAgGQAAgFAHgGQAGgGAJgEQALgFALABQALAAAIACQAIAEAGAGQAGAFADAIQADAJAAAKIAABFIgEABQgDAAgCgCQgCgDAAgHIAAgLQgDAFgEAFIgKAIIgNAFQgGABgHABQgJAAgHgCgAABABQgLADgIADQgJADgEAGQgEAEAAAHQAAAGACADQACAFAEACQAEADAFACQAFABAHABQAHAAAIgEQAIgDAGgFQAGgFAEgHQADgHAAgIIAAgLIgDAAIggABg");
	this.shape_36.setTransform(32.2,15.5);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#193670").s().p("AgTA2QgKgEgIgIQgIgIgEgLQgEgKAAgNQAAgLAEgLQAFgKAHgJQAIgIAKgEQALgFAKAAQALAAAKAEQAKAEAGAIQAHAHAEAKQAEAKAAANIAAABQAAACgFAAIhbAAQABAKADAJQAEAJAGAGQAGAHAJADQAIAEAIAAQAJAAAHgCQAGgCAFgEQAJgFAFgKIADABQAEACAAADQAAAFgIAIQgGAFgJAEQgMAFgNAAQgLAAgLgFgAAqgHQgBgJgDgHQgCgIgGgFQgFgGgHgDQgIgDgIAAQgHAAgIADQgHADgGAGQgGAFgEAIQgEAHgBAJIBTAAIAAAAg");
	this.shape_37.setTransform(20.3,15.5);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#193670").s().p("AgmBOQgHgBAAgGIAAiOQAAgFAFgBIABAAQAFABAAAFIAACJIBLAAQAFABAAAFIAAAAQAAAFgFABg");
	this.shape_38.setTransform(8.6,13.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,532,28);


(lib.CTA_btn = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#00FFFF").s().p("A6PV3MAAAgruMA0eAAAMAAAArug");
	this.shape.setTransform(168,140);
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(3).to({_off:false},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = null;


(lib.border336x280 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,0,3).p("Eg4ygG8MBxlAAAIAAN5MhxlAAAg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-364.5,-45.5,729,91);


(lib.blocks = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#557C6B").s().p("AiWCSIAAkjIEtAAIAAEjg");
	this.shape.setTransform(-15.2,45);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#92AF2B").s().p("AiWCXIAAktIEtAAIAAEtg");
	this.shape_1.setTransform(-15.2,15.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#005A8C").s().p("AiWCXIAAktIEtAAIAAEtg");
	this.shape_2.setTransform(-15.2,74.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-30.3,0,30.4,90);


(lib.logoblock = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// logo
	this.instance = new lib.TEC_logorev("synched",0);
	this.instance.setTransform(-13.5,60.8,0.49,0.49,0,0,0,181.4,32.2);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// bkgd
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#193670").s().p("AwAG9IAArdQAAibCdgBIdkAAIAAN5g");
	this.shape.setTransform(-102.5,45.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-205,1,205,89);


(lib.LogoLockup728x90 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.blocks();
	this.instance.setTransform(385,12.5,1,1,0,0,0,150,12.5);

	this.instance_1 = new lib.logoblock();
	this.instance_1.setTransform(355,50,1,1,0,0,0,150,50);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_1},{t:this.instance}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,235,90);


// stage content:
(lib.TEC201609_Garden_728x90_AdR = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.clickthru_btn.on("click", function(evt){
		  window.open(clickTag, "_blank");
		});
	}
	this.frame_125 = function() {
		this.stop();
		 
		this.replay_btn.addEventListener("click", fl_ClickToGoToAndPlayFromFrame.bind(this));
		function fl_ClickToGoToAndPlayFromFrame() 
		{
		this.gotoAndPlay(1);
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(125).call(this.frame_125).wait(1));

	// replay btn
	this.replay_btn = new lib.replaybtn();
	this.replay_btn.setTransform(471,7.5,0.75,0.75);
	this.replay_btn._off = true;
	new cjs.ButtonHelper(this.replay_btn, 0, 1, 2, false, new lib.replaybtn(), 3);

	this.timeline.addTween(cjs.Tween.get(this.replay_btn).wait(125).to({_off:false},0).wait(1));

	// cta btn
	this.clickthru_btn = new lib.CTA_btn();
	this.clickthru_btn.setTransform(-0.2,0,2.167,0.321,0,0,0,-0.1,0);
	new cjs.ButtonHelper(this.clickthru_btn, 0, 1, 2, false, new lib.CTA_btn(), 3);

	this.timeline.addTween(cjs.Tween.get(this.clickthru_btn).wait(126));

	// border
	this.instance = new lib.border336x280();
	this.instance.setTransform(364,45);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(126));

	// head1
	this.instance_1 = new lib.head1("synched",0);
	this.instance_1.setTransform(195,21);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(118).to({startPosition:0},0).to({x:13},5).wait(3));

	// sub1
	this.instance_2 = new lib.sub1("synched",0);
	this.instance_2.setTransform(844,1098.5,5,5,0,0,0,131.4,220.7);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(66).to({_off:false},0).to({scaleX:1,scaleY:1,x:326.4,y:267.7},5).wait(47).to({startPosition:0},0).to({x:144.4},5).wait(3));

	// logo block
	this.instance_3 = new lib.LogoLockup728x90();
	this.instance_3.setTransform(921.5,45,1,1,0,0,0,192.5,45);

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(118).to({x:685.5},5).wait(3));

	// mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_0 = new cjs.Graphics().p("AuAIgIAAw/IcBAAIAAQ/g");
	var mask_graphics_118 = new cjs.Graphics().p("AuAIgIAAw/IcBAAIAAQ/g");
	var mask_graphics_119 = new cjs.Graphics().p("AuAIgIAAw/IcBAAIAAQ/g");
	var mask_graphics_120 = new cjs.Graphics().p("AuAIgIAAw/IcBAAIAAQ/g");
	var mask_graphics_121 = new cjs.Graphics().p("AuAIgIAAw/IcBAAIAAQ/g");
	var mask_graphics_122 = new cjs.Graphics().p("AuAIgIAAw/IcBAAIAAQ/g");
	var mask_graphics_123 = new cjs.Graphics().p("AuAIgIAAw/IcBAAIAAQ/g");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:mask_graphics_0,x:89.7,y:54.5}).wait(118).to({graphics:mask_graphics_118,x:89.7,y:54.5}).wait(1).to({graphics:mask_graphics_119,x:54.1,y:54.5}).wait(1).to({graphics:mask_graphics_120,x:18.5,y:54.5}).wait(1).to({graphics:mask_graphics_121,x:-17.1,y:54.5}).wait(1).to({graphics:mask_graphics_122,x:-52.7,y:54.5}).wait(1).to({graphics:mask_graphics_123,x:-88.2,y:54.5}).wait(1).to({graphics:null,x:0,y:0}).wait(2));

	// pic
	this.instance_4 = new lib.pic();
	this.instance_4.setTransform(-55,-7.7,0.485,0.485,0,0,0,-0.2,-0.3);

	this.instance_4.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(118).to({x:-232.9},5).to({_off:true},1).wait(2));

	// bkgd
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape.setTransform(364,45);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(126));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(364,45,964.1,90);

})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{});
var lib, images, createjs, ss;