(function (lib, img, cjs, ss) {

var p; // shortcut to reference prototypes
lib.webFontTxtFilters = {}; 

// library properties:
lib.properties = {
	width: 250,
	height: 250,
	fps: 18,
	color: "#CCCCCC",
	opacity: 1.00,
	webfonts: {},
	manifest: [
		{src:"images/_336x280hikers.jpg", id:"_336x280hikers"}
	]
};



lib.ssMetadata = [];


lib.webfontAvailable = function(family) { 
	lib.properties.webfonts[family] = true;
	var txtFilters = lib.webFontTxtFilters && lib.webFontTxtFilters[family] || [];
	for(var f = 0; f < txtFilters.length; ++f) {
		txtFilters[f].updateCache();
	}
};
// symbols:



(lib._336x280hikers = function() {
	this.initialize(img._336x280hikers);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,515,200);


(lib.TEC_logorev = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// TEC_logo-rev.ai
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AhBBcIAAjjIAJgDIAYgKQAUgKAKgIIADADIAABbIAvgCIABAbIgwgBIAACaQAAAJAGAGQAIAIAOgDQAQgDAPgPIAGACIAAABIgFAXIAAAAQAAADgMAKQgOAMgOAEQgMAEgKAAQhAAAAAhLg");
	this.shape.setTransform(42.1,-10.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("Ag+BcIAAiMIguAAIAAgaIAuACIAAg/IAJgDIAXgKQAVgKAJgIIAEADIAABbIBpAAIgBAYIhoAAIAACaQAAAJAGAGQAIAIANgDQARgDAPgPIAGACIAAABIgFAXIAAAAQgBADgLAKQgOAMgOAEQgMAEgMAAQg+AAAAhLg");
	this.shape_1.setTransform(25.5,-10.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AhUB5IAAjsIBHAAIgBAuIABABQAIgUASgQQAWgQAWAAQANAAAPAEIgBABQgVAVgLAgIgCADIgDgBQgHgCgHAAQgWAAgMAPQgMAOAAAUIAACGg");
	this.shape_2.setTransform(-14.8,-6.5);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgnBzQgZgKgPgTQgOgRgHgXQgGgVAAgYQgBgZAKgYQAKgZAQgPQAQgRAZgKQAagJAaAAQAdAAATAGQAVAHARAKQgIALgEANIgEALIgHAAQgJgPgOgIQgQgKgSAAIgBAAQgcAAgPAbQgPAbAAAvQAAAsATAZQARAYAkAAQAPAAAPgHQAOgIAHgIIAGAEIgGAPIgFAPQgKAIgRAGQgSAFgWABQgiAAgZgLg");
	this.shape_3.setTransform(166.8,-6.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AggB2QgXgHgPgOQgQgPgKgZQgKgYAAggQAAgeAJgYQAIgXAQgRQAOgPAWgIQAUgJAYABQAxAAAZAcQAaAcAAA1IAAAPIiMAAQAAATAEASQAEAQAIAPQAIANALAHQANAHARAAQAhAAAkgdIAGACIAAABIgEAXQgQASgdAKQgSAFgcABQgVAAgXgIgAApgVQgBglgIgVQgIgXgTAAQgJAAgIAHQgHAIgEALQgEALgDAPIgDAdIBKAAIAAAAg");
	this.shape_4.setTransform(3,-6.3);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AggB2QgXgHgPgOQgSgQgIgYQgKgYAAggQAAgeAJgYQAHgXAQgRQAPgPAVgIQAVgJAXABQAyAAAaAcQAaAdAAA0IAAAPIiNAAQAAATAEASQADAQAJAPQAIANALAHQANAHAQAAQAiAAAkgdIAGACIAAABIgEAXQgQASgdAKQgSAFgcABQgVAAgXgIgAAogVQAAglgJgVQgHgXgUAAQgJAAgHAHQgHAIgEALQgEALgDAPIgDAdIBJAAIAAAAg");
	this.shape_5.setTransform(-37.3,-6.3);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AggB2QgXgHgQgOQgQgPgKgZQgJgYgBggQABgeAIgYQAJgXAPgRQAOgPAWgIQAVgJAXABQAyAAAZAcQAaAdAAA0IAAAPIiMAAQAAATAEASQAFASAHANQAIANALAHQANAHARAAQAgAAAlgdIAGACIAAABIgEAXQgQASgdAKQgSAFgcABQgWAAgWgIgAApgVQgBglgIgVQgJgXgSAAQgJAAgIAHQgHAIgEALQgEALgDAPIgDAdIBKAAIAAAAg");
	this.shape_6.setTransform(-118.1,-6.3);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgPB2IgOAAIhEi8IgSgvIAUABIA4gBIA1CrIACAAIAehVIAdhWIAUACIAVgCIgTAsIgYA4IgaBAQgQAsgJAbg");
	this.shape_7.setTransform(-58.8,-6.3);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AheC7IAAl1IBXADIBAgBIAmgCQgCALAAAKIACAXIgggCIgggCIgdgCIgUgBIAABmIBWgEIAPApQg8gDgpAAIAACkIA5gBQAfgCAZgDIgBAWIAAAMIABAIg");
	this.shape_8.setTransform(-81.2,-13.1);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AggB3IAAjtIAPACIARABQAOAAATgDIAADtg");
	this.shape_9.setTransform(149,-6.3);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AggB3IAAjtIAOACIASABQANAAAUgDIAADtg");
	this.shape_10.setTransform(111.6,-6.3);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AASC6IgxABIAAl1IAOACIARABIASgBIAOgCIAAF1g");
	this.shape_11.setTransform(100,-13.1);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgaA2IAAhpIAPAAIAAAWQALgZAZABIABAAIAAAPIgBAAQgPgBgKAKQgLALAAARIAAA3g");
	this.shape_12.setTransform(36.7,22.9);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AAZA1IgZhVIgYBVIgPAAIgjhpIAQAAIAaBWIAZhWIAOAAIAaBWIAahWIAQAAIgjBpg");
	this.shape_13.setTransform(91.8,23);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgCBAQgFgGAAgNIAAhGIgTAAIAAgMIATAAIAAggIAMAAIAAAgIAWAAIAAAMIgWAAIAABEQAAAHACADQACADAGAAIAMAAIAAANIgNABQgNgBgDgFg");
	this.shape_14.setTransform(49.7,21.5);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AAdBJIAAhCQAAgdgaAAQgMAAgJAJQgJAKAAAOIAAA+IgPAAIAAiRIAPAAIAAA4QAEgIAJgGQAJgFAJAAQAUAAAKAKQAJAKAAAUIAABEg");
	this.shape_15.setTransform(60,20.9);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgpCzQgjgOgXgXQgXgXgNgjQgNgiAAglQABg1AQgoQAPgnAcgZQAbgZAkgLQAggLAoAAQAPAAANACIAbAFQARAFAJAEQALAEAJAGIgHAbQgCANgCAPIgHAAQgRgZgWgMQgSgLgcAAQgVAAgTAJQgSAKgRAVQgPASgLAgQgKAgAAApQAAApAKAeQALAeAQASQARATATAJQAWAIAUAAQANAAAMgDQANgEALgEQALgFALgIQALgHAIgKIAGAFIgGAWQgDAOgBAKQgpAWg8AAQgqAAghgNg");
	this.shape_16.setTransform(76.7,-12.9);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AghApQgNgPAAgaQAAgVALgPQANgTAWAAQAVAAALANQAPAPAAAbIAAAEIhPAAQABAQAIALQAJANAOAAQAaAAAGgbIABAAIAOAAIAAABQgJAmgmAAQgUAAgNgPgAAhgHQgCgOgHgLQgJgLgPABQgMgBgKALQgHALgDAOIBBAAIAAAAg");
	this.shape_17.setTransform(71.4,23);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AAcBJIAAhCQAAgdgaAAQgMAAgIAJQgJAKgBAOIAAA+IgOAAIAAiRIAOAAIAAA4QAKgTAWAAQAUAAAKAKQAJAKAAAUIAABEg");
	this.shape_18.setTransform(105.9,20.9);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AglAmQgMgQAAgWQAAgWAMgPQAOgSAXAAQAYAAAOASQAMAPAAAWQAAAWgMAQQgOASgYAAQgXAAgOgSgAgagdQgJANAAAQQAAARAJAMQAKAPAQAAQAQAAAKgPQAJgMAAgRQAAgQgJgNQgKgOgQABQgQgBgKAOg");
	this.shape_19.setTransform(117.2,23);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgIALIAAgVIARAAIAAAVg");
	this.shape_20.setTransform(180.5,27.1);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgqAOIAAhEIAPAAIAABEQAAAcAbAAQANAAAIgNQAHgMAAgQIAAg3IAPAAIAABpIgOAAIAAgRQgLAUgWABQgmAAAAgpg");
	this.shape_21.setTransform(173.2,23.1);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgGBJIAAiRIANAAIAACRg");
	this.shape_22.setTransform(125.3,20.9);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AghApQgNgPgBgaQAAgVALgPQANgTAXAAQAUAAAMANQAQAPAAAbIAAAEIhPAAQAAAQAIALQAJANAOAAQAZAAAHgbIAAAAIAPAAIAAABQgJAmgmAAQgVAAgMgPgAAggHQAAgOgJgLQgJgLgOABQgMgBgJALQgJALgBAOIA/AAIAAAAg");
	this.shape_23.setTransform(133.1,23);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AgbBJIgIgCIgBAAIAAgNIAKABQAHAAAEgDQACgDAEgJIAFgMIgrhoIAQAAIAgBWIAghWIAPAAIgvB5QgEAOgFAFQgFAEgMABg");
	this.shape_24.setTransform(150.7,24.9);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AglAmQgMgQAAgWQAAgWAMgPQAOgSAXAAQAYAAAOASQAMAPAAAWQAAAWgMAQQgOASgYAAQgXAAgOgSgAgagdQgJANAAAQQAAARAJAMQAKAPAQAAQARAAAKgPQAIgMAAgRQAAgQgIgNQgKgOgRABQgQgBgKAOg");
	this.shape_25.setTransform(161.6,23);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("ABaB5IgjAAIgPABIAAiNIgCgaQgBgLgEgGQgLgPgUAAQgTAAgLATQgKAUAAAiIAAB+IgQgBIgzABIAAjtIAQACIAQABIATgBIAQgCIAAAlIABABQANgVARgLQASgMAXAAQAgAAAUAWQAUAVAAAvIAACZIgQgBg");
	this.shape_26.setTransform(130.5,-6.6);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("ABeC6IgnAAIgQABIAAiPIAAgaQgCgLgFgGQgKgNgTAAQgVAAgKARQgKAUAAAiIAACAIgQgBIg3ABIAAl1IAQACIATABIAUgBIAQgCIAACtIABABQANgVASgLQAQgMAXAAQAlAAAUAWQAUAVAAAtIAACbIgQgBg");
	this.shape_27.setTransform(-142.5,-13.1);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AgjC6IAAlNIhbAGIAAgsIBZADICkgDIAAAWIAAAWIhYgGIAAFNg");
	this.shape_28.setTransform(-168.7,-13.2);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AgtBJIAAiRIBbAAIAAAOIhMAAIAAAyIBEAAIAAAMIhEAAIAABFg");
	this.shape_29.setTransform(15.1,20.9);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("AglAmQgMgQAAgWQAAgWAMgPQAOgSAXAAQAYAAAOASQAMAPAAAWQAAAWgMAQQgOASgYAAQgXAAgOgSgAgagdQgIANAAAQQAAARAIAMQAKAPAQAAQARAAAKgPQAJgMAAgRQAAgQgJgNQgKgOgRABQgQgBgKAOg");
	this.shape_30.setTransform(26.1,23);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("AgYAbQgLgMAAgPQAAgOALgLQALgMANAAQAPAAAKAMQALALAAAOQAAAQgLALQgKALgPAAQgNAAgLgLg");
	this.shape_31.setTransform(149.1,-26.8);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FFFFFF").s().p("AgYAbQgLgMAAgPQAAgOALgLQAKgMAOAAQAPAAAKAMQALALAAAOQAAAPgLAMQgKALgPAAQgOAAgKgLg");
	this.shape_32.setTransform(111.5,-26.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-181.4,-32.2,362.9,64.4);


(lib.sub1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// type
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#6B8A21").s().p("AAAAGQgFABAAgHIAAAAQAAgFAFAAIAAAAQAGAAAAAFIAAAAQAAAHgGgBg");
	this.shape.setTransform(221.5,33.8);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#6B8A21").s().p("AAgArQgEAAgBgEIAAgrQAAgHgBgFQgCgGgDgEQgEgEgEgCQgFgCgGAAIgJABIgIAEIgGAHIgGAIIAAA1QABAEgEAAIgBAAQgEAAAAgEIAAhPIADgBQABAAAAAAQABAAAAABQABAAAAAAQAAAAAAABQACACAAAFIAAAHIAGgHIAHgFQAEgDAEgBQAFgBADAAQAIAAAHADQAGACAEAFQAFAFACAHQACAHAAAJIAAArQAAAEgDAAg");
	this.shape_1.setTransform(215,30.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#6B8A21").s().p("AgQApQgIgEgFgGQgHgGgCgIQgEgIAAgJQAAgIAEgIQACgJAHgGQAFgFAIgEQAJgDAHAAQAJAAAIADQAIAEAGAGQAGAGADAIQADAIAAAIQAAAJgDAIQgDAIgGAGQgGAGgIAEQgIADgJAAQgHAAgJgDgAgMghQgGADgFAFQgFAFgCAHQgDAGAAAHQAAAHADAHQACAHAFAFQAFAFAGADQAHACAFAAQAHAAAHgCQAGgDAEgFQAFgFADgHQADgGgBgIQABgGgDgHQgDgHgFgFQgEgFgGgDQgHgCgHAAQgFAAgHACg");
	this.shape_2.setTransform(205.1,30.2);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#6B8A21").s().p("AAAA8QgCAAAAgEIAAhMQAAgEACAAIAAAAQAEAAAAAEIAABMQAAAEgEAAgAgEg1QgBgGAFAAQAFAAAAAGQABAGgGAAQgEAAAAgGg");
	this.shape_3.setTransform(198.3,28.4);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#6B8A21").s().p("AgRApQgHgDgEgEQgFgEABgDQAAgEAEgBQAFAGAGAFIAJADIAJAAIAKAAIAIgEIAEgGQACgCAAgEQAAgEgCgDIgGgFQgEgCgNgDQgOgDgGgBQgFgEgCgDQgDgFAAgFQAAgFACgFQACgFAFgDQAEgDAGgCQAGgCAFAAQAJAAAIADQAGADAFADQADAEAAADQAAAAAAABQAAAAgBABQAAAAAAABQgBAAAAAAIgDABQgEgGgGgDQgHgDgJAAIgIAAQgEACgDACQgEACgBADQgCADABAEQgBAEACACIAGAFQAEACAMADIALADQAGAAAEACQAFADADADQACAEAAAHQABAFgDAFQgCAEgFAEQgEADgGACQgGACgIAAQgIAAgJgDg");
	this.shape_4.setTransform(192.6,30.2);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#6B8A21").s().p("AgRApQgHgDgEgEQgFgEAAgDQABgEAFgBQAEAGAGAFIAJADIAIAAIAKAAIAIgEIAFgGQACgCAAgEQAAgEgCgDIgGgFQgEgCgNgDQgOgDgGgBQgEgEgDgDQgDgFAAgFQAAgFADgFQACgFAEgDQAEgDAGgCQAGgCAFAAQAJAAAIADQAGADAEADQAEAEAAADQAAAAAAABQAAAAgBABQAAAAAAABQgBAAgBAAIgCABQgEgGgGgDQgHgDgJAAIgIAAQgEACgEACQgDACgBADQgBADAAAEQAAAEABACIAFAFQAFACAMADIALADQAGAAAEACQAFADADADQADAEAAAHQgBAFgCAFQgDAEgDAEQgFADgGACQgHACgHAAQgJAAgIgDg");
	this.shape_5.setTransform(184.6,30.2);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#6B8A21").s().p("AgNApQgIgEgGgFQgGgGgDgIQgDgJAAgJQAAgIADgIQADgIAGgGQAGgGAHgEQAIgDAHAAQAJAAAHADQAHADAGAFQAFAGADAIQACAHAAAKIAAABQAAAAAAAAQAAAAgBAAQAAAAgBAAQAAAAgBAAIhEAAQABAJACAGQADAHAEAEQAFAFAGADQAHACAFAAQAHAAAFgBQAFgCAEgCQAGgFAEgHIADABQAAAAABABQAAAAAAABQABAAAAABQAAAAAAABQAAAEgGAFQgEAFgHADQgJADgKAAQgHAAgIgDgAAfgFQAAgHgCgFQgCgGgEgEQgEgEgGgCQgFgDgHABQgEgBgGADQgGACgEAEIgHAKQgDAFgBAHIA9AAIAAAAg");
	this.shape_6.setTransform(176,30.2);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#6B8A21").s().p("AgRApQgHgDgEgEQgFgEABgDQAAgEAEgBQAEAGAHAFIAJADIAIAAIALAAIAHgEIAFgGQACgCAAgEQAAgEgCgDIgGgFQgEgCgNgDQgOgDgGgBQgEgEgDgDQgDgFAAgFQAAgFACgFQACgFAFgDQAEgDAGgCQAGgCAFAAQAKAAAHADQAGADAEADQAEAEAAADQAAAAAAABQAAAAgBABQAAAAAAABQgBAAAAAAIgDABQgDgGgHgDQgHgDgJAAIgIAAQgEACgEACQgCACgCADQgCADABAEQgBAEACACIAGAFQAEACAMADIALADQAGAAAEACQAFADADADQACAEAAAHQABAFgDAFQgDAEgEAEQgEADgGACQgHACgHAAQgJAAgIgDg");
	this.shape_7.setTransform(167.3,30.2);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#6B8A21").s().p("AgQApQgIgEgGgGQgFgGgEgIQgDgIAAgJQAAgIADgIQAEgJAFgGQAGgFAIgEQAIgDAIAAQAJAAAIADQAIAEAGAGQAFAGAEAIQADAIAAAIQAAAJgDAIQgEAIgFAGQgGAGgIAEQgIADgJAAQgIAAgIgDgAgMghQgHADgFAFQgEAFgDAHQgCAGAAAHQAAAHACAHQADAHAEAFQAFAFAHADQAGACAGAAQAHAAAGgCQAHgDAFgFQAFgFACgHQACgGABgIQgBgGgCgHQgCgHgFgFQgFgFgHgDQgGgCgHAAQgGAAgGACg");
	this.shape_8.setTransform(155.2,30.2);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#6B8A21").s().p("AgGA+QgDAAAAgEIAAhIIgPAAQgDAAAAgEIAAAAQAAgEADAAIAPAAIAAgJQgBgHACgGQACgFADgEQADgEACgCQAEgCAHAAQAEAAAEACQADABACACQABABAAAAQABABAAAAQAAABAAABQAAAAAAABIgBADIgBABQgCgDgEgBQgDgCgEAAQgFAAgCABQgDACgCACIgBAHIgBAKIAAAJIARAAQAEAAAAAEIAAAAQAAAEgEAAIgRAAIAABIQAAAEgEAAg");
	this.shape_9.setTransform(147.7,28.2);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#6B8A21").s().p("AAgArQgEAAgBgEIAAgrQAAgHgBgFQgCgGgDgEQgEgEgEgCQgFgCgGAAIgJABIgIAEIgGAHIgGAIIAAA1QABAEgEAAIgBAAQgEAAAAgEIAAhPIADgBQABAAAAAAQABAAAAABQABAAAAAAQAAAAABABQABACAAAFIAAAHIAGgHIAHgFQAEgDAEgBQAEgBAEAAQAIAAAHADQAGACAEAFQAFAFACAHQACAHAAAJIAAArQAAAEgEAAg");
	this.shape_10.setTransform(139.8,30.1);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#6B8A21").s().p("AAAA8QgCAAgBgEIAAhMQABgEACAAIAAAAQAEAAAAAEIAABMQAAAEgEAAgAgEg1QAAgGAEAAQAFAAAAAGQABAGgGAAQgEAAAAgGg");
	this.shape_11.setTransform(133.2,28.4);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#6B8A21").s().p("AgNApQgIgEgGgFQgGgGgDgIQgDgJAAgJQAAgIADgIQADgIAGgGQAGgGAHgEQAIgDAHAAQAJAAAHADQAHADAGAFQAFAGADAIQACAHAAAKIAAABQAAAAAAAAQAAAAgBAAQAAAAgBAAQAAAAgBAAIhEAAQABAJACAGQADAHAEAEQAFAFAGADQAHACAFAAQAHAAAFgBQAFgCAEgCQAGgFAEgHIADABQAAAAABABQAAAAAAABQABAAAAABQAAAAAAABQAAAEgGAFQgEAFgHADQgJADgKAAQgHAAgIgDgAAfgFQAAgHgCgFQgCgGgEgEQgEgEgGgCQgFgDgHABQgEgBgGADQgGACgEAEIgHAKQgDAFgBAHIA9AAIAAAAg");
	this.shape_12.setTransform(123.6,30.2);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#6B8A21").s().p("AgNApQgIgEgGgFQgGgGgDgIQgDgJAAgJQAAgIADgIQADgIAGgGQAGgGAHgEQAIgDAHAAQAJAAAHADQAHADAGAFQAFAGADAIQACAHAAAKIAAABQAAAAAAAAQAAAAgBAAQAAAAgBAAQAAAAgBAAIhEAAQABAJACAGQADAHAEAEQAFAFAGADQAHACAFAAQAHAAAFgBQAFgCAEgCQAGgFAEgHIADABQAAAAABABQAAAAAAABQAAAAABABQAAAAAAABQAAAEgGAFQgEAFgHADQgJADgKAAQgHAAgIgDgAAfgFQAAgHgCgFQgCgGgEgEQgEgEgGgCQgFgDgHABQgEgBgGADQgGACgEAEIgHAKQgDAFgBAHIA9AAIAAAAg");
	this.shape_13.setTransform(114.2,30.2);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#6B8A21").s().p("AgQArQgEAAgBgEIAAhPIAEgBQAAAAABAAQAAAAABABQAAAAAAAAQABAAAAABQACACAAAFIAAAKQABgFADgEQABgEADgCQAEgDABgBQAEgBAFAAQAEAAAEACQAEACgBADQAAABAAAAQAAABAAAAQAAABAAAAQgBAAAAABIgBABQgFgEgFAAQgGAAgDADQgEACgDAGQgCAEgBAIQgCAHAAAGIAAAlQAAAEgEAAg");
	this.shape_14.setTransform(107,30.1);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#6B8A21").s().p("AgFA+QgFAAAAgEIAAhIIgNAAQgFAAAAgEIAAAAQAAgEAFAAIANAAIAAgJQABgHABgGQACgFADgEQADgEACgCQAEgCAHAAQAEAAAEACQADABACACQABABAAAAQABABAAAAQAAABAAABQABAAAAABIgCADIgBABQgCgDgDgBQgFgCgDAAQgFAAgDABQgCACgCACIgBAHIgBAKIAAAJIARAAQAEAAAAAEIAAAAQAAAEgEAAIgRAAIAABIQAAAEgDAAg");
	this.shape_15.setTransform(101.1,28.2);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#6B8A21").s().p("AgRAqQgGgBgEgDQgEgDgCgFQgCgEAAgFQAAgIAFgFQADgFAIgDQAHgCAMgBIAZgCIACAAIAAgFQAAgGgCgEQgCgFgDgDQgDgDgFgCQgFgCgGAAIgIABIgJAEQgGAEgEAHQgFAAAAgFQAAgDAFgFQAFgFAGgCQAJgEAHAAQAIAAAHADQAGACAEAEQAFAEACAGQADAHgBAHIAAA0IgCABQgBAAgBAAQAAAAgBgBQAAAAgBAAQAAAAgBgBQgBgCAAgFIAAgJQgCAEgDAEQgDADgFADIgJAEIgKABQgHAAgFgCgAABABIgPAEQgFADgEADQgDAEAAAGQABADABADQACADADACQACADAEABIAJABQAFAAAGgCQAGgDAEgDQAFgEADgGQACgFAAgGIAAgIIgCAAQgPAAgJABg");
	this.shape_16.setTransform(90.1,30.1);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#6B8A21").s().p("AgQArQgFAAAAgEIAAhPIAEgBQAAAAABAAQAAAAABABQAAAAAAAAQABAAAAABQACACAAAFIAAAKQABgFADgEQACgEACgCQAEgDACgBQADgBAFAAQAEAAAEACQADACAAADQAAABAAAAQAAABAAAAQAAABAAAAQgBAAAAABIgBABQgFgEgFAAQgGAAgDADQgEACgCAGQgDAEgCAIQgBAHAAAGIAAAlQAAAEgDAAg");
	this.shape_17.setTransform(80.3,30.1);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#6B8A21").s().p("AgQApQgIgEgGgGQgFgGgEgIQgDgIAAgJQAAgIADgIQAEgJAFgGQAGgFAIgEQAIgDAIAAQAJAAAIADQAIAEAGAGQAGAGADAIQADAIAAAIQAAAJgDAIQgDAIgGAGQgGAGgIAEQgIADgJAAQgIAAgIgDgAgMghQgHADgFAFQgEAFgDAHQgCAGAAAHQAAAHACAHQADAHAEAFQAFAFAHADQAGACAGAAQAHAAAGgCQAHgDAFgFQAFgFACgHQADgGAAgIQAAgGgDgHQgCgHgFgFQgFgFgHgDQgGgCgHAAQgGAAgGACg");
	this.shape_18.setTransform(71.8,30.2);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#6B8A21").s().p("AgGA+QgDAAAAgEIAAhIIgPAAQgDAAAAgEIAAAAQAAgEADAAIAPAAIAAgJQgBgHACgGQACgFADgEQADgEACgCQAEgCAGAAQAFAAAEACQADABACACQABABAAAAQABABAAAAQAAABAAABQAAAAAAABIgBADIgBABQgCgDgEgBQgDgCgFAAQgEAAgCABQgEACgBACIgBAHIgBAKIAAAJIARAAQAEAAAAAEIAAAAQAAAEgEAAIgRAAIAABIQAAAEgEAAg");
	this.shape_19.setTransform(64.4,28.2);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#6B8A21").s().p("AgRArQgDAAAAgEIAAhPIACgBQABAAABAAQAAAAABABQAAAAAAAAQABAAAAABQACACAAAFIAAAKQABgFACgEQADgEADgCQACgDADgBQADgBAEAAQAGAAADACQADACABADQAAABgBAAQAAABAAAAQAAABAAAAQgBAAAAABIgBABQgEgEgHAAQgFAAgDADQgDACgEAGQgCAEgBAIQgCAHAAAGIAAAlQAAAEgEAAg");
	this.shape_20.setTransform(55.7,30.1);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#6B8A21").s().p("AgNApQgIgEgGgFQgGgGgDgIQgDgJAAgJQAAgIADgIQADgIAGgGQAGgGAHgEQAIgDAHAAQAJAAAHADQAHADAGAFQAFAGADAIQACAHAAAKIAAABQAAAAAAAAQAAAAgBAAQAAAAgBAAQAAAAgBAAIhEAAQABAJACAGQADAHAEAEQAFAFAGADQAHACAFAAQAHAAAFgBQAFgCAEgCQAGgFAEgHIADABQAAAAABABQAAAAAAABQABAAAAABQAAAAAAABQAAAEgGAFQgEAFgHADQgJADgKAAQgHAAgIgDgAAfgFQAAgHgCgFQgCgGgEgEQgEgEgGgCQgFgDgHABQgEgBgGADQgGACgEAEIgHAKQgDAFgBAHIA9AAIAAAAg");
	this.shape_21.setTransform(47.5,30.2);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#6B8A21").s().p("AAAAzQgDgBgDgDQgCgEgBgEQgCgGAAgGIAAgzIgLAAQgDAAAAgEIAAAAQAAgEADABIALAAIAAgRQAAgFAEAAIABAAQAEAAgBAFIAAARIAXAAQAEgBABAEIAAAAQgBAEgEAAIgXAAIAAAyQAAAKADAFQACAFAIAAQAFAAADgCQAEgCABgDIACABQAAAAABAAQAAAAAAABQAAAAAAABQABAAAAABQAAACgEADQgBADgEABQgEABgEAAQgGAAgEgCg");
	this.shape_22.setTransform(39.9,29.2);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#6B8A21").s().p("AgRApQgHgDgEgEQgEgEgBgDQAAgEAGgBQADAGAHAFIAJADIAIAAIAKAAIAIgEIAFgGQACgCAAgEQAAgEgCgDIgGgFQgEgCgNgDQgOgDgGgBQgEgEgDgDQgDgFAAgFQAAgFADgFQACgFAEgDQAEgDAGgCQAGgCAFAAQAJAAAIADQAHADADADQAEAEAAADQAAAAAAABQAAAAgBABQAAAAAAABQgBAAgBAAIgCABQgDgGgHgDQgHgDgJAAIgIAAQgEACgEACQgDACgBADQgCADAAAEQAAAEACACIAFAFQAFACAMADIALADQAGAAAEACQAFADACADQAEAEAAAHQgBAFgCAFQgCAEgEAEQgFADgGACQgGACgIAAQgIAAgJgDg");
	this.shape_23.setTransform(32.9,30.2);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#6B8A21").s().p("AAAA8QgCAAgBgEIAAhMQABgEACAAIAAAAQAEAAAAAEIAABMQAAAEgEAAgAgFg1QABgGAEAAQAGAAgBAGQAAAGgFAAQgFAAAAgGg");
	this.shape_24.setTransform(27.2,28.4);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#6B8A21").s().p("AgRBBQgIgCgFgDQgFgDgCgEQgDgEAAgGQAAgFADgEQACgEAEgDIAJgGIALgDQgDgBgBgCQgCgDAAgDQAAgFAFgEIgJgCIgHgGIgEgIQgBgFAAgFQAAgGACgGQADgFAEgFQAFgEAGgCQAGgDAHAAQAEAAAGACQAFACAFADIAIgLQADgFAEABQADACAAACIgNAPQADAEACAFQACAFAAAGQAAAGgCAGQgDAFgFAEQgEAFgGAAQgHACgFAAIgGAAQgDACAAAEQAAAEAHACIAPAEIAKADIAJAFIAGAGQADAEAAAFQAAAGgDAFQgDAEgGAEQgFADgIABQgIACgIAAQgKAAgHgBgAgLAZIgLAEQgEADgDADQgCAEAAAEQAAAEACADQACADAEACQAEACAGABQAFABAIAAQAGAAAGgBIALgDQAEgDADgDQACgDAAgEQAAgEgCgCIgFgFQgFgDgJgCIgLgDIgLACgAgKgwQgEACgEADQgDADgCAFQgCAEAAAFQAAAFACAEQACAFADADQAEADAEACQAFABAFAAQAEAAAEgBQAFgCADgDQAEgDABgFQACgEAAgFQAAgFgCgEQgBgFgEgDQgDgDgFgCQgEgBgEAAQgFAAgFABg");
	this.shape_25.setTransform(21.4,31.5);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#6B8A21").s().p("AgNApQgIgEgGgFQgGgGgDgIQgDgJAAgJQAAgIADgIQADgIAGgGQAGgGAHgEQAIgDAHAAQAJAAAHADQAHADAGAFQAFAGADAIQACAHAAAKIAAABQAAAAAAAAQAAAAgBAAQAAAAgBAAQAAAAgBAAIhEAAQABAJACAGQADAHAEAEQAFAFAGADQAHACAFAAQAHAAAFgBQAFgCAEgCQAGgFAEgHIADABQAAAAABABQAAAAAAABQABAAAAABQAAAAAAABQAAAEgGAFQgEAFgHADQgJADgKAAQgHAAgIgDgAAfgFQAAgHgCgFQgCgGgEgEQgEgEgGgCQgFgDgHABQgEgBgGADQgGACgEAEIgHAKQgDAFgBAHIA9AAIAAAAg");
	this.shape_26.setTransform(12.6,30.2);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#6B8A21").s().p("AgQArQgFAAAAgEIAAhPIADgBQABAAABAAQAAAAABABQAAAAAAAAQABAAAAABQACACAAAFIAAAKQABgFACgEQADgEACgCQADgDADgBQADgBAFAAQAFAAADACQADACABADQgBABAAAAQAAABAAAAQAAABAAAAQgBAAAAABIgBABQgEgEgGAAQgGAAgDADQgDACgDAGQgDAEgCAIQgBAHAAAGIAAAlQAAAEgDAAg");
	this.shape_27.setTransform(5.5,30.1);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#6B8A21").s().p("AgRArQgDAAAAgEIAAhPIACgBQABAAABAAQAAAAABABQAAAAAAAAQABAAAAABQACACAAAFIAAAKQABgFACgEQACgEAEgCQACgDACgBQAEgBAEAAQAGAAADACQAEACAAADQAAABgBAAQAAABAAAAQAAABAAAAQgBAAAAABIgBABQgEgEgHAAQgFAAgDADQgDACgEAGQgCAEgBAIQgCAHAAAGIAAAlQAAAEgEAAg");
	this.shape_28.setTransform(214,12.1);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#6B8A21").s().p("AgQApQgIgEgFgGQgHgGgCgIQgEgIAAgJQAAgIAEgJQACgIAHgGQAFgFAIgEQAJgDAHAAQAJAAAIADQAIAEAGAGQAGAGADAIQADAIAAAIQAAAJgDAIQgDAIgGAGQgGAGgIAEQgIADgJAAQgHAAgJgDgAgMghQgGADgFAFQgFAFgCAHQgDAGAAAHQAAAHADAHQACAHAFAFQAFAFAGADQAHACAFAAQAHAAAHgCQAGgDAEgFQAFgFADgHQADgGgBgIQABgGgDgHQgDgHgFgFQgEgFgGgDQgHgCgHAAQgFAAgHACg");
	this.shape_29.setTransform(205.5,12.2);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#6B8A21").s().p("AgNApQgIgEgGgFQgGgGgDgJQgDgIAAgJQAAgIADgIQADgIAGgGQAGgGAHgEQAIgDAHAAQAJAAAHADQAHADAGAFQAFAGADAIQACAHAAAKIAAABQAAAAAAAAQAAAAgBAAQAAAAgBAAQAAAAgBAAIhEAAQABAJACAGQADAHAEAEQAFAFAGADQAHACAFAAQAHAAAFgBQAFgCAEgCQAGgFAEgHIADABQAAAAABABQAAAAAAABQAAAAABABQAAAAAAABQAAAEgGAFQgEAFgHADQgJADgKAAQgHAAgIgDgAAfgFQAAgHgCgFQgCgGgEgEQgEgEgGgCQgFgDgHABQgEgBgGADQgGACgEAEIgHAKQgDAFgBAHIA9AAIAAAAg");
	this.shape_30.setTransform(192.7,12.2);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#6B8A21").s().p("AgRArQgDAAAAgEIAAhPIACgBQABAAABAAQAAAAABABQAAAAAAAAQABAAAAABQACACAAAFIAAAKQABgFACgEQACgEAEgCQADgDABgBQAEgBAEAAQAFAAAEACQAEACAAADQAAABgBAAQAAABAAAAQAAABAAAAQgBAAAAABIgBABQgFgEgGAAQgFAAgDADQgEACgDAGQgCAEgBAIQgCAHAAAGIAAAlQAAAEgEAAg");
	this.shape_31.setTransform(185.5,12.1);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#6B8A21").s().p("AgQApQgIgEgFgGQgHgGgCgIQgEgIAAgJQAAgIAEgJQACgIAHgGQAFgFAIgEQAJgDAHAAQAJAAAIADQAIAEAGAGQAGAGADAIQADAIAAAIQAAAJgDAIQgDAIgGAGQgGAGgIAEQgIADgJAAQgHAAgJgDgAgMghQgGADgGAFQgEAFgCAHQgDAGAAAHQAAAHADAHQACAHAEAFQAGAFAGADQAHACAFAAQAHAAAHgCQAGgDAFgFQAEgFADgHQADgGgBgIQABgGgDgHQgDgHgEgFQgFgFgGgDQgHgCgHAAQgFAAgHACg");
	this.shape_32.setTransform(177.1,12.2);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#6B8A21").s().p("AA7ArQgDAAAAgEIAAgsQAAgHgCgFQgCgGgDgEQgCgDgGgCQgEgCgGAAIgJABIgIAEIgFAGIgGAJIAAA1QAAAEgDAAIAAAAQgDAAAAgEIAAguQAAgGgBgFQgCgFgDgEQgDgDgFgCQgEgCgHAAQgEAAgEABIgHAEQgEADgDADIgFAJIAAA1QAAAEgEAAIgBAAQgEAAAAgEIAAhPIAEgBQAAAAABAAQAAAAABABQAAAAAAAAQABAAAAABQACACAAAFIAAAHIAFgHIAHgFIAIgEIAJgBQAFAAAFABIAIAEQAEADACAEIADAIIAEgIIAHgHIAJgEQAFgBAFAAQAIAAAHACQAFADAFAEQAEAFACAHQACAHABAJIAAAsQAAAEgFAAg");
	this.shape_33.setTransform(164.4,12.1);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#6B8A21").s().p("AAgArQgFAAAAgEIAAgrQAAgHgBgFQgCgGgDgEQgDgEgFgCQgFgCgHAAIgIABIgIAEIgGAHIgGAIIAAA1QAAAEgDAAIgBAAQgEAAAAgEIAAhPIADgBQABAAAAAAQABAAAAABQABAAAAAAQAAAAABABQABACAAAFIAAAHIAGgHIAGgFQAFgDAEgBQAFgBADAAQAJAAAGADQAGACAEAFQAFAFACAHQACAHAAAJIAAArQAAAEgDAAg");
	this.shape_34.setTransform(148.7,12.1);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#6B8A21").s().p("AgQArQgFAAAAgEIAAhPIADgBQABAAABAAQAAAAABABQAAAAAAAAQABAAAAABQACACAAAFIAAAKQABgFACgEQADgEACgCQADgDADgBQADgBAFAAQAFAAADACQADACABADQgBABAAAAQAAABAAAAQAAABAAAAQgBAAAAABIgBABQgEgEgGAAQgGAAgDADQgEACgCAGQgDAEgCAIQgBAHAAAGIAAAlQAAAEgDAAg");
	this.shape_35.setTransform(141.4,12.1);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#6B8A21").s().p("AgRAqQgGgBgEgDQgDgDgCgFQgCgEgBgFQABgIAEgFQADgFAHgDQAIgCALgBIAagCIACAAIAAgFQAAgGgCgEQgCgFgDgDQgDgDgFgCQgFgCgGAAIgIABIgIAEQgIAEgDAHQgFAAAAgFQAAgDAFgFQAEgFAIgCQAHgEAJAAQAHAAAGADQAHACAEAEQAFAEACAGQACAHAAAHIAAA0IgDABQAAAAgBAAQAAAAgBgBQAAAAgBAAQAAAAAAgBQgCgCAAgFIAAgJQgCAEgDAEQgDADgFADIgKAEIgJABQgHAAgFgCgAABABIgOAEQgHADgCADQgDAEgBAGQAAADACADQABADADACQADADAEABIAJABQAFAAAGgCQAGgDAEgDQAFgEACgGQADgFAAgGIAAgIIgDAAQgNAAgKABg");
	this.shape_36.setTransform(133.2,12.1);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#6B8A21").s().p("AgNApQgIgEgGgFQgGgGgDgJQgDgIAAgJQAAgIADgIQADgIAGgGQAGgGAHgEQAIgDAHAAQAJAAAHADQAHADAGAFQAFAGADAIQACAHAAAKIAAABQAAAAAAAAQAAAAgBAAQAAAAgBAAQAAAAgBAAIhEAAQABAJACAGQADAHAEAEQAFAFAGADQAHACAFAAQAHAAAFgBQAFgCAEgCQAGgFAEgHIADABQAAAAABABQAAAAAAABQABAAAAABQAAAAAAABQAAAEgGAFQgEAFgHADQgJADgKAAQgHAAgIgDgAAfgFQAAgHgCgFQgCgGgEgEQgEgEgGgCQgFgDgHABQgEgBgGADQgGACgEAEIgHAKQgDAFgBAHIA9AAIAAAAg");
	this.shape_37.setTransform(124.2,12.2);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#6B8A21").s().p("AAAA9QgDAAAAgEIAAh0IADgBQAAAAAAAAQAAAAAAABQABAAAAAAQAAAAABABQACACAAAFIAABsQAAAEgEAAg");
	this.shape_38.setTransform(117.8,10.3);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#6B8A21").s().p("AgQApQgIgEgFgGQgHgGgCgIQgEgIAAgJQAAgIAEgJQACgIAHgGQAFgFAIgEQAJgDAHAAQAJAAAIADQAIAEAGAGQAGAGADAIQADAIAAAIQAAAJgDAIQgDAIgGAGQgGAGgIAEQgIADgJAAQgHAAgJgDgAgMghQgGADgFAFQgFAFgCAHQgDAGAAAHQAAAHADAHQACAHAFAFQAFAFAGADQAHACAFAAQAHAAAHgCQAGgDAEgFQAFgFADgHQADgGgBgIQABgGgDgHQgDgHgFgFQgEgFgGgDQgHgCgHAAQgFAAgHACg");
	this.shape_39.setTransform(107.9,12.2);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#6B8A21").s().p("AAAAzQgDgBgDgDQgCgEgBgEQgCgGAAgGIAAgzIgLAAQgEAAAAgEIAAAAQAAgEAEABIALAAIAAgRQAAgFAEAAIABAAQAEAAAAAFIAAARIAWAAQAFgBAAAEIAAAAQAAAEgFAAIgWAAIAAAyQAAAKACAFQADAFAHAAQAEAAAEgCQAEgCACgDIABABQAAAAABAAQAAAAAAABQAAAAAAABQAAAAAAABQAAACgCADQgCADgEABQgEABgFAAQgFAAgEgCg");
	this.shape_40.setTransform(99.9,11.2);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#6B8A21").s().p("AghA6QgGAAAAgGIAAhnQAAgGAGAAIBDAAQAFAAAAAEIAAABQAAADgFAAIhAAAIAAAtIAyAAQADAAAAAEIAAAAQAAACgDAAIgyAAIAAAwIBCAAQAEAAAAADIAAABQAAAEgEAAg");
	this.shape_41.setTransform(89.1,10.6);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#6B8A21").s().p("AAcA3IgqgvIgPAAIAAAuQAAAEgEAAIgBAAQgEAAAAgEIAAhpQAAgGAGAAIAfAAQAIAAAIACQAIACAFAEQAGAFACAGQADAGAAAIQAAAIgDAHQgCAGgFADQgGADgHACQgHADgJAAIgDAAIAqAuQAAAAAAAAQAAAAAAABQgBAAAAAAQAAABgBAAQAAABgBAAQAAAAgBABQAAAAgBAAQAAAAgBAAQgDAAgCgDgAgdAAIAdAAQAGAAAGAAQAGgBAEgEQAEgEACgEQACgFAAgGQAAgFgCgFQgCgFgEgDQgEgDgGgCQgGgCgGAAIgdAAg");
	this.shape_42.setTransform(78.9,10.6);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#6B8A21").s().p("AgiA6QgFAAAAgGIAAhnQAAgGAFAAIBFAAQADAAAAAEIAAABQAAADgDAAIhBAAIAAAtIAxAAQAFAAAAAEIAAAAQAAACgFAAIgxAAIAAAwIBCAAQAEAAAAADIAAABQAAAEgEAAg");
	this.shape_43.setTransform(68.9,10.6);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#6B8A21").s().p("AApA6QgEAAAAgEIAAgyIhJAAIAAAyQAAAEgEAAIgBAAQgEAAAAgEIAAhrQAAgEAEAAIABAAQAEAAAAAEIAAAyIBJAAIAAgyQAAgEAEAAIABAAQAEAAAAAEIAABrQAAAEgEAAg");
	this.shape_44.setTransform(57.4,10.6);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#6B8A21").s().p("AAbA4Ig3g4IAAA2QAAAEgEAAIgBAAQgEAAAAgEIAAhrQAAgEAEAAIABAAQAEAAAAAEIAAA0IA2g2QAEgDADABQABAAAAABQABAAAAABQAAAAABABQAAAAgBABIg1A1IA3A2QABADgEABIgCAAQgCAAgDgCg");
	this.shape_45.setTransform(43.9,10.6);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#6B8A21").s().p("AgFA6IgLgDQgFgCgFgDIgIgHIgHgJIgFgKIgDgMIgBgMQAAgFABgGIADgLIAFgLIAHgIIAIgIIAKgFIALgDQAFgCAGAAQAJAAAOAFQAIADAGAGQAGAGAAAFQAAADgCACIgDABQgCgFgEgEIgJgHIgLgFIgNgCIgIABIgJADQgJAEgGAHQgHAHgDAKQgEANAAAGQABAOADAGQADAKAHAHIAHAGIAIAFIAJADIAJABQAIAAAGgCQAHgCAFgEQAFgDADgFIAFgJQAGABAAAEQgDAJgFAFQgGAGgJADQgOAFgIAAQgGAAgFgCg");
	this.shape_46.setTransform(32.9,10.6);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("#6B8A21").s().p("AAAA6QgDAAAAgEIAAhrQAAgEADAAIAAAAQAEAAAAAEIAABrQAAAEgEAAg");
	this.shape_47.setTransform(24.9,10.6);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("#6B8A21").s().p("AgcA6QgGAAAAgGIAAhpQAAgEAEAAIABAAQAEAAAAAEIAABnIA3AAQAFAAAAADIAAABQAAAEgFAAg");
	this.shape_48.setTransform(18.7,10.6);

	this.shape_49 = new cjs.Shape();
	this.shape_49.graphics.f("#6B8A21").s().p("AgFA6IgLgDQgFgCgFgDIgIgHIgHgJIgFgKIgDgMIgBgMQAAgFABgGIADgLIAFgLIAHgIIAIgIIAKgFIALgDQAFgCAGAAQAJAAAOAFQAIADAGAGQAGAGAAAFQAAADgCACIgDABQgCgFgEgEIgJgHIgLgFIgNgCIgIABIgJADQgJAEgGAHQgHAHgDAKQgEANAAAGQABAOADAGQADAKAHAHIAHAGIAIAFIAJADIAJABQAIAAAGgCQAHgCAFgEQAFgDADgFIAFgJQAGABAAAEQgDAJgFAFQgGAGgJADQgOAFgIAAQgGAAgFgCg");
	this.shape_49.setTransform(8,10.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_49},{t:this.shape_48},{t:this.shape_47},{t:this.shape_46},{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,232,40);


(lib.replaybtn = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#666666").s().p("Ak9BwIAAjgIJ6AAIAADgg");
	this.shape.setTransform(9.1,9.8,0.438,1.268,0,0,0,-0.2,0);
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(3).to({_off:false},0).wait(1));

	// Layer 2
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#BFBFBF").s().p("AgEBGQghgDgWgXQgXgZAAgfQAAgQAGgQQAOggAfgNQARgGAOgBQAiAAAYAZQAZAYAAAjIgUAAQAAgbgTgSQgSgTgaAAQgZAAgSATQgTATAAAaQAAAXARASQAQASAZACIgNgcIBVAnIhWAlg");
	this.shape_1.setTransform(8.4,9.7);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#666666").s().p("AgEBGQghgDgWgXQgXgZAAgfQAAgQAGgQQAOggAfgNQARgGAOgBQAiAAAYAZQAZAYAAAjIgUAAQAAgbgTgSQgSgTgaAAQgZAAgSATQgTATAAAaQAAAXARASQAQASAZACIgNgcIBVAnIhWAlg");
	this.shape_2.setTransform(8.4,9.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AgEBGQghgDgWgXQgXgZAAgfQAAgQAGgQQAOggAfgNQARgGAOgBQAiAAAYAZQAZAYAAAjIgUAAQAAgbgTgSQgSgTgaAAQgZAAgSATQgTATAAAaQAAAXARASQAQASAZACIgNgcIBVAnIhWAlg");
	this.shape_3.setTransform(8.4,9.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1}]}).to({state:[{t:this.shape_2}]},1).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_3}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,16.7,19.4);


(lib.pic = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib._336x280hikers();

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,515,200);


(lib.logoblock = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// bkgd
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#193670").s().p("A9jHCIAArkQAAiUCIgKIAAgBMA23AAAIAAABQCIAKAACUIAALkg");
	this.shape.setTransform(-37.7,45);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-227,0,378.6,90);


(lib.head1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#193670").s().p("AAAAHQgGAAAAgHIAAAAQAAgGAGAAIAAAAQAHAAAAAGIAAAAQAAAHgHAAg");
	this.shape.setTransform(160.3,37.3);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#193670").s().p("AgTAtQgIgCgEgFQgFgFAAgDQAAgEAFgBQAFAHAIAEIAJAEIAKABQAGAAAFgCQAFgBAEgCQADgDACgDQACgEAAgEQAAgEgCgDQgCgEgEgCQgGgCgOgEQgQgDgGgCQgFgDgDgEQgDgFAAgGQAAgGACgGQADgFAFgDQAEgEAHgCQAGgCAGAAQALAAAIADQAHADAFAFQADADAAAEQAAAAAAABQAAAAAAABQgBAAAAABQgBAAAAABIgDABQgEgHgHgEQgIgEgKAAQgEAAgFACQgFABgDACIgFAGQgCADAAAEQAAAFACADIAGAFQAFACANAEIANADIALACQAFADADAEQADAFAAAHQAAAGgCAFQgDAFgFAEQgFAEgGACQgHACgJAAQgKAAgJgEg");
	this.shape_1.setTransform(153.9,33.3);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#193670").s().p("AAjAwQgFAAABgEIAAgxQAAgHgDgGQgBgHgEgEQgDgEgGgDQgGgCgGAAQgEAAgGACQgEABgFADQgEADgDAEQgDAEgCAFIAAA8QgBAEgEAAIgBAAQgEAAAAgEIAAhYIADgBQABAAAAAAQABAAABAAQAAAAABAAQAAABABAAQABADAAAFIAAAJIAGgIIAHgHIAKgDIAJgCQAKAAAGADQAIADAFAGQAFAFACAIQACAHAAAKIAAAxQAAAEgEAAg");
	this.shape_2.setTransform(144.2,33.2);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#193670").s().p("AgSAtQgJgEgGgGQgHgHgDgJQgEgJAAgKQAAgJAEgJQADgJAHgHQAGgHAJgDQAJgEAJAAQAKAAAJAEQAJAEAGAGQAHAHADAJQAEAJAAAJQAAAKgEAJQgDAJgHAHQgGAGgJAEQgJAEgKAAQgJAAgJgEgAgOgkQgHADgFAFQgFAGgDAHQgDAIAAAHQAAAIADAIQADAHAFAGQAFAFAHADQAHADAHAAQAIAAAHgDQAHgDAFgFQAFgGADgHQADgIAAgIQAAgHgDgHQgDgIgFgGQgFgFgHgDQgHgDgIAAQgHAAgHADg");
	this.shape_3.setTransform(133.2,33.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#193670").s().p("AAABDQgDgBAAgEIAAhUQAAgFADAAIAAAAQAFAAgBAFIAABUQABAEgFABgAgFg7QAAgGAFAAQAGAAAAAGQAAAHgGAAQgFAAAAgHg");
	this.shape_4.setTransform(125.7,31.4);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#193670").s().p("AAAA5QgDgBgEgDQgCgEgCgGQgCgGAAgHIAAg4IgLAAQgFAAABgFIAAgBQgBgDAFAAIALAAIAAgSQAAgGAFAAIABAAQAEAAAAAGIAAASIAZAAQAFAAAAADIAAABQAAAFgFAAIgZAAIAAA3QAAAMADAFQACAGAJAAQAFAAAEgDQADgCADgEIACABQAAAAABABQAAAAAAABQAAAAAAABQAAAAAAABQABADgEADQgCADgEABQgEABgGAAQgGAAgEgCg");
	this.shape_5.setTransform(120.5,32.2);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#193670").s().p("AgpBDQgDAAAAgFIAAh9IACgBQABAAABAAQABAAAAAAQABAAAAAAQABABAAAAQACADAAAFIAAALIAGgJQAEgEAEgDQAGgDAFgBQAGgCAFAAQAJAAAIAEQAIADAGAGQAHAHADAJQADAJABALQgBALgDAHQgDAJgHAHQgGAGgIAEQgIADgKAAQgFAAgHgCQgFgBgFgDIgIgHIgFgIIAAA1QAAAFgFAAgAgLg4QgGACgFADIgIAIQgDAFgCAGIAAAWQAAAHACAEQADAHAFAEQAFAFAGACQAIADAGAAQAHAAAHgDQAGgDAGgGQAFgFACgFQACgIABgJQgBgIgCgJQgDgGgEgGQgGgFgHgDQgGgDgHgBQgGAAgFACg");
	this.shape_6.setTransform(111.9,35.1);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#193670").s().p("AgSAtQgJgEgGgGQgHgHgDgJQgEgJAAgKQAAgJAEgJQADgJAHgHQAGgHAJgDQAJgEAJAAQAKAAAJAEQAJAEAGAGQAHAHADAJQAEAJAAAJQAAAKgEAJQgDAJgHAHQgGAGgJAEQgJAEgKAAQgJAAgJgEgAgOgkQgHADgFAFQgFAGgDAHQgDAIAAAHQAAAIADAIQADAHAFAGQAFAFAHADQAHADAHAAQAIAAAHgDQAHgDAFgFQAFgGADgHQADgIAAgIQAAgHgDgHQgDgIgFgGQgFgFgHgDQgHgDgIAAQgHAAgHADg");
	this.shape_7.setTransform(100.3,33.3);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#193670").s().p("AgPAtQgJgDgHgHQgGgHgDgJQgEgJAAgKQAAgJAEgJQADgJAHgHQAGgGAIgEQAJgEAIAAQAKAAAIADQAIAEAGAGQAGAGADAJQADAIAAAKIAAABQAAACgEAAIhLAAQAAAIADAIQADAHAFAFQAFAGAHACQAHADAHAAQAHAAAGgBQAFgCAEgDQAHgEAEgJIADABQADACAAADQAAAEgGAGQgFAFgIADQgJAEgLAAQgJAAgJgEgAAjgFQgBgIgCgGQgDgGgEgFQgEgFgGgCQgGgCgIAAQgFAAgGACQgHADgFAEQgEAFgEAGQgDAGgBAIIBFAAIAAAAg");
	this.shape_8.setTransform(86.1,33.3);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#193670").s().p("AgTBIQgJgCgFgDQgGgDgDgFQgCgFAAgGQAAgGACgEQADgFAEgEQAFgDAGgCIAMgEIgFgEQgCgDAAgDQAAgGAFgEQgFAAgEgCIgIgIIgFgJQgBgEAAgGQAAgHADgGQACgGAFgFQAGgFAGgDQAHgCAIAAQAFAAAGACQAGACAFADIAJgMQADgFAFABQAEABAAADIgQARQAEAEADAGQACAGAAAFQAAAHgDAHQgDAGgFAFQgFAEgHABQgHACgGAAIgGAAQgEACAAAEQAAAFAHADIASAEIALAEQAFACAEADQAFADADAEQACAEAAAGQAAAGgDAFQgDAGgGADQgGAEgJABQgJACgJAAQgLAAgIgBgAgNAcQgGABgFADQgFADgDAEQgDAEAAAFQAAAEACADQADAEAEACQAFACAGABIAPABIAOgBQAHgBAFgDQAEgCADgEQADgDAAgFQAAgEgCgDIgGgEQgFgEgLgCIgMgEQgGABgHACgAgLg1QgFABgEAEQgDAEgCAEQgCAFAAAGQAAAGACAEQACAFADAEQAEADAFACQAFACAGAAQAEAAAFgCQAFgCAEgDQAEgEACgFQACgEAAgGQAAgGgCgFQgCgEgEgEQgEgEgFgBQgFgCgEAAQgGAAgFACg");
	this.shape_9.setTransform(76.4,34.8);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#193670").s().p("AgTAvQgGgCgFgDQgEgEgCgFQgCgEAAgGQAAgIAEgGQAEgGAIgDQAIgCANgCIAdgCIACAAIAAgFQAAgHgCgFQgCgFgEgEQgDgDgGgCQgFgCgHAAQgEAAgFABIgJAEQgIAFgEAIQgGgBAAgFQAAgEAGgFQAFgFAHgDQAJgEAKAAQAIAAAHADQAIACAEAFQAFAFADAGQACAHAAAJIAAA5IgDABQAAAAgBAAQgBAAAAAAQgBAAAAgBQgBAAAAgBQgCgCAAgFIAAgKIgGAIQgEAEgFADQgEADgGABQgFACgGAAQgHAAgGgCgAABABQgJACgHACQgHADgDAEQgEAFAAAGQAAAEACADQACAEADACIAHAEIAKABQAGAAAHgDQAGgCAFgEQAFgFADgGQADgGAAgGIAAgJIgDAAIgaABg");
	this.shape_10.setTransform(66.5,33.3);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#193670").s().p("AAAA5QgDgBgDgDQgEgEgBgGQgBgGgBgHIAAg4IgLAAQgEAAgBgFIAAgBQABgDAEAAIALAAIAAgSQABgGAEAAIABAAQAEAAAAAGIAAASIAZAAQAFAAAAADIAAABQAAAFgFAAIgZAAIAAA3QAAAMADAFQADAGAIAAQAFAAAEgDQAEgCACgEIACABQAAAAABABQAAAAAAABQAAAAAAABQABAAAAABQgBADgDADQgCADgEABQgEABgFAAQgHAAgEgCg");
	this.shape_11.setTransform(58.6,32.2);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#193670").s().p("AAjAwQgFAAAAgEIAAgxQAAgHgCgGQgBgHgEgEQgEgEgFgDQgFgCgHAAQgEAAgFACQgFABgEADQgFADgDAEQgDAEgDAFIAAA8QABAEgFAAIgBAAQgEAAAAgEIAAhYIADgBQABAAAAAAQABAAABAAQAAAAABAAQAAABAAAAQACADAAAFIAAAJIAGgIIAIgHIAJgDIAJgCQAJAAAIADQAHADAEAGQAFAFADAIQACAHAAAKIAAAxQAAAEgEAAg");
	this.shape_12.setTransform(49.9,33.2);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#193670").s().p("AgTAvQgGgCgFgDQgEgEgCgFQgCgEAAgGQAAgIAEgGQAEgGAIgDQAIgCANgCIAdgCIACAAIAAgFQAAgHgCgFQgCgFgEgEQgDgDgGgCQgFgCgHAAQgEAAgFABIgJAEQgIAFgEAIQgGgBAAgFQAAgEAGgFQAFgFAHgDQAJgEAKAAQAIAAAHADQAIACAEAFQAFAFADAGQACAHAAAJIAAA5IgDABQAAAAgBAAQgBAAAAAAQgBAAAAgBQgBAAAAgBQgCgCAAgFIAAgKIgGAIQgEAEgFADQgEADgGABQgFACgGAAQgHAAgGgCgAABABQgJACgHACQgHADgDAEQgEAFAAAGQAAAEACADQACAEADACIAHAEIAKABQAGAAAHgDQAGgCAFgEQAFgFADgGQADgGAAgGIAAgJIgDAAIgaABg");
	this.shape_13.setTransform(39.1,33.3);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#193670").s().p("AgFAsIglhYQAIgGAFAKIAdBOIAghOQADgLAIAHIgkBYQgCAEgFAAQgDAAgCgEg");
	this.shape_14.setTransform(29.8,33.3);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#193670").s().p("AgRBBQgIgEgHgGQgGgHgDgJQgEgJABgLQgBgLAEgIQADgIAGgHQAHgGAIgEQAJgDAIAAQAGAAAFABQAHACAEADIAIAGIAGAIIAAg6IADgBQABAAAAAAQABAAABAAQAAAAABABQAAAAABAAQABADABAFIAAB4QgBAFgEAAIgBAAQgEAAAAgFIAAgPIgHAJQgDAEgFACQgFADgFACQgGABgFAAQgJAAgIgDgAgNgRQgHADgFAFQgFAGgDAFQgCAIAAAJQAAAIACAIQADAIAFAFQAFAGAHADQAGADAHAAQAHAAAGgDQAHgCAFgFQAFgFADgGQADgGAAgHIAAgWIgGgJQgDgFgFgDQgEgDgGgCQgGgCgGAAQgHAAgGADg");
	this.shape_15.setTransform(19.3,31.3);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#193670").s().p("Ag3A+IAxh6QACgEAEAAQAGAAABAEIAxB6QgIAGgEgIIgPgpIg5AAIgQApQgBAFgEAAQgCAAgEgDgAAZALIgZhAIgYBAIAxAAg");
	this.shape_16.setTransform(8,31.5);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#193670").s().p("AgPAtQgJgDgHgHQgGgHgDgJQgEgJAAgKQAAgJAEgJQADgJAHgHQAGgGAIgEQAJgEAIAAQAKAAAIADQAIAEAGAGQAGAGADAJQADAIAAAKIAAABQAAACgEAAIhLAAQAAAIADAIQADAHAFAFQAFAGAHACQAHADAHAAQAHAAAGgBQAFgCAEgDQAHgEAEgJIADABQADACAAADQAAAEgGAGQgFAFgIADQgJAEgLAAQgJAAgJgEgAAjgFQgBgIgCgGQgDgGgEgFQgEgFgGgCQgGgCgIAAQgFAAgGACQgHADgFAEQgEAFgEAGQgDAGgBAIIBFAAIAAAAg");
	this.shape_17.setTransform(220.1,13.3);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#193670").s().p("AgTAwQgEAAAAgEIAAhYIADgCQABAAABABQAAAAABAAQAAAAABAAQAAABABAAQABADAAAFIAAAMIAEgKQADgFADgCQADgDADgCQAEgBAEAAQAGAAAEACQAEACAAAEIgBAEIgCABQgEgEgHAAQgHAAgDADQgEADgDAGQgDAFgCAIQgBAIAAAIIAAApQAAAEgFAAg");
	this.shape_18.setTransform(212.1,13.2);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#193670").s().p("AgTAvQgGgCgFgDQgEgEgCgFQgCgEAAgGQAAgIAEgGQAEgGAIgDQAIgCANgCIAdgCIACAAIAAgFQAAgHgCgFQgCgFgEgEQgDgDgGgCQgFgCgHAAQgEAAgFABIgJAEQgIAFgEAIQgGgBAAgFQAAgEAGgFQAFgFAHgDQAJgEAKAAQAIAAAHADQAIACAEAFQAFAFADAGQACAHAAAJIAAA5IgDABQgBAAAAAAQgBAAAAAAQgBgBAAAAQgBAAAAgBQgCgCAAgFIAAgKIgGAIQgEAEgFADQgEADgGABQgFACgGAAQgHAAgGgCgAABABQgJACgHACQgHADgDAEQgEAFAAAGQAAAEACADQACAEADACIAHAEIAKABQAGAAAHgDQAGgCAFgEQAFgFADgGQADgGAAgGIAAgJIgDAAIgaABg");
	this.shape_19.setTransform(203,13.3);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#193670").s().p("AgOAtQgJgEgGgGQgHgHgDgJQgEgJABgKQgBgJAEgJQADgJAHgHQAGgHAJgDQAJgEAIAAQAMAAAIAEQAIADAGAFQAGAIABAGQgBADgDABIgCABIgFgJIgHgHQgEgDgFgCQgGgBgIAAQgFAAgIADQgHADgFAFQgGAGgCAHQgDAIAAAHQAAAIADAIQADAHAFAGQAFAFAHADQAHADAGAAQAIAAAGgBQAFgCAEgDQAGgEAGgMQAFABABAEQgDAIgFAGQgFAFgIADQgIAEgMAAQgIAAgJgEg");
	this.shape_20.setTransform(193.2,13.3);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#193670").s().p("AAABDQgDAAAAgFIAAhVQAAgEADAAIAAAAQAFAAgBAEIAABVQABAFgFAAgAgFg7QAAgHAFABQAGgBAAAHQAAAHgGAAQgFAAAAgHg");
	this.shape_21.setTransform(186.1,11.4);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#193670").s().p("AgRBBQgIgEgHgGQgGgHgDgJQgDgJAAgLQAAgLADgIQADgIAGgHQAHgGAIgEQAJgDAIAAQAGAAAFABQAHACAFADIAHAGIAGAIIAAg6IADgBQABAAAAAAQABAAABAAQAAAAABABQAAAAABAAQABADAAAFIAAB4QAAAFgEAAIgBAAQgEAAAAgFIAAgPIgHAJQgDAEgFACQgFADgFACQgGABgFAAQgJAAgIgDgAgNgRQgHADgFAFQgFAGgDAFQgCAIAAAJQAAAIACAIQADAIAFAFQAFAGAHADQAGADAHAAQAHAAAHgDQAGgCAFgFQAFgFADgGQADgGAAgHIAAgWIgGgJQgDgFgEgDQgFgDgGgCQgGgCgGAAQgHAAgGADg");
	this.shape_22.setTransform(178.2,11.3);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#193670").s().p("AgPAtQgJgDgHgHQgGgHgDgJQgEgJAAgKQAAgJAEgJQADgJAHgHQAGgGAIgEQAJgEAIAAQAKAAAIADQAIAEAGAGQAGAGADAJQADAIAAAKIAAABQAAACgEAAIhLAAQAAAIADAIQADAHAFAFQAFAGAHACQAHADAHAAQAHAAAGgBQAFgCAEgDQAHgEAEgJIADABQADACAAADQAAAEgGAGQgFAFgIADQgJAEgLAAQgJAAgJgEgAAjgFQgBgIgCgGQgDgGgEgFQgEgFgGgCQgGgCgIAAQgFAAgGACQgHADgFAEQgEAFgEAGQgDAGgBAIIBFAAIAAAAg");
	this.shape_23.setTransform(167.7,13.3);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#193670").s().p("AA0BBQgEAAgBgFIAAhwIgnBLQgDAGgFAAQgEAAgDgGIgohLIAABwQAAAFgEAAIgBAAQgEAAAAgFIAAh1QAAgHAHAAIACAAQADAAACACIAEAGIAmBMIAnhMQACgFACgBQABgCAEAAIACAAQAHAAAAAHIAAB1QAAAFgEAAg");
	this.shape_24.setTransform(155.1,11.5);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#193670").s().p("AgTAwQgEAAAAgEIAAhYIADgCQABAAABABQAAAAABAAQAAAAABAAQAAABABAAQABADAAAFIAAAMIAEgKQADgFADgCQADgDADgCQAEgBAEAAQAGAAAEACQAEACAAAEIgBAEIgCABQgEgEgHAAQgHAAgDADQgEADgDAGQgDAFgCAIQgBAIAAAIIAAApQAAAEgFAAg");
	this.shape_25.setTransform(141.5,13.2);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#193670").s().p("AgSAtQgHgDgFgGQgEgFgDgIQgCgIAAgJIAAgxQAAgEAEAAIABAAQAEAAAAAEIAAAwQAAAIACAGQACAGAEAFQADAFAGABQAFADAHAAIAJgBQAFgCAFgDIAHgHIAGgJIAAg8QAAgEAEAAIABAAQAEAAAAAEIAABYIgDACQgBAAAAgBQgBAAgBAAQAAAAAAgBQgBAAAAgBQgCgCAAgFIAAgIIgGAHQgDAEgFACIgJAFIgJABQgKAAgHgDg");
	this.shape_26.setTransform(132.2,13.4);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#193670").s().p("AgSAtQgJgEgGgGQgHgHgDgJQgEgJAAgKQAAgJAEgJQADgJAHgHQAGgHAJgDQAJgEAJAAQAKAAAJAEQAJAEAGAGQAHAHADAJQAEAJAAAJQAAAKgEAJQgDAJgHAHQgGAGgJAEQgJAEgKAAQgJAAgJgEgAgOgkQgHADgFAFQgFAGgDAHQgDAIAAAHQAAAIADAIQADAHAFAGQAFAFAHADQAHADAHAAQAIAAAHgDQAHgDAFgFQAFgGADgHQADgIAAgIQAAgHgDgHQgDgIgFgGQgFgFgHgDQgHgDgIAAQgHAAgHADg");
	this.shape_27.setTransform(121.3,13.3);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#193670").s().p("AgOBBIgCgBIAQgpQgEAAgBgEIgkhSQAHgGAEAKIAgBMIAchMQAFgLAHAHIguB7QgCAGgFAAg");
	this.shape_28.setTransform(111.2,15.2);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#193670").s().p("AAAA6QgDgCgDgEQgEgEgBgFQgCgGABgHIAAg5IgMAAQgEAAgBgDIAAgBQABgEAEAAIAMAAIAAgTQAAgEAEAAIABAAQAEAAAAAEIAAATIAaAAQAEAAAAAEIAAABQAAADgEAAIgaAAIAAA4QAAAMADAFQADAGAIgBQAFAAAEgCQADgCADgEIACABQAAAAABABQAAAAAAABQAAAAAAABQABAAAAABQgBADgDADQgCACgEACQgEACgFgBQgHAAgEgBg");
	this.shape_29.setTransform(99.9,12.2);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#193670").s().p("AgSAtQgHgDgFgGQgEgFgDgIQgCgIAAgJIAAgxQAAgEAEAAIABAAQAEAAAAAEIAAAwQAAAIACAGQACAGAEAFQADAFAGABQAFADAHAAIAJgBQAFgCAFgDIAHgHIAGgJIAAg8QAAgEAEAAIABAAQAEAAAAAEIAABYIgDACQgBAAAAgBQgBAAgBAAQAAAAAAgBQgBAAAAgBQgCgCAAgFIAAgIIgGAHQgDAEgFACIgJAFIgJABQgKAAgHgDg");
	this.shape_30.setTransform(91.1,13.4);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#193670").s().p("AgSAtQgJgEgGgGQgHgHgDgJQgEgJAAgKQAAgJAEgJQADgJAHgHQAGgHAJgDQAJgEAJAAQAKAAAJAEQAJAEAGAGQAHAHADAJQAEAJAAAJQAAAKgEAJQgDAJgHAHQgGAGgJAEQgJAEgKAAQgJAAgJgEgAgOgkQgHADgFAFQgFAGgDAHQgDAIAAAHQAAAIADAIQADAHAFAGQAFAFAHADQAHADAHAAQAIAAAHgDQAHgDAFgFQAFgGADgHQADgIAAgIQAAgHgDgHQgDgIgFgGQgFgFgHgDQgHgDgIAAQgHAAgHADg");
	this.shape_31.setTransform(80.2,13.3);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#193670").s().p("AgLBCQgHgBgEgDQgFgDgDgEQgDgEgCgEIAAAPQAAAFgFAAIgBAAQgDAAAAgFIAAiAIACgBQABAAABAAQABAAAAAAQABAAAAABQABAAAAAAQACADAAAFIAAAzIAHgJQAEgEAEgCQAEgDAGgCQAGgBAEAAQAKAAAIADQAIAEAHAGQAFAHAEAIQADAIAAALQAAALgDAJQgEAJgFAGQgHAHgIAEQgIADgKAAQgGAAgFgCgAgLgSQgGACgFADIgHAIQgEAFgCAEIAAAWQAAAHACAGQADAGAFAFQAFAFAGACQAIADAGAAQAHAAAHgDQAHgDAFgGQAEgFADgIQACgHABgJQgBgJgCgIQgDgFgEgFQgFgGgHgDQgHgDgHAAQgFAAgGACg");
	this.shape_32.setTransform(69.3,11.3);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#193670").s().p("AgTAvQgGgCgFgDQgEgEgCgFQgCgEAAgGQAAgIAEgGQAEgGAIgDQAIgCANgCIAdgCIACAAIAAgFQAAgHgCgFQgCgFgEgEQgDgDgGgCQgFgCgHAAQgEAAgFABIgJAEQgIAFgEAIQgGgBAAgFQAAgEAGgFQAFgFAHgDQAJgEAKAAQAIAAAHADQAIACAEAFQAFAFADAGQACAHAAAJIAAA5IgDABQAAAAgBAAQgBAAAAAAQgBgBAAAAQgBAAAAgBQgCgCAAgFIAAgKIgGAIQgEAEgFADQgEADgGABQgFACgGAAQgHAAgGgCgAABABQgJACgHACQgHADgDAEQgEAFAAAGQAAAEACADQACAEADACIAHAEIAKABQAGAAAHgDQAGgCAFgEQAFgFADgGQADgGAAgGIAAgJIgDAAIgaABg");
	this.shape_33.setTransform(58,13.3);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#193670").s().p("AAjAwQgFAAAAgEIAAgxQAAgHgCgHQgBgGgEgEQgEgFgFgCQgFgCgHAAQgEAAgFABQgFACgEADQgFADgDAEQgDAEgDAFIAAA8QABAEgFAAIgBAAQgEAAAAgEIAAhYIADgCQABAAAAABQABAAABAAQAAAAABAAQAAABAAAAQACADAAAFIAAAIIAGgHIAIgGIAJgFIAJgBQAJAAAHADQAIADAEAGQAFAFADAIQACAIAAAJIAAAxQAAAEgEAAg");
	this.shape_34.setTransform(44.5,13.2);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#193670").s().p("AgTAwQgEAAAAgEIAAhYIADgCQABAAABABQAAAAABAAQAAAAABAAQAAABABAAQABADAAAFIAAAMIAEgKQADgFADgCQADgDADgCQAEgBAEAAQAGAAAEACQAEACAAAEIgBAEIgCABQgEgEgHAAQgHAAgDADQgEADgDAGQgDAFgCAIQgBAIAAAIIAAApQAAAEgFAAg");
	this.shape_35.setTransform(36.3,13.2);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#193670").s().p("AgTAvQgGgCgFgDQgEgEgCgFQgCgEAAgGQAAgIAEgGQAEgGAIgDQAIgCANgCIAdgCIACAAIAAgFQAAgHgCgFQgCgFgEgEQgDgDgGgCQgFgCgHAAQgEAAgFABIgJAEQgIAFgEAIQgGgBAAgFQAAgEAGgFQAFgFAHgDQAJgEAKAAQAIAAAHADQAIACAEAFQAFAFADAGQACAHAAAJIAAA5IgDABQAAAAgBAAQgBAAAAAAQgBgBAAAAQgBAAAAgBQgCgCAAgFIAAgKIgGAIQgEAEgFADQgEADgGABQgFACgGAAQgHAAgGgCgAABABQgJACgHACQgHADgDAEQgEAFAAAGQAAAEACADQACAEADACIAHAEIAKABQAGAAAHgDQAGgCAFgEQAFgFADgGQADgGAAgGIAAgJIgDAAIgaABg");
	this.shape_36.setTransform(27.2,13.3);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#193670").s().p("AgPAtQgJgDgHgHQgGgHgDgJQgEgJAAgKQAAgJAEgJQADgJAHgHQAGgGAIgEQAJgEAIAAQAKAAAIADQAIAEAGAGQAGAGADAJQADAIAAAKIAAABQAAACgEAAIhLAAQAAAIADAIQADAHAFAFQAFAGAHACQAHADAHAAQAHAAAGgBQAFgCAEgDQAHgEAEgJIADABQADACAAADQAAAEgGAGQgFAFgIADQgJAEgLAAQgJAAgJgEgAAjgFQgBgIgCgGQgDgGgEgFQgEgFgGgCQgGgCgIAAQgFAAgGACQgHADgFAEQgEAFgEAGQgDAGgBAIIBFAAIAAAAg");
	this.shape_37.setTransform(17.3,13.3);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#193670").s().p("AggBBQgFAAgBgHIAAh1QABgFADABIACAAQAEgBAAAFIAABzIA9AAQAFAAABADIAAACQgBAEgFAAg");
	this.shape_38.setTransform(7.5,11.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,315,44);


(lib.CTA_btn = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#00FFFF").s().p("A6PV3MAAAgruMA0eAAAMAAAArug");
	this.shape.setTransform(168,140);
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(3).to({_off:false},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = null;


(lib.border336x280 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,0,3).p("AzczcMAm5AAAMAAAAm5Mgm5AAAg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-125.5,-125.5,251,251);


(lib.blocks = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#557C6B").s().p("AiWCSIAAkjIEtAAIAAEjg");
	this.shape.setTransform(-15.2,45);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#92AF2B").s().p("AiWCXIAAktIEtAAIAAEtg");
	this.shape_1.setTransform(-15.2,15.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#005A8C").s().p("AiWCXIAAktIEtAAIAAEtg");
	this.shape_2.setTransform(-15.2,74.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-30.3,0,30.4,90);


// stage content:
(lib.TEC201609_Hikers_250x250_AdR = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.clickthru_btn.on("click", function(evt){
		  window.open(clickTag, "_blank");
		});
	}
	this.frame_125 = function() {
		this.stop();
		 
		this.replay_btn.addEventListener("click", fl_ClickToGoToAndPlayFromFrame.bind(this));
		function fl_ClickToGoToAndPlayFromFrame() 
		{
		this.gotoAndPlay(1);
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(125).call(this.frame_125).wait(1));

	// replay btn
	this.replay_btn = new lib.replaybtn();
	this.replay_btn.setTransform(7,155,0.75,0.75);
	this.replay_btn._off = true;
	new cjs.ButtonHelper(this.replay_btn, 0, 1, 2, false, new lib.replaybtn(), 3);

	this.timeline.addTween(cjs.Tween.get(this.replay_btn).wait(125).to({_off:false},0).wait(1));

	// cta btn
	this.clickthru_btn = new lib.CTA_btn();
	this.clickthru_btn.setTransform(0,-0.1,0.744,0.893,0,0,0,-0.1,-0.1);
	new cjs.ButtonHelper(this.clickthru_btn, 0, 1, 2, false, new lib.CTA_btn(), 3);

	this.timeline.addTween(cjs.Tween.get(this.clickthru_btn).wait(126));

	// border
	this.instance = new lib.border336x280();
	this.instance.setTransform(125,125);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(126));

	// head1
	this.instance_1 = new lib.head1("synched",0);
	this.instance_1.setTransform(12,186);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(54).to({startPosition:0},0).to({y:130},5).wait(59).to({startPosition:0},0).to({y:30},5).wait(3));

	// sub1
	this.instance_2 = new lib.sub1("synched",0);
	this.instance_2.setTransform(657,1261.5,5,5,0,0,0,131.4,220.7);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(66).to({_off:false},0).to({scaleX:1,scaleY:1,x:143.4,y:409.7},5).wait(47).to({startPosition:0},0).to({y:317.7},5).wait(3));

	// blocks
	this.instance_3 = new lib.blocks();
	this.instance_3.setTransform(373.8,260.5,0.83,0.83,0,0,0,150,12.6);

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(118).to({y:184.8},5).wait(3));

	// logo
	this.instance_4 = new lib.TEC_logorev("synched",0);
	this.instance_4.setTransform(205.4,303.9,0.512,0.512,0,0,0,181.3,32.2);

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(118).to({startPosition:0},0).to({y:228.2},5).wait(3));

	// logo block
	this.instance_5 = new lib.logoblock();
	this.instance_5.setTransform(263.9,291.5,0.83,0.83,0,0,0,150,50);

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(118).to({y:215.8},5).wait(3));

	// pic
	this.instance_6 = new lib.pic();
	this.instance_6.setTransform(0,0,0.85,0.85);

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(54).to({regX:0.2,regY:0.2,scaleX:0.58,scaleY:0.58,x:1.1,y:-6.9},5).wait(59).to({y:-117.9},5).to({_off:true},1).wait(2));

	// bkgd
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AzhTiMAAAgnDMAnDAAAMAAAAnDg");
	this.shape.setTransform(125,125);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(126));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(76,125,486.9,324.7);

})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{});
var lib, images, createjs, ss;