(function (lib, img, cjs, ss) {

var p; // shortcut to reference prototypes
lib.webFontTxtFilters = {}; 

// library properties:
lib.properties = {
	width: 468,
	height: 60,
	fps: 18,
	color: "#CCCCCC",
	opacity: 1.00,
	webfonts: {},
	manifest: [
		{src:"images/_336x280gardener.jpg", id:"_336x280gardener"}
	]
};



lib.ssMetadata = [];


lib.webfontAvailable = function(family) { 
	lib.properties.webfonts[family] = true;
	var txtFilters = lib.webFontTxtFilters && lib.webFontTxtFilters[family] || [];
	for(var f = 0; f < txtFilters.length; ++f) {
		txtFilters[f].updateCache();
	}
};
// symbols:



(lib._336x280gardener = function() {
	this.initialize(img._336x280gardener);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,515,200);


(lib.TEC_logorev = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// TEC_logo-rev.ai
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AhBBcIAAjjIAJgDIAYgKQAUgKAKgIIADADIAABbIAvgCIABAbIgwgBIAACaQAAAJAGAGQAIAIAOgDQAQgDAPgPIAGACIAAABIgFAXIAAAAQAAADgMAKQgOAMgOAEQgMAEgKAAQhAAAAAhLg");
	this.shape.setTransform(42.1,-10.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("Ag+BcIAAiMIguAAIAAgaIAuACIAAg/IAJgDIAXgKQAVgKAJgIIAEADIAABbIBpAAIgBAYIhoAAIAACaQAAAJAGAGQAIAIANgDQARgDAPgPIAGACIAAABIgFAXIAAAAQgBADgLAKQgOAMgOAEQgMAEgMAAQg+AAAAhLg");
	this.shape_1.setTransform(25.5,-10.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AhUB5IAAjsIBHAAIgBAuIABABQAIgUASgQQAWgQAWAAQANAAAPAEIgBABQgVAVgLAgIgCADIgDgBQgHgCgHAAQgWAAgMAPQgMAOAAAUIAACGg");
	this.shape_2.setTransform(-14.8,-6.5);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgnBzQgZgKgPgTQgOgRgHgXQgGgVAAgYQgBgZAKgYQAKgZAQgPQAQgRAZgKQAagJAaAAQAdAAATAGQAVAHARAKQgIALgEANIgEALIgHAAQgJgPgOgIQgQgKgSAAIgBAAQgcAAgPAbQgPAbAAAvQAAAsATAZQARAYAkAAQAPAAAPgHQAOgIAHgIIAGAEIgGAPIgFAPQgKAIgRAGQgSAFgWABQgiAAgZgLg");
	this.shape_3.setTransform(166.8,-6.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AggB2QgXgHgPgOQgQgPgKgZQgKgYAAggQAAgeAJgYQAIgXAQgRQAOgPAWgIQAUgJAYABQAxAAAZAcQAaAcAAA1IAAAPIiMAAQAAATAEASQAEAQAIAPQAIANALAHQANAHARAAQAhAAAkgdIAGACIAAABIgEAXQgQASgdAKQgSAFgcABQgVAAgXgIgAApgVQgBglgIgVQgIgXgTAAQgJAAgIAHQgHAIgEALQgEALgDAPIgDAdIBKAAIAAAAg");
	this.shape_4.setTransform(3,-6.3);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AggB2QgXgHgPgOQgSgQgIgYQgKgYAAggQAAgeAJgYQAHgXAQgRQAPgPAVgIQAVgJAXABQAyAAAaAcQAaAdAAA0IAAAPIiNAAQAAATAEASQADAQAJAPQAIANALAHQANAHAQAAQAiAAAkgdIAGACIAAABIgEAXQgQASgdAKQgSAFgcABQgVAAgXgIgAAogVQAAglgJgVQgHgXgUAAQgJAAgHAHQgHAIgEALQgEALgDAPIgDAdIBJAAIAAAAg");
	this.shape_5.setTransform(-37.3,-6.3);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AggB2QgXgHgQgOQgQgPgKgZQgJgYgBggQABgeAIgYQAJgXAPgRQAOgPAWgIQAVgJAXABQAyAAAZAcQAaAdAAA0IAAAPIiMAAQAAATAEASQAFASAHANQAIANALAHQANAHARAAQAgAAAlgdIAGACIAAABIgEAXQgQASgdAKQgSAFgcABQgWAAgWgIgAApgVQgBglgIgVQgJgXgSAAQgJAAgIAHQgHAIgEALQgEALgDAPIgDAdIBKAAIAAAAg");
	this.shape_6.setTransform(-118.1,-6.3);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgPB2IgOAAIhEi8IgSgvIAUABIA4gBIA1CrIACAAIAehVIAdhWIAUACIAVgCIgTAsIgYA4IgaBAQgQAsgJAbg");
	this.shape_7.setTransform(-58.8,-6.3);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AheC7IAAl1IBXADIBAgBIAmgCQgCALAAAKIACAXIgggCIgggCIgdgCIgUgBIAABmIBWgEIAPApQg8gDgpAAIAACkIA5gBQAfgCAZgDIgBAWIAAAMIABAIg");
	this.shape_8.setTransform(-81.2,-13.1);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AggB3IAAjtIAPACIARABQAOAAATgDIAADtg");
	this.shape_9.setTransform(149,-6.3);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AggB3IAAjtIAOACIASABQANAAAUgDIAADtg");
	this.shape_10.setTransform(111.6,-6.3);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AASC6IgxABIAAl1IAOACIARABIASgBIAOgCIAAF1g");
	this.shape_11.setTransform(100,-13.1);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgaA2IAAhpIAPAAIAAAWQALgZAZABIABAAIAAAPIgBAAQgPgBgKAKQgLALAAARIAAA3g");
	this.shape_12.setTransform(36.7,22.9);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AAZA1IgZhVIgYBVIgPAAIgjhpIAQAAIAaBWIAZhWIAOAAIAaBWIAahWIAQAAIgjBpg");
	this.shape_13.setTransform(91.8,23);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgCBAQgFgGAAgNIAAhGIgTAAIAAgMIATAAIAAggIAMAAIAAAgIAWAAIAAAMIgWAAIAABEQAAAHACADQACADAGAAIAMAAIAAANIgNABQgNgBgDgFg");
	this.shape_14.setTransform(49.7,21.5);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AAdBJIAAhCQAAgdgaAAQgMAAgJAJQgJAKAAAOIAAA+IgPAAIAAiRIAPAAIAAA4QAEgIAJgGQAJgFAJAAQAUAAAKAKQAJAKAAAUIAABEg");
	this.shape_15.setTransform(60,20.9);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgpCzQgjgOgXgXQgXgXgNgjQgNgiAAglQABg1AQgoQAPgnAcgZQAbgZAkgLQAggLAoAAQAPAAANACIAbAFQARAFAJAEQALAEAJAGIgHAbQgCANgCAPIgHAAQgRgZgWgMQgSgLgcAAQgVAAgTAJQgSAKgRAVQgPASgLAgQgKAgAAApQAAApAKAeQALAeAQASQARATATAJQAWAIAUAAQANAAAMgDQANgEALgEQALgFALgIQALgHAIgKIAGAFIgGAWQgDAOgBAKQgpAWg8AAQgqAAghgNg");
	this.shape_16.setTransform(76.7,-12.9);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AghApQgNgPAAgaQAAgVALgPQANgTAWAAQAVAAALANQAPAPAAAbIAAAEIhPAAQABAQAIALQAJANAOAAQAaAAAGgbIABAAIAOAAIAAABQgJAmgmAAQgUAAgNgPgAAhgHQgCgOgHgLQgJgLgPABQgMgBgKALQgHALgDAOIBBAAIAAAAg");
	this.shape_17.setTransform(71.4,23);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AAcBJIAAhCQAAgdgaAAQgMAAgIAJQgJAKgBAOIAAA+IgOAAIAAiRIAOAAIAAA4QAKgTAWAAQAUAAAKAKQAJAKAAAUIAABEg");
	this.shape_18.setTransform(105.9,20.9);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AglAmQgMgQAAgWQAAgWAMgPQAOgSAXAAQAYAAAOASQAMAPAAAWQAAAWgMAQQgOASgYAAQgXAAgOgSgAgagdQgJANAAAQQAAARAJAMQAKAPAQAAQAQAAAKgPQAJgMAAgRQAAgQgJgNQgKgOgQABQgQgBgKAOg");
	this.shape_19.setTransform(117.2,23);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgIALIAAgVIARAAIAAAVg");
	this.shape_20.setTransform(180.5,27.1);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgqAOIAAhEIAPAAIAABEQAAAcAbAAQANAAAIgNQAHgMAAgQIAAg3IAPAAIAABpIgOAAIAAgRQgLAUgWABQgmAAAAgpg");
	this.shape_21.setTransform(173.2,23.1);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgGBJIAAiRIANAAIAACRg");
	this.shape_22.setTransform(125.3,20.9);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AghApQgNgPgBgaQAAgVALgPQANgTAXAAQAUAAAMANQAQAPAAAbIAAAEIhPAAQAAAQAIALQAJANAOAAQAZAAAHgbIAAAAIAPAAIAAABQgJAmgmAAQgVAAgMgPgAAggHQAAgOgJgLQgJgLgOABQgMgBgJALQgJALgBAOIA/AAIAAAAg");
	this.shape_23.setTransform(133.1,23);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AgbBJIgIgCIgBAAIAAgNIAKABQAHAAAEgDQACgDAEgJIAFgMIgrhoIAQAAIAgBWIAghWIAPAAIgvB5QgEAOgFAFQgFAEgMABg");
	this.shape_24.setTransform(150.7,24.9);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AglAmQgMgQAAgWQAAgWAMgPQAOgSAXAAQAYAAAOASQAMAPAAAWQAAAWgMAQQgOASgYAAQgXAAgOgSgAgagdQgJANAAAQQAAARAJAMQAKAPAQAAQARAAAKgPQAIgMAAgRQAAgQgIgNQgKgOgRABQgQgBgKAOg");
	this.shape_25.setTransform(161.6,23);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("ABaB5IgjAAIgPABIAAiNIgCgaQgBgLgEgGQgLgPgUAAQgTAAgLATQgKAUAAAiIAAB+IgQgBIgzABIAAjtIAQACIAQABIATgBIAQgCIAAAlIABABQANgVARgLQASgMAXAAQAgAAAUAWQAUAVAAAvIAACZIgQgBg");
	this.shape_26.setTransform(130.5,-6.6);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("ABeC6IgnAAIgQABIAAiPIAAgaQgCgLgFgGQgKgNgTAAQgVAAgKARQgKAUAAAiIAACAIgQgBIg3ABIAAl1IAQACIATABIAUgBIAQgCIAACtIABABQANgVASgLQAQgMAXAAQAlAAAUAWQAUAVAAAtIAACbIgQgBg");
	this.shape_27.setTransform(-142.5,-13.1);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AgjC6IAAlNIhbAGIAAgsIBZADICkgDIAAAWIAAAWIhYgGIAAFNg");
	this.shape_28.setTransform(-168.7,-13.2);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AgtBJIAAiRIBbAAIAAAOIhMAAIAAAyIBEAAIAAAMIhEAAIAABFg");
	this.shape_29.setTransform(15.1,20.9);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("AglAmQgMgQAAgWQAAgWAMgPQAOgSAXAAQAYAAAOASQAMAPAAAWQAAAWgMAQQgOASgYAAQgXAAgOgSgAgagdQgIANAAAQQAAARAIAMQAKAPAQAAQARAAAKgPQAJgMAAgRQAAgQgJgNQgKgOgRABQgQgBgKAOg");
	this.shape_30.setTransform(26.1,23);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("AgYAbQgLgMAAgPQAAgOALgLQALgMANAAQAPAAAKAMQALALAAAOQAAAQgLALQgKALgPAAQgNAAgLgLg");
	this.shape_31.setTransform(149.1,-26.8);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FFFFFF").s().p("AgYAbQgLgMAAgPQAAgOALgLQAKgMAOAAQAPAAAKAMQALALAAAOQAAAPgLAMQgKALgPAAQgOAAgKgLg");
	this.shape_32.setTransform(111.5,-26.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-181.4,-32.2,362.9,64.4);


(lib.sub1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// type
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#6B8A21").s().p("AAAAEQgDAAAAgEIAAAAQAAgDADAAIAAAAQAEAAAAADIAAAAQAAAEgEAAg");
	this.shape.setTransform(550.6,-3.8);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#6B8A21").s().p("AAVAdQgBAAAAAAQgBgBAAAAQAAAAgBgBQAAgBAAAAIAAgcQAAgFgBgDQgBgEgCgDIgGgEQgDgBgEAAIgFABIgFACIgFAEIgDAGIAAAjQAAAAAAABQgBABAAAAQAAAAgBABQAAAAgBAAIAAAAQgBAAAAAAQgBgBAAAAQAAAAgBgBQAAgBAAAAIAAg0IACgBIADABIABAFIAAAFIADgFIAFgDIAFgDIAFgBQAGAAAEACQAEACADADQADAEABAEQACAFAAAGIAAAcQAAAAAAABQgBABAAAAQAAAAgBABQAAAAgBAAg");
	this.shape_1.setTransform(546.3,-6.3);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#6B8A21").s().p("AgLAbQgEgCgFgEQgDgEgCgFQgDgGAAgGQAAgFADgFQACgFADgFQAFgDAEgCQAGgDAFAAQAFAAAGADQAGACADADQAEAFACAFQACAGABAEQgBAGgCAGQgCAFgEAEQgDAEgGACQgGACgFAAQgFAAgGgCgAgIgVIgHAFQgDADgCAFQgCAEAAAEQAAAEACAGQACAEADADQADADAEACQAEACAEAAQAEAAAFgCQAEgCADgDQADgDACgEQABgFAAgFQAAgEgBgEIgFgIIgHgFQgEgCgFAAQgEAAgEACg");
	this.shape_2.setTransform(539.7,-6.2);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#6B8A21").s().p("AAAAoQAAAAAAAAQAAgBgBAAQAAAAAAgBQAAgBAAAAIAAgyQAAgBAAAAQAAgBAAAAQABAAAAgBQAAAAAAAAIAAAAQAAAAABAAQAAABABAAQAAAAAAABQAAAAAAABIAAAyQAAAAAAABQAAABAAAAQgBAAAAABQgBAAAAAAgAgCgjQAAgEACAAQADAAAAAEQAAAEgDAAQgCAAAAgEg");
	this.shape_3.setTransform(535.2,-7.4);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#6B8A21").s().p("AgLAbQgEgCgDgDQgDgCAAgCQAAgBAAAAQAAgBABAAQAAAAABgBQAAAAABAAQADAEAFACIAFACIAFABIAHgBIAFgCIADgDIABgFIgBgEIgDgEIgMgDQgJgCgEgBQgDgBgBgCQgCgEAAgEQAAgDABgDIAFgFIAGgEIAHgBQAGAAAFACQAEACADACQABABAAAAQAAABABAAQAAABAAAAQAAABAAAAQAAABAAAAQAAABAAAAQAAAAgBAAQAAABAAAAIgCABQgCgFgEgCQgFgCgGAAIgFABIgFACIgDAEIgBADIABAFQAAAAABABQAAAAABABQAAAAABAAQAAABABAAQADACAHACIAIABIAGABQAEACABACQACADAAAEIgBAIQgCACgDACQgDADgEABIgJABQgFAAgGgCg");
	this.shape_4.setTransform(531.4,-6.2);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#6B8A21").s().p("AgLAbQgEgCgDgDQgDgCAAgCQAAgBAAAAQAAgBABAAQAAAAABgBQAAAAABAAQADAEAFACIAFACIAFABIAHgBIAFgCIADgDIABgFIgBgEIgDgEIgMgDQgJgCgEgBQgDgBgBgCQgCgEAAgEQAAgDABgDIAFgFIAGgEIAHgBQAGAAAFACQAEACADACQABABAAAAQAAABABAAQAAABAAAAQAAABAAAAQAAABAAAAQAAABAAAAQAAAAgBAAQAAABAAAAIgCABQgCgFgEgCQgFgCgGAAIgFABIgFACIgDAEIgBADIABAFQAAAAABABQAAAAABABQAAAAABAAQAAABABAAQADACAHACIAIABIAGABQAEACABACQACADAAAEIgBAIQgCACgDACQgDADgEABIgJABQgFAAgGgCg");
	this.shape_5.setTransform(526.1,-6.2);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#6B8A21").s().p("AgJAbQgFgCgEgEQgEgEgCgFQgCgGAAgGQAAgEACgGQACgFAEgFQAEgDAFgCQAFgDAFAAQAFAAAFACQAFACADADQAEAEACAFQACAFAAAHIAAAAQAAAAAAAAQgBAAAAAAQAAAAgBAAQAAABgBAAIgsAAQAAAFACAEQABAFAEADIAHAEQAEACADAAIAIgBQADAAADgCQAEgEACgFIACABQABAAAAABQAAAAAAAAQABABAAAAQAAABAAAAQAAACgEAEQgDADgEACQgGACgHAAQgEAAgGgCgAAVgDIgCgIIgEgHQgDgCgEgCQgDgBgEAAQgDAAgEABQgDACgDADQgDACgCAEQgCAEgBAEIApAAIAAAAg");
	this.shape_6.setTransform(520.4,-6.2);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#6B8A21").s().p("AgLAbQgEgCgDgDQgDgCAAgCQAAgBAAAAQAAgBABAAQAAAAABgBQAAAAABAAQADAEAFACIAFACIAFABIAHgBIAFgCIADgDIABgFIgBgEIgDgEIgMgDQgJgCgEgBQgDgBgBgCQgCgEAAgEQAAgDABgDIAFgFIAGgEIAHgBQAGAAAFACQAEACADACQABABAAAAQABABAAAAQAAABAAAAQAAABAAAAQAAABAAAAQAAABAAAAQAAAAgBAAQAAABAAAAIgCABQgCgFgEgCQgFgCgGAAIgFABIgFACIgDAEIgBADIABAFQAAAAABABQAAAAABABQAAAAABAAQAAABABAAQADACAHACIAIABIAGABQAEACABACQACADAAAEIgBAIQgCACgDACQgDADgEABIgJABQgFAAgGgCg");
	this.shape_7.setTransform(514.5,-6.2);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#6B8A21").s().p("AgLAbQgEgCgFgEQgDgEgCgFQgCgGAAgGQAAgFACgFQACgFADgFQAFgDAEgCQAGgDAFAAQAFAAAGADQAGACADADQAEAFACAFQACAGAAAEQAAAGgCAGQgCAFgEAEQgDAEgGACQgGACgFAAQgFAAgGgCgAgIgVIgHAFQgEADgBAFQgCAEAAAEQAAAEACAGQABAEAEADQADADAEACQAFACADAAQAEAAAFgCQAEgCADgDQADgDACgEQABgFAAgFQAAgEgBgEIgFgIIgHgFQgFgCgEAAQgDAAgFACg");
	this.shape_8.setTransform(506.5,-6.2);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#6B8A21").s().p("AgDApQgBAAAAAAQgBAAAAgBQAAAAAAgBQgBAAAAgBIAAgvIgJAAQgBAAAAAAQgBAAAAgBQgBAAAAAAQAAgBAAgBIAAAAQAAgBAAAAQAAgBABAAQAAAAABAAQAAAAABAAIAJAAIAAgHIACgIIADgGIACgEIAHgBIAGABIADACIACADIgBACIgBABIgDgDIgGgBIgEABIgEACIAAAFIAAAHIAAAGIAKAAQABAAABAAQAAAAABAAQAAAAAAABQABAAAAABIAAAAQAAABgBABQAAAAAAAAQgBABAAAAQgBAAgBAAIgKAAIAAAvQAAABAAAAQAAABgBAAQAAABAAAAQgBAAAAAAg");
	this.shape_9.setTransform(501.5,-7.5);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#6B8A21").s().p("AAVAdQgBAAAAAAQgBgBAAAAQAAAAgBgBQAAgBAAAAIAAgcQAAgFgBgDQgBgEgCgDIgGgEQgDgBgEAAIgFABIgFACIgFAEIgDAGIAAAjQAAAAAAABQgBABAAAAQAAAAgBABQAAAAgBAAIAAAAQgBAAAAAAQgBgBAAAAQAAAAgBgBQAAgBAAAAIAAg0IACgBIADABIABAFIAAAFIADgFIAFgDIAFgDIAFgBQAGAAAEACQAEACADADQADAEABAEQACAFAAAGIAAAcQAAAAAAABQgBABAAAAQAAAAgBABQAAAAgBAAg");
	this.shape_10.setTransform(496.3,-6.3);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#6B8A21").s().p("AAAAoQAAAAAAAAQAAgBgBAAQAAAAAAgBQAAgBAAAAIAAgyQAAgBAAAAQAAgBAAAAQABAAAAgBQAAAAAAAAIAAAAQAAAAABAAQAAABABAAQAAAAAAABQAAAAAAABIAAAyQAAAAAAABQAAABAAAAQgBAAAAABQgBAAAAAAgAgCgjQAAgEACAAQADAAAAAEQAAAEgDAAQgCAAAAgEg");
	this.shape_11.setTransform(491.9,-7.4);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#6B8A21").s().p("AgJAbQgFgCgEgEQgEgEgCgFQgCgGAAgGQAAgEACgGQACgFAEgFQAEgDAFgCQAFgDAFAAQAFAAAFACQAFACADADQAEAEACAFQACAFAAAHIAAAAQAAAAAAAAQgBAAAAAAQAAAAgBAAQAAABgBAAIgsAAQAAAFACAEQABAFAEADIAHAEQAEACADAAIAIgBQADAAADgCQAEgEACgFIACABQABAAAAABQAAAAAAAAQABABAAAAQAAABAAAAQAAACgEAEQgDADgEACQgGACgHAAQgEAAgGgCgAAVgDIgCgIIgEgHQgDgCgEgCQgDgBgEAAQgDAAgEABQgDACgDADQgDACgCAEQgCAEgBAEIApAAIAAAAg");
	this.shape_12.setTransform(485.5,-6.2);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#6B8A21").s().p("AgJAbQgFgCgEgEQgEgEgCgFQgCgGAAgGQAAgEACgGQACgFAEgFQAEgDAFgCQAFgDAFAAQAFAAAFACQAFACADADQAEAEACAFQACAFAAAHIAAAAQAAAAAAAAQgBAAAAAAQAAAAgBAAQAAABgBAAIgsAAQAAAFACAEQABAFAEADIAHAEQAEACADAAIAIgBQADAAADgCQAEgEACgFIACABQABAAAAABQAAAAAAAAQABABAAAAQAAABAAAAQAAACgEAEQgDADgEACQgGACgHAAQgEAAgGgCgAAVgDIgCgIIgEgHQgDgCgEgCQgDgBgEAAQgDAAgEABQgDACgDADQgDACgCAEQgCAEgBAEIApAAIAAAAg");
	this.shape_13.setTransform(479.3,-6.2);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#6B8A21").s().p("AgKAdQgBAAgBAAQAAgBAAAAQgBAAAAgBQAAgBAAAAIAAg0IACgBIACABIABAFIAAAHIADgGIADgEQACgCAAgBIAGgBQAEAAACACQAAAAABAAQAAABAAAAQABABAAAAQAAABAAAAIAAACIgBABQgEgCgDAAQgEAAgCACQgCABgCAEIgDAIIgBAIIAAAZQAAAAAAABQAAABAAAAQAAAAgBABQAAAAgBAAg");
	this.shape_14.setTransform(474.5,-6.3);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#6B8A21").s().p("AgDApQgBAAAAAAQgBAAAAgBQAAAAAAgBQAAAAAAgBIAAgvIgKAAQgBAAAAAAQgBAAAAgBQgBAAAAAAQAAgBAAgBIAAAAQAAgBAAAAQAAgBABAAQAAAAABAAQAAAAABAAIAKAAIAAgHIABgIIACgGIAEgEIAGgBIAGABIADACIACADIgBACIgBABIgDgDIgGgBIgEABIgEACIAAAFIAAAHIAAAGIALAAQAAAAABAAQAAAAABAAQAAAAAAABQABAAAAABIAAAAQAAABgBABQAAAAAAAAQgBABAAAAQgBAAAAAAIgLAAIAAAvQAAABAAAAQAAABgBAAQAAABAAAAQgBAAAAAAg");
	this.shape_15.setTransform(470.6,-7.5);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#6B8A21").s().p("AgLAcIgHgDQgCgCgBgDQgBgDAAgEQAAgEACgEQADgDAEgCQAFgBAIgBQAFgBALAAIABAAIAAgDIgBgHQgBgDgCgDQgCgCgEgBIgHAAIgEAAIgGACQgEADgDAFQgBAAgBAAQAAAAgBgBQAAAAAAgBQAAAAAAgBQgBgDAEgDQADgDAEgBQAGgDAEAAQAGAAAEABQAEACADADQADADACAEQACAEAAAFIAAAiIgCABQgBAAAAgBQgBAAAAAAQAAAAgBAAQAAgBAAAAQAAAAgBgBQAAAAAAgBQAAAAAAgBQgBgBAAgBIAAgGQAAAEgDABIgFAEQgDADgDAAIgGABIgIgBgAAAABIgJACQgDACgDACQgCADAAADIABAFIADADIAEACIAHABIAHgBIAHgEIAEgGIABgIIAAgFIgBAAIgQABg");
	this.shape_16.setTransform(463.3,-6.2);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#6B8A21").s().p("AgLAdQAAAAgBAAQAAgBAAAAQgBAAAAgBQAAgBAAAAIAAg0IABgBIADABIABAFIAAAHIADgGIADgEQACgCABgBIAFgBQADAAADACQAAAAABAAQAAABAAAAQABABAAAAQAAABAAAAIAAACIgBABQgEgCgEAAQgDAAgCACQgCABgCAEIgCAIIgCAIIAAAZQAAAAAAABQAAABAAAAQAAAAgBABQAAAAgBAAg");
	this.shape_17.setTransform(456.7,-6.3);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#6B8A21").s().p("AgKAbQgFgCgEgEQgEgEgDgFQgCgGAAgGQAAgFACgFQADgFAEgFQADgDAGgCQAFgDAFAAQAGAAAFADQAFACAFADQADAFACAFQACAGAAAEQAAAGgCAGQgCAFgDAEQgFAEgFACQgFACgGAAQgFAAgFgCgAgIgVIgHAFQgEADgBAFQgCAEAAAEQAAAEACAGQABAEAEADQADADAEACQAFACADAAQAFAAADgCQAFgCADgDQADgDACgEQABgFABgFQgBgEgBgEIgFgIIgHgFQgFgCgEAAQgDAAgFACg");
	this.shape_18.setTransform(451.1,-6.2);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#6B8A21").s().p("AgDApQgBAAAAAAQgBAAAAgBQAAAAAAgBQAAAAAAgBIAAgvIgKAAQgBAAAAAAQgBAAAAgBQgBAAAAAAQAAgBAAgBIAAAAQAAgBAAAAQAAgBABAAQAAAAABAAQAAAAABAAIAKAAIAAgHIAAgIIADgGIAEgEIAGgBIAGABIAEACIABADIAAACIgBABIgFgDIgFgBIgFABIgCACIgBAFIAAAHIAAAGIALAAQAAAAABAAQAAAAABAAQAAAAAAABQAAAAAAABIAAAAQAAABAAABQAAAAAAAAQgBABAAAAQgBAAAAAAIgLAAIAAAvQAAABAAAAQAAABgBAAQAAABAAAAQgBAAgBAAg");
	this.shape_19.setTransform(446.1,-7.5);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#6B8A21").s().p("AgLAdQAAAAgBAAQAAgBAAAAQgBAAAAgBQAAgBAAAAIAAg0IABgBIAEABIABAFIAAAHIACgGIADgEQACgCABgBIAFgBQADAAADACQABAAAAAAQAAABABAAQAAABAAAAQAAABAAAAIgBACIgBABQgCgCgFAAQgDAAgCACQgCABgCAEIgCAIIgBAIIAAAZQAAAAgBABQAAABAAAAQAAAAgBABQAAAAgBAAg");
	this.shape_20.setTransform(440.4,-6.3);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#6B8A21").s().p("AgJAbQgFgCgEgEQgEgEgCgFQgCgGAAgGQAAgEACgGQACgFAEgFQAEgDAFgCQAFgDAFAAQAFAAAFACQAFACADADQAEAEACAFQACAFAAAHIAAAAQAAAAAAAAQgBAAAAAAQAAAAgBAAQAAABgBAAIgsAAQAAAFACAEQABAFAEADIAHAEQAEACADAAIAIgBQADAAADgCQAEgEACgFIACABQABAAAAABQAAAAAAAAQABABAAAAQAAABAAAAQAAACgEAEQgDADgEACQgGACgHAAQgEAAgGgCgAAVgDIgCgIIgEgHQgDgCgEgCQgDgBgEAAQgDAAgEABQgDACgDADQgDACgCAEQgCAEgBAEIApAAIAAAAg");
	this.shape_21.setTransform(435,-6.2);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#6B8A21").s().p("AAAAiIgDgDIgDgFIgBgIIAAghIgHAAQAAAAgBAAQAAgBgBAAQAAAAAAgBQgBAAAAgBIAAAAQAAgBABAAQAAgBAAAAQABAAAAgBQABAAAAAAIAHAAIAAgLQAAAAABgBQAAAAAAgBQAAAAABAAQAAAAABAAIABAAQAAAAABAAQAAAAAAAAQABABAAAAQAAABAAAAIAAALIAPAAQAAAAABAAQAAABAAAAQABAAAAABQAAAAAAABIAAAAQAAABAAAAQAAABgBAAQAAAAAAABQgBAAAAAAIgPAAIAAAgQAAAHABADQACAEAFAAQADAAACgCIAEgDIAAAAIABADIgBADIgEACIgGABIgGgBg");
	this.shape_22.setTransform(429.9,-6.9);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#6B8A21").s().p("AgLAbQgEgCgDgDQgDgCAAgCQAAgBAAAAQAAgBABAAQAAAAABgBQAAAAABAAQADAEAFACIAFACIAFABIAHgBIAFgCIADgDIABgFIgBgEIgDgEIgMgDQgJgCgEgBQgDgBgBgCQgCgEAAgEQAAgDABgDIAFgFIAGgEIAHgBQAGAAAFACQAEACADACQABABAAAAQAAABABAAQAAABAAAAQAAABAAAAQAAABAAAAQAAABAAAAQAAAAgBAAQAAABAAAAIgCABQgCgFgEgCQgFgCgGAAIgFABIgFACIgDAEIgBADIABAFQAAAAABABQAAAAABABQAAAAABAAQAAABABAAQADACAHACIAIABIAGABQAEACABACQACADAAAEIgBAIQgCACgDACQgDADgEABIgJABQgFAAgGgCg");
	this.shape_23.setTransform(425.2,-6.2);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#6B8A21").s().p("AAAAoQAAAAAAAAQAAgBgBAAQAAAAAAgBQAAgBAAAAIAAgyQAAgBAAAAQAAgBAAAAQABAAAAgBQAAAAAAAAIAAAAQAAAAABAAQAAABABAAQAAAAAAABQAAAAAAABIAAAyQAAAAAAABQAAABAAAAQgBAAAAABQgBAAAAAAgAgCgjQAAgEACAAQADAAAAAEQAAAEgDAAQgCAAAAgEg");
	this.shape_24.setTransform(421.4,-7.4);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#6B8A21").s().p("AgLArIgIgDIgGgFQgBgDAAgDQAAgEABgCIAFgFIAGgEIAHgCIgCgCQgBgBAAAAQAAgBgBAAQAAgBAAAAQAAgBAAAAQAAgEADgCIgGgBIgEgEIgDgFIgBgGQAAgFACgEQABgDADgDQADgDAFgCQAEgBAEAAIAHABIAGADIAFgHQADgDACABQABAAAAAAQABAAAAAAQAAABAAAAQABABAAAAIgKAKIAEAGIABAHQAAAEgCAEQgBAEgDADIgHACQgEABgEAAIgEAAQAAAAAAABQgBAAAAAAQAAABAAAAQgBABAAABQABADAEABIAJADIAHACIAGADIAFAEIABAGQAAAEgCADQgCAEgEACIgJADIgKABIgLgBgAgHARIgHACIgEAEQgCADAAADQAAAAAAABQAAAAAAABQAAABAAAAQABABAAAAIAEAEIAHACIAIAAIAIgBIAHgCIAEgDIACgFIgBgEIgDgDIgKgEIgHgCIgHACgAgGgfQgDABgCACIgEAFQgBADAAADQAAAEABADIAEAFIAFADIAGABIAGgBIAEgDIAEgFQABgDABgEQgBgDgBgDIgEgFQgCgCgCgBIgGgBIgGABg");
	this.shape_25.setTransform(417.6,-5.3);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#6B8A21").s().p("AgJAbQgFgCgEgEQgEgEgCgFQgCgGAAgGQAAgEACgGQACgFAEgFQAEgDAFgCQAFgDAFAAQAFAAAFACQAFACADADQAEAEACAFQACAFAAAHIAAAAQAAAAAAAAQgBAAAAAAQAAAAgBAAQAAABgBAAIgsAAQAAAFACAEQABAFAEADIAHAEQAEACADAAIAIgBQADAAADgCQAEgEACgFIACABQABAAAAABQAAAAAAAAQABABAAAAQAAABAAAAQAAACgEAEQgDADgEACQgGACgHAAQgEAAgGgCgAAVgDIgCgIIgEgHQgDgCgEgCQgDgBgEAAQgDAAgEABQgDACgDADQgDACgCAEQgCAEgBAEIApAAIAAAAg");
	this.shape_26.setTransform(411.8,-6.2);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#6B8A21").s().p("AgKAdQgBAAgBAAQAAgBAAAAQgBAAAAgBQAAgBAAAAIAAg0IACgBIACABIABAFIAAAHIADgGIADgEQACgCAAgBIAGgBQAEAAACACQAAAAABAAQAAABAAAAQABABAAAAQAAABAAAAIAAACIgBABQgEgCgDAAQgEAAgCACQgCABgCAEIgDAIIgBAIIAAAZQAAAAAAABQAAABAAAAQAAAAgBABQAAAAgBAAg");
	this.shape_27.setTransform(407,-6.3);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#6B8A21").s().p("AgLAdQAAAAgBAAQAAgBAAAAQgBAAAAgBQAAgBAAAAIAAg0IABgBIADABIACAFIAAAHIACgGIADgEQACgCABgBIAFgBQADAAADACQAAAAABAAQAAABABAAQAAABAAAAQAAABAAAAIgBACIgBABQgCgCgFAAQgDAAgCACQgCABgCAEIgCAIIgBAIIAAAZQAAAAgBABQAAABAAAAQAAAAgBABQAAAAgBAAg");
	this.shape_28.setTransform(401,-6.3);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#6B8A21").s().p("AgLAbQgEgCgFgEQgEgEgCgFQgCgGAAgGQAAgFACgFQACgFAEgFQAFgDAEgCQAGgDAFAAQAGAAAFADQAFACAFADQADAFACAFQADAGAAAEQAAAGgDAGQgCAFgDAEQgFAEgFACQgFACgGAAQgFAAgGgCgAgIgVIgHAFQgDADgCAFQgCAEAAAEQAAAEACAGQACAEADADQADADAEACQAEACAEAAQAFAAADgCQAFgCADgDQADgDACgEQABgFABgFQgBgEgBgEIgFgIIgHgFQgEgCgFAAQgEAAgEACg");
	this.shape_29.setTransform(395.4,-6.2);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#6B8A21").s().p("AgJAbQgFgCgEgEQgEgEgCgFQgCgGAAgGQAAgEACgGQACgFAEgFQAEgDAFgCQAFgDAFAAQAFAAAFACQAFACADADQAEAEACAFQACAFAAAHIAAAAQAAAAAAAAQgBAAAAAAQAAAAgBAAQAAABgBAAIgsAAQAAAFACAEQABAFAEADIAHAEQAEACADAAIAIgBQADAAADgCQAEgEACgFIACABQABAAAAABQAAAAAAAAQABABAAAAQAAABAAAAQAAACgEAEQgDADgEACQgGACgHAAQgEAAgGgCgAAVgDIgCgIIgEgHQgDgCgEgCQgDgBgEAAQgDAAgEABQgDACgDADQgDACgCAEQgCAEgBAEIApAAIAAAAg");
	this.shape_30.setTransform(386.9,-6.2);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#6B8A21").s().p("AgLAdQAAAAgBAAQAAgBAAAAQgBAAAAgBQAAgBAAAAIAAg0IABgBIADABIACAFIAAAHIACgGIADgEQACgCABgBIAFgBQADAAADACQAAAAABAAQAAABABAAQAAABAAAAQAAABAAAAIgBACIgBABQgCgCgFAAQgDAAgCACQgCABgCAEIgCAIIgBAIIAAAZQAAAAgBABQAAABAAAAQAAAAgBABQAAAAgBAAg");
	this.shape_31.setTransform(382.1,-6.3);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#6B8A21").s().p("AgLAbQgEgCgFgEQgEgEgCgFQgCgGAAgGQAAgFACgFQACgFAEgFQAFgDAEgCQAGgDAFAAQAGAAAFADQAGACAEADQADAFACAFQADAGAAAEQAAAGgDAGQgCAFgDAEQgEAEgGACQgFACgGAAQgFAAgGgCgAgIgVIgHAFQgDADgCAFQgCAEAAAEQAAAEACAGQACAEADADQADADAEACQAEACAEAAQAFAAADgCQAFgCADgDQADgDACgEQABgFABgFQgBgEgBgEIgFgIIgHgFQgEgCgFAAQgEAAgEACg");
	this.shape_32.setTransform(376.5,-6.2);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#6B8A21").s().p("AAnAdQAAAAgBAAQAAgBgBAAQAAAAAAgBQAAgBAAAAIAAgdIgBgIIgDgGIgFgEIgIgBIgFABIgFACIgFAEIgDAGIAAAjQAAAAAAABQAAABAAAAQgBAAAAABQgBAAAAAAIAAAAQAAAAAAAAQgBgBAAAAQAAAAgBgBQAAgBAAAAIAAgeIgBgIIgDgGIgFgDIgHgBIgGABIgFACIgEAEIgDAGIAAAjQAAAAAAABQgBABAAAAQAAAAgBABQAAAAgBAAIAAAAQgBAAAAAAQgBgBAAAAQAAAAgBgBQAAgBAAAAIAAg0IACgBIADABIABAFIAAAFIADgFIAEgEIAGgCIAGgBIAHABIAFADIAEAEIABAGQABgDADgDIAEgEIAGgDIAHgBQAFAAAEACQAEACADADQADADABAEQACAFAAAGIAAAdQAAAAAAABQgBABAAAAQAAAAgBABQAAAAgBAAg");
	this.shape_33.setTransform(368.1,-6.3);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#6B8A21").s().p("AAVAdQgBAAAAAAQgBgBAAAAQAAAAgBgBQAAgBAAAAIAAgcQAAgFgBgDQgBgEgCgDIgGgEQgDgBgEAAIgFABIgFACIgFAEIgDAGIAAAjQAAAAAAABQgBABAAAAQAAAAgBABQAAAAgBAAIAAAAQgBAAAAAAQgBgBAAAAQAAAAgBgBQAAgBAAAAIAAg0IACgBIADABIABAFIAAAFIADgFIAFgDIAFgDIAFgBQAGAAAEACQAEACADADQADAEABAEQACAFAAAGIAAAcQAAAAAAABQgBABAAAAQAAAAgBABQAAAAgBAAg");
	this.shape_34.setTransform(357.6,-6.3);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#6B8A21").s().p("AgLAdQAAAAgBAAQAAgBAAAAQgBAAAAgBQAAgBAAAAIAAg0IABgBIADABIABAFIAAAHIADgGIADgEQACgCABgBIAFgBQADAAADACQAAAAABAAQAAABAAAAQABABAAAAQAAABAAAAIgBACIAAABQgEgCgEAAQgDAAgCACQgCABgCAEIgCAIIgCAIIAAAZQAAAAAAABQAAABAAAAQAAAAgBABQAAAAgBAAg");
	this.shape_35.setTransform(352.8,-6.3);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#6B8A21").s().p("AgLAcIgGgDQgDgCgBgDQgBgDgBgEQABgEACgEQACgDAFgCQAFgBAIgBQAGgBALAAIABAAIAAgDIgBgHQgBgDgDgDQgCgCgDgBIgIAAIgFAAIgFACQgEADgDAFQgBAAgBAAQAAAAgBgBQAAAAAAgBQgBAAAAgBQAAgDAEgDQADgDAFgBQAFgDAEAAQAGAAAEABQAFACADADQACADABAEQACAEABAFIAAAiIgDABQAAAAAAgBQgBAAAAAAQAAAAgBAAQAAgBAAAAQAAAAgBgBQAAAAAAgBQAAAAAAgBQAAgBAAgBIAAgGQgCAEgCABIgFAEQgDADgEAAIgFABIgIgBgAAAABIgIACQgFACgCACQgBADAAADIABAFIACADIAFACIAFABIAHgBIAHgEIAFgGIACgIIAAgFIgCAAIgQABg");
	this.shape_36.setTransform(347.3,-6.2);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#6B8A21").s().p("AgJAbQgFgCgEgEQgEgEgCgFQgCgGAAgGQAAgEACgGQACgFAEgFQAEgDAFgCQAFgDAFAAQAFAAAFACQAFACADADQAEAEACAFQACAFAAAHIAAAAQAAAAAAAAQgBAAAAAAQAAAAgBAAQAAABgBAAIgsAAQAAAFACAEQABAFAEADIAHAEQAEACADAAIAIgBQADAAADgCQAEgEACgFIACABQABAAAAABQAAAAAAAAQABABAAAAQAAABAAAAQAAACgEAEQgDADgEACQgGACgHAAQgEAAgGgCgAAVgDIgCgIIgEgHQgDgCgEgCQgDgBgEAAQgDAAgEABQgDACgDADQgDACgCAEQgCAEgBAEIApAAIAAAAg");
	this.shape_37.setTransform(341.4,-6.2);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#6B8A21").s().p("AAAApQAAAAAAgBQAAAAgBAAQAAgBAAAAQAAgBAAgBIAAhLIABgBIABABIABAEIAABHQAAABAAABQAAAAAAABQgBAAAAAAQgBABAAAAg");
	this.shape_38.setTransform(337.1,-7.4);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#6B8A21").s().p("AgKAbQgFgCgEgEQgEgEgDgFQgCgGABgGQgBgFACgFQADgFAEgFQAEgDAFgCQAFgDAFAAQAGAAAFADQAFACAFADQADAFACAFQACAGAAAEQAAAGgCAGQgCAFgDAEQgFAEgFACQgFACgGAAQgFAAgFgCgAgIgVIgHAFQgEADgBAFQgCAEAAAEQAAAEACAGQABAEAEADQADADAEACQAFACADAAQAFAAADgCQAFgCADgDQADgDACgEQABgFABgFQgBgEgBgEIgFgIIgHgFQgFgCgEAAQgDAAgFACg");
	this.shape_39.setTransform(330.5,-6.2);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#6B8A21").s().p("AAAAiIgDgDIgDgFIgBgIIAAghIgGAAQgBAAgBAAQAAgBgBAAQAAAAAAgBQgBAAAAgBIAAAAQAAgBABAAQAAgBAAAAQABAAAAgBQABAAABAAIAGAAIAAgLQAAAAABgBQAAAAAAgBQAAAAABAAQAAAAABAAIABAAQAAAAABAAQAAAAAAAAQABABAAAAQAAABAAAAIAAALIAPAAQAAAAABAAQAAABAAAAQABAAAAABQAAAAAAABIAAAAQAAABAAAAQAAABgBAAQAAAAAAABQgBAAAAAAIgPAAIAAAgQAAAHABADQACAEAEAAQADAAADgCIADgDIABAAIABADIgCADIgDACIgGABIgGgBg");
	this.shape_40.setTransform(325.2,-6.9);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#6B8A21").s().p("AgWAmQgBAAgBAAQAAAAgBgBQAAAAAAgBQgBAAAAgBIAAhFQAAgBABAAQAAgBAAAAQABgBAAAAQABAAABAAIAtAAQAAAAABAAQAAAAABAAQAAABAAAAQAAABAAAAIAAABQAAAAAAABQAAAAAAABQgBAAAAAAQgBAAAAAAIgrAAIAAAeIAhAAQAAAAABAAQAAAAABAAQAAABAAAAQAAABAAAAIAAAAQAAAAAAAAQAAAAAAABQgBAAAAAAQgBAAAAAAIghAAIAAAgIArAAQABAAABAAQAAAAABAAQAAABAAAAQAAABAAAAIAAABQAAAAAAABQAAAAAAABQgBAAAAAAQgBAAgBAAg");
	this.shape_41.setTransform(318,-7.3);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#6B8A21").s().p("AASAkIgbgfIgKAAIAAAeQAAABAAABQAAAAAAABQgBAAAAAAQgBABgBAAIAAAAQgBAAAAgBQgBAAAAAAQAAgBgBAAQAAgBAAgBIAAhFQAAgBAAgBQABAAAAgBQABAAAAAAQABgBABAAIAVAAQAFABAFABQAFABADADQAEADACAEQACAEAAAGQAAAFgCAEIgFAGQgEACgFACQgFABgFAAIgBAAIAaAeIAAACIgDACQgBAAAAgBQgBAAAAAAQgBAAAAgBQAAAAgBgBgAgTAAIATAAIAIAAQAEAAACgDQADgCABgEIABgGIgBgHQgBgEgDgCIgHgDIgHgBIgTAAg");
	this.shape_42.setTransform(311.2,-7.2);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#6B8A21").s().p("AgWAmQgBAAgBAAQAAAAgBgBQAAAAAAgBQAAAAAAgBIAAhFQAAgBAAAAQAAgBAAAAQABgBAAAAQABAAABAAIAsAAQABAAABAAQAAAAABAAQAAABAAAAQABABAAAAIAAABQAAAAgBABQAAAAAAABQgBAAAAAAQgBAAgBAAIgpAAIAAAeIAfAAQABAAABAAQAAAAABAAQAAABAAAAQABABAAAAIAAAAQAAAAgBAAQAAAAAAABQgBAAAAAAQgBAAgBAAIgfAAIAAAgIArAAQAAAAABAAQAAAAABAAQAAABAAAAQABABAAAAIAAABQAAAAgBABQAAAAAAABQgBAAAAAAQgBAAAAAAg");
	this.shape_43.setTransform(304.6,-7.3);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#6B8A21").s().p("AAbAnQgBAAAAAAQgBgBAAAAQAAAAgBgBQAAgBAAAAIAAgiIgvAAIAAAiQAAAAAAABQgBABAAAAQAAAAgBABQAAAAgBAAIgBAAQAAAAgBAAQAAgBgBAAQAAAAAAgBQAAgBAAAAIAAhHQAAAAAAgBQAAgBAAAAQABAAAAgBQABAAAAAAIABAAQABAAAAAAQABABAAAAQAAAAABABQAAABAAAAIAAAiIAvAAIAAgiQAAAAAAgBQABgBAAAAQAAAAABgBQAAAAABAAIABAAQAAAAABAAQAAABABAAQAAAAAAABQAAABAAAAIAABHQAAAAAAABQAAABAAAAQgBAAAAABQgBAAAAAAg");
	this.shape_44.setTransform(296.9,-7.3);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#6B8A21").s().p("AgVAnQgBAAAAAAQgBgBAAAAQAAAAgBgBQAAAAAAgBIAAhHQAAAAAAgBQABgBAAAAQAAAAABgBQAAAAABAAIABAAQAAAAABAAQAAABABAAQAAAAAAABQAAABAAAAIAAAjIAjgkQABAAAAgBQABAAABAAQAAgBABAAQAAAAABAAQAAABABAAQAAAAAAABQABAAAAAAQAAABAAAAIgjAjIAkAjQAAABAAAAQAAABgBAAQAAABAAAAQgBAAAAAAQgBABAAAAQgBAAgBAAQAAgBgBAAQAAAAgBgBIgkglIAAAkQAAABAAAAQAAABAAAAQgBAAAAABQgBAAAAAAg");
	this.shape_45.setTransform(287.9,-7.3);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#6B8A21").s().p("AgCAnIgIgDQgEgBgDgCIgFgFIgFgGIgDgGIgCgHIgBgJIABgHIACgIIADgGIAFgGIAFgFIAHgDIAIgCIAGgCQAGABAJADQAFACAEAEQAFAEAAADQAAABgBAAQAAAAAAABQAAAAAAAAQgBABAAAAIgCABIgEgGIgGgFIgHgDIgIgBIgFAAIgHACQgGADgEAEQgEAFgCAGQgCAKgBADIADANQACAHAEAFIAFAEIAFADIAHACIAFABQAFgBAFgBQAEgBAEgDIAFgFIADgGQAEAAAAADQgCAGgDADQgEAEgGADQgKACgFAAIgGAAg");
	this.shape_46.setTransform(280.6,-7.3);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("#6B8A21").s().p("AAAAnQAAAAAAAAQgBgBAAAAQAAAAAAgBQgBgBAAAAIAAhHQAAAAABgBQAAgBAAAAQAAAAABgBQAAAAAAAAIAAAAQABAAAAAAQABABAAAAQAAAAAAABQAAABAAAAIAABHQAAAAAAABQAAABAAAAQAAAAgBABQAAAAgBAAg");
	this.shape_47.setTransform(275.2,-7.3);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("#6B8A21").s().p("AgSAmQgBAAgBAAQgBAAAAAAQgBgBAAAAQAAgBAAgBIAAhFQAAgBAAgBQAAAAABgBQAAAAAAAAQABAAAAAAIACAAQAAAAABAAQAAAAAAAAQABABAAAAQAAABAAABIAABDIAkAAQABAAAAAAQABAAAAABQABAAAAAAQAAABAAABIAAAAQAAABAAAAQAAABgBAAQAAAAgBAAQAAAAgBAAg");
	this.shape_48.setTransform(271.2,-7.3);

	this.shape_49 = new cjs.Shape();
	this.shape_49.graphics.f("#6B8A21").s().p("AgCAnIgIgDQgDgBgEgCIgFgFIgFgGIgDgGIgCgHIgBgJIABgHIACgIIADgGIAFgGIAFgFIAHgDIAIgCIAGgCQAGABAJADQAFACAFAEQADAEAAADQAAABAAAAQAAAAAAABQAAAAAAAAQgBABAAAAIgCABIgEgGIgFgFIgIgDIgIgBIgGAAIgGACQgFADgFAEQgEAFgCAGQgCAKgBADIADANQACAHAEAFIAFAEIAFADIAHACIAFABQAFgBAFgBQAEgBAEgDIAFgFIADgGQAEAAAAADQgCAGgDADQgEAEgGADQgKACgFAAIgGAAg");
	this.shape_49.setTransform(264,-7.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_49},{t:this.shape_48},{t:this.shape_47},{t:this.shape_46},{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(258,-15,533,16);


(lib.replaybtn = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#666666").s().p("Ak9BwIAAjgIJ6AAIAADgg");
	this.shape.setTransform(9.1,9.8,0.438,1.268,0,0,0,-0.2,0);
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(3).to({_off:false},0).wait(1));

	// Layer 2
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#BFBFBF").s().p("AgEBGQghgDgWgXQgXgZAAgfQAAgQAGgQQAOggAfgNQARgGAOgBQAiAAAYAZQAZAYAAAjIgUAAQAAgbgTgSQgSgTgaAAQgZAAgSATQgTATAAAaQAAAXARASQAQASAZACIgNgcIBVAnIhWAlg");
	this.shape_1.setTransform(8.4,9.7);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#666666").s().p("AgEBGQghgDgWgXQgXgZAAgfQAAgQAGgQQAOggAfgNQARgGAOgBQAiAAAYAZQAZAYAAAjIgUAAQAAgbgTgSQgSgTgaAAQgZAAgSATQgTATAAAaQAAAXARASQAQASAZACIgNgcIBVAnIhWAlg");
	this.shape_2.setTransform(8.4,9.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AgEBGQghgDgWgXQgXgZAAgfQAAgQAGgQQAOggAfgNQARgGAOgBQAiAAAYAZQAZAYAAAjIgUAAQAAgbgTgSQgSgTgaAAQgZAAgSATQgTATAAAaQAAAXARASQAQASAZACIgNgcIBVAnIhWAlg");
	this.shape_3.setTransform(8.4,9.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1}]}).to({state:[{t:this.shape_2}]},1).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_3}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,16.7,19.4);


(lib.pic = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib._336x280gardener();

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,515,200);


(lib.head1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#193670").s().p("AAAAFQgEAAAAgFIAAAAQAAgEAEAAIAAAAQAFAAAAAEIAAAAQAAAFgFAAg");
	this.shape.setTransform(548.6,7.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#193670").s().p("AgOAiQgGgCgDgDQgEgEAAgCQAAgDAEgBQAEAFAGADIAHADIAGABIAJgBIAGgEQADgBABgDQACgCAAgEQAAgDgCgCQgBgCgDgCQgEgCgLgCQgLgDgFgBQgEgCgCgDQgDgEAAgFQAAgFACgDQACgEAEgCQADgDAFgCQAFgCAEAAQAIAAAGADQAGACADADQADADAAADQAAAAAAAAQAAABgBAAQAAABAAAAQgBAAAAAAIgCABQgDgEgGgEQgGgCgHAAIgGAAIgGADIgEAFQgCACAAADQAAADACACIAEAFQAEABAKADIAJACIAIACQAEACACADQADAEAAAEQAAAFgCAEQgCAEgEADQgDADgFABQgGACgGAAQgHAAgHgDg");
	this.shape_1.setTransform(543.8,4.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#193670").s().p("AAaAkQgBAAgBAAQAAAAgBgBQAAAAAAgBQgBgBAAAAIAAgkIgBgLQgBgEgDgEQgDgDgDgBQgEgCgGAAIgGABQgEABgEACIgFAGIgEAGIAAAtQAAAAAAABQAAABgBAAQAAABgBAAQAAAAgBAAIgBAAQgBAAAAAAQgBAAAAgBQgBAAAAgBQAAgBAAAAIAAhCIACgBQABAAAAAAQABAAAAAAQABABAAAAQAAAAABAAQABACAAAFIAAAGIAEgGIAGgFIAHgDIAHgBQAGAAAGACQAFACADAFQAEAEACAGQACAFAAAHIAAAlQAAAAAAABQAAABgBAAQAAABgBAAQAAAAgBAAg");
	this.shape_2.setTransform(536.6,4.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#193670").s().p("AgNAhQgHgCgFgFQgEgFgDgHQgDgHAAgHQAAgGADgHQADgHAEgFQAFgFAHgCQAHgEAGAAQAHAAAHAEQAHACAFAFQAEAFADAHQADAHAAAGQAAAIgDAGQgDAHgEAFQgFAFgHACQgHADgHABQgGgBgHgDgAgKgbQgFADgEADQgEAFgCAFQgDAGAAAFQAAAGADAGQACAFAEAFQAEADAFADQAFACAFAAQAGAAAFgCQAFgDAEgDQAEgEACgGQADgGAAgGQAAgEgDgHQgCgFgEgEQgEgFgFgCQgFgCgGAAQgFAAgFACg");
	this.shape_3.setTransform(528.3,4.5);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#193670").s().p("AAAAyQAAAAAAAAQgBgBAAAAQgBgBAAAAQAAgBAAgBIAAg/QAAgBAAAAQAAgBABAAQAAgBABAAQAAAAAAAAIAAAAQABAAABAAQAAAAABABQAAAAAAABQABAAAAABIAAA/QAAABgBABQAAAAAAABQgBAAAAABQgBAAgBAAgAgDgsQgBgFAEAAQAEAAABAFQAAAFgFAAQgDAAAAgFg");
	this.shape_4.setTransform(522.7,3);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#193670").s().p("AAAArQgCgBgCgDQgCgDgBgEQgCgEAAgGIAAgqIgIAAQgBAAgBAAQgBAAAAAAQgBgBAAAAQAAgBAAAAIAAgBQAAgBAAAAQAAgBABAAQAAgBABAAQABAAABAAIAIAAIAAgOQAAgDADAAIABAAQADAAABADIAAAOIASAAQABAAABAAQAAAAABABQAAAAAAABQAAAAAAABIAAABQAAAAAAABQAAAAAAABQgBAAAAAAQgBAAgBAAIgSAAIAAApQAAAKABADQACAFAGAAQAEAAADgCIAEgFIACABIABADQAAACgDACIgEADIgHACQgFAAgDgCg");
	this.shape_5.setTransform(518.8,3.7);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#193670").s().p("AgeAyQgBAAAAAAQgBAAAAgBQgBAAAAgBQAAAAAAgBIAAheIACgBQABAAAAAAQABAAAAAAQABAAAAABQAAAAAAAAQACACAAAEIAAAIIAFgHIAGgFIAIgDIAHgBQAHAAAHACQAFADAFAFQAFAFADAHQACAHAAAIQAAAIgCAFQgDAGgFAFQgFAFgFADQgHADgHAAQgDAAgFgCQgFgBgDgCIgGgFIgEgGIAAAoQAAABAAAAQAAABgBAAQAAABgBAAQAAAAgBAAgAgIgpQgFABgDACIgGAHIgEAHIAAARQAAAFACADQACAEAEAEQAEAEAFABQAEACAFAAQAFAAAFgCQAGgCADgEQADgEACgEQACgGAAgGQAAgHgCgGQgCgFgDgEQgEgEgFgDQgFgCgFAAQgDAAgFACg");
	this.shape_6.setTransform(512.3,5.8);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#193670").s().p("AgNAhQgHgCgFgFQgEgFgDgHQgDgHAAgHQAAgGADgHQADgHAEgFQAFgFAHgCQAHgEAGAAQAHAAAHAEQAHACAFAFQAEAFADAHQADAHAAAGQAAAIgDAGQgDAHgEAFQgFAFgHACQgHADgHABQgGgBgHgDgAgKgbQgFADgEADQgEAFgCAFQgDAGAAAFQAAAGADAGQACAFAEAFQAEADAFADQAFACAFAAQAGAAAFgCQAFgDAEgDQAEgEACgGQADgGAAgGQAAgEgDgHQgCgFgEgEQgEgFgFgCQgFgCgGAAQgFAAgFACg");
	this.shape_7.setTransform(503.6,4.5);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#193670").s().p("AgLAiQgGgDgFgFQgGgFgCgHQgDgGAAgIQAAgGADgHQADgHAFgFQAFgFAGgCQAGgEAGAAQAHAAAHADQAFADAEAEQAFAFACAGQACAHABAHIAAABQAAAAgBAAQAAAAAAAAQgBAAAAAAQgBABAAAAIg5AAQABAGACAGQACAFAEAEQAEAEAFACQAGACAEAAIAKgBQAEgBACgDQAGgDADgGIADAAQAAABAAAAQABABAAAAQAAABAAAAQABAAAAABQgBADgEAFQgEADgGACQgHADgIABQgGAAgHgDgAAagDQAAgGgCgFQgCgEgEgEQgDgEgEgCQgFgBgFAAQgEAAgFACQgEACgEADQgDAEgCAEQgDAFgBAGIAzAAIAAAAg");
	this.shape_8.setTransform(493,4.5);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#193670").s().p("AgOA2QgGgCgEgCQgFgDgCgDQgCgEAAgEQAAgEACgEQACgDADgDIAIgFIAKgCIgEgDQgBgBAAAAQAAgBAAAAQgBgBAAAAQAAgBAAgBQAAgEAEgDIgHgCIgGgFIgDgHIgBgHQAAgGACgEQACgFAEgEQADgDAFgCQAGgCAFAAQAEAAAEABIAIAEIAHgJQADgEADABQABABABAAQAAAAAAABQABAAAAAAQAAABAAAAIgMANIAFAHIACAJQAAAFgCAFQgCAFgEADQgEAEgFAAQgGACgEAAIgEgBQgDACAAADQAAAEAFACIANADIAIADIAIADIAFAGQACADAAAEQAAAFgDAEQgCAEgFACQgEADgHABQgGACgHAAIgOgBgAgJAVQgFABgEACIgGAFQgCADAAAEQAAADACACQACADADABQADACAFABIALABIAKgBIAJgDIAGgEQACgDAAgEIgCgFIgEgDQgEgDgIgCIgJgCIgJACgAgIgoQgEACgCACQgDADgCAEQgBADAAAEQAAAFABADQACAEADADQACACAEACIAIABIAHgBIAHgEIAEgHQABgDAAgFQAAgEgBgDIgEgHIgHgEQgEgBgDAAQgEAAgEABg");
	this.shape_9.setTransform(485.7,5.6);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#193670").s().p("AgOAjIgIgEQgDgDgCgDQgCgDAAgFQAAgGADgFQAEgDAGgDQAGgBAKgCQAHgBAOAAIACAAIAAgEQgBgFgBgEQgBgDgEgDQgCgDgEgCQgEgBgFAAIgHABIgGADQgHADgCAHQgEgBgBgEQABgCAEgFQADgDAGgCQAGgEAHAAQAHAAAFADQAFABAEAEQADAEADAEQACAFAAAHIAAAqIgDABQAAAAgBAAQAAAAgBAAQAAAAgBAAQAAgBgBAAIAAgFIAAgIIgFAGIgGAFIgIADQgEACgEAAQgFAAgFgCgAABABIgMADQgFACgDAEQgCADAAAEIABAGIADAEIAGADIAIABQAEAAAEgCQAFgCAEgEQAEgDACgEQACgFABgFIAAgGIgCAAIgUABg");
	this.shape_10.setTransform(478.3,4.5);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#193670").s().p("AAAArQgCgBgCgDQgDgDAAgEQgCgEAAgGIAAgqIgIAAQgBAAgBAAQgBAAAAAAQgBgBAAAAQAAgBAAAAIAAgBQAAgBAAAAQAAgBABAAQAAgBABAAQABAAABAAIAIAAIAAgOQAAgDAEAAIAAAAQABAAABAAQAAAAABABQAAAAAAABQAAABAAAAIAAAOIATAAQABAAABAAQAAAAABABQAAAAAAABQAAAAAAABIAAABQAAAAAAABQAAAAAAABQgBAAAAAAQgBAAgBAAIgTAAIAAApQAAAKACADQACAFAGAAQAEAAADgCIAEgFIACABIABADQAAACgDACIgEADIgHACQgFAAgDgCg");
	this.shape_11.setTransform(472.3,3.7);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#193670").s().p("AAaAkQgBAAgBAAQAAAAgBgBQAAAAAAgBQgBgBAAAAIAAgkIgBgLQgBgEgDgEQgCgDgEgBQgFgCgFAAIgGABQgEABgEACIgFAGIgEAGIAAAtQAAAAAAABQAAABgBAAQAAABgBAAQAAAAgBAAIgBAAQgBAAAAAAQgBAAAAgBQgBAAAAgBQAAgBAAAAIAAhCIACgBQABAAAAAAQABAAAAAAQABABAAAAQAAAAABAAQABACAAAFIAAAGIAEgGIAGgFIAHgDIAHgBQAGAAAGACQAFACADAFQAEAEACAGQACAFAAAHIAAAlQAAAAAAABQAAABgBAAQAAABgBAAQAAAAgBAAg");
	this.shape_12.setTransform(465.8,4.4);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#193670").s().p("AgOAjIgIgEQgDgDgCgDQgBgDAAgFQAAgGACgFQADgDAHgDQAGgBAKgCQAHgBAOAAIACAAIAAgEQAAgFgCgEQgCgDgDgDQgCgDgEgCQgFgBgFAAIgGABIgGADQgHADgCAHQgFgBAAgEQAAgCAFgFQAEgDAFgCQAHgEAGAAQAGAAAGADQAFABAEAEQADAEACAEQACAFAAAHIAAAqIgCABQAAAAgBAAQAAAAgBAAQAAAAgBAAQAAgBAAAAIgBgFIAAgIIgFAGIgHAFIgHADQgEACgEAAQgFAAgFgCgAAAABIgLADQgFACgCAEQgDADAAAEIABAGIADAEIAHADIAHABQADAAAGgCQAEgCAFgEQADgDACgEQADgFAAgFIAAgGIgDAAIgUABg");
	this.shape_13.setTransform(457.8,4.5);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#193670").s().p("AgEAhIgbhCQAGgFADAIIAWA6IAXg6QADgIAGAFIgbBBQgCADgDAAQgDAAgBgCg");
	this.shape_14.setTransform(450.8,4.5);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#193670").s().p("AgNAxQgFgDgFgFQgFgFgDgHQgCgHAAgIQAAgIACgGQADgGAFgFQAFgEAFgDQAHgDAGAAQAFAAAEABIAHADIAHAGIAEAGIAAgsIACgBIADABQACACAAAEIAABaQAAAAAAABQAAABgBAAQAAABgBAAQAAAAgBAAIgBAAQgBAAAAAAQgBAAAAgBQgBAAAAgBQAAgBAAAAIAAgMIgFAGIgGAGQgDACgFABIgIABQgHAAgGgCgAgKgMQgFACgDAEQgDAEgCAEQgDAFAAAHQAAAGADAGQACAGADAEQADAEAFACQAGACAEAAQAFAAAFgCQAFgBAEgDQADgFACgEQADgFAAgFIAAgQIgFgGIgFgHQgEgCgEgBQgEgBgFAAQgEAAgGACg");
	this.shape_15.setTransform(442.9,3);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#193670").s().p("AgpAuIAlhbQABgDADAAQAEAAABADIAlBbQgHAFgCgGIgMgfIgpAAIgMAfQgCAEgCAAQgCAAgDgDgAATAIIgTgwIgSAwIAlAAg");
	this.shape_16.setTransform(434.4,3.2);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#193670").s().p("AgLAiQgHgDgEgFQgFgFgDgHQgCgGAAgIQAAgGACgHQADgHAFgFQAEgFAHgCQAHgEAFAAQAHAAAGADQAGADAEAEQAFAFACAGQADAHgBAHIAAABQAAAAAAAAQAAAAAAAAQgBAAAAAAQgBABAAAAIg5AAQAAAGADAGQACAFAEAEQAEAEAFACQAGACAEAAIAKgBQADgBAEgDQAFgDADgGIADAAQAAABAAAAQABABAAAAQAAABAAAAQABAAAAABQgBADgEAFQgEADgGACQgHADgIABQgGAAgHgDgAAagDQAAgGgCgFQgCgEgDgEQgDgEgFgCQgFgBgFAAQgDAAgGACQgEACgDADQgFAEgBAEQgDAFgBAGIAzAAIAAAAg");
	this.shape_17.setTransform(423.4,4.5);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#193670").s().p("AgOAkQgBAAAAAAQgBAAAAgBQAAAAgBgBQAAgBAAAAIAAhCIACgBQABAAAAAAQABAAAAAAQABABAAAAQABAAAAAAQABACAAAFIAAAJIADgIIAEgGIAEgDIAHgBQAEAAADABQADADAAACIgBADIgBABQgEgDgFAAQgFAAgCACQgDADgCAEIgEAKIgBAKIAAAgQAAAAAAABQAAABAAAAQgBABAAAAQgBAAgBAAg");
	this.shape_18.setTransform(417.4,4.4);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#193670").s().p("AgOAjIgIgEQgDgDgCgDQgBgDAAgFQAAgGACgFQADgDAHgDQAGgBAKgCQAHgBAOAAIACAAIAAgEQgBgFgBgEQgCgDgDgDQgCgDgEgCQgEgBgGAAIgGABIgGADQgHADgCAHQgFgBAAgEQAAgCAFgFQAEgDAFgCQAHgEAGAAQAGAAAGADQAFABAEAEQADAEACAEQACAFABAHIAAAqIgDABQAAAAgBAAQAAAAgBAAQAAAAgBAAQAAgBAAAAIgBgFIAAgIIgFAGIgGAFIgIADQgEACgEAAQgGAAgEgCgAAAABIgLADQgFACgCAEQgDADAAAEIABAGIADAEIAHADIAHABQAEAAAFgCQAFgCAEgEQADgDACgEQACgFABgFIAAgGIgCAAIgVABg");
	this.shape_19.setTransform(410.6,4.5);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#193670").s().p("AgKAhQgHgCgFgFQgEgFgDgHQgDgHABgHQgBgGADgHQADgHAEgFQAFgFAHgCQAHgEAGAAQAIAAAHAEQAFACAFADQAEAHAAAEQAAAAAAABQAAAAAAABQAAAAgBAAQAAABAAAAIgDABIgDgHIgFgFQgDgDgFgBQgEgBgFAAQgEAAgGACQgFADgEADQgEAFgCAFQgCAGAAAFQAAAGACAGQACAFAEAFQADADAGADQAGACAEAAIAJgBIAIgEQAEgDAEgJQAFABgBADQgBAGgEAFQgEAEgFACQgHADgIAAQgGgBgHgDg");
	this.shape_20.setTransform(403.3,4.5);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#193670").s().p("AAAAyQAAAAAAAAQgBgBAAAAQgBgBAAAAQAAgBAAgBIAAg/QAAgBAAAAQAAgBABAAQAAgBABAAQAAAAAAAAIAAAAQABAAABAAQAAAAABABQAAAAAAABQAAAAAAABIAAA/QAAABAAABQAAAAAAABQgBAAAAABQgBAAgBAAgAgEgsQABgFADAAQAFAAgBAFQAAAFgEAAQgEAAAAgFg");
	this.shape_21.setTransform(398,3);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#193670").s().p("AgMAxQgGgDgGgFQgEgFgCgHQgDgHAAgIQAAgIADgGQACgGAFgFQAEgEAHgDQAGgDAGAAQAEAAAFABIAHADIAHAGIAEAGIAAgsIACgBIAEABQABACAAAEIAABaQAAAAAAABQAAABgBAAQAAABgBAAQAAAAgBAAIgBAAQgBAAAAAAQgBAAAAgBQgBAAAAgBQAAgBAAAAIAAgMIgFAGIgGAGQgEACgEABIgIABQgHAAgFgCgAgJgMQgFACgEAEQgEAEgCAEQgCAFAAAHQAAAGACAGQACAGAEAEQAEAEAFACQAFACAEAAQAFAAAFgCQAFgBAEgDQAEgFACgEQACgFAAgFIAAgQIgEgGIgGgHQgEgCgEgBQgEgBgFAAQgEAAgFACg");
	this.shape_22.setTransform(392.1,3);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#193670").s().p("AgLAiQgGgDgFgFQgGgFgCgHQgCgGAAgIQAAgGACgHQADgHAFgFQAFgFAGgCQAGgEAGAAQAHAAAGADQAGADAEAEQAFAFACAGQADAHgBAHIAAABQAAAAAAAAQAAAAAAAAQgBAAAAAAQgBABAAAAIg5AAQAAAGADAGQACAFAEAEQAEAEAFACQAGACAEAAIAKgBQADgBADgDQAGgDADgGIADAAQAAABAAAAQABABAAAAQAAABAAAAQABAAAAABQgBADgEAFQgEADgGACQgHADgIABQgGAAgHgDgAAagDQAAgGgCgFQgCgEgEgEQgDgEgEgCQgFgBgFAAQgDAAgGACQgEACgEADQgDAEgCAEQgDAFgBAGIAzAAIAAAAg");
	this.shape_23.setTransform(384.2,4.5);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#193670").s().p("AAnAwQgBAAgBAAQAAAAgBAAQAAgBgBAAQAAgBAAgBIAAhUIgdA4QgCAFgEAAQgDAAgCgFIgeg4IAABUQAAABAAABQAAAAgBABQAAAAAAAAQgBAAgBAAIgBAAQgBAAAAAAQgBAAAAAAQAAgBgBAAQAAgBAAgBIAAhYQAAgEAFAAIACAAQABAAAAAAQABAAABAAQAAAAAAAAQABABAAAAIADAEIAcA5IAdg5IADgEQAAAAABgBQAAAAABAAQAAAAABAAQAAAAABAAIABAAQAGAAAAAEIAABYQAAABAAABQgBAAAAABQgBAAAAAAQgBAAgBAAg");
	this.shape_24.setTransform(374.7,3.2);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#193670").s().p("AgOAkQAAAAgBAAQgBAAAAgBQAAAAgBgBQAAgBAAAAIAAhCIACgBQABAAAAAAQABAAAAAAQABABAAAAQABAAAAAAQABACAAAFIAAAJIADgIIAEgGIAEgDIAHgBQAEAAADABQADADAAACIgBADIgBABQgEgDgFAAQgFAAgCACQgDADgCAEIgEAKIgBAKIAAAgQAAAAAAABQAAABgBAAQAAABAAAAQgBAAgBAAg");
	this.shape_25.setTransform(364.6,4.4);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#193670").s().p("AgNAiQgFgDgEgEQgDgEgCgGQgCgFAAgHIAAglQAAAAAAgBQAAgBABAAQAAgBABAAQAAAAABAAIABAAQABAAABAAQAAAAABABQAAAAAAABQAAABAAAAIAAAkQAAAFACAGIAEAIQADADAEABQAEACAFAAIAGgBIAHgDIAGgGIAEgHIAAgsQAAAAAAgBQAAgBAAAAQABgBAAAAQABAAABAAIABAAQABAAAAAAQABAAAAABQABAAAAABQAAABAAAAIAABCIgCABQgBAAAAAAQgBAAAAAAQgBgBAAAAQgBAAAAAAQgBgCAAgEIAAgHIgEAGIgGAFIgHADIgHABQgHAAgFgCg");
	this.shape_26.setTransform(357.6,4.5);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#193670").s().p("AgNAhQgHgCgFgFQgEgFgDgHQgDgHAAgHQAAgGADgHQADgHAEgFQAFgFAHgCQAHgEAGAAQAHAAAHAEQAHACAFAFQAEAFADAHQADAHAAAGQAAAIgDAGQgDAHgEAFQgFAFgHACQgHADgHABQgGgBgHgDgAgKgbQgFADgEADQgEAFgCAFQgDAGAAAFQAAAGADAGQACAFAEAFQAEADAFADQAFACAFAAQAGAAAFgCQAFgDAEgDQAEgEACgGQADgGAAgGQAAgEgDgHQgCgFgEgEQgEgFgFgCQgFgCgGAAQgFAAgFACg");
	this.shape_27.setTransform(349.4,4.5);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#193670").s().p("AgKAxIgBgBIALgfQgCAAgBgDIgcg9QAGgFADAIIAXA5IAWg5QADgIAGAFIgjBcQgBAFgEAAg");
	this.shape_28.setTransform(341.8,5.9);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#193670").s().p("AAAArQgCgBgCgDQgCgDgBgEQgCgEAAgGIAAgqIgIAAQgBAAgBAAQgBAAAAAAQgBgBAAAAQAAgBAAAAIAAgBQAAgBAAAAQAAgBABAAQAAgBABAAQABAAABAAIAIAAIAAgOQAAgDADAAIABAAQADAAABADIAAAOIASAAQABAAABAAQAAAAABABQAAAAAAABQAAAAAAABIAAABQAAAAAAABQAAAAAAABQgBAAAAAAQgBAAgBAAIgSAAIAAApQAAAKABADQACAFAGAAQAEAAADgCIAEgFIACABIABADQAAACgDACIgEADIgHACQgFAAgDgCg");
	this.shape_29.setTransform(333.4,3.7);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#193670").s().p("AgNAiQgFgDgEgEQgDgEgCgGQgCgFAAgHIAAglQAAAAAAgBQAAgBABAAQAAgBABAAQAAAAABAAIABAAQABAAABAAQAAAAABABQAAAAAAABQAAABAAAAIAAAkQAAAFACAGIAEAIQADADAEABQAEACAFAAIAGgBIAHgDIAGgGIAEgHIAAgsQAAAAAAgBQAAgBABAAQAAgBAAAAQABAAABAAIABAAQABAAAAAAQABAAAAABQABAAAAABQAAABAAAAIAABCIgCABQgBAAAAAAQgBAAAAAAQgBgBAAAAQgBAAAAAAQgBgCAAgEIAAgHIgEAGIgGAFIgHADIgHABQgHAAgFgCg");
	this.shape_30.setTransform(326.8,4.5);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#193670").s().p("AgNAhQgHgCgFgFQgEgFgDgHQgDgHAAgHQAAgGADgHQADgHAEgFQAFgFAHgCQAHgEAGAAQAHAAAHAEQAHACAFAFQAEAFADAHQADAHAAAGQAAAIgDAGQgDAHgEAFQgFAFgHACQgHADgHABQgGgBgHgDgAgKgbQgFADgEADQgEAFgCAFQgDAGAAAFQAAAGADAGQACAFAEAFQAEADAFADQAFACAFAAQAGAAAFgCQAFgDAEgDQAEgEACgGQADgGAAgGQAAgEgDgHQgCgFgEgEQgEgFgFgCQgFgCgGAAQgFAAgFACg");
	this.shape_31.setTransform(318.6,4.5);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#193670").s().p("AgJAyIgIgEIgFgFIgEgGIAAAMQAAAAAAABQAAABgBAAQAAABgBAAQAAAAgBAAIgBAAQgBAAAAAAQgBAAAAgBQgBAAAAgBQAAgBAAAAIAAhgIACgBIADABQACACAAAEIAAAmIAFgGIAHgGIAHgDIAHgBQAHAAAHACQAFADAFAFQAFAFACAGQADAGAAAIQAAAIgDAHQgCAHgFAFQgFAFgFADQgHACgHAAIgJgBgAgIgNQgEABgEACIgGAHIgEAGIAAAQQAAAFACAFQACAEAEAEQAEAEAEABQAFACAFAAQAFAAAGgCQAFgCADgEQADgEACgGQACgFAAgHQAAgGgCgGQgCgEgDgEQgEgEgFgCQgFgCgFAAQgEAAgEABg");
	this.shape_32.setTransform(310.5,3);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#193670").s().p("AgOAjIgIgEQgDgDgCgDQgCgDAAgFQAAgGAEgFQADgDAGgDQAGgBAKgCQAIgBANAAIABAAIAAgEQABgFgCgEQgBgDgEgDQgCgDgEgCQgEgBgFAAIgHABIgGADQgGADgEAHQgDgBAAgEQAAgCADgFQAEgDAGgCQAHgEAGAAQAHAAAFADQAFABAEAEQADAEADAEQACAFAAAHIAAAqIgDABQgBAAAAAAQAAAAgBAAQAAAAgBAAQAAgBgBAAIgBgFIAAgIIgEAGIgGAFIgJADQgDACgEAAQgFAAgFgCgAABABIgMADQgFACgDAEQgCADAAAEIABAGIAEAEIAFADIAIABQAEAAAEgCQAGgCADgEQAEgDACgEQADgFgBgFIAAgGIgBAAIgUABg");
	this.shape_33.setTransform(302,4.5);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#193670").s().p("AAaAkQgBAAgBAAQAAAAgBgBQAAAAAAgBQgBgBAAAAIAAgkIgBgLQgBgEgDgEQgDgDgEgBQgDgCgGAAIgGABQgEABgEACIgFAGIgEAGIAAAtQAAAAAAABQAAABgBAAQAAABgBAAQAAAAgBAAIgBAAQgBAAAAAAQgBAAAAgBQgBAAAAgBQAAgBAAAAIAAhCIACgBQABAAAAAAQABAAAAAAQABABAAAAQAAAAABAAQABACAAAFIAAAGIAEgGIAGgFIAHgDIAGgBQAHAAAGACQAFACADAFQAFAEABAGQACAFAAAHIAAAlQAAAAAAABQAAABgBAAQAAABgBAAQAAAAgBAAg");
	this.shape_34.setTransform(291.9,4.4);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#193670").s().p("AgOAkQAAAAgBAAQgBAAAAgBQAAAAgBgBQAAgBAAAAIAAhCIACgBQABAAAAAAQABAAAAAAQABABAAAAQABAAAAAAQABACAAAFIAAAJIADgIIAEgGIAEgDIAHgBQAEAAADABQADADAAACIgBADIgBABQgEgDgFAAQgFAAgCACQgDADgCAEIgEAKIgBAKIAAAgQAAAAAAABQAAABgBAAQAAABAAAAQgBAAgBAAg");
	this.shape_35.setTransform(285.7,4.4);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#193670").s().p("AgOAjIgIgEQgDgDgBgDQgCgDAAgFQAAgGADgFQADgDAGgDQAGgBAKgCQAIgBANAAIABAAIAAgEQAAgFgBgEQgBgDgDgDQgDgDgEgCQgFgBgEAAIgHABIgHADQgFADgEAHQgDgBAAgEQAAgCADgFQAEgDAGgCQAGgEAHAAQAGAAAGADQAFABAEAEQADAEACAEQACAFAAAHIAAAqIgCABQgBAAAAAAQAAAAgBAAQAAAAgBAAQAAgBAAAAIgCgFIAAgIIgEAGIgHAFIgIADQgDACgEAAQgGAAgEgCgAABABIgMADQgFACgCAEQgDADAAAEIABAGIAEAEIAGADIAHABQADAAAGgCQAEgCAFgEQADgDACgEQACgFAAgFIAAgGIgCAAIgTABg");
	this.shape_36.setTransform(278.9,4.5);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#193670").s().p("AgLAiQgGgDgGgFQgFgFgCgHQgDgGAAgIQAAgGADgHQADgHAEgFQAGgFAGgCQAHgEAFAAQAHAAAHADQAFADAFAEQAEAFACAGQACAHABAHIAAABQAAAAgBAAQAAAAAAAAQgBAAAAAAQgBABAAAAIg5AAQABAGACAGQACAFAEAEQAEAEAFACQAFACAFAAIAJgBQAFgBACgDQAGgDADgGIACAAQABABAAAAQABABAAAAQAAABAAAAQABAAAAABQAAADgFAFQgEADgGACQgHADgIABQgGAAgHgDgAAagDQAAgGgCgFQgCgEgEgEQgDgEgEgCQgEgBgGAAQgEAAgFACQgEACgEADQgDAEgCAEQgDAFgBAGIAzAAIAAAAg");
	this.shape_37.setTransform(271.5,4.5);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#193670").s().p("AgYAwQgEAAAAgEIAAhYQAAgBAAAAQABgBAAAAQAAgBABAAQABAAAAAAIABAAQABAAABAAQAAAAABABQAAAAAAABQAAAAAAABIAABVIAuAAQABAAABAAQAAABABAAQAAABABAAQAAABAAABIAAAAQAAABAAABQgBAAAAABQgBAAAAAAQgBAAgBAAg");
	this.shape_38.setTransform(264.1,3.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(258,-6,532,19);


(lib.CTA_btn = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#00FFFF").s().p("A6PV3MAAAgruMA0eAAAMAAAArug");
	this.shape.setTransform(168,140);
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(3).to({_off:false},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = null;


(lib.border336x280 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,0,3).p("EgkegEmMBI9AAAIAAJNMhI9AAAg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-234.5,-30.5,469.1,61);


(lib.blocks = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#557C6B").s().p("AiWCSIAAkjIEtAAIAAEjg");
	this.shape.setTransform(-15.2,45);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#92AF2B").s().p("AiWCXIAAktIEtAAIAAEtg");
	this.shape_1.setTransform(-15.2,15.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#005A8C").s().p("AiWCXIAAktIEtAAIAAEtg");
	this.shape_2.setTransform(-15.2,74.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-30.3,0,30.4,90);


(lib.logoblock = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// logo
	this.instance = new lib.TEC_logorev("synched",0);
	this.instance.setTransform(-13.5,60.8,0.49,0.49,0,0,0,181.4,32.2);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// bkgd
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#193670").s().p("AwAG9IAArdQAAibCdgBIdkAAIAAN5g");
	this.shape.setTransform(-102.5,45.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-205,1,205,89);


(lib.LogoLockup_468x60 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.blocks();
	this.instance.setTransform(256.7,8.4,0.667,0.667,0,0,0,150,12.5);

	this.instance_1 = new lib.logoblock();
	this.instance_1.setTransform(236.7,33.4,0.667,0.667,0,0,0,150,50);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_1},{t:this.instance}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,156.7,60);


// stage content:
(lib.TEC201609_Garden_468x60_AdR = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.clickthru_btn.on("click", function(evt){
		  window.open(clickTag, "_blank");
		});
	}
	this.frame_125 = function() {
		this.stop();
		 
		this.replay_btn.addEventListener("click", fl_ClickToGoToAndPlayFromFrame.bind(this));
		function fl_ClickToGoToAndPlayFromFrame() 
		{
		this.gotoAndPlay(1);
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(125).call(this.frame_125).wait(1));

	// replay btn
	this.replay_btn = new lib.replaybtn();
	this.replay_btn.setTransform(317,41.5,0.75,0.75);
	this.replay_btn._off = true;
	new cjs.ButtonHelper(this.replay_btn, 0, 1, 2, false, new lib.replaybtn(), 3);

	this.timeline.addTween(cjs.Tween.get(this.replay_btn).wait(125).to({_off:false},0).wait(1));

	// cta btn
	this.clickthru_btn = new lib.CTA_btn();
	this.clickthru_btn.setTransform(-0.3,0,1.393,0.214,0,0,0,-0.2,0);
	new cjs.ButtonHelper(this.clickthru_btn, 0, 1, 2, false, new lib.CTA_btn(), 3);

	this.timeline.addTween(cjs.Tween.get(this.clickthru_btn).wait(126));

	// border
	this.instance = new lib.border336x280();
	this.instance.setTransform(234.1,30);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(126));

	// head1
	this.instance_1 = new lib.head1("synched",0);
	this.instance_1.setTransform(-91,21);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(118).to({startPosition:0},0).to({x:-247},5).wait(3));

	// sub1
	this.instance_2 = new lib.sub1("synched",0);
	this.instance_2.setTransform(-487.9,1171,5,5,0,0,0,131.4,220.7);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(66).to({_off:false},0).to({scaleX:1,scaleY:1,x:40.4,y:267.7},5).wait(47).to({startPosition:0},0).to({x:-115.6},5).wait(3));

	// logo block
	this.instance_3 = new lib.LogoLockup_468x60();
	this.instance_3.setTransform(659.5,45,1,1,0,0,0,192.5,45);
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(118).to({_off:false},0).to({x:503.5},5).wait(3));

	// mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_0 = new cjs.Graphics().p("AuAIgIAAw/IcBAAIAAQ/g");
	var mask_graphics_118 = new cjs.Graphics().p("AuAIgIAAw/IcBAAIAAQ/g");
	var mask_graphics_119 = new cjs.Graphics().p("AuAIgIAAw/IcBAAIAAQ/g");
	var mask_graphics_120 = new cjs.Graphics().p("AuAIgIAAw/IcBAAIAAQ/g");
	var mask_graphics_121 = new cjs.Graphics().p("AuAIgIAAw/IcBAAIAAQ/g");
	var mask_graphics_122 = new cjs.Graphics().p("AuAIgIAAw/IcBAAIAAQ/g");
	var mask_graphics_123 = new cjs.Graphics().p("AuAIgIAAw/IcBAAIAAQ/g");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:mask_graphics_0,x:67.7,y:29.5}).wait(118).to({graphics:mask_graphics_118,x:67.6,y:29.5}).wait(1).to({graphics:mask_graphics_119,x:35.5,y:29.5}).wait(1).to({graphics:mask_graphics_120,x:3.5,y:29.5}).wait(1).to({graphics:mask_graphics_121,x:-28.7,y:29.5}).wait(1).to({graphics:mask_graphics_122,x:-60.8,y:29.5}).wait(1).to({graphics:mask_graphics_123,x:-92.8,y:29.5}).wait(1).to({graphics:null,x:0,y:0}).wait(2));

	// pic
	this.instance_4 = new lib.pic();
	this.instance_4.setTransform(-33.6,-7.1,0.378,0.378,0,0,0,-0.2,-0.2);

	this.instance_4.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(118).to({x:-194.1},5).to({_off:true},1).wait(2));

	// bkgd
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("EgkjAEsIAApXMBJHAAAIAAJXg");
	this.shape.setTransform(234,30);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(126));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(211.9,23,721.1,75.5);

})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{});
var lib, images, createjs, ss;