(function (lib, img, cjs, ss) {

var p; // shortcut to reference prototypes
lib.webFontTxtFilters = {}; 

// library properties:
lib.properties = {
	width: 336,
	height: 280,
	fps: 18,
	color: "#CCCCCC",
	opacity: 1.00,
	webfonts: {},
	manifest: [
		{src:"images/_336x280womanbar.jpg", id:"_336x280womanbar"}
	]
};



lib.ssMetadata = [];


lib.webfontAvailable = function(family) { 
	lib.properties.webfonts[family] = true;
	var txtFilters = lib.webFontTxtFilters && lib.webFontTxtFilters[family] || [];
	for(var f = 0; f < txtFilters.length; ++f) {
		txtFilters[f].updateCache();
	}
};
// symbols:



(lib._336x280womanbar = function() {
	this.initialize(img._336x280womanbar);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,515,200);


(lib.TEC_logorev = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// TEC_logo-rev.ai
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AhBBcIAAjjIAJgDIAYgKQAUgKAKgIIADADIAABbIAvgCIABAbIgwgBIAACaQAAAJAGAGQAIAIAOgDQAQgDAPgPIAGACIAAABIgFAXIAAAAQAAADgMAKQgOAMgOAEQgMAEgKAAQhAAAAAhLg");
	this.shape.setTransform(42.1,-10.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("Ag+BcIAAiMIguAAIAAgaIAuACIAAg/IAJgDIAXgKQAVgKAJgIIAEADIAABbIBpAAIgBAYIhoAAIAACaQAAAJAGAGQAIAIANgDQARgDAPgPIAGACIAAABIgFAXIAAAAQgBADgLAKQgOAMgOAEQgMAEgMAAQg+AAAAhLg");
	this.shape_1.setTransform(25.5,-10.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AhUB5IAAjsIBHAAIgBAuIABABQAIgUASgQQAWgQAWAAQANAAAPAEIgBABQgVAVgLAgIgCADIgDgBQgHgCgHAAQgWAAgMAPQgMAOAAAUIAACGg");
	this.shape_2.setTransform(-14.8,-6.5);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgnBzQgZgKgPgTQgOgRgHgXQgGgVAAgYQgBgZAKgYQAKgZAQgPQAQgRAZgKQAagJAaAAQAdAAATAGQAVAHARAKQgIALgEANIgEALIgHAAQgJgPgOgIQgQgKgSAAIgBAAQgcAAgPAbQgPAbAAAvQAAAsATAZQARAYAkAAQAPAAAPgHQAOgIAHgIIAGAEIgGAPIgFAPQgKAIgRAGQgSAFgWABQgiAAgZgLg");
	this.shape_3.setTransform(166.8,-6.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AggB2QgXgHgPgOQgQgPgKgZQgKgYAAggQAAgeAJgYQAIgXAQgRQAOgPAWgIQAUgJAYABQAxAAAZAcQAaAcAAA1IAAAPIiMAAQAAATAEASQAEAQAIAPQAIANALAHQANAHARAAQAhAAAkgdIAGACIAAABIgEAXQgQASgdAKQgSAFgcABQgVAAgXgIgAApgVQgBglgIgVQgIgXgTAAQgJAAgIAHQgHAIgEALQgEALgDAPIgDAdIBKAAIAAAAg");
	this.shape_4.setTransform(3,-6.3);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AggB2QgXgHgPgOQgSgQgIgYQgKgYAAggQAAgeAJgYQAHgXAQgRQAPgPAVgIQAVgJAXABQAyAAAaAcQAaAdAAA0IAAAPIiNAAQAAATAEASQADAQAJAPQAIANALAHQANAHAQAAQAiAAAkgdIAGACIAAABIgEAXQgQASgdAKQgSAFgcABQgVAAgXgIgAAogVQAAglgJgVQgHgXgUAAQgJAAgHAHQgHAIgEALQgEALgDAPIgDAdIBJAAIAAAAg");
	this.shape_5.setTransform(-37.3,-6.3);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AggB2QgXgHgQgOQgQgPgKgZQgJgYgBggQABgeAIgYQAJgXAPgRQAOgPAWgIQAVgJAXABQAyAAAZAcQAaAdAAA0IAAAPIiMAAQAAATAEASQAFASAHANQAIANALAHQANAHARAAQAgAAAlgdIAGACIAAABIgEAXQgQASgdAKQgSAFgcABQgWAAgWgIgAApgVQgBglgIgVQgJgXgSAAQgJAAgIAHQgHAIgEALQgEALgDAPIgDAdIBKAAIAAAAg");
	this.shape_6.setTransform(-118.1,-6.3);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgPB2IgOAAIhEi8IgSgvIAUABIA4gBIA1CrIACAAIAehVIAdhWIAUACIAVgCIgTAsIgYA4IgaBAQgQAsgJAbg");
	this.shape_7.setTransform(-58.8,-6.3);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AheC7IAAl1IBXADIBAgBIAmgCQgCALAAAKIACAXIgggCIgggCIgdgCIgUgBIAABmIBWgEIAPApQg8gDgpAAIAACkIA5gBQAfgCAZgDIgBAWIAAAMIABAIg");
	this.shape_8.setTransform(-81.2,-13.1);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AggB3IAAjtIAPACIARABQAOAAATgDIAADtg");
	this.shape_9.setTransform(149,-6.3);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AggB3IAAjtIAOACIASABQANAAAUgDIAADtg");
	this.shape_10.setTransform(111.6,-6.3);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AASC6IgxABIAAl1IAOACIARABIASgBIAOgCIAAF1g");
	this.shape_11.setTransform(100,-13.1);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgaA2IAAhpIAPAAIAAAWQALgZAZABIABAAIAAAPIgBAAQgPgBgKAKQgLALAAARIAAA3g");
	this.shape_12.setTransform(36.7,22.9);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AAZA1IgZhVIgYBVIgPAAIgjhpIAQAAIAaBWIAZhWIAOAAIAaBWIAahWIAQAAIgjBpg");
	this.shape_13.setTransform(91.8,23);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgCBAQgFgGAAgNIAAhGIgTAAIAAgMIATAAIAAggIAMAAIAAAgIAWAAIAAAMIgWAAIAABEQAAAHACADQACADAGAAIAMAAIAAANIgNABQgNgBgDgFg");
	this.shape_14.setTransform(49.7,21.5);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AAdBJIAAhCQAAgdgaAAQgMAAgJAJQgJAKAAAOIAAA+IgPAAIAAiRIAPAAIAAA4QAEgIAJgGQAJgFAJAAQAUAAAKAKQAJAKAAAUIAABEg");
	this.shape_15.setTransform(60,20.9);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgpCzQgjgOgXgXQgXgXgNgjQgNgiAAglQABg1AQgoQAPgnAcgZQAbgZAkgLQAggLAoAAQAPAAANACIAbAFQARAFAJAEQALAEAJAGIgHAbQgCANgCAPIgHAAQgRgZgWgMQgSgLgcAAQgVAAgTAJQgSAKgRAVQgPASgLAgQgKAgAAApQAAApAKAeQALAeAQASQARATATAJQAWAIAUAAQANAAAMgDQANgEALgEQALgFALgIQALgHAIgKIAGAFIgGAWQgDAOgBAKQgpAWg8AAQgqAAghgNg");
	this.shape_16.setTransform(76.7,-12.9);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AghApQgNgPAAgaQAAgVALgPQANgTAWAAQAVAAALANQAPAPAAAbIAAAEIhPAAQABAQAIALQAJANAOAAQAaAAAGgbIABAAIAOAAIAAABQgJAmgmAAQgUAAgNgPgAAhgHQgCgOgHgLQgJgLgPABQgMgBgKALQgHALgDAOIBBAAIAAAAg");
	this.shape_17.setTransform(71.4,23);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AAcBJIAAhCQAAgdgaAAQgMAAgIAJQgJAKgBAOIAAA+IgOAAIAAiRIAOAAIAAA4QAKgTAWAAQAUAAAKAKQAJAKAAAUIAABEg");
	this.shape_18.setTransform(105.9,20.9);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AglAmQgMgQAAgWQAAgWAMgPQAOgSAXAAQAYAAAOASQAMAPAAAWQAAAWgMAQQgOASgYAAQgXAAgOgSgAgagdQgJANAAAQQAAARAJAMQAKAPAQAAQAQAAAKgPQAJgMAAgRQAAgQgJgNQgKgOgQABQgQgBgKAOg");
	this.shape_19.setTransform(117.2,23);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgIALIAAgVIARAAIAAAVg");
	this.shape_20.setTransform(180.5,27.1);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgqAOIAAhEIAPAAIAABEQAAAcAbAAQANAAAIgNQAHgMAAgQIAAg3IAPAAIAABpIgOAAIAAgRQgLAUgWABQgmAAAAgpg");
	this.shape_21.setTransform(173.2,23.1);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgGBJIAAiRIANAAIAACRg");
	this.shape_22.setTransform(125.3,20.9);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AghApQgNgPgBgaQAAgVALgPQANgTAXAAQAUAAAMANQAQAPAAAbIAAAEIhPAAQAAAQAIALQAJANAOAAQAZAAAHgbIAAAAIAPAAIAAABQgJAmgmAAQgVAAgMgPgAAggHQAAgOgJgLQgJgLgOABQgMgBgJALQgJALgBAOIA/AAIAAAAg");
	this.shape_23.setTransform(133.1,23);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AgbBJIgIgCIgBAAIAAgNIAKABQAHAAAEgDQACgDAEgJIAFgMIgrhoIAQAAIAgBWIAghWIAPAAIgvB5QgEAOgFAFQgFAEgMABg");
	this.shape_24.setTransform(150.7,24.9);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AglAmQgMgQAAgWQAAgWAMgPQAOgSAXAAQAYAAAOASQAMAPAAAWQAAAWgMAQQgOASgYAAQgXAAgOgSgAgagdQgJANAAAQQAAARAJAMQAKAPAQAAQARAAAKgPQAIgMAAgRQAAgQgIgNQgKgOgRABQgQgBgKAOg");
	this.shape_25.setTransform(161.6,23);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("ABaB5IgjAAIgPABIAAiNIgCgaQgBgLgEgGQgLgPgUAAQgTAAgLATQgKAUAAAiIAAB+IgQgBIgzABIAAjtIAQACIAQABIATgBIAQgCIAAAlIABABQANgVARgLQASgMAXAAQAgAAAUAWQAUAVAAAvIAACZIgQgBg");
	this.shape_26.setTransform(130.5,-6.6);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("ABeC6IgnAAIgQABIAAiPIAAgaQgCgLgFgGQgKgNgTAAQgVAAgKARQgKAUAAAiIAACAIgQgBIg3ABIAAl1IAQACIATABIAUgBIAQgCIAACtIABABQANgVASgLQAQgMAXAAQAlAAAUAWQAUAVAAAtIAACbIgQgBg");
	this.shape_27.setTransform(-142.5,-13.1);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AgjC6IAAlNIhbAGIAAgsIBZADICkgDIAAAWIAAAWIhYgGIAAFNg");
	this.shape_28.setTransform(-168.7,-13.2);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AgtBJIAAiRIBbAAIAAAOIhMAAIAAAyIBEAAIAAAMIhEAAIAABFg");
	this.shape_29.setTransform(15.1,20.9);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("AglAmQgMgQAAgWQAAgWAMgPQAOgSAXAAQAYAAAOASQAMAPAAAWQAAAWgMAQQgOASgYAAQgXAAgOgSgAgagdQgIANAAAQQAAARAIAMQAKAPAQAAQARAAAKgPQAJgMAAgRQAAgQgJgNQgKgOgRABQgQgBgKAOg");
	this.shape_30.setTransform(26.1,23);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("AgYAbQgLgMAAgPQAAgOALgLQALgMANAAQAPAAAKAMQALALAAAOQAAAQgLALQgKALgPAAQgNAAgLgLg");
	this.shape_31.setTransform(149.1,-26.8);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FFFFFF").s().p("AgYAbQgLgMAAgPQAAgOALgLQAKgMAOAAQAPAAAKAMQALALAAAOQAAAPgLAMQgKALgPAAQgOAAgKgLg");
	this.shape_32.setTransform(111.5,-26.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-181.4,-32.2,362.9,64.4);


(lib.sub1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// type
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#6B8A21").s().p("AAAAIQgIAAABgIIAAAAQgBgHAIAAIABAAQAIAAAAAHIAAAAQAAAIgIAAg");
	this.shape.setTransform(282.5,42.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#6B8A21").s().p("AAoA3QgFAAAAgFIAAg3QAAgJgCgHQgCgHgEgGQgFgFgGgCQgGgDgIAAQgFAAgGACQgGACgEADIgJAIIgGAKIAABFQAAAFgFAAIgCAAQgEAAAAgFIAAhmIADgBQAEAAABACQACADAAAGIAAAKIAHgJIAJgHIALgFQAGgBAFAAQAKAAAJADQAIAEAFAGQAGAGACAJQADAJAAALIAAA4QAAAFgFAAg");
	this.shape_1.setTransform(274.2,37.9);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#6B8A21").s().p("AgVA0QgKgEgIgIQgHgIgEgKQgEgKAAgMQAAgLAEgKQAEgLAHgHQAIgHAKgFQAKgEALAAQALAAALAEQAKAFAIAHQAHAIAEAKQAEALAAAKQAAAMgEAKQgEAKgHAIQgIAIgKAEQgLAEgLAAQgLAAgKgEgAgQgqQgIAEgHAGQgFAGgEAJQgDAJAAAIQAAAJADAJQAEAIAFAHQAHAGAIAEQAIADAIABQAJgBAJgDQAIgDAFgHQAHgGACgIQAEgJAAgKQAAgIgEgIQgCgKgHgGQgFgGgIgEQgJgEgJAAQgIAAgIAEg");
	this.shape_2.setTransform(261.5,38);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#6B8A21").s().p("AAABNQgEAAAAgGIAAhhQAAgGAEABIAAAAQAFgBAAAGIAABhQAAAGgFAAgAgGhEQAAgIAGABQAHgBAAAIQAAAIgHAAQgGAAAAgIg");
	this.shape_3.setTransform(252.9,35.8);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#6B8A21").s().p("AgWA1QgJgEgFgFQgGgGAAgDQAAgFAGgBQAGAIAJAFQAFADAFABQAHABAFAAQAHAAAGgBQAGgCAEgDQAEgCACgEQACgFAAgEQAAgFgCgEQgDgDgEgDQgGgDgRgEQgSgEgIgCQgGgDgDgGQgDgFAAgHQAAgIADgGQACgFAGgFQAFgEAIgCQAHgCAHAAQAMAAAKAEQAIADAGAFQAEAEAAAEQAAACgDACIgDABQgFgGgIgFQgJgFgMAAQgFAAgFACQgGABgEADQgEADgCAEQgCAEAAAEQAAAFACAEQADADAEACQAGAEAQADIAOADIANADQAGAEADAFQAEAGAAAHQAAAHgDAHQgDAFgGAEQgFAEgIADQgIACgKAAQgLAAgLgDg");
	this.shape_4.setTransform(245.5,38);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#6B8A21").s().p("AgWA1QgJgEgFgFQgGgGAAgDQAAgFAGgBQAGAIAJAFQAFADAFABQAHABAFAAQAHAAAGgBQAGgCAEgDQAEgCACgEQACgFAAgEQAAgFgCgEQgDgDgEgDQgGgDgRgEQgSgEgIgCQgGgDgDgGQgDgFAAgHQAAgIADgGQACgFAGgFQAFgEAIgCQAHgCAHAAQAMAAAKAEQAIADAGAFQAEAEAAAEQAAACgDACIgDABQgFgGgIgFQgJgFgMAAQgFAAgFACQgGABgEADQgEADgCAEQgCAEAAAEQAAAFACAEQADADAEACQAGAEAQADIAOADIANADQAGAEADAFQAEAGAAAHQAAAHgDAHQgDAFgGAEQgFAEgIADQgIACgKAAQgLAAgLgDg");
	this.shape_5.setTransform(235.4,38);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#6B8A21").s().p("AgSA0QgKgEgHgIQgIgHgEgLQgEgKAAgMQAAgKAEgLQAEgKAIgIQAHgIAKgDQAKgFAKAAQALAAAJAEQAJADAHAHQAGAIAEAKQAEAKAAALIAAABQAAACgFAAIhXAAQAAAKAEAJQADAHAGAHQAGAGAIAEQAIADAIAAQAIAAAHgCQAGgCAFgEQAIgFAFgKIADACQADABAAAEQAAAFgHAHQgFAFgKAEQgKAEgNAAQgKAAgLgEgAAogGQAAgJgDgIQgDgHgFgEQgFgGgHgCQgHgDgIgBQgHABgHADQgHACgGAGQgGAFgDAHQgEAHgBAJIBPAAIAAAAg");
	this.shape_6.setTransform(224.4,38);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#6B8A21").s().p("AgWA1QgJgEgFgFQgGgGAAgDQAAgFAGgBQAGAIAJAFQAFADAFABQAHABAFAAQAHAAAGgBQAGgCAEgDQAEgCACgEQACgFAAgEQAAgFgCgEQgDgDgEgDQgGgDgRgEQgSgEgIgCQgGgDgDgGQgDgFAAgHQAAgIADgGQACgFAGgFQAFgEAIgCQAHgCAHAAQAMAAAKAEQAIADAGAFQAEAEAAAEQAAACgDACIgDABQgFgGgIgFQgJgFgMAAQgFAAgFACQgGABgEADQgEADgCAEQgCAEAAAEQAAAFACAEQADADAEACQAGAEAQADIAOADIANADQAGAEADAFQAEAGAAAHQAAAHgDAHQgDAFgGAEQgFAEgIADQgIACgKAAQgLAAgLgDg");
	this.shape_7.setTransform(213.2,38);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#6B8A21").s().p("AgVA0QgKgEgHgIQgIgIgEgKQgEgKAAgMQAAgLAEgKQAEgLAIgHQAHgHAKgFQAKgEALAAQALAAALAEQAKAFAIAHQAHAIAEAKQAEALAAAKQAAAMgEAKQgEAKgHAIQgIAIgKAEQgLAEgLAAQgLAAgKgEgAgQgqQgIAEgGAGQgHAGgCAJQgEAJAAAIQAAAJAEAJQACAIAHAHQAGAGAIAEQAIADAIABQAJgBAIgDQAIgDAHgHQAGgGADgIQADgJAAgKQAAgIgDgIQgDgKgGgGQgHgGgIgEQgIgEgJAAQgIAAgIAEg");
	this.shape_8.setTransform(197.8,38);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#6B8A21").s().p("AgHBPQgGAAAAgFIAAhdIgSAAQgFAAAAgEIAAgBQAAgFAFAAIASAAIAAgLQAAgKACgHQADgHAEgEQADgFAEgDQAFgCAIAAQAGAAAFACQAEABADADQADADAAADQAAAAAAABQAAABAAAAQgBABAAAAQAAAAAAABIgDABQgCgDgFgCQgFgCgFAAQgFAAgEABQgEACgBAEQgCADgBAGIgBAMIAAALIAXAAQAFAAAAAFIAAABQAAAEgFAAIgXAAIAABdQABAFgFAAg");
	this.shape_9.setTransform(188.2,35.5);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#6B8A21").s().p("AAoA3QgFAAAAgFIAAg3QAAgJgCgHQgCgHgEgGQgFgFgGgCQgGgDgIAAQgFAAgGACQgGACgEADIgJAIIgGAKIAABFQAAAFgFAAIgCAAQgEAAAAgFIAAhmIADgBQAEAAABACQACADAAAGIAAAKIAHgJIAJgHIALgFQAGgBAFAAQAKAAAJADQAIAEAFAGQAGAGACAJQADAJAAALIAAA4QAAAFgFAAg");
	this.shape_10.setTransform(178.1,37.9);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#6B8A21").s().p("AAABNQgEAAAAgGIAAhhQAAgGAEABIAAAAQAFgBAAAGIAABhQAAAGgFAAgAgGhEQAAgIAGABQAHgBAAAIQAAAIgHAAQgGAAAAgIg");
	this.shape_11.setTransform(169.6,35.8);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#6B8A21").s().p("AgSA0QgKgEgHgIQgIgHgEgLQgEgKAAgMQAAgKAEgLQAEgKAIgIQAHgIAKgDQAKgFAKAAQALAAAJAEQAJADAHAHQAGAIAEAKQAEAKAAALIAAABQAAACgFAAIhXAAQAAAKAEAJQADAHAGAHQAGAGAIAEQAIADAIAAQAIAAAHgCQAGgCAFgEQAIgFAFgKIADACQADABAAAEQAAAFgHAHQgFAFgKAEQgKAEgNAAQgKAAgLgEgAAogGQAAgJgDgIQgDgHgFgEQgFgGgHgCQgHgDgIgBQgHABgHADQgHACgGAGQgGAFgDAHQgEAHgBAJIBPAAIAAAAg");
	this.shape_12.setTransform(157.4,38);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#6B8A21").s().p("AgSA0QgKgEgHgIQgIgHgEgLQgEgKAAgMQAAgKAEgLQAEgKAIgIQAHgIAKgDQAKgFAKAAQALAAAJAEQAJADAHAHQAGAIAEAKQAEAKAAALIAAABQAAACgFAAIhXAAQAAAKAEAJQADAHAGAHQAGAGAIAEQAIADAIAAQAIAAAHgCQAGgCAFgEQAIgFAFgKIADACQADABAAAEQAAAFgHAHQgFAFgKAEQgKAEgNAAQgKAAgLgEgAAogGQAAgJgDgIQgDgHgFgEQgFgGgHgCQgHgDgIgBQgHABgHADQgHACgGAGQgGAFgDAHQgEAHgBAJIBPAAIAAAAg");
	this.shape_13.setTransform(145.3,38);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#6B8A21").s().p("AgWA3QgEAAAAgFIAAhmIADgBQAEAAABACQACADAAAGIAAAOIAEgMQAEgFADgDQAEgDADgCQAEgBAGAAQAHAAAEACQAEADABAEQAAABgBAAQAAABAAAAQAAABAAAAQgBABAAAAIgCACQgFgFgIAAQgHAAgEAEQgFADgDAHQgEAGgCAJQgCAJABAJIAAAvQAAAFgGAAg");
	this.shape_14.setTransform(136.2,37.9);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#6B8A21").s().p("AgIBPQgEAAAAgFIAAhdIgSAAQgGAAAAgEIAAgBQAAgFAGAAIASAAIAAgLQAAgKABgHQADgHAEgEQAEgFADgDQAGgCAHAAQAGAAAFACQAEABADADQADADAAADQAAAAAAABQAAABAAAAQgBABAAAAQAAAAgBABIgCABQgCgDgFgCQgFgCgFAAQgFAAgEABQgDACgCAEQgCADgBAGIgBAMIAAALIAXAAQAFAAAAAFIAAABQAAAEgFAAIgXAAIAABdQAAAFgEAAg");
	this.shape_15.setTransform(128.6,35.5);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#6B8A21").s().p("AgXA2QgGgCgFgEQgFgEgDgGQgCgFAAgGQgBgKAFgGQAEgHALgEQAJgCAPgDQAMgCAVAAIADAAIAAgGQAAgHgDgGQgCgGgEgFQgFgEgGgCQgGgCgIAAQgFAAgGACQgFABgFADQgJAFgFAKQgGgBAAgGQAAgFAGgFQAGgGAIgEQALgEALAAQAKAAAIADQAIADAGAFQAFAGAEAHQADAJAAAJIAABDIgFABQgDAAgBgCQgCgDAAgGIAAgMQgDAGgEAEQgEAEgGADIgNAGIgLABQgJAAgIgCgAABACQgKABgIADQgIAEgFAEQgDAGAAAHQAAAEABAEQACAEAEACIAJAFQAFABAGAAQAHAAAIgDQAHgDAGgEQAGgGADgGQAEgHAAgHIAAgLIgEAAIgeACg");
	this.shape_16.setTransform(114.6,38);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#6B8A21").s().p("AgVA3QgGAAAAgFIAAhmIAEgBQADAAACACQACADAAAGIAAAOIAFgMQACgFAFgDQADgDADgCQAEgBAGAAQAHAAAEACQAFADgBAEQAAABAAAAQAAABAAAAQAAABAAAAQgBABAAAAIgCACQgFgFgIAAQgHAAgEAEQgFADgEAHQgDAGgCAJQgCAJAAAJIAAAvQAAAFgEAAg");
	this.shape_17.setTransform(102,37.9);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#6B8A21").s().p("AgVA0QgKgEgHgIQgIgIgEgKQgEgKAAgMQAAgLAEgKQAEgLAIgHQAHgHAKgFQAKgEALAAQAMAAAKAEQAKAFAIAHQAHAIAEAKQAEALAAAKQAAAMgEAKQgEAKgHAIQgIAIgKAEQgKAEgMAAQgLAAgKgEgAgQgqQgIAEgGAGQgHAGgCAJQgEAJAAAIQAAAJAEAJQACAIAHAHQAGAGAIAEQAIADAIABQAJgBAIgDQAIgDAHgHQAFgGAEgIQADgJAAgKQAAgIgDgIQgEgKgFgGQgHgGgIgEQgIgEgJAAQgIAAgIAEg");
	this.shape_18.setTransform(91.2,38);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#6B8A21").s().p("AgHBPQgGAAAAgFIAAhdIgSAAQgFAAAAgEIAAgBQAAgFAFAAIASAAIAAgLQAAgKACgHQADgHAEgEQADgFAEgDQAFgCAIAAQAGAAAFACQAFABACADQADADAAADQAAAAAAABQAAABAAAAQgBABAAAAQAAAAAAABIgDABQgCgDgFgCQgFgCgFAAQgFAAgDABQgFACgBAEQgCADgBAGIgBAMIAAALIAWAAQAGAAAAAFIAAABQAAAEgGAAIgWAAIAABdQABAFgFAAg");
	this.shape_19.setTransform(81.6,35.5);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#6B8A21").s().p("AgWA3QgEAAAAgFIAAhmIADgBQADAAACACQACADAAAGIAAAOIAEgMQAEgFADgDQAEgDADgCQAEgBAGAAQAGAAAFACQAEADAAAEQAAABAAAAQAAABAAAAQAAABAAAAQgBABAAAAIgCACQgFgFgIAAQgHAAgEAEQgFADgDAHQgEAGgCAJQgBAJgBAJIAAAvQABAFgGAAg");
	this.shape_20.setTransform(70.6,37.9);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#6B8A21").s().p("AgSA0QgKgEgHgIQgIgHgEgLQgEgKAAgMQAAgKAEgLQAEgKAIgIQAHgIAKgDQAKgFAKAAQALAAAJAEQAJADAHAHQAGAIAEAKQAEAKAAALIAAABQAAACgFAAIhXAAQAAAKAEAJQADAHAGAHQAGAGAIAEQAIADAIAAQAIAAAHgCQAGgCAFgEQAIgFAFgKIADACQADABAAAEQAAAFgHAHQgFAFgKAEQgKAEgNAAQgKAAgLgEgAAogGQAAgJgDgIQgDgHgFgEQgFgGgHgCQgHgDgIgBQgHABgHADQgHACgGAGQgGAFgDAHQgEAHgBAJIBPAAIAAAAg");
	this.shape_21.setTransform(60.2,38);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#6B8A21").s().p("AAABCQgEgCgEgEQgDgEgBgGQgCgHAAgIIAAhCIgOAAQgFAAAAgEIAAgBQAAgFAFAAIAOAAIAAgVQAAgFAEAAIACAAQAEAAABAFIAAAVIAdAAQAFAAAAAFIAAABQAAAEgFAAIgdAAIAABBQAAANADAGQADAGAKAAQAFAAAFgCQAEgDADgEIACABQABAAAAABQAAAAABABQAAAAAAABQAAABAAAAQAAAEgEADQgDADgEACQgFABgGAAQgHAAgFgCg");
	this.shape_22.setTransform(50.4,36.7);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#6B8A21").s().p("AgWA1QgJgEgFgFQgGgGAAgDQAAgFAGgBQAGAIAJAFQAFADAFABQAHABAFAAQAHAAAGgBQAGgCAEgDQAEgCACgEQACgFAAgEQAAgFgCgEQgDgDgEgDQgGgDgRgEQgSgEgIgCQgGgDgDgGQgDgFAAgHQAAgIADgGQACgFAGgFQAFgEAIgCQAHgCAHAAQAMAAAKAEQAIADAGAFQAEAEAAAEQAAACgDACIgDABQgFgGgIgFQgJgFgMAAQgFAAgFACQgGABgEADQgEADgCAEQgCAEAAAEQAAAFACAEQADADAEACQAGAEAQADIAOADIANADQAGAEADAFQAEAGAAAHQAAAHgDAHQgDAFgGAEQgFAEgIADQgIACgKAAQgLAAgLgDg");
	this.shape_23.setTransform(41.4,38);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#6B8A21").s().p("AAABNQgEAAAAgGIAAhhQAAgGAEABIAAAAQAFgBAAAGIAABhQAAAGgFAAgAgGhEQAAgIAGABQAHgBAAAIQAAAIgHAAQgGAAAAgIg");
	this.shape_24.setTransform(34.2,35.8);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#6B8A21").s().p("AgXBSQgJgCgHgDQgFgEgEgGQgDgFAAgHQAAgHADgFQACgFAGgEQAFgEAHgDIAOgEQgDgCgDgDQgCgDAAgEQAAgHAGgEQgGAAgFgDQgFgEgDgFQgEgEgCgGQgCgFAAgHQAAgIADgHQADgHAGgGQAHgFAHgDQAIgDAJAAQAFAAAIACQAHACAGAEIAKgOQAEgGAFACQAFABgBADIgSAUQAFAFADAGQACAHAAAHQAAAIgDAHQgDAHgGAFQgGAGgHABQgJADgHAAIgHgBQgFADAAAEQAAAGAJADIAVAFIAMAEIALAGQAGADACAFQADAFAAAGQAAAIgEAGQgDAGgHAEQgIAEgKACQgJACgLAAQgNAAgKgCgAgPAgIgNAFQgFADgEAFQgDAEAAAGQAAAFACADQADAEAFADQAFACAIACQAHABAKAAQAIAAAIgBQAIgCAFgDQAGgCADgFQADgEAAgFQAAgEgCgEIgGgFQgGgEgNgDIgOgEQgIABgHACgAgNg+QgFACgFAEQgEAEgDAGQgCAFAAAHQAAAHACAFQADAGAEAEQAFADAFADQAGACAHAAQAFAAAGgCIAKgGQAFgEACgGQACgFAAgHQAAgHgCgFQgCgGgFgEQgEgEgGgCQgGgCgFAAQgHAAgGACg");
	this.shape_25.setTransform(26.8,39.8);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#6B8A21").s().p("AgSA0QgKgEgHgIQgIgHgEgLQgEgKAAgMQAAgKAEgLQAEgKAIgIQAHgIAKgDQAKgFAKAAQALAAAJAEQAJADAHAHQAGAIAEAKQAEAKAAALIAAABQAAACgFAAIhXAAQAAAKAEAJQADAHAGAHQAGAGAIAEQAIADAIAAQAIAAAHgCQAGgCAFgEQAIgFAFgKIADACQADABAAAEQAAAFgHAHQgFAFgKAEQgKAEgNAAQgKAAgLgEgAAogGQAAgJgDgIQgDgHgFgEQgFgGgHgCQgHgDgIgBQgHABgHADQgHACgGAGQgGAFgDAHQgEAHgBAJIBPAAIAAAAg");
	this.shape_26.setTransform(15.6,38);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#6B8A21").s().p("AgVA3QgGAAAAgFIAAhmIAEgBQADAAACACQACADAAAGIAAAOIAFgMQACgFAEgDQAEgDADgCQAFgBAFAAQAGAAAFACQAFADgBAEQAAABAAAAQAAABAAAAQAAABAAAAQgBABAAAAIgCACQgFgFgIAAQgHAAgEAEQgFADgDAHQgEAGgCAJQgBAJgBAJIAAAvQAAAFgEAAg");
	this.shape_27.setTransform(6.4,37.9);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#6B8A21").s().p("AgWA3QgEAAgBgFIAAhmIAEgBQAEAAABACQACADAAAGIAAAOIAEgMQAEgFAEgDQADgDADgCQAFgBAFAAQAGAAAFACQAFADAAAEQAAAAgBABQAAABAAAAQAAABAAAAQgBABAAAAIgCACQgFgFgIAAQgHAAgEAEQgFADgEAHQgDAGgCAJQgBAJAAAJIAAAvQgBAFgFAAg");
	this.shape_28.setTransform(272.8,14.9);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#6B8A21").s().p("AgVA0QgKgEgIgIQgHgHgEgLQgEgLAAgLQAAgLAEgKQAEgKAHgIQAIgHAKgFQAKgEALAAQALAAALAEQAKAFAHAHQAIAIAEALQAEAKAAAKQAAAMgEALQgEAJgIAIQgHAIgKAEQgLAEgLAAQgLAAgKgEgAgQgqQgIADgGAHQgGAGgDAJQgEAIAAAJQAAAKAEAIQADAIAGAHQAGAHAIADQAIAEAIgBQAJABAJgEQAIgEAFgFQAHgHACgJQAEgIAAgKQAAgIgEgJQgCgJgHgGQgFgGgIgEQgJgDgJAAQgIAAgIADg");
	this.shape_29.setTransform(262,15);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#6B8A21").s().p("AgSA0QgKgEgHgHQgIgIgEgKQgEgLAAgMQAAgKAEgKQAEgLAIgIQAHgHAKgFQAKgEAKAAQALAAAJADQAJAFAHAGQAGAIAEAJQAEAKAAAMIAAABQAAACgFAAIhXAAQAAAKAEAIQADAJAGAGQAGAGAIAEQAIACAIAAQAIAAAHgCQAGgBAFgDQAIgGAFgJIADAAQADADAAADQAAAFgHAHQgFAGgKADQgKAEgNAAQgKAAgLgEgAAogHQAAgIgDgIQgDgHgFgFQgFgFgHgDQgHgCgIAAQgHAAgHACQgHADgGAFQgGAGgDAHQgEAHgBAIIBPAAIAAAAg");
	this.shape_30.setTransform(245.6,15);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#6B8A21").s().p("AgWA3QgEAAAAgFIAAhmIADgBQAEAAABACQACADAAAGIAAAOIAEgMQADgFAFgDQADgDADgCQAFgBAFAAQAGAAAFACQAEADABAEQAAAAgBABQAAABAAAAQAAABAAAAQgBABAAAAIgCACQgFgFgIAAQgHAAgEAEQgFADgDAHQgEAGgCAJQgCAJABAJIAAAvQAAAFgGAAg");
	this.shape_31.setTransform(236.4,14.9);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#6B8A21").s().p("AgVA0QgKgEgIgIQgHgHgEgLQgEgLAAgLQAAgLAEgKQAEgKAHgIQAIgHAKgFQAKgEALAAQAMAAAKAEQAKAFAHAHQAIAIAEALQAEAKAAAKQAAAMgEALQgEAJgIAIQgHAIgKAEQgKAEgMAAQgLAAgKgEgAgQgqQgIADgHAHQgFAGgEAJQgDAIAAAJQAAAKADAIQAEAIAFAHQAHAHAIADQAIAEAIgBQAJABAJgEQAHgEAGgFQAHgHACgJQAEgIAAgKQAAgIgEgJQgCgJgHgGQgGgGgHgEQgJgDgJAAQgIAAgIADg");
	this.shape_32.setTransform(225.6,15);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#6B8A21").s().p("ABNA3QgGAAAAgFIAAg5QAAgJgCgHQgBgHgFgEQgDgFgHgDQgFgCgIAAIgLACQgFABgFAEQgEADgEAFQgEAEgCAGIAABFQAAAFgFAAIAAAAQgEAAAAgFIAAg7QAAgIgCgHQgCgGgEgFQgEgEgGgDQgGgCgIAAIgKACQgFABgFAEQgFADgDAFQgEAEgDAGIAABFQAAAFgEAAIgCAAQgEAAgBgFIAAhmIAEgBQADAAACACQACADAAAGIAAAKIAHgJIAIgHQAFgDAGgCIAKgBQAIAAAGABQAGACAFAEQAFADADAFQACAEABAGQADgGADgEQAEgFAFgDQAFgEAGgCQAGgBAIAAQAKAAAIADQAHADAFAGQAGAGACAJQADAIAAAMIAAA5QAAAFgEAAg");
	this.shape_33.setTransform(209.5,14.9);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#6B8A21").s().p("AAoA3QgFAAAAgFIAAg3QAAgJgCgHQgCgHgEgGQgFgFgGgCQgGgDgIAAQgFAAgGACQgGACgEADIgJAIIgGAKIAABFQAAAFgFAAIgCAAQgEAAAAgFIAAhmIADgBQAEAAABACQACADAAAGIAAAKIAHgJIAJgHIALgFQAGgBAFAAQAKAAAJADQAIAEAFAGQAGAGACAJQADAJAAALIAAA4QAAAFgFAAg");
	this.shape_34.setTransform(189.4,14.9);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#6B8A21").s().p("AgWA3QgEAAgBgFIAAhmIAEgBQAEAAABACQACADAAAGIAAAOIAEgMQAEgFAEgDQADgDADgCQAFgBAFAAQAGAAAFACQAFADAAAEQAAAAgBABQAAABAAAAQAAABAAAAQgBABAAAAIgCACQgFgFgIAAQgHAAgEAEQgFADgEAHQgDAGgCAJQgBAJAAAJIAAAvQgBAFgFAAg");
	this.shape_35.setTransform(180.1,14.9);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#6B8A21").s().p("AgWA2QgIgCgFgEQgFgEgCgGQgDgFAAgHQAAgJAFgHQAFgGAJgEQAKgCAPgDQAMgCAVAAIACAAIAAgFQAAgJgCgGQgCgFgFgEQgEgEgGgDQgGgCgIAAQgFAAgGABQgGACgEADQgJAGgFAIQgGAAAAgFQAAgGAGgGQAGgFAIgEQALgEALAAQAKAAAIADQAIACAFAGQAHAFACAJQADAHABAKIAABCIgFABQgDAAgBgCQgDgCAAgGIAAgLQgCAEgEAFQgFAEgGAEIgMAEIgLACQgKAAgGgCgAABABQgKACgJAEQgHACgEAGQgEAFAAAGQAAAFACAEQACAEADADIAJADQAFACAGAAQAHAAAIgDQAIgDAFgFQAGgEADgHQAEgHgBgIIAAgKIgCAAIgfABg");
	this.shape_36.setTransform(169.6,15);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#6B8A21").s().p("AgSA0QgKgEgHgHQgIgIgEgKQgEgLAAgMQAAgKAEgKQAEgLAIgIQAHgHAKgFQAKgEAKAAQALAAAJADQAJAFAHAGQAGAIAEAJQAEAKAAAMIAAABQAAACgFAAIhXAAQAAAKAEAIQADAJAGAGQAGAGAIAEQAIACAIAAQAIAAAHgCQAGgBAFgDQAIgGAFgJIADAAQADADAAADQAAAFgHAHQgFAGgKADQgKAEgNAAQgKAAgLgEgAAogHQAAgIgDgIQgDgHgFgFQgFgFgHgDQgHgCgIAAQgHAAgHACQgHADgGAFQgGAGgDAHQgEAHgBAIIBPAAIAAAAg");
	this.shape_37.setTransform(158.2,15);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#6B8A21").s().p("AAABOQgEAAAAgFIAAiVIADgBQACAAACACQACADAAAGIAACLQAAAFgFAAg");
	this.shape_38.setTransform(149.9,12.6);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#6B8A21").s().p("AgVA0QgKgEgHgIQgIgHgEgLQgEgLAAgLQAAgLAEgKQAEgKAIgIQAHgHAKgFQALgEAKAAQALAAALAEQAKAFAHAHQAIAIAEALQAEAKAAAKQAAAMgEALQgEAJgIAIQgHAIgKAEQgLAEgLAAQgKAAgLgEgAgQgqQgIADgHAHQgFAGgEAJQgDAIAAAJQAAAKADAIQAEAIAFAHQAHAHAIADQAIAEAIgBQAJABAJgEQAIgEAGgFQAFgHAEgJQADgIAAgKQAAgIgDgJQgEgJgFgGQgGgGgIgEQgJgDgJAAQgIAAgIADg");
	this.shape_39.setTransform(137.3,15);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#6B8A21").s().p("AAABCQgEgCgEgEQgDgEgBgGQgCgHgBgIIAAhCIgNAAQgFAAAAgEIAAgBQAAgFAFAAIANAAIAAgVQABgFAEAAIACAAQAFAAAAAFIAAAVIAdAAQAFAAABAFIAAABQgBAEgFAAIgdAAIAABBQAAANADAGQADAGAKAAQAFAAAFgCQAEgDADgEIACABQAAAAABABQAAAAAAABQABAAAAABQAAAAAAABQAAAEgEADQgCADgFACQgEABgHAAQgHAAgFgCg");
	this.shape_40.setTransform(127.1,13.7);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#6B8A21").s().p("AgrBKQgHAAAAgHIAAiFQAAgHAHAAIBXAAQAFAAAAAFIAAABQAAAEgFABIhTAAIAAA4IBAAAQAFABAAAEIAAABQAAADgFgBIhAAAIAAA+IBVAAQAFAAAAAEIAAABQAAAFgFAAg");
	this.shape_41.setTransform(113.3,13);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#6B8A21").s().p("AAjBGIg2g8IgSAAIAAA7QAAAFgFAAIgCAAQgFAAAAgFIAAiHQAAgHAHAAIAoAAQALAAAKADQAKACAHAGQAHAFADAIQAEAIAAAKQAAALgEAHQgDAIgHAFQgGAEgKADQgJADgLAAIgEAAIA1A7QAAAAAAAAQAAABAAAAQAAABAAAAQgBABAAAAQgDACgDAAQgDAAgEgEgAglAAIAlAAQAIAAAHAAQAIgCAFgFQAFgEACgGQADgGAAgHQAAgIgDgGQgCgGgFgEQgGgFgHgCQgIgCgIAAIgkAAg");
	this.shape_42.setTransform(100.3,13);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#6B8A21").s().p("AgrBKQgHAAAAgHIAAiFQAAgHAHAAIBXAAQAFAAAAAFIAAABQAAAEgFABIhTAAIAAA4IBAAAQAFABAAAEIAAABQAAADgFgBIhAAAIAAA+IBVAAQAFAAAAAEIAAABQAAAFgFAAg");
	this.shape_43.setTransform(87.5,13);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#6B8A21").s().p("AA0BKQgFAAAAgEIAAhBIhdAAIAABBQAAAEgFAAIgCAAQgFAAAAgEIAAiKQAAgGAFABIACAAQAFgBAAAGIAABAIBdAAIAAhAQAAgGAFABIACAAQAFgBAAAGIAACKQAAAEgFAAg");
	this.shape_44.setTransform(72.8,13);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#6B8A21").s().p("AAjBIIhHhIIAABFQAAAFgFAAIgBAAQgFAAAAgFIAAiJQAAgGAFAAIABAAQAFAAAAAGIAABCIBFhEQAFgFAEACQAEABAAAEIhFBDIBHBFQAAAEgEACIgDABQgDAAgDgDg");
	this.shape_45.setTransform(55.6,13);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#6B8A21").s().p("AgHBLQgHgBgHgDQgGgDgHgEQgFgEgFgFIgJgLIgGgOQgDgGgBgIIgBgQQgBgGACgJIAEgOQADgHADgGQAEgHAFgEIALgJQAFgFAIgDIANgDQAHgCAHAAQAMAAARAFQALAFAIAHQAIAIAAAHQAAADgDACIgEABQgDgGgEgFQgGgGgGgDQgHgEgHgCQgHgCgJAAIgLABIgMAEQgLAEgJAKQgIAJgEAMQgEARgBAIQACASADAJQAEAMAIAIIAKAIIAKAHIANADIAKABQALAAAIgCQAIgDAHgFQAGgDAFgHQADgFADgGQAHABAAAFQgDALgHAHQgHAIgMAEQgRAFgMAAIgOgBg");
	this.shape_46.setTransform(41.5,13);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("#6B8A21").s().p("AAABKQgEAAAAgEIAAiKQAAgGAEABIAAAAQAFgBAAAGIAACKQAAAEgFAAg");
	this.shape_47.setTransform(31.2,13);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("#6B8A21").s().p("AgkBKQgIAAAAgHIAAiHQAAgFAGAAIABAAQAFAAAAAFIAACEIBHAAQAFAAAAAFIAAAAQAAAFgFAAg");
	this.shape_48.setTransform(23.4,12.9);

	this.shape_49 = new cjs.Shape();
	this.shape_49.graphics.f("#6B8A21").s().p("AgGBLQgIgBgHgDQgHgDgFgEQgGgEgFgFIgJgLIgGgOQgDgGgBgIIgCgQQAAgGACgJIAEgOQACgHAFgGQADgHAFgEIALgJQAGgFAGgDIAPgDQAGgCAIAAQALAAASAFQALAFAHAHQAIAIAAAHQAAADgEACIgDABQgDgGgFgFQgEgGgHgDQgHgEgHgCQgIgCgIAAIgLABIgMAEQgLAEgIAKQgJAJgEAMQgFARABAIQABASADAJQAEAMAJAIIAJAIIAKAHIAMADIAMABQAJAAAJgCQAIgDAHgFQAGgDAFgHQADgFACgGQAJABgBAFQgDALgHAHQgHAIgLAEQgSAFgMAAIgNgBg");
	this.shape_49.setTransform(9.7,13);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_49},{t:this.shape_48},{t:this.shape_47},{t:this.shape_46},{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,294,50);


(lib.replaybtn = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#666666").s().p("Ak9BwIAAjgIJ6AAIAADgg");
	this.shape.setTransform(9.1,9.8,0.438,1.268,0,0,0,-0.2,0);
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(3).to({_off:false},0).wait(1));

	// Layer 2
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#BFBFBF").s().p("AgEBGQghgDgWgXQgXgZAAgfQAAgQAGgQQAOggAfgNQARgGAOgBQAiAAAYAZQAZAYAAAjIgUAAQAAgbgTgSQgSgTgaAAQgZAAgSATQgTATAAAaQAAAXARASQAQASAZACIgNgcIBVAnIhWAlg");
	this.shape_1.setTransform(8.4,9.7);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#666666").s().p("AgEBGQghgDgWgXQgXgZAAgfQAAgQAGgQQAOggAfgNQARgGAOgBQAiAAAYAZQAZAYAAAjIgUAAQAAgbgTgSQgSgTgaAAQgZAAgSATQgTATAAAaQAAAXARASQAQASAZACIgNgcIBVAnIhWAlg");
	this.shape_2.setTransform(8.4,9.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AgEBGQghgDgWgXQgXgZAAgfQAAgQAGgQQAOggAfgNQARgGAOgBQAiAAAYAZQAZAYAAAjIgUAAQAAgbgTgSQgSgTgaAAQgZAAgSATQgTATAAAaQAAAXARASQAQASAZACIgNgcIBVAnIhWAlg");
	this.shape_3.setTransform(8.4,9.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1}]}).to({state:[{t:this.shape_2}]},1).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_3}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,16.7,19.4);


(lib.pic = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib._336x280womanbar();

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,515,200);


(lib.logoblock = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// bkgd
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#193670").s().p("A9jHCIAArkQAAiUCIgKIAAgBMA23AAAIAAABQCIAKAACUIAALkg");
	this.shape.setTransform(-37.7,45);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-227,0,378.6,90);


(lib.head1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#193670").s().p("AAAAJQgIAAgBgJIAAAAQABgJAIAAIAAAAQAKAAgBAJIAAAAQABAJgKAAg");
	this.shape.setTransform(208,47.9);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#193670").s().p("AgZA7QgKgEgHgFQgFgGgBgFQABgFAGgCQAHAKAJAFQAGADAGABQAIACAGAAQAIAAAHgCIALgEQAFgEACgEQACgEAAgFQAAgHgCgEQgDgEgFgCQgHgEgTgEQgVgFgJgDQgGgDgEgGQgEgHAAgIQAAgIADgGQAEgHAGgFQAGgFAJgCQAIgCAJgBQANAAALAFQAJADAGAGQAEAFABAEQAAADgDACIgEABQgFgHgKgGQgKgFgMAAQgHAAgGACQgGACgFACQgEADgDAFQgCAEAAAFQAAAGADAEQACAEAFADQAHADASAFIAQADQAJABAGADQAGAEAEAGQAFAGgBAIQABAIgEAHQgEAGgFAFQgHAFgJADQgJACgKAAQgOABgMgFg");
	this.shape_1.setTransform(199.7,42.6);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#193670").s().p("AAtA/QgFAAAAgGIAAg/QAAgKgCgIQgDgJgFgFQgEgGgIgDQgHgDgIAAQgGAAgHACQgHACgFAEQgGADgEAGQgEAFgDAGIAABPQAAAGgGAAIgBAAQgGAAAAgGIAAh0IAFgBQADAAADACQACADAAAHIAAAMIAHgKQAEgFAGgEIAMgFQAIgCAFAAQAMAAAJAEQAKAEAGAHQAGAHADALQAEAKgBAMIAABAQABAGgGAAg");
	this.shape_2.setTransform(187.1,42.5);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#193670").s().p("AgYA7QgLgFgIgJQgJgIgFgMQgEgMAAgNQAAgMAEgMQAFgLAJgKQAIgIALgEQAMgGAMAAQANAAAMAGQALAEAJAJQAIAIAFANQAEALAAAMQAAAOgEALQgFAMgIAIQgJAJgLAFQgMAEgNAAQgMAAgMgEgAgSgvQgJAEgHAGQgHAIgEAJQgEALAAAJQAAAKAEALQAEAJAHAIQAHAGAJAFQAJADAJAAQAKAAAKgDQAJgEAHgHQAHgIADgJQAEgKAAgLQAAgJgEgKQgDgKgHgHQgHgIgJgDQgJgEgLgBQgJABgJAEg");
	this.shape_3.setTransform(172.7,42.6);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#193670").s().p("AAABXQgFAAAAgGIAAhvQAAgGAFAAIAAAAQAFAAABAGIAABvQgBAGgFAAgAgHhNQAAgJAHAAQAIAAAAAJQAAAIgIAAQgHAAAAgIg");
	this.shape_4.setTransform(163,40.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#193670").s().p("AAABLQgEgCgFgFQgEgFgBgHQgCgHAAgKIAAhKIgPAAQgHAAAAgFIAAgBQAAgFAHAAIAPAAIAAgYQgBgGAGAAIABAAQAGAAAAAGIAAAYIAiAAQAFAAABAFIAAABQgBAFgFAAIgiAAIAABJQAAAPAEAHQADAHALAAQAHAAAFgDQAFgDADgFIADABQACACAAADQgBAEgEAEQgDADgFACQgFACgHAAQgJAAgFgCg");
	this.shape_5.setTransform(156.2,41.2);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#193670").s().p("Ag1BXQgFAAAAgGIAAikIAEgCQAEAAACADQACADAAAHIAAANIAIgLQAFgFAGgEQAHgDAHgCQAHgCAHAAQAMAAALAEQAKAFAIAIQAIAJAFALQAEAMAAAOQAAAPgEAKQgEALgJAJQgIAJgKAEQgLAFgNAAQgHAAgIgCQgIgDgGgEQgGgDgEgFQgEgFgDgGIAABFQAAAGgFAAgAgPhJQgHACgGAFQgGAEgFAGQgEAHgDAHIAAAcQAAAKAEAGQADAIAHAGQAGAGAJADQAIAEAJAAQAKAAAIgEQAJgEAHgHQAGgHADgIQAEgKAAgMQAAgLgEgKQgDgJgHgHQgGgIgJgDQgJgEgJAAQgHAAgIACg");
	this.shape_6.setTransform(144.9,45);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#193670").s().p("AgYA7QgLgFgIgJQgJgIgFgMQgEgMAAgNQAAgMAEgMQAFgLAJgKQAIgIALgEQAMgGAMAAQANAAAMAGQALAEAJAJQAIAIAFANQAEALAAAMQAAAOgEALQgFAMgIAIQgJAJgLAFQgMAEgNAAQgMAAgMgEgAgSgvQgJAEgHAGQgHAIgEAJQgEALAAAJQAAAKAEALQAEAJAHAIQAHAGAJAFQAJADAJAAQAKAAAKgDQAJgEAHgHQAHgIADgJQAEgKAAgLQAAgJgEgKQgDgKgHgHQgHgIgJgDQgJgEgLgBQgJABgJAEg");
	this.shape_7.setTransform(129.9,42.6);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#193670").s().p("AgUA7QgMgEgIgKQgJgIgEgMQgFgMABgNQgBgMAFgLQAFgNAIgIQAJgJALgEQALgGALAAQANABAKAEQAKAEAIAIQAHAIAEALQAFALAAAOIAAABQgBACgFAAIhiAAQAAAMAEAJQADAJAIAIQAGAGAJAEQAKAEAJgBQAJAAAIgBQAGgDAGgDQAJgHAGgLIADACQAEACAAAEQAAAFgIAJQgGAGgLAEQgMAEgOAAQgMABgMgFgAAtgIQAAgJgDgJQgDgHgGgGQgGgHgIgCQgIgDgJgBQgHABgJADQgIADgGAGQgHAGgEAIQgEAIgCAJIBaAAIAAAAg");
	this.shape_8.setTransform(111.4,42.6);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#193670").s().p("AgaBdQgKgCgIgEQgHgEgDgGQgEgHAAgIQAAgHAEgGQADgGAFgFQAGgEAIgDIAQgFQgFgCgBgDQgDgDAAgFQAAgIAGgEQgGgBgGgEQgFgEgEgFQgFgFgBgHQgDgGAAgHQAAgJAEgIQADgJAHgGQAGgGAKgDQAJgEAKAAQAGAAAJADQAHACAGAFIAMgQQAFgHAGACQAFABgBAEIgUAWQAGAGADAHQADAHAAAIQAAAJgEAIQgEAIgGAGQgHAHgJABQgJADgJAAIgIAAQgFACABAGQgBAGAKADIAXAHIAPAEIAMAGQAGAFADAFQAEAFAAAHQAAAJgFAHQgDAGgJAFQgIAFgLACQgMACgMAAQgOAAgLgCgAgRAkQgJACgGAEQgGAEgEAFQgEAFAAAGQAAAGADAEQADAEAGADQAGADAIACQAIABALAAQAKAAAJgBQAJgCAHgDQAFgDAEgFQADgFAAgGQAAgFgDgEQgCgDgEgDQgHgEgPgEIgPgEQgJABgIACgAgPhGQgGADgFAEQgFAFgDAGQgCAGAAAIQAAAHACAGQADAGAFAFQAFAEAGADQAHACAIAAQAGAAAGgCQAHgDAFgEQAEgFADgGQADgGAAgHQAAgIgDgGQgCgGgFgFQgFgEgGgDQgIgCgFAAQgIAAgHACg");
	this.shape_9.setTransform(98.8,44.6);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#193670").s().p("AgaA9QgIgDgFgEQgFgEgDgHQgEgFAAgIQABgLAFgHQAFgHALgFQAKgDASgCQAOgDAXgBIADAAIAAgFQAAgJgDgHQgCgHgFgEQgFgGgHgBQgHgDgJAAQgFAAgHACIgMAEQgKAHgFAKQgIgBABgGQgBgGAIgGQAGgGAKgEQAMgGAMAAQALAAAKAEQAJADAGAGQAHAGADAJQADAJABALIAABLQgBABgBAAQAAAAgBABQAAAAgBAAQAAAAgBAAQgDAAgCgDQgDgDAAgGIAAgOQgDAGgEAGQgGAFgGADQgGADgHACQgHACgIAAQgJAAgJgCgAABACQgMABgJAEQgJAEgFAFQgDAGAAAIQAAAFACAFQABAEAFADQAEADAGABQAFACAHAAQAIABAJgEQAIgDAHgGQAHgFADgIQAEgIAAgIIAAgMIgDAAIgjACg");
	this.shape_10.setTransform(86,42.6);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#193670").s().p("AAABLQgEgCgFgFQgDgFgCgHQgCgHgBgKIAAhKIgOAAQgHAAAAgFIAAgBQAAgFAHAAIAOAAIAAgYQAAgGAGAAIABAAQAGAAAAAGIAAAYIAiAAQAFAAAAAFIAAABQAAAFgFAAIgiAAIAABJQAAAPAEAHQAEAHAKAAQAHAAAFgDQAFgDADgFIADABQACACAAADQgBAEgEAEQgDADgFACQgGACgGAAQgIAAgGgCg");
	this.shape_11.setTransform(75.6,41.2);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#193670").s().p("AAtA/QgFAAAAgGIAAg/QAAgKgDgIQgCgJgFgFQgFgGgGgDQgIgDgJAAQgFAAgHACQgGACgHAEQgEADgFAGQgEAFgDAGIAABPQAAAGgFAAIgCAAQgFAAAAgGIAAh0IADgBQAFAAABACQACADAAAHIAAAMIAIgKQAEgFAGgEIANgFQAGgCAGAAQAMAAAKAEQAIAEAHAHQAGAHADALQADAKABAMIAABAQgBAGgFAAg");
	this.shape_12.setTransform(64.3,42.5);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#193670").s().p("AgZA9QgJgDgFgEQgGgEgDgHQgDgFAAgIQABgLAFgHQAFgHALgFQAKgDASgCQAOgDAYgBIACAAIAAgFQAAgJgCgHQgDgHgFgEQgFgGgGgBQgIgDgJAAQgFAAgHACIgMAEQgKAHgGAKQgGgBAAgGQAAgGAGgGQAIgGAJgEQAMgGAMAAQAMAAAJAEQAJADAGAGQAHAGADAJQAEAJAAALIAABLQgBABgBAAQAAAAgBABQAAAAgBAAQAAAAgBAAQgEAAgBgDQgDgDAAgGIAAgOQgDAGgFAGQgFAFgGADQgGADgHACQgHACgHAAQgLAAgHgCgAABACQgMABgJAEQgJAEgFAFQgDAGAAAIQAAAFACAFQABAEAEADQAFADAGABQAFACAIAAQAHABAJgEQAJgDAGgGQAHgFAEgIQADgIAAgIIAAgMIgDAAIgjACg");
	this.shape_13.setTransform(50.3,42.6);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#193670").s().p("AgIA5IgvhyQALgJAFANIAnBnIAohnQAGgNAKAJIgwByQgBAFgHAAQgFAAgDgFg");
	this.shape_14.setTransform(38.2,42.6);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#193670").s().p("AgXBUQgKgEgIgIQgIgJgFgMQgEgMAAgOQAAgOAEgLQAFgKAIgJQAIgJALgFQAKgEAMAAQAIAAAIACQAHACAGAEQAGADAFAGQAEAEADAGIAAhNQABAAAAAAQABAAAAgBQABAAAAAAQABAAAAAAQAEAAACACQACAEAAAGIAACdQAAAHgFAAIgBAAQgGAAAAgHIAAgTIgIALQgFAFgGADQgGAEgHACQgIACgHAAQgMAAgLgFgAgRgWQgJADgGAIQgHAHgDAHQgEAKAAAMQAAALAEAKQADAKAHAHQAGAIAJADQAJAEAIAAQAJAAAJgEQAJgCAGgHQAHgGADgIQAEgIAAgJIAAgdQgDgFgEgHQgFgFgFgFQgGgFgIgCQgHgCgJAAQgIAAgJAEg");
	this.shape_15.setTransform(24.4,40.1);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#193670").s().p("AA6BOIgVg1IhKAAIgUA1QgFALgKgIIBAigQACgEAGAAQAIAAABAEIBACgQgFADgDAAQgFAAgCgGgAAhAOIghhTIggBTIBBAAg");
	this.shape_16.setTransform(9.8,40.3);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#193670").s().p("AgUA7QgLgFgJgIQgIgJgFgMQgEgMAAgNQAAgLAEgMQAFgMAIgJQAIgJALgEQAMgFALgBQAMAAALAFQALAEAHAIQAHAIAFALQAEALAAANIAAACQgBACgFAAIhiAAQAAAMAEAJQADAJAIAIQAGAGAKAEQAIAEAKgBQAJAAAIgCQAGgCAGgDQAJgHAGgKIADABQAEACAAAEQAAAFgIAJQgGAFgLAEQgMAFgOABQgNAAgLgFgAAugIQgBgJgEgJQgDgIgFgFQgGgHgIgCQgHgDgKAAQgHAAgJADQgIADgHAGQgGAGgEAIQgEAIgCAJIBbAAIAAAAg");
	this.shape_17.setTransform(285.7,16.6);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#193670").s().p("AgZA/QgFAAAAgGIAAh0IAEgBQAEAAACACQACADAAAHIAAAQQACgIADgFQADgGAFgEQAEgDADgCQAFgCAHAAQAHAAAFADQAFADAAAFQAAADgCACIgCABQgFgFgJAAQgJAAgEAEQgGAEgEAHQgEAHgCALQgCAKAAAKIAAA2QAAAGgFAAg");
	this.shape_18.setTransform(275.3,16.5);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#193670").s().p("AgZA9QgJgCgFgEQgFgFgEgHQgDgFAAgIQABgKAFgIQAFgHALgFQALgDAQgCQAPgDAYgBIACAAIAAgFQAAgJgCgHQgDgHgFgEQgFgGgGgBQgIgDgJAAQgGAAgGACIgMAEQgKAHgGAKQgGgBAAgGQAAgGAGgGQAIgHAJgDQALgFANgBQALAAAKAEQAJADAGAGQAGAGAEAJQAEAJAAALIAABLQgBABgBAAQAAAAgBABQAAAAgBAAQAAAAgBAAQgDAAgDgDQgCgCAAgHIAAgNQgDAFgFAGQgFAEgGAEQgGADgHACQgHACgHABQgLAAgHgDgAABACQgMACgJADQgJAEgEAFQgEAGgBAIQABAFACAFQACAEADADQAFADAFABQAGACAIAAQAHAAAJgDQAJgDAGgGQAHgFAEgIQADgIAAgIIAAgMIgDAAIgjACg");
	this.shape_19.setTransform(263.5,16.6);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#193670").s().p("AgSA6QgMgEgIgIQgIgJgGgMQgEgMAAgNQAAgMAEgMQAGgMAIgJQAIgIAMgEQAMgFALgBQAOABAMAFQAJADAHAHQAKAKAAAHQAAAEgEACIgEABQgDgGgDgEQgDgGgGgEQgGgEgGgCQgIgCgJAAQgJAAgKADQgIAFgHAGQgHAIgDAJQgFALAAAJQAAAKAFALQADAJAHAIQAHAHAIAEQAKADAJAAQAJAAAIgCQAGgCAGgEQAHgGAIgOQAIAAAAAHQgDAKgHAHQgHAHgJAEQgMAFgOAAQgLgBgMgFg");
	this.shape_20.setTransform(250.8,16.6);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#193670").s().p("AAABXQgEAAgBgGIAAhvQABgGAEAAIAAAAQAGAAAAAGIAABvQAAAGgGAAgAgHhNQAAgJAHAAQAIAAAAAJQAAAIgIAAQgHAAAAgIg");
	this.shape_21.setTransform(241.6,14.1);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#193670").s().p("AgXBVQgKgFgIgJQgIgIgFgMQgEgMAAgOQAAgOAEgLQAFgLAIgIQAIgJALgFQAKgEAMAAQAIAAAIACQAHACAGAEQAGADAFAGQAEAEADAGIAAhNQABAAAAAAQAAAAABgBQAAAAABAAQABAAAAAAQAEAAACACQACAEAAAHIAACcQAAAHgFAAIgBAAQgGAAAAgHIAAgUIgIAMQgFAFgGADQgGAEgHACQgIACgHAAQgMAAgLgEgAgRgWQgJADgGAIQgHAGgDAJQgEAJAAAMQAAALAEAKQADAKAHAHQAGAIAJADQAJAEAIAAQAJAAAJgEQAJgCAGgHQAHgGADgIQAEgIAAgJIAAgdQgDgFgEgHQgFgFgFgFQgGgFgIgCQgHgCgJAAQgIAAgJAEg");
	this.shape_22.setTransform(231.2,14.1);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#193670").s().p("AgUA7QgMgFgIgIQgJgJgEgMQgEgMgBgNQABgLAEgMQAFgMAIgJQAIgJALgEQAMgFALgBQAMAAALAFQAKAEAIAIQAHAIAFALQADALAAANIAAACQABACgGAAIhiAAQAAAMAEAJQAEAJAGAIQAHAGAKAEQAJAEAIgBQAKAAAHgCQAHgCAGgDQAJgHAGgKIADABQAEACAAAEQAAAFgIAJQgHAFgKAEQgMAFgPABQgLAAgMgFgAAugIQgBgJgEgJQgDgIgFgFQgGgHgIgCQgHgDgKAAQgHAAgJADQgIADgHAGQgGAGgEAIQgEAIgBAJIBaAAIAAAAg");
	this.shape_23.setTransform(217.5,16.6);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#193670").s().p("ABDBVQgFAAAAgHIAAiSIgzBiQgEAIgHAAQgHAAgDgIIgzhiIAACSQAAAHgFAAIgCAAQgGAAAAgHIAAiZQAAgIAJgBIAEAAQAEABACACQACABADAGIAyBkIAzhkIAFgHQACgCAEgBIADAAQAKABAAAIIAACZQgBAHgFAAg");
	this.shape_24.setTransform(201.1,14.4);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#193670").s().p("AgZA/QgFAAAAgGIAAh0IAEgBQAEAAACACQACADAAAHIAAAQQACgIADgFQADgGAFgEQAEgDADgCQAFgCAHAAQAHAAAFADQAFADAAAFQAAADgCACIgCABQgFgFgJAAQgJAAgEAEQgGAEgEAHQgEAHgCALQgCAKAAAKIAAA2QAAAGgFAAg");
	this.shape_25.setTransform(183.5,16.5);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#193670").s().p("AgYA7QgJgEgGgHQgGgHgEgKQgDgLAAgMIAAhAQABgGAFAAIACAAQAFAAAAAGIAAA/QAAAKADAIQACAJAFAFQAEAGAIADQAGADAKAAQAFAAAHgCQAGgCAGgEQAGgDAEgGQAEgFACgGIAAhPQAAgGAGAAIACAAQAFAAABAGIAAB0IgFABQgDAAgCgCQgDgDAAgHIAAgMQgDAGgEAFIgKAIQgHADgGACQgHACgFAAQgNAAgJgEg");
	this.shape_26.setTransform(171.5,16.7);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#193670").s().p("AgYA6QgLgEgIgIQgJgJgFgMQgEgMAAgNQAAgMAEgMQAFgMAJgJQAIgIALgEQAMgFAMgBQANABAMAFQALAEAJAJQAIAJAFAMQAEALAAAMQAAANgEAMQgFAMgIAJQgJAIgLAEQgMAFgNABQgMgBgMgFgAgSgwQgJAFgHAGQgHAIgEAJQgEALAAAJQAAAKAEALQAEAJAHAIQAHAHAJAEQAJADAJAAQAKAAAKgDQAJgEAHgHQAHgIADgJQAEgKAAgLQAAgJgEgKQgDgKgHgHQgHgIgJgEQgJgDgLAAQgJAAgJADg");
	this.shape_27.setTransform(157.2,16.6);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#193670").s().p("AgTBVIgCgCIAVg1QgFAAgCgFIgwhrQAKgJAGAOIApBjIAmhjQAFgOALAJIg9CgQgDAIgGAAg");
	this.shape_28.setTransform(144.1,19.1);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#193670").s().p("AAABLQgFgCgDgFQgFgFgBgHQgCgHAAgKIAAhKIgQAAQgFAAgBgFIAAgBQABgFAFAAIAQAAIAAgYQgBgGAGAAIABAAQAGAAgBAGIAAAYIAjAAQAFAAABAFIAAABQgBAFgFAAIgjAAIAABJQAAAPAFAHQAEAHAKAAQAHAAAFgDQAFgDADgFIADABQABACAAADQAAAEgEAEQgDADgFACQgGACgGAAQgJAAgFgCg");
	this.shape_29.setTransform(129.3,15.2);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#193670").s().p("AgYA7QgJgEgGgHQgGgHgEgKQgDgLAAgMIAAhAQABgGAFAAIACAAQAFAAAAAGIAAA/QAAAKADAIQACAJAFAFQAEAGAIADQAGADAKAAQAFAAAHgCQAGgCAGgEQAGgDAEgGQAEgFACgGIAAhPQAAgGAGAAIACAAQAFAAABAGIAAB0IgFABQgDAAgCgCQgDgDAAgHIAAgMQgDAGgEAFIgKAIQgHADgGACQgHACgFAAQgNAAgJgEg");
	this.shape_30.setTransform(117.9,16.7);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#193670").s().p("AgYA6QgLgEgIgIQgJgJgFgMQgEgMAAgNQAAgMAEgMQAFgMAJgJQAIgIALgEQAMgFAMgBQANABAMAFQALAEAJAJQAIAJAFAMQAEALAAAMQAAANgEAMQgFAMgIAJQgJAIgLAEQgMAFgNABQgMgBgMgFgAgSgwQgJAFgHAGQgHAIgEAJQgEALAAAJQAAAKAEALQAEAJAHAIQAHAHAJAEQAJADAJAAQAKAAAKgDQAJgEAHgHQAHgIADgJQAEgKAAgLQAAgJgEgKQgDgKgHgHQgHgIgJgEQgJgDgLAAQgJAAgJADg");
	this.shape_31.setTransform(103.7,16.6);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#193670").s().p("AgPBXQgIgDgGgEQgGgDgEgFQgFgFgCgGIAAAUQAAAHgFAAIgCAAQgFAAAAgHIAAioIAEgBQAEAAACACQACAEAAAHIAABCQAEgHAFgEQAFgGAGgDQAGgEAHgCQAHgCAHAAQAMAAALAEQAKAFAIAJQAIAIAFALQAEALAAAOQAAAOgEAMQgEALgJAJQgIAJgKAFQgLAEgNAAQgHAAgIgCgAgPgYQgHACgGAFQgGAFgFAFQgEAHgDAGIAAAcQAAAJAEAIQADAIAHAGQAGAGAJADQAIAEAJAAQAKAAAIgEQAJgDAHgIQAGgHADgKQAEgJAAgMQAAgMgEgJQgDgIgHgHQgGgHgJgEQgJgEgJAAQgHAAgIACg");
	this.shape_32.setTransform(89.5,14.1);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#193670").s().p("AgaA9QgHgCgGgEQgFgFgDgHQgDgFgBgIQAAgKAGgIQAFgHALgFQALgDARgCQAOgDAXgBIADAAIAAgFQAAgJgDgHQgCgHgFgEQgEgGgIgBQgHgDgJAAQgFAAgHACIgMAEQgKAHgFAKQgIgBAAgGQAAgGAIgGQAGgHAKgDQAMgFAMgBQAMAAAJAEQAJADAHAGQAGAGADAJQADAJAAALIAABLQAAABgBAAQAAAAgBABQAAAAgBAAQAAAAgBAAQgDAAgCgDQgDgCAAgHIAAgNQgDAFgEAGQgGAEgGAEQgGADgIACQgGACgIABQgKAAgIgDgAABACQgMACgJADQgJAEgFAFQgDAGAAAIQAAAFABAFQACAEAFADQAEADAGABQAFACAHAAQAIAAAJgDQAJgDAGgGQAHgFADgIQAEgIAAgIIAAgMIgDAAIgjACg");
	this.shape_33.setTransform(74.9,16.6);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#193670").s().p("AAtA/QgFAAAAgGIAAg/QAAgKgDgIQgCgJgFgFQgEgGgIgDQgGgDgKAAQgFAAgHACQgGACgHAEQgFADgEAGQgEAFgDAGIAABPQAAAGgGAAIgBAAQgFAAgBgGIAAh0IAFgBQADAAACACQACADABAHIAAAMIAHgKQAFgFAFgEIANgFQAGgCAGAAQAMAAAKAEQAJAEAGAHQAGAHADALQADAKAAAMIAABAQAAAGgFAAg");
	this.shape_34.setTransform(57.3,16.5);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#193670").s().p("AgZA/QgFAAAAgGIAAh0IAEgBQAEAAACACQACADAAAHIAAAQQACgIADgFQADgGAFgEQAEgDADgCQAFgCAHAAQAHAAAFADQAFADAAAFQAAADgCACIgCABQgFgFgJAAQgJAAgEAEQgGAEgEAHQgEAHgCALQgCAKAAAKIAAA2QAAAGgFAAg");
	this.shape_35.setTransform(46.6,16.5);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#193670").s().p("AgZA9QgJgCgFgEQgGgFgDgHQgCgFAAgIQAAgKAFgIQAFgHALgFQALgDAQgCQAPgDAYgBIACAAIAAgFQAAgJgCgHQgDgHgFgEQgFgGgGgBQgIgDgIAAQgHAAgGACIgMAEQgKAHgGAKQgGgBgBgGQABgGAGgGQAIgHAJgDQALgFANgBQALAAAKAEQAJADAHAGQAFAGAEAJQADAJAAALIAABLQAAABgBAAQAAAAgBABQAAAAgBAAQAAAAgBAAQgEAAgCgDQgCgCAAgHIAAgNQgDAFgFAGQgEAEgHAEQgGADgIACQgGACgHABQgLAAgHgDgAACACQgNACgJADQgJAEgEAFQgFAGAAAIQAAAFADAFQACAEADADQAFADAFABQAGACAIAAQAHAAAJgDQAJgDAGgGQAHgFAEgIQADgIAAgIIAAgMIgDAAIgiACg");
	this.shape_36.setTransform(34.8,16.6);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#193670").s().p("AgUA7QgMgFgIgIQgIgJgFgMQgEgMgBgNQABgLAEgMQAFgMAIgJQAJgJAKgEQAMgFALgBQAMAAALAFQALAEAHAIQAIAIAEALQADALAAANIAAACQABACgGAAIhiAAQAAAMAEAJQAEAJAGAIQAHAGAJAEQAKAEAIgBQAKAAAHgCQAHgCAGgDQAJgHAFgKIAFABQADACAAAEQAAAFgIAJQgHAFgKAEQgMAFgPABQgLAAgMgFgAAugIQgBgJgEgJQgDgIgFgFQgGgHgIgCQgIgDgJAAQgIAAgIADQgIADgHAGQgGAGgEAIQgEAIgBAJIBaAAIAAAAg");
	this.shape_37.setTransform(21.9,16.6);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#193670").s().p("AgqBUQgHAAAAgIIAAiZQAAgGAFAAIACAAQAGAAAAAGIAACVIBQAAQAGAAAAAGIAAABQAAAFgGAAg");
	this.shape_38.setTransform(9.1,14.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,315,56);


(lib.CTA_btn = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#00FFFF").s().p("A6PV3MAAAgruMA0eAAAMAAAArug");
	this.shape.setTransform(168,140);
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(3).to({_off:false},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = null;


(lib.border336x280 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,0,3).p("A6K1yMA0VAAAMAAAArlMg0VAAAg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-168.5,-140.5,337,281);


(lib.blocks = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#557C6B").s().p("AiWCSIAAkjIEtAAIAAEjg");
	this.shape.setTransform(-15.2,45);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#92AF2B").s().p("AiWCXIAAktIEtAAIAAEtg");
	this.shape_1.setTransform(-15.2,15.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#005A8C").s().p("AiWCXIAAktIEtAAIAAEtg");
	this.shape_2.setTransform(-15.2,74.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-30.3,0,30.4,90);


(lib.LogoLockup_300x250 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.blocks();
	this.instance.setTransform(422.8,10.5,0.83,0.83,0,0,0,150,12.6);

	this.instance_1 = new lib.TEC_logorev("synched",0);
	this.instance_1.setTransform(254.4,53.9,0.512,0.512,0,0,0,181.3,32.2);

	this.instance_2 = new lib.logoblock();
	this.instance_2.setTransform(312.9,41.5,0.83,0.83,0,0,0,150,50);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_2},{t:this.instance_1},{t:this.instance}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,314.3,74.7);


// stage content:
(lib.TEC201609_Bar_336x280_AdR = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.clickthru_btn.on("click", function(evt){
		  window.open(clickTag, "_blank");
		});
	}
	this.frame_125 = function() {
		this.stop();
		 
		this.replay_btn.addEventListener("click", fl_ClickToGoToAndPlayFromFrame.bind(this));
		function fl_ClickToGoToAndPlayFromFrame() 
		{
		this.gotoAndPlay(1);
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(125).call(this.frame_125).wait(1));

	// replay btn
	this.replay_btn = new lib.replaybtn();
	this.replay_btn.setTransform(315,184,0.75,0.75);
	this.replay_btn._off = true;
	new cjs.ButtonHelper(this.replay_btn, 0, 1, 2, false, new lib.replaybtn(), 3);

	this.timeline.addTween(cjs.Tween.get(this.replay_btn).wait(125).to({_off:false},0).wait(1));

	// cta btn
	this.clickthru_btn = new lib.CTA_btn();
	new cjs.ButtonHelper(this.clickthru_btn, 0, 1, 2, false, new lib.CTA_btn(), 3);

	this.timeline.addTween(cjs.Tween.get(this.clickthru_btn).wait(126));

	// border
	this.instance = new lib.border336x280();
	this.instance.setTransform(168,140);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(126));

	// head1
	this.instance_1 = new lib.head1("synched",0);
	this.instance_1.setTransform(18,211);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(54).to({startPosition:0},0).to({y:149},5).wait(59).to({startPosition:0},0).to({y:36.8},5).wait(3));

	// sub1
	this.instance_2 = new lib.sub1("synched",0);
	this.instance_2.setTransform(663,1257.5,5,5,0,0,0,131.4,220.7);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(66).to({_off:false},0).to({scaleX:1,scaleY:1,x:149.4,y:435.7},5).wait(47).to({startPosition:0},0).to({y:339.7},5).wait(3));

	// logo block
	this.instance_3 = new lib.LogoLockup_300x250();
	this.instance_3.setTransform(186.7,330,1,1,0,0,0,150,50);
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(118).to({_off:false},0).to({y:255.5},5).wait(3));

	// pic
	this.instance_4 = new lib.pic();

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(54).to({scaleX:0.68,scaleY:0.68,x:1,y:1},5).wait(59).to({y:-140},5).to({_off:true},1).wait(2));

	// bkgd
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("A6PV3MAAAgruMA0eAAAMAAAArug");
	this.shape.setTransform(168,140);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(126));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(168,140,515,280);

})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{});
var lib, images, createjs, ss;