(function (lib, img, cjs, ss) {

var p; // shortcut to reference prototypes
lib.webFontTxtFilters = {}; 

// library properties:
lib.properties = {
	width: 160,
	height: 600,
	fps: 18,
	color: "#CCCCCC",
	opacity: 1.00,
	webfonts: {},
	manifest: [
		{src:"images/_336x280gardener.jpg", id:"_336x280gardener"}
	]
};



lib.ssMetadata = [];


lib.webfontAvailable = function(family) { 
	lib.properties.webfonts[family] = true;
	var txtFilters = lib.webFontTxtFilters && lib.webFontTxtFilters[family] || [];
	for(var f = 0; f < txtFilters.length; ++f) {
		txtFilters[f].updateCache();
	}
};
// symbols:



(lib._336x280gardener = function() {
	this.initialize(img._336x280gardener);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,515,200);


(lib.TEC_logostackrev = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgaA2IAAhpIAPAAIAAAWQALgZAZABIABAAIAAAPIgBAAQgPgBgKAKQgLALAAARIAAA3g");
	this.shape.setTransform(-86.9,100.2,1.483,1.483);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAZA1IgZhVIgYBVIgPAAIgjhpIAQAAIAaBWIAZhWIAOAAIAaBWIAahWIAQAAIgjBpg");
	this.shape_1.setTransform(-5,100.3,1.483,1.483);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgCBAQgFgGAAgNIAAhGIgTAAIAAgMIATAAIAAggIAMAAIAAAgIAWAAIAAAMIgWAAIAABEQAAAHACADQACADAGAAIAMAAIAAANIgNABQgNgBgDgFg");
	this.shape_2.setTransform(-67.5,98.1,1.483,1.483);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AAdBJIAAhCQAAgdgaAAQgMAAgJAJQgJAKAAAOIAAA+IgPAAIAAiRIAPAAIAAA4QAEgIAJgGQAJgFAJAAQAUAAAKAKQAJAKAAAUIAABEg");
	this.shape_3.setTransform(-52.3,97.3,1.483,1.483);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AghApQgNgPAAgaQAAgVALgPQANgTAWAAQAVAAALANQAPAPAAAbIAAAEIhPAAQABAQAIALQAJANAOAAQAaAAAGgbIABAAIAOAAIAAABQgJAmgmAAQgUAAgNgPgAAhgHQgCgOgHgLQgJgLgPABQgMgBgKALQgHALgDAOIBBAAIAAAAg");
	this.shape_4.setTransform(-35.4,100.3,1.483,1.483);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAcBJIAAhCQAAgdgaAAQgMAAgIAJQgJAKgBAOIAAA+IgOAAIAAiRIAOAAIAAA4QAKgTAWAAQAUAAAKAKQAJAKAAAUIAABEg");
	this.shape_5.setTransform(15.8,97.3,1.483,1.483);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AglAmQgMgQAAgWQAAgWAMgPQAOgSAXAAQAYAAAOASQAMAPAAAWQAAAWgMAQQgOASgYAAQgXAAgOgSgAgagdQgJANAAAQQAAARAJAMQAKAPAQAAQAQAAAKgPQAJgMAAgRQAAgQgJgNQgKgOgQABQgQgBgKAOg");
	this.shape_6.setTransform(32.7,100.3,1.483,1.483);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgqAOIAAhEIAPAAIAABEQAAAcAbAAQANAAAIgNQAHgMAAgQIAAg3IAPAAIAABpIgOAAIAAgRQgLAUgWABQgmAAAAgpg");
	this.shape_7.setTransform(115.7,100.5,1.483,1.483);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AghApQgNgPgBgaQAAgVALgPQANgTAXAAQAUAAAMANQAQAPAAAbIAAAEIhPAAQAAAQAIALQAJANAOAAQAZAAAHgbIAAAAIAPAAIAAABQgJAmgmAAQgVAAgMgPgAAggHQAAgOgJgLQgJgLgOABQgMgBgJALQgJALgBAOIA/AAIAAAAg");
	this.shape_8.setTransform(56.1,100.3,1.483,1.483);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgbBJIgIgCIgBAAIAAgNIAKABQAHAAAEgDQACgDAEgJIAFgMIgrhoIAQAAIAgBWIAghWIAPAAIgvB5QgEAOgFAFQgFAEgMABg");
	this.shape_9.setTransform(82.3,103.2,1.483,1.483);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AglAmQgMgQAAgWQAAgWAMgPQAOgSAXAAQAYAAAOASQAMAPAAAWQAAAWgMAQQgOASgYAAQgXAAgOgSgAgagdQgJANAAAQQAAARAJAMQAKAPAQAAQARAAAKgPQAIgMAAgRQAAgQgIgNQgKgOgRABQgQgBgKAOg");
	this.shape_10.setTransform(98.4,100.3,1.483,1.483);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AglAmQgMgQAAgWQAAgWAMgPQAOgSAXAAQAYAAAOASQAMAPAAAWQAAAWgMAQQgOASgYAAQgXAAgOgSgAgagdQgIANAAAQQAAARAIAMQAKAPAQAAQARAAAKgPQAJgMAAgRQAAgQgJgNQgKgOgRABQgQgBgKAOg");
	this.shape_11.setTransform(-102.5,100.3,1.483,1.483);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("ATYBtIAAgjIAcAAIAAAjgAGoBtIAAjZIAVAAIAADZgAzzBtIAAjZICLAAIAAAVIh1AAIAABKIBpAAIAAATIhpAAIAABng");
	this.shape_12.setTransform(1.1,97.3);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgnBzQgZgKgPgTQgOgRgHgXQgGgVAAgYQgBgZAKgYQAKgZAQgPQAQgRAZgKQAagJAaAAQAdAAATAGQAVAHARAKQgIALgEANIgEALIgHAAQgJgPgOgIQgQgKgSAAIgBAAQgcAAgPAbQgPAbAAAvQAAAsATAZQARAYAkAAQAPAAAPgHQAOgIAHgIIAGAEIgGAPIgFAPQgKAIgRAGQgSAFgWABQgiAAgZgLg");
	this.shape_13.setTransform(106.4,56.1,1.483,1.483);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AggB3IAAjtIAPACIARABQAOAAATgDIAADtg");
	this.shape_14.setTransform(80,56.1,1.483,1.483);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AggB3IAAjtIAOACIASABQANAAAUgDIAADtg");
	this.shape_15.setTransform(24.5,56.1,1.483,1.483);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AASC6IgxABIAAl1IAOACIARABIASgBIAOgCIAAF1g");
	this.shape_16.setTransform(7.3,46,1.483,1.483);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgpCzQgjgOgXgXQgXgXgNgjQgNgiAAglQABg1AQgoQAPgnAcgZQAbgZAkgLQAggLAoAAQAPAAANACIAbAFQARAFAJAEQALAEAJAGIgHAbQgCANgCAPIgHAAQgRgZgWgMQgSgLgcAAQgVAAgTAJQgSAKgRAVQgPASgLAgQgKAgAAApQAAApAKAeQALAeAQASQARATATAJQAWAIAUAAQANAAAMgDQANgEALgEQALgFALgIQALgHAIgKIAGAFIgGAWQgDAOgBAKQgpAWg8AAQgqAAghgNg");
	this.shape_17.setTransform(-27.2,46.3,1.483,1.483);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("ABaB5IgjAAIgPABIAAiNIgCgaQgBgLgEgGQgLgPgUAAQgTAAgLATQgKAUAAAiIAAB+IgQgBIgzABIAAjtIAQACIAQABIATgBIAQgCIAAAlIABABQANgVARgLQASgMAXAAQAgAAAUAWQAUAVAAAvIAACZIgQgBg");
	this.shape_18.setTransform(52.6,55.6,1.483,1.483);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgYAbQgLgMAAgPQAAgOALgLQALgMANAAQAPAAAKAMQALALAAAOQAAAQgLALQgKALgPAAQgNAAgLgLg");
	this.shape_19.setTransform(80.2,25.7,1.483,1.483);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgYAbQgLgMAAgPQAAgOALgLQAKgMAOAAQAPAAAKAMQALALAAAOQAAAPgLAMQgKALgPAAQgOAAgKgLg");
	this.shape_20.setTransform(24.4,25.7,1.483,1.483);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AhBBcIAAjjIAJgDIAYgKQAUgKAKgIIADADIAABbIAvgCIABAbIgwgBIAACaQAAAJAGAGQAIAIAOgDQAQgDAPgPIAGACIAAABIgFAXIAAAAQAAADgMAKQgOAMgOAEQgMAEgKAAQhAAAAAhLg");
	this.shape_21.setTransform(114,-19.7,1.483,1.483);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("Ag+BcIAAiMIguAAIAAgaIAuACIAAg/IAJgDIAXgKQAVgKAJgIIAEADIAABbIBpAAIgBAYIhoAAIAACaQAAAJAGAGQAIAIANgDQARgDAPgPIAGACIAAABIgFAXIAAAAQgBADgLAKQgOAMgOAEQgMAEgMAAQg+AAAAhLg");
	this.shape_22.setTransform(89.4,-19.7,1.483,1.483);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AhUB5IAAjsIBHAAIgBAuIABABQAIgUASgQQAWgQAWAAQANAAAPAEIgBABQgVAVgLAgIgCADIgDgBQgHgCgHAAQgWAAgMAPQgMAOAAAUIAACGg");
	this.shape_23.setTransform(29.7,-13.9,1.483,1.483);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AggB2QgXgHgPgOQgQgPgKgZQgKgYAAggQAAgeAJgYQAIgXAQgRQAOgPAWgIQAUgJAYABQAxAAAZAcQAaAcAAA1IAAAPIiMAAQAAATAEASQAEAQAIAPQAIANALAHQANAHARAAQAhAAAkgdIAGACIAAABIgEAXQgQASgdAKQgSAFgcABQgVAAgXgIgAApgVQgBglgIgVQgIgXgTAAQgJAAgIAHQgHAIgEALQgEALgDAPIgDAdIBKAAIAAAAg");
	this.shape_24.setTransform(56,-13.5,1.483,1.483);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AggB2QgXgHgPgOQgSgQgIgYQgKgYAAggQAAgeAJgYQAHgXAQgRQAPgPAVgIQAVgJAXABQAyAAAaAcQAaAdAAA0IAAAPIiNAAQAAATAEASQADAQAJAPQAIANALAHQANAHAQAAQAiAAAkgdIAGACIAAABIgEAXQgQASgdAKQgSAFgcABQgVAAgXgIgAAogVQAAglgJgVQgHgXgUAAQgJAAgHAHQgHAIgEALQgEALgDAPIgDAdIBJAAIAAAAg");
	this.shape_25.setTransform(-3.7,-13.5,1.483,1.483);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AgPB2IgOAAIhEi8IgSgvIAUABIA4gBIA1CrIACAAIAehVIAdhWIAUACIAVgCIgTAsIgYA4IgaBAQgQAsgJAbg");
	this.shape_26.setTransform(-35.6,-13.5,1.483,1.483);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AheC7IAAl1IBXADIBAgBIAmgCQgCALAAAKIACAXIgggCIgggCIgdgCIgUgBIAABmIBWgEIAPApQg8gDgpAAIAACkIA5gBQAfgCAZgDIgBAWIAAAMIABAIg");
	this.shape_27.setTransform(-68.9,-23.6,1.483,1.483);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AggB2QgXgHgQgOQgQgPgKgZQgJgYgBggQABgeAIgYQAJgXAPgRQAOgPAWgIQAVgJAXABQAyAAAZAcQAaAdAAA0IAAAPIiMAAQAAATAEASQAFASAHANQAIANALAHQANAHARAAQAgAAAlgdIAGACIAAABIgEAXQgQASgdAKQgSAFgcABQgWAAgWgIgAApgVQgBglgIgVQgJgXgSAAQgJAAgIAHQgHAIgEALQgEALgDAPIgDAdIBKAAIAAAAg");
	this.shape_28.setTransform(107.6,-76.1,1.483,1.483);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("ABeC6IgnAAIgQABIAAiPIAAgaQgCgLgFgGQgKgNgTAAQgVAAgKARQgKAUAAAiIAACAIgQgBIg3ABIAAl1IAQACIATABIAUgBIAQgCIAACtIABABQANgVASgLQAQgMAXAAQAlAAAUAWQAUAVAAAtIAACbIgQgBg");
	this.shape_29.setTransform(71.6,-86.3,1.483,1.483);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("AgjC6IAAlNIhbAGIAAgsIBZADICkgDIAAAWIAAAWIhYgGIAAFNg");
	this.shape_30.setTransform(32.7,-86.4,1.483,1.483);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-125.7,-114,253.7,228.1);


(lib.sub1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// type
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#6B8A21").s().p("AAAAIQgHAAgBgIIAAAAQABgHAHAAIAAAAQAIAAAAAHIAAAAQAAAIgIAAg");
	this.shape.setTransform(76.4,111.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#6B8A21").s().p("AAoA3QgFAAAAgFIAAg3QAAgJgCgHQgCgHgEgGQgFgFgGgCQgGgDgIAAQgFAAgGACQgGACgEADIgJAIIgGAKIAABFQAAAFgFAAIgCAAQgEAAAAgFIAAhmIADgBQAEAAABACQACADAAAGIAAAKIAHgJIAJgHIALgFQAGgBAFAAQAKAAAJADQAIAEAFAGQAGAGACAJQADAJAAALIAAA4QAAAFgFAAg");
	this.shape_1.setTransform(68,106.9);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#6B8A21").s().p("AgVA0QgKgEgHgIQgIgHgEgLQgEgKAAgMQAAgLAEgKQAEgKAIgIQAHgHAKgFQALgEAKAAQALAAALAEQAKAFAHAHQAIAIAEALQAEAKAAAKQAAAMgEALQgEAKgIAHQgHAIgKAEQgLAEgLAAQgKAAgLgEgAgQgqQgIAEgHAGQgFAHgEAIQgDAJAAAIQAAAJADAJQAEAJAFAGQAHAGAIAEQAIAEAIAAQAJAAAIgEQAJgEAGgGQAFgGAEgJQADgIAAgKQAAgIgDgJQgEgIgFgGQgGgHgJgEQgIgDgJgBQgIABgIADg");
	this.shape_2.setTransform(55.4,107);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#6B8A21").s().p("AAABMQgEAAAAgEIAAhiQAAgFAEgBIAAAAQAFABAAAFIAABiQAAAEgFAAgAgGhEQAAgIAGAAQAHAAAAAIQAAAIgHAAQgGAAAAgIg");
	this.shape_3.setTransform(46.8,104.8);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#6B8A21").s().p("AgWA0QgJgDgFgGQgGgEAAgFQAAgEAGgBQAGAIAJAFQAFACAFABQAHACAFAAQAHAAAGgCQAGgBAEgDQAEgCACgFQACgEAAgEQAAgGgCgDQgDgDgEgDQgGgDgRgEQgSgEgIgCQgGgEgDgEQgDgGAAgHQAAgHADgHQACgFAGgEQAFgEAIgDQAHgCAHAAQAMAAAKADQAIADAGAGQAEAEAAAEQAAADgDACIgDABQgFgIgIgEQgJgFgMAAQgFAAgFABQgGACgEADQgEADgCADQgCAFAAAEQAAAFACADQADAEAEACQAGADAQAFIAOACIANAEQAGADADAFQAEAGAAAHQAAAIgDAGQgDAFgGAFQgFAEgIACQgIACgKAAQgLAAgLgEg");
	this.shape_4.setTransform(39.4,107);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#6B8A21").s().p("AgWA0QgJgDgFgGQgGgEAAgFQAAgEAGgBQAGAIAJAFQAFACAFABQAHACAFAAQAHAAAGgCQAGgBAEgDQAEgCACgFQACgEAAgEQAAgGgCgDQgDgDgEgDQgGgDgRgEQgSgEgIgCQgGgEgDgEQgDgGAAgHQAAgHADgHQACgFAGgEQAFgEAIgDQAHgCAHAAQAMAAAKADQAIADAGAGQAEAEAAAEQAAADgDACIgDABQgFgIgIgEQgJgFgMAAQgFAAgFABQgGACgEADQgEADgCADQgCAFAAAEQAAAFACADQADAEAEACQAGADAQAFIAOACIANAEQAGADADAFQAEAGAAAHQAAAIgDAGQgDAFgGAFQgFAEgIACQgIACgKAAQgLAAgLgEg");
	this.shape_5.setTransform(29.2,107);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#6B8A21").s().p("AgSA0QgKgEgHgHQgIgIgEgKQgEgLAAgMQAAgKAEgKQAEgLAIgIQAHgHAKgEQAKgFAKAAQALAAAJADQAJAFAHAHQAGAGAEALQAEAKAAALIAAABQAAACgFAAIhXAAQAAAKAEAJQADAHAGAHQAGAGAIADQAIADAIABQAIgBAHgCQAGgBAFgDQAIgGAFgKIADABQADACAAAEQAAAFgHAHQgFAFgKAEQgKAEgNAAQgKAAgLgEgAAogHQAAgIgDgHQgDgHgFgGQgFgFgHgDQgHgDgIAAQgHAAgHADQgHAEgGAEQgGAGgDAHQgEAHgBAIIBPAAIAAAAg");
	this.shape_6.setTransform(18.2,107);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#6B8A21").s().p("AgWA0QgJgDgFgGQgGgEAAgFQAAgEAGgBQAGAIAJAFQAFACAFABQAHACAFAAQAHAAAGgCQAGgBAEgDQAEgCACgFQACgEAAgEQAAgGgCgDQgDgDgEgDQgGgDgRgEQgSgEgIgCQgGgEgDgEQgDgGAAgHQAAgHADgHQACgFAGgEQAFgEAIgDQAHgCAHAAQAMAAAKADQAIADAGAGQAEAEAAAEQAAADgDACIgDABQgFgIgIgEQgJgFgMAAQgFAAgFABQgGACgEADQgEADgCADQgCAFAAAEQAAAFACADQADAEAEACQAGADAQAFIAOACIANAEQAGADADAFQAEAGAAAHQAAAIgDAGQgDAFgGAFQgFAEgIACQgIACgKAAQgLAAgLgEg");
	this.shape_7.setTransform(7,107);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#6B8A21").s().p("AgVA0QgKgEgHgIQgIgHgEgLQgEgKAAgMQAAgKAEgLQAEgLAIgHQAHgHAKgFQAKgEALAAQALAAALAEQAKAFAIAHQAHAIAEAKQAEALAAAKQAAAMgEAKQgEAKgHAIQgIAIgKAEQgLAEgLAAQgLAAgKgEgAgQgqQgIAEgGAGQgHAHgCAIQgEAJAAAIQAAAKAEAIQACAJAHAGQAGAGAIAEQAIADAIABQAJgBAIgDQAIgDAHgGQAGgHADgIQADgJAAgKQAAgIgDgIQgDgJgGgHQgHgGgIgEQgIgDgJAAQgIAAgIADg");
	this.shape_8.setTransform(90.7,84);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#6B8A21").s().p("AgHBPQgGAAABgFIAAhdIgTAAQgFAAAAgEIAAgBQAAgFAFAAIATAAIAAgLQgBgKACgHQADgHAEgEQADgFAEgDQAFgCAIAAQAGAAAFACQAEABADADQADADAAADQAAAAAAABQAAABAAAAQgBABAAAAQAAAAAAABIgDABQgCgDgFgCQgFgCgFAAQgFAAgEABQgEACgBAEQgCADgBAGIgBAMIAAALIAXAAQAFAAAAAFIAAABQAAAEgFAAIgXAAIAABdQABAFgFAAg");
	this.shape_9.setTransform(81.1,81.5);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#6B8A21").s().p("AAoA3QgFAAAAgFIAAg3QAAgJgCgHQgCgHgEgGQgFgFgGgCQgGgDgIAAQgFAAgGACQgGACgEADIgJAIIgGAKIAABFQAAAFgFAAIgCAAQgEAAAAgFIAAhmIADgBQAEAAABACQACADAAAGIAAAKIAHgJIAJgHIALgFQAGgBAFAAQAKAAAJADQAIAEAFAGQAGAGACAJQADAJAAALIAAA4QAAAFgFAAg");
	this.shape_10.setTransform(71,83.9);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#6B8A21").s().p("AAABNQgEAAAAgGIAAhhQAAgGAEABIAAAAQAFgBAAAGIAABhQAAAGgFAAgAgGhEQAAgHAGAAQAHAAAAAHQAAAIgHAAQgGAAAAgIg");
	this.shape_11.setTransform(62.5,81.8);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#6B8A21").s().p("AgSA0QgKgEgHgIQgIgHgEgLQgEgKAAgMQAAgKAEgLQAEgKAIgIQAHgIAKgDQAKgFAKAAQALAAAJAEQAJAEAHAGQAGAIAEAJQAEALAAALIAAABQAAACgFAAIhXAAQAAAKAEAIQADAJAGAGQAGAGAIAEQAIACAIABQAIgBAHgBQAGgCAFgEQAIgFAFgJIADABQADACAAADQAAAFgHAHQgFAGgKADQgKAEgNAAQgKAAgLgEgAAogGQAAgJgDgIQgDgGgFgFQgFgGgHgCQgHgDgIAAQgHAAgHADQgHACgGAGQgGAFgDAHQgEAHgBAJIBPAAIAAAAg");
	this.shape_12.setTransform(50.3,84);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#6B8A21").s().p("AgSA0QgKgEgHgIQgIgHgEgLQgEgKAAgMQAAgKAEgLQAEgKAIgIQAHgIAKgDQAKgFAKAAQALAAAJAEQAJAEAHAGQAGAIAEAJQAEALAAALIAAABQAAACgFAAIhXAAQAAAKAEAIQADAJAGAGQAGAGAIAEQAIACAIABQAIgBAHgBQAGgCAFgEQAIgFAFgJIADABQADACAAADQAAAFgHAHQgFAGgKADQgKAEgNAAQgKAAgLgEgAAogGQAAgJgDgIQgDgGgFgFQgFgGgHgCQgHgDgIAAQgHAAgHADQgHACgGAGQgGAFgDAHQgEAHgBAJIBPAAIAAAAg");
	this.shape_13.setTransform(38.2,84);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#6B8A21").s().p("AgWA3QgEAAAAgFIAAhmIADgBQAEAAABACQACADAAAGIAAAOIAEgMQAEgFADgDQAEgDADgCQAEgBAGAAQAHAAAEACQAEADABAEQAAAAgBABQAAABAAAAQAAABAAAAQgBABAAAAIgCACQgFgFgIAAQgHAAgEAEQgFADgDAHQgEAGgCAJQgCAJABAJIAAAvQAAAFgGAAg");
	this.shape_14.setTransform(29.1,83.9);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#6B8A21").s().p("AgIBPQgEAAAAgFIAAhdIgSAAQgGAAAAgEIAAgBQAAgFAGAAIASAAIAAgLQAAgKACgHQACgHAEgEQAEgFADgDQAGgCAHAAQAGAAAFACQAEABADADQADADAAADQAAAAAAABQAAABAAAAQgBABAAAAQAAAAgBABIgCABQgCgDgFgCQgFgCgFAAQgFAAgEABQgDACgCAEQgCADgBAGIgBAMIAAALIAXAAQAFAAAAAFIAAABQAAAEgFAAIgXAAIAABdQAAAFgEAAg");
	this.shape_15.setTransform(21.5,81.5);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#6B8A21").s().p("AgXA2QgGgCgFgEQgFgEgDgGQgCgFAAgGQgBgKAFgHQAEgGALgEQAJgDAPgCQAMgCAVAAIADAAIAAgGQAAgHgDgGQgCgHgEgDQgFgEgGgDQgGgCgIAAQgFAAgGACQgFABgFADQgJAFgFAKQgGgBAAgGQAAgFAGgFQAGgGAIgEQALgEALAAQAKAAAIADQAIADAGAFQAFAGAEAHQADAJAAAJIAABDIgFABQgDAAgBgCQgCgDAAgGIAAgMQgDAGgEAEQgEAEgGADIgNAGIgLABQgJAAgIgCgAABACQgKABgIAEQgIADgFAEQgDAFAAAIQAAAEABAEQACAEAEACIAJAFQAFABAGAAQAHAAAIgDQAHgDAGgEQAGgFADgHQAEgHAAgIIAAgKIgEAAIgeACg");
	this.shape_16.setTransform(7.5,84);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#6B8A21").s().p("AgVA3QgGAAAAgFIAAhmIAEgBQADAAACACQACADAAAGIAAAOIAFgMQACgFAFgDQADgDADgCQAEgBAGAAQAHAAAEACQAFADgBAEQAAAAAAABQAAABAAAAQAAABAAAAQgBABAAAAIgCACQgFgFgIAAQgHAAgEAEQgFADgEAHQgDAGgCAJQgCAJAAAJIAAAvQAAAFgEAAg");
	this.shape_17.setTransform(126.3,60.9);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#6B8A21").s().p("AgVA0QgKgEgHgIQgIgHgEgLQgEgLAAgLQAAgLAEgKQAEgLAIgHQAHgHAKgFQAKgEALAAQAMAAAKAEQAKAFAIAHQAHAIAEALQAEAKAAAKQAAAMgEALQgEAKgHAHQgIAIgKAEQgKAEgMAAQgLAAgKgEgAgQgqQgIAEgGAGQgHAGgCAJQgEAIAAAJQAAAJAEAJQACAIAHAHQAGAGAIAEQAIADAIAAQAJAAAIgDQAIgEAHgGQAFgGAEgJQADgIAAgKQAAgIgDgJQgEgIgFgGQgHgHgIgEQgIgDgJAAQgIAAgIADg");
	this.shape_18.setTransform(115.5,61);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#6B8A21").s().p("AgHBPQgGAAAAgFIAAhdIgSAAQgFAAAAgEIAAgBQAAgFAFAAIASAAIAAgLQAAgKACgHQADgHADgEQAEgFAEgDQAFgCAIAAQAGAAAFACQAFABACADQADADAAADQAAAAAAABQAAAAAAABQgBAAAAABQAAAAAAABIgDABQgCgDgFgCQgFgCgFAAQgFAAgDABQgFACgBAEQgCADgBAGIgBAMIAAALIAWAAQAGAAAAAFIAAABQAAAEgGAAIgWAAIAABdQABAFgFAAg");
	this.shape_19.setTransform(105.9,58.5);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#6B8A21").s().p("AgWA3QgEAAAAgFIAAhmIADgBQADAAACACQACADAAAGIAAAOIAEgMQAEgFADgDQAEgDADgCQAEgBAGAAQAGAAAFACQAEADABAEQgBAAAAABQAAABAAAAQAAABAAAAQgBABAAAAIgCACQgFgFgIAAQgHAAgEAEQgFADgDAHQgEAGgCAJQgBAJAAAJIAAAvQAAAFgGAAg");
	this.shape_20.setTransform(94.9,60.9);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#6B8A21").s().p("AgSA0QgKgEgHgHQgIgIgEgKQgEgLAAgMQAAgKAEgKQAEgLAIgIQAHgHAKgFQAKgEAKAAQALAAAJADQAJAFAHAHQAGAHAEAJQAEAKAAAMIAAABQAAACgFAAIhXAAQAAAKAEAIQADAIAGAHQAGAGAIADQAIADAIAAQAIAAAHgCQAGgBAFgDQAIgGAFgJIADAAQADACAAAEQAAAFgHAHQgFAFgKAEQgKAEgNAAQgKAAgLgEgAAogHQAAgIgDgHQgDgHgFgGQgFgFgHgDQgHgCgIAAQgHAAgHACQgHAEgGAEQgGAGgDAHQgEAHgBAIIBPAAIAAAAg");
	this.shape_21.setTransform(84.5,61);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#6B8A21").s().p("AAABCQgEgCgEgEQgDgEgBgGQgCgHAAgIIAAhCIgOAAQgFAAAAgEIAAgBQAAgFAFAAIAOAAIAAgVQAAgFAEAAIACAAQAEAAABAFIAAAVIAdAAQAFAAAAAFIAAABQAAAEgFAAIgdAAIAABBQAAANADAGQADAGAKAAQAFAAAFgCQAEgDADgEIACABQABAAAAABQAAAAABABQAAAAAAABQAAABAAAAQAAAEgEADQgDADgEACQgFABgGAAQgHAAgFgCg");
	this.shape_22.setTransform(74.7,59.7);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#6B8A21").s().p("AgWA0QgJgDgFgGQgGgFAAgEQAAgEAGgCQAGAJAJAFQAFADAFAAQAHACAFAAQAHAAAGgCQAGgBAEgDQAEgDACgEQACgDAAgFQAAgGgCgDQgDgEgEgCQgGgDgRgEQgSgEgIgCQgGgEgDgEQgDgGAAgIQAAgHADgGQACgFAGgEQAFgEAIgDQAHgCAHAAQAMAAAKADQAIAEAGAFQAEAEAAAEQAAADgDACIgDABQgFgIgIgEQgJgFgMAAQgFAAgFABQgGACgEADQgEADgCADQgCAEAAAFQAAAFACADQADADAEADQAGAEAQAEIAOADIANADQAGADADAFQAEAFAAAJQAAAHgDAFQgDAGgGAFQgFAEgIACQgIACgKAAQgLAAgLgEg");
	this.shape_23.setTransform(65.7,61);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#6B8A21").s().p("AAABMQgEAAAAgEIAAhiQAAgFAEgBIAAAAQAFABAAAFIAABiQAAAEgFAAgAgGhEQAAgIAGAAQAHAAAAAIQAAAIgHAAQgGAAAAgIg");
	this.shape_24.setTransform(58.5,58.8);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#6B8A21").s().p("AgXBSQgJgCgHgDQgFgEgEgGQgDgFAAgHQAAgHADgFQACgFAGgEQAFgEAHgDIAOgEQgDgCgDgDQgCgDAAgEQAAgHAGgEQgGAAgFgDQgFgEgDgFQgEgEgCgGQgCgFAAgHQAAgIADgHQADgHAGgGQAHgFAHgDQAIgDAJAAQAFAAAIACQAHACAGAEIAKgOQAEgGAFACQAFABgBADIgSAUQAFAFADAGQACAHAAAHQAAAIgDAHQgDAHgGAFQgGAGgHABQgJADgHAAIgHgBQgFADAAAEQAAAGAJADIAVAFIAMAEIALAGQAGADACAFQADAFAAAGQAAAIgEAGQgDAGgIAEQgHAEgKACQgKACgKAAQgNAAgKgCgAgPAgIgNAFQgFADgEAFQgDAEAAAGQAAAFACADQADAEAFADQAFACAIACQAHABAKAAQAIAAAIgBQAIgCAFgDQAGgCADgFQADgEAAgFQAAgEgCgEIgGgFQgGgEgNgDIgOgEQgIABgHACgAgNg+QgFACgFAEQgEAEgDAGQgCAFAAAHQAAAHACAFQADAGAEAEQAFADAFADQAGACAHAAQAFAAAGgCIAKgGQAFgEACgGQACgFAAgHQAAgHgCgFQgCgGgFgEQgEgEgGgCQgGgCgFAAQgHAAgGACg");
	this.shape_25.setTransform(51.1,62.8);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#6B8A21").s().p("AgSA0QgKgEgHgHQgIgIgEgKQgEgLAAgMQAAgKAEgKQAEgLAIgIQAHgHAKgFQAKgEAKAAQALAAAJADQAJAFAHAHQAGAHAEAJQAEAKAAAMIAAABQAAACgFAAIhXAAQAAAKAEAIQADAIAGAHQAGAGAIADQAIADAIAAQAIAAAHgCQAGgBAFgDQAIgGAFgJIADAAQADACAAAEQAAAFgHAHQgFAFgKAEQgKAEgNAAQgKAAgLgEgAAogHQAAgIgDgHQgDgHgFgGQgFgFgHgDQgHgCgIAAQgHAAgHACQgHAEgGAEQgGAGgDAHQgEAHgBAIIBPAAIAAAAg");
	this.shape_26.setTransform(39.9,61);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#6B8A21").s().p("AgVA3QgGAAAAgFIAAhmIAEgBQADAAACACQACADAAAGIAAAOIAFgMQADgFADgDQAEgDADgCQAFgBAFAAQAGAAAFACQAFADgBAEQAAAAAAABQAAABAAAAQAAABAAAAQgBABAAAAIgCACQgFgFgIAAQgHAAgEAEQgFADgEAHQgDAGgCAJQgBAJgBAJIAAAvQAAAFgEAAg");
	this.shape_27.setTransform(30.7,60.9);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#6B8A21").s().p("AgVA3QgGAAAAgFIAAhmIAEgBQAEAAABACQACADAAAGIAAAOIAFgMQACgFAFgDQADgDADgCQAEgBAGAAQAHAAAEACQAFADgBAEQAAAAAAABQAAABAAAAQAAABAAAAQgBABAAAAIgCACQgFgFgIAAQgHAAgEAEQgFADgEAHQgDAGgCAJQgCAJAAAJIAAAvQAAAFgEAAg");
	this.shape_28.setTransform(19.2,60.9);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#6B8A21").s().p("AgVA0QgKgEgHgIQgIgHgEgLQgEgLAAgLQAAgLAEgKQAEgLAIgHQAHgHAKgFQAKgEALAAQAMAAAKAEQAKAFAIAHQAHAIAEALQAEAKAAAKQAAAMgEALQgEAKgHAHQgIAIgKAEQgKAEgMAAQgLAAgKgEgAgQgqQgIAEgGAGQgHAGgCAJQgEAIAAAJQAAAJAEAJQACAIAHAHQAGAGAIAEQAIADAIAAQAJAAAIgDQAIgEAHgGQAFgGAEgJQADgIAAgKQAAgIgDgJQgEgIgFgGQgHgHgIgEQgIgDgJAAQgIAAgIADg");
	this.shape_29.setTransform(8.4,61);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#6B8A21").s().p("AgSA0QgKgEgHgIQgIgHgEgLQgEgKAAgMQAAgKAEgLQAEgKAIgIQAHgIAKgDQAKgFAKAAQALAAAJAEQAJADAHAHQAGAIAEAKQAEAKAAALIAAABQAAACgFAAIhXAAQAAAKAEAJQADAHAGAHQAGAGAIAEQAIADAIAAQAIAAAHgCQAGgCAFgEQAIgFAFgKIADACQADABAAAEQAAAFgHAHQgFAFgKAEQgKAEgNAAQgKAAgLgEgAAogGQAAgJgDgIQgDgHgFgEQgFgGgHgCQgHgDgIgBQgHABgHADQgHACgGAGQgGAFgDAHQgEAHgBAJIBPAAIAAAAg");
	this.shape_30.setTransform(124.3,38);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#6B8A21").s().p("AgVA3QgFAAgBgFIAAhmIAEgBQADAAACACQACADAAAGIAAAOIAEgMQADgFAFgDQADgDADgCQAFgBAFAAQAGAAAFACQAFADAAAEQAAABgBAAQAAABAAAAQAAABAAAAQgBABAAAAIgCACQgFgFgIAAQgHAAgEAEQgFADgEAHQgDAGgCAJQgBAJAAAJIAAAvQgBAFgFAAg");
	this.shape_31.setTransform(115.2,37.9);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#6B8A21").s().p("AgVA0QgKgEgIgIQgHgIgEgKQgEgKAAgMQAAgLAEgKQAEgLAHgHQAIgHAKgFQALgEAKAAQAMAAAKAEQAKAFAIAHQAHAIAEAKQAEALAAAKQAAAMgEAKQgEAKgHAIQgIAIgKAEQgKAEgMAAQgKAAgLgEgAgQgqQgIAEgGAGQgHAGgCAJQgEAJAAAIQAAAJAEAJQACAIAHAHQAGAGAIAEQAIADAIABQAJgBAIgDQAJgDAFgHQAGgGADgIQAEgJAAgKQAAgIgEgIQgDgKgGgGQgFgGgJgEQgIgEgJAAQgIAAgIAEg");
	this.shape_32.setTransform(104.4,38);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#6B8A21").s().p("ABNA3QgGAAABgFIAAg5QgBgJgBgHQgDgHgEgEQgEgFgGgDQgFgCgIAAIgLACQgGABgEAEQgFADgDAFQgEAEgCAGIAABFQAAAFgFAAIAAAAQgEAAAAgFIAAg7QAAgIgCgHQgCgGgEgFQgEgEgGgDQgGgCgHAAIgLACQgGABgEAEQgFADgDAFQgFAEgCAGIAABFQABAFgGAAIgBAAQgFAAABgFIAAhmIADgBQADAAACACQACADAAAGIAAAKIAHgJIAIgHQAFgDAGgCQAFgBAFAAQAIAAAGABQAGACAFAEQAEADAEAFQACAEABAGQADgGAEgEQADgFAGgDQAFgEAFgCQAHgBAHAAQAJAAAJADQAIADAFAGQAFAGADAJQACAIAAAMIAAA5QAAAFgEAAg");
	this.shape_33.setTransform(88.2,37.9);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#6B8A21").s().p("AAoA3QgFAAAAgFIAAg3QAAgJgCgHQgCgHgEgGQgFgFgGgCQgGgDgIAAQgFAAgGACQgGACgEADIgJAIIgGAKIAABFQAAAFgFAAIgCAAQgEAAAAgFIAAhmIADgBQAEAAABACQACADAAAGIAAAKIAHgJIAJgHIALgFQAGgBAFAAQAKAAAJADQAIAEAFAGQAGAGACAJQADAJAAALIAAA4QAAAFgFAAg");
	this.shape_34.setTransform(68.2,37.9);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#6B8A21").s().p("AgVA3QgGAAAAgFIAAhmIAEgBQAEAAABACQACADAAAGIAAAOIAFgMQACgFAFgDQADgDADgCQAEgBAGAAQAHAAAEACQAFADgBAEQAAABAAAAQAAABAAAAQAAABAAAAQgBABAAAAIgCACQgFgFgIAAQgHAAgEAEQgFADgEAHQgDAGgCAJQgCAJAAAJIAAAvQAAAFgEAAg");
	this.shape_35.setTransform(58.8,37.9);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#6B8A21").s().p("AgWA2QgHgCgGgEQgEgEgDgGQgCgFgBgGQABgKAEgGQAEgHAKgEQAKgCAPgDQANgCAUAAIACAAIAAgGQABgHgDgGQgCgGgFgFQgDgEgHgCQgGgCgIAAQgFAAgGACQgFABgFADQgJAFgFAKQgGgBAAgGQAAgFAGgFQAGgGAJgEQAKgEALAAQAKAAAIADQAIADAFAFQAGAGADAHQADAJAAAJIAABDIgDABQgEAAgCgCQgCgDAAgGIAAgMQgCAGgFAEQgDAEgHADIgLAGIgNABQgIAAgHgCgAABACQgKABgJADQgHAEgEAEQgEAGAAAHQAAAEACAEQABAEAEACIAJAFQAFABAGAAQAHAAAIgDQAHgDAGgEQAGgGADgGQADgHAAgHIAAgLIgCAAIgfACg");
	this.shape_36.setTransform(48.4,38);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#6B8A21").s().p("AgSA0QgKgEgHgIQgIgHgEgLQgEgKAAgMQAAgKAEgLQAEgKAIgIQAHgIAKgDQAKgFAKAAQALAAAJAEQAJADAHAHQAGAIAEAKQAEAKAAALIAAABQAAACgFAAIhXAAQAAAKAEAJQADAHAGAHQAGAGAIAEQAIADAIAAQAIAAAHgCQAGgCAFgEQAIgFAFgKIADACQADABAAAEQAAAFgHAHQgFAFgKAEQgKAEgNAAQgKAAgLgEgAAogGQAAgJgDgIQgDgHgFgEQgFgGgHgCQgHgDgIgBQgHABgHADQgHACgGAGQgGAFgDAHQgEAHgBAJIBPAAIAAAAg");
	this.shape_37.setTransform(36.9,38);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#6B8A21").s().p("AAABOQgEAAAAgFIAAiVIADgBQACAAACACQACADAAAGIAACLQAAAFgFAAg");
	this.shape_38.setTransform(28.7,35.6);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#6B8A21").s().p("AgVA0QgKgEgIgIQgHgIgEgKQgEgKAAgMQAAgLAEgKQAEgLAHgHQAIgHAKgFQALgEAKAAQAMAAAKAEQAKAFAHAHQAIAIAEAKQAEALAAAKQAAAMgEAKQgEAKgIAIQgHAIgKAEQgKAEgMAAQgKAAgLgEgAgQgqQgIAEgHAGQgGAGgDAJQgDAJAAAIQAAAJADAJQADAIAGAHQAHAGAIAEQAIADAIABQAJgBAJgDQAHgDAGgHQAHgGACgIQAEgJAAgKQAAgIgEgIQgCgKgHgGQgGgGgHgEQgJgEgJAAQgIAAgIAEg");
	this.shape_39.setTransform(16,38);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#6B8A21").s().p("AAABCQgEgCgEgEQgDgEgCgGQgCgHAAgIIAAhCIgNAAQgFAAAAgEIAAgBQAAgFAFAAIANAAIAAgVQAAgFAGAAIABAAQAFAAgBAFIAAAVIAeAAQAGAAAAAFIAAABQAAAEgGAAIgeAAIAABBQABANADAGQADAGAJAAQAHAAAEgCQAEgDADgEIACABQAAAAABABQAAAAAAABQABAAAAABQAAABAAAAQAAAEgEADQgDADgEACQgFABgGAAQgHAAgFgCg");
	this.shape_40.setTransform(5.9,36.7);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#6B8A21").s().p("AgrBKQgHAAAAgHIAAiFQAAgHAHAAIBXAAQAFAAAAAFIAAABQAAAEgFABIhTAAIAAA4IBAAAQAFABAAAEIAAABQAAADgFgBIhAAAIAAA+IBVAAQAFAAAAAEIAAABQAAAFgFAAg");
	this.shape_41.setTransform(113.3,13);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#6B8A21").s().p("AAjBGIg2g8IgSAAIAAA7QAAAFgFAAIgCAAQgFAAAAgFIAAiHQAAgHAHAAIAoAAQALAAAKADQAKACAHAGQAHAFADAIQAEAIAAAKQAAALgEAHQgDAIgHAFQgGAEgKADQgJADgLAAIgEAAIA1A7QAAAAAAAAQAAABAAAAQAAABAAAAQgBABAAAAQgDACgDAAQgDAAgEgEgAglAAIAlAAQAIAAAHAAQAIgCAFgFQAFgEACgGQADgGAAgHQAAgIgDgGQgCgGgFgEQgGgFgHgCQgIgCgIAAIgkAAg");
	this.shape_42.setTransform(100.3,13);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#6B8A21").s().p("AgrBKQgHAAAAgHIAAiFQAAgHAHAAIBXAAQAFAAAAAFIAAABQAAAEgFABIhTAAIAAA4IBAAAQAFABAAAEIAAABQAAADgFgBIhAAAIAAA+IBVAAQAFAAAAAEIAAABQAAAFgFAAg");
	this.shape_43.setTransform(87.5,13);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#6B8A21").s().p("AA0BKQgFAAAAgEIAAhBIhdAAIAABBQAAAEgFAAIgCAAQgFAAAAgEIAAiKQAAgGAFABIACAAQAFgBAAAGIAABAIBdAAIAAhAQAAgGAFABIACAAQAFgBAAAGIAACKQAAAEgFAAg");
	this.shape_44.setTransform(72.8,13);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#6B8A21").s().p("AAjBIIhHhIIAABFQAAAFgFAAIgBAAQgFAAAAgFIAAiJQAAgGAFAAIABAAQAFAAAAAGIAABCIBFhEQAFgFAEACQAEABAAAEIhFBDIBHBFQAAAEgEACIgDABQgDAAgDgDg");
	this.shape_45.setTransform(55.6,13);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#6B8A21").s().p("AgHBLQgHgBgHgDQgGgDgHgEQgFgEgFgFIgJgLIgGgOQgDgGgBgIIgBgQQgBgGACgJIAEgOQADgHADgGQAEgHAFgEIALgJQAFgFAIgDIANgDQAHgCAHAAQAMAAARAFQALAFAIAHQAIAIAAAHQAAADgDACIgEABQgDgGgEgFQgGgGgGgDQgHgEgHgCQgHgCgJAAIgLABIgMAEQgLAEgJAKQgIAJgEAMQgEARgBAIQACASADAJQAEAMAIAIIAKAIIAKAHIANADIAKABQALAAAIgCQAIgDAHgFQAGgDAFgHQADgFADgGQAHABAAAFQgDALgHAHQgHAIgMAEQgRAFgMAAIgOgBg");
	this.shape_46.setTransform(41.5,13);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("#6B8A21").s().p("AAABKQgEAAAAgEIAAiKQAAgGAEABIAAAAQAFgBAAAGIAACKQAAAEgFAAg");
	this.shape_47.setTransform(31.2,13);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("#6B8A21").s().p("AgkBKQgIAAAAgHIAAiHQAAgFAGAAIABAAQAFAAAAAFIAACEIBHAAQAFAAAAAFIAAAAQAAAFgFAAg");
	this.shape_48.setTransform(23.4,12.9);

	this.shape_49 = new cjs.Shape();
	this.shape_49.graphics.f("#6B8A21").s().p("AgGBLQgIgBgHgDQgHgDgFgEQgGgEgFgFIgJgLIgGgOQgDgGgBgIIgCgQQAAgGACgJIAEgOQACgHAFgGQADgHAFgEIALgJQAGgFAGgDIAPgDQAGgCAIAAQALAAASAFQALAFAHAHQAIAIAAAHQAAADgEACIgDABQgDgGgFgFQgEgGgHgDQgHgEgHgCQgIgCgIAAIgLABIgMAEQgLAEgIAKQgJAJgEAMQgFARABAIQABASADAJQAEAMAJAIIAJAIIAKAHIAMADIAMABQAJAAAJgCQAIgDAHgFQAGgDAFgHQADgFACgGQAJABgBAFQgDALgHAHQgHAIgLAEQgSAFgMAAIgNgBg");
	this.shape_49.setTransform(9.7,13);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_49},{t:this.shape_48},{t:this.shape_47},{t:this.shape_46},{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,139,119);


(lib.replaybtn = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#666666").s().p("Ak9BwIAAjgIJ6AAIAADgg");
	this.shape.setTransform(9.1,9.8,0.438,1.268,0,0,0,-0.2,0);
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(3).to({_off:false},0).wait(1));

	// Layer 2
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#BFBFBF").s().p("AgEBGQghgDgWgXQgXgZAAgfQAAgQAGgQQAOggAfgNQARgGAOgBQAiAAAYAZQAZAYAAAjIgUAAQAAgbgTgSQgSgTgaAAQgZAAgSATQgTATAAAaQAAAXARASQAQASAZACIgNgcIBVAnIhWAlg");
	this.shape_1.setTransform(8.4,9.7);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#666666").s().p("AgEBGQghgDgWgXQgXgZAAgfQAAgQAGgQQAOggAfgNQARgGAOgBQAiAAAYAZQAZAYAAAjIgUAAQAAgbgTgSQgSgTgaAAQgZAAgSATQgTATAAAaQAAAXARASQAQASAZACIgNgcIBVAnIhWAlg");
	this.shape_2.setTransform(8.4,9.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AgEBGQghgDgWgXQgXgZAAgfQAAgQAGgQQAOggAfgNQARgGAOgBQAiAAAYAZQAZAYAAAjIgUAAQAAgbgTgSQgSgTgaAAQgZAAgSATQgTATAAAaQAAAXARASQAQASAZACIgNgcIBVAnIhWAlg");
	this.shape_3.setTransform(8.4,9.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1}]}).to({state:[{t:this.shape_2}]},1).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_3}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,16.7,19.4);


(lib.pic = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib._336x280gardener();
	this.instance.setTransform(-143,0);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-143,0,515,200);


(lib.head1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#193670").s().p("AAAAIQgIAAAAgIIAAAAQAAgHAIAAIAAAAQAJAAgBAHIAAAAQABAIgJAAg");
	this.shape.setTransform(77.4,111.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#193670").s().p("AgWA0QgJgDgFgGQgGgEAAgFQAAgEAGgBQAGAIAJAFQAFACAFABQAHACAFAAQAHAAAGgCQAGgBAEgDQAEgCACgFQACgEAAgEQAAgGgCgDQgDgDgEgDQgGgDgRgEQgSgEgIgCQgGgEgDgEQgDgGAAgHQAAgHADgHQACgFAGgEQAFgEAIgDQAHgCAHAAQAMAAAKADQAIADAGAGQAEAEAAAEQAAADgDACIgDABQgFgIgIgEQgJgFgMAAQgFAAgFABQgGACgEADQgEADgCADQgCAFAAAEQAAAFACADQADAEAEACQAGADAQAFIAOACIANAEQAGADADAFQAEAGAAAHQAAAIgDAGQgDAFgGAFQgFAEgIACQgIACgKAAQgLAAgLgEg");
	this.shape_1.setTransform(70.1,107);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#193670").s().p("AAoA3QgFAAAAgFIAAg3QAAgJgCgHQgCgHgEgGQgFgFgGgCQgGgDgIAAQgFAAgGACQgGACgEADIgJAIIgGAKIAABFQAAAFgFAAIgCAAQgEAAAAgFIAAhmIADgBQAEAAABACQACADAAAGIAAAKIAHgJIAJgHIALgFQAGgBAFAAQAKAAAJADQAIAEAFAGQAGAGACAJQADAJAAALIAAA4QAAAFgFAAg");
	this.shape_2.setTransform(58.9,106.9);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#193670").s().p("AgVA0QgKgEgIgIQgHgHgEgLQgEgKAAgMQAAgLAEgKQAEgKAHgIQAIgHAKgFQALgEAKAAQAMAAAKAEQAKAFAHAHQAIAIAEALQAEAKAAAKQAAAMgEALQgEAKgIAHQgHAIgKAEQgKAEgMAAQgKAAgLgEgAgQgqQgIAEgHAGQgFAHgEAIQgDAJAAAIQAAAJADAJQAEAJAFAGQAHAGAIAEQAIAEAIAAQAJAAAJgEQAHgEAGgGQAHgGACgJQAEgIAAgKQAAgIgEgJQgCgIgHgGQgGgHgHgEQgJgDgJgBQgIABgIADg");
	this.shape_3.setTransform(46.3,107);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#193670").s().p("AAABMQgEAAAAgEIAAhiQAAgFAEgBIAAAAQAFABAAAFIAABiQAAAEgFAAgAgGhEQAAgIAGAAQAHAAAAAIQAAAIgHAAQgGAAAAgIg");
	this.shape_4.setTransform(37.7,104.8);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#193670").s().p("AAABCQgEgCgDgEQgEgEgCgGQgBgHAAgIIAAhCIgOAAQgFAAAAgEIAAgBQAAgFAFAAIAOAAIAAgVQAAgFAEAAIACAAQAEAAAAAFIAAAVIAeAAQAGAAgBAFIAAABQABAEgGAAIgeAAIAABBQAAANAEAGQADAGAJAAQAGAAAFgCQAEgDADgEIACABQABAAAAABQAAAAABABQAAAAAAABQAAABAAAAQAAAEgEADQgDADgEACQgFABgGAAQgHAAgFgCg");
	this.shape_5.setTransform(31.7,105.7);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#193670").s().p("AguBNQgFAAAAgFIAAiSIADgBQAEAAABACQACADAAAGIAAAMIAIgKQAEgEAGgEIALgFQAHgBAGAAQAKAAAKAEQAJAEAHAHQAIAIADAKQAEALAAAMQAAANgEAIQgDALgHAHQgIAIgJAEQgKAEgLAAQgGAAgHgCQgHgCgFgEQgGgDgDgEQgEgFgCgEIAAA9QAAAFgFAAgAgNhBQgGACgGAFQgFADgEAGIgHAMIAAAZQAAAIAEAFQADAHAFAGQAGAFAIADQAHADAIAAQAIAAAIgDQAIgDAGgHQAFgGADgHQADgJAAgKQAAgKgDgJQgDgIgGgGQgFgHgIgDQgIgEgIAAQgGAAgHACg");
	this.shape_6.setTransform(21.7,109.1);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#193670").s().p("AgVA0QgKgEgHgIQgIgHgEgLQgEgKAAgMQAAgLAEgKQAEgKAIgIQAHgHAKgFQAKgEALAAQAMAAAKAEQAKAFAIAHQAHAIAEALQAEAKAAAKQAAAMgEALQgEAKgHAHQgIAIgKAEQgKAEgMAAQgLAAgKgEgAgQgqQgIAEgGAGQgHAHgCAIQgEAJAAAIQAAAJAEAJQACAJAHAGQAGAGAIAEQAIAEAIAAQAJAAAIgEQAIgEAHgGQAFgGAEgJQADgIAAgKQAAgIgDgJQgEgIgFgGQgHgHgIgEQgIgDgJgBQgIABgIADg");
	this.shape_7.setTransform(8.4,107);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#193670").s().p("AgSA0QgKgEgHgIQgIgHgEgLQgEgKAAgMQAAgKAEgLQAEgKAIgIQAHgIAKgDQAKgFAKAAQALAAAJAEQAJAEAHAGQAGAIAEAJQAEALAAALIAAABQAAACgFAAIhXAAQAAAKAEAIQADAJAGAGQAGAGAIAEQAIACAIABQAIgBAHgBQAGgCAFgEQAIgFAFgJIADABQADACAAADQAAAFgHAHQgFAGgKADQgKAEgNAAQgKAAgLgEgAAogGQAAgJgDgIQgDgGgFgFQgFgGgHgCQgHgDgIAAQgHAAgHADQgHACgGAGQgGAFgDAHQgEAHgBAJIBPAAIAAAAg");
	this.shape_8.setTransform(98.7,84);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#193670").s().p("AgXBSQgJgCgHgDQgFgEgEgGQgDgFAAgHQAAgHADgFQACgFAGgEQAFgEAHgDIAOgEQgDgCgDgDQgCgDAAgEQAAgHAGgEQgGAAgFgDQgFgEgDgFQgEgEgCgGQgCgFAAgHQAAgIADgHQADgHAGgGQAHgFAHgDQAIgDAJAAQAFAAAIACQAHACAGAEIAKgOQAEgGAFACQAFABgBADIgSAUQAFAFADAGQACAHAAAHQAAAIgDAHQgDAHgGAFQgGAGgHABQgJADgHAAIgHgBQgFADAAAEQAAAGAJADIAVAFIAMAEIALAGQAGADACAFQADAFAAAGQAAAIgEAGQgDAGgIAEQgHAEgKACQgJACgLAAQgNAAgKgCgAgPAgIgNAFQgFADgEAFQgDAEAAAGQAAAFACADQADAEAFADQAFACAIACQAHABAKAAQAIAAAIgBQAIgCAFgDQAGgCADgFQADgEAAgFQAAgEgCgEIgGgFQgGgEgNgDIgOgEQgIABgHACgAgNg+QgFACgFAEQgEAEgDAGQgCAFAAAHQAAAHACAFQADAGAEAEQAFADAFADQAGACAHAAQAFAAAGgCIAKgGQAFgEACgGQACgFAAgHQAAgHgCgFQgCgGgFgEQgEgEgGgCQgGgCgFAAQgHAAgGACg");
	this.shape_9.setTransform(87.6,85.8);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#193670").s().p("AgWA2QgHgCgGgEQgEgEgDgGQgCgFgBgGQABgKAEgHQAEgGAKgEQAKgDAPgCQANgCAUAAIACAAIAAgGQABgHgDgGQgCgHgFgDQgDgEgHgDQgGgCgIAAQgFAAgGACQgFABgFADQgJAFgFAKQgGgBAAgGQAAgFAGgFQAGgGAJgEQAKgEALAAQAKAAAIADQAIADAGAFQAFAGADAHQADAJAAAJIAABDIgDABQgEAAgCgCQgCgDAAgGIAAgMQgCAGgFAEQgDAEgHADIgLAGIgNABQgIAAgHgCgAABACQgKABgJAEQgHADgEAEQgEAFAAAIQAAAEACAEQABAEAEACIAJAFQAFABAGAAQAHAAAIgDQAHgDAGgEQAGgFADgHQADgHAAgIIAAgKIgCAAIgfACg");
	this.shape_10.setTransform(76.3,84);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#193670").s().p("AAABCQgEgCgDgEQgEgEgCgGQgCgHAAgIIAAhCIgNAAQgFAAAAgEIAAgBQAAgFAFAAIANAAIAAgVQAAgFAGAAIABAAQAFAAgBAFIAAAVIAeAAQAGAAAAAFIAAABQAAAEgGAAIgeAAIAABBQABANADAGQADAGAJAAQAHAAAEgCQAEgDADgEIACABQAAAAABABQAAAAAAABQABAAAAABQAAAAAAABQAAAEgEADQgDADgEACQgFABgGAAQgHAAgFgCg");
	this.shape_11.setTransform(67.1,82.7);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#193670").s().p("AAoA3QgFAAAAgFIAAg3QAAgJgCgHQgCgHgEgGQgFgFgGgCQgGgDgIAAQgFAAgGACQgGACgEADIgJAIIgGAKIAABFQAAAFgFAAIgCAAQgEAAAAgFIAAhmIADgBQAEAAABACQACADAAAGIAAAKIAHgJIAJgHIALgFQAGgBAFAAQAKAAAJADQAIAEAFAGQAGAGACAJQADAJAAALIAAA4QAAAFgFAAg");
	this.shape_12.setTransform(57.1,83.9);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#193670").s().p("AgWA2QgHgCgGgEQgEgEgDgGQgCgFgBgGQABgKAEgHQAEgGAKgEQAKgDAPgCQANgCAUAAIACAAIAAgGQABgHgDgGQgCgHgFgDQgDgEgHgDQgGgCgIAAQgFAAgGACQgFABgFADQgJAFgFAKQgGgBAAgGQAAgFAGgFQAGgGAJgEQAKgEALAAQAKAAAIADQAIADAFAFQAGAGADAHQADAJAAAJIAABDIgDABQgEAAgCgCQgCgDAAgGIAAgMQgCAGgFAEQgDAEgHADIgLAGIgNABQgIAAgHgCgAABACQgKABgJAEQgHADgEAEQgEAFAAAIQAAAEACAEQABAEAEACIAJAFQAFABAGAAQAHAAAIgDQAHgDAGgEQAGgFADgHQADgHAAgIIAAgKIgCAAIgfACg");
	this.shape_13.setTransform(44.8,84);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#193670").s().p("AgGAyIgqhkQAJgIAFAMIAiBaIAkhaQAFgNAIAJIgpBkQgCAFgGAAQgEAAgCgFg");
	this.shape_14.setTransform(34,84);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#193670").s().p("AgUBKQgKgDgGgIQgHgHgFgKQgDgLAAgNQAAgMADgKQAFgJAHgIQAGgHAKgFQAKgEAKAAQAHAAAGACQAHACAGAEQAFADAEAEQAEAEACAFIAAhEIAEgBQAEAAABACQADADAAAGIAACLQgBAFgFAAIgBAAQgFAAAAgFIAAgRIgHAJQgEAFgFADQgGAEgHABQgGACgGAAQgKgBgKgEgAgPgUQgIAEgGAGQgFAGgEAHQgDAIAAALQAAAKADAJQAEAJAFAGQAGAGAIADQAHAEAIAAQAIAAAIgDQAHgDAGgGQAGgFADgGQADgIAAgIIAAgaIgGgJQgEgGgFgEQgGgEgGgCQgHgCgHAAQgIAAgHADg");
	this.shape_15.setTransform(21.9,81.7);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#193670").s().p("AAzBFIgTgvIhAAAIgSAvQgFAKgJgIIA5iNQACgEAFAAQAHAAABAEIA5CNQgFAEgDAAQgEAAgCgGgAAdAMIgdhJIgcBJIA5AAg");
	this.shape_16.setTransform(8.9,82);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#193670").s().p("AgSA0QgKgEgHgHQgIgIgEgKQgEgLAAgMQAAgKAEgKQAEgLAIgIQAHgHAKgFQAKgEAKAAQALAAAJADQAJAFAHAHQAGAHAEAJQAEAKAAAMIAAABQAAACgFAAIhXAAQAAAKAEAIQADAIAGAHQAGAGAIADQAIADAIAAQAIAAAHgCQAGgBAFgDQAIgGAFgJIADAAQADACAAAEQAAAFgHAHQgFAFgKAEQgKAEgNAAQgKAAgLgEgAAogHQAAgIgDgHQgDgHgFgGQgFgFgHgDQgHgCgIAAQgHAAgHACQgHAEgGAEQgGAGgDAHQgEAHgBAIIBPAAIAAAAg");
	this.shape_17.setTransform(85.2,61);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#193670").s().p("AgWA3QgEAAAAgFIAAhmIADgBQADAAACACQACADAAAGIAAAOIAFgMQADgFADgDQAEgDADgCQAEgBAGAAQAGAAAFACQAEADAAAEQAAAAAAABQAAABAAAAQAAABAAAAQgBABAAAAIgCACQgFgFgIAAQgHAAgEAEQgFADgDAHQgEAGgCAJQgBAJgBAJIAAAvQAAAFgEAAg");
	this.shape_18.setTransform(76.1,60.9);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#193670").s().p("AgXA2QgGgCgFgEQgFgEgDgFQgDgGABgHQgBgJAFgHQAEgGALgEQAJgDAPgCQAMgCAVAAIADAAIAAgFQgBgIgCgHQgCgFgEgFQgFgDgGgDQgGgCgIAAQgFAAgGABQgGACgEADQgJAGgFAIQgGAAAAgFQAAgGAGgGQAGgFAJgEQAKgEALAAQAKAAAIADQAIACAGAGQAFAFAEAJQACAHAAAKIAABCIgDABQgEAAgCgCQgBgCAAgHIAAgKQgDAEgEAFQgFAFgFADIgMAEIgNACQgIAAgIgCgAABABQgLACgHADQgIAEgFAFQgDAFAAAGQAAAFABAEQACAEAEADIAJADQAFACAGAAQAHAAAIgDQAHgDAGgFQAGgFADgGQADgHABgIIAAgKIgEAAIgeABg");
	this.shape_19.setTransform(65.6,61);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#193670").s().p("AgQA0QgKgEgIgIQgHgHgEgLQgEgLAAgLQAAgLAEgKQAEgLAHgHQAIgHAKgFQAKgEAKAAQANAAAKAEQAJAEAGAGQAIAJAAAGQAAADgDACIgEABIgFgJQgDgGgFgCQgFgEgGgDQgHgBgIAAQgHAAgJADQgIAEgGAGQgGAGgDAJQgDAIAAAJQAAAJADAJQADAIAGAHQAGAGAIAEQAIADAIAAQAIAAAHgCQAGgCAFgDQAGgFAHgMQAHAAAAAFQgCAJgHAHQgGAFgIAEQgKAEgNAAQgKAAgKgEg");
	this.shape_20.setTransform(54.3,61);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#193670").s().p("AAABMQgEAAAAgEIAAhiQAAgFAEgBIAAAAQAFABAAAFIAABiQAAAEgFAAgAgGhEQAAgIAGAAQAHAAAAAIQAAAIgHAAQgGAAAAgIg");
	this.shape_21.setTransform(46.2,58.8);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#193670").s().p("AgUBLQgJgFgIgHQgHgIgDgKQgFgKAAgNQAAgNAFgJQADgJAHgIQAIgIAJgDQAKgEAKgBQAGABAIACQAGABAFADQAGADAEAFQAEAEADAFIAAhDIADgCQADABACACQADACgBAHIAACKQAAAFgEAAIgCAAQgEAAAAgFIAAgSIgIAKQgEAFgGADQgFADgGACQgHABgGAAQgLAAgJgDgAgQgTQgHADgFAGQgHAGgCAHQgDAIAAALQAAAKADAJQACAJAHAGQAFAGAHAEQAJADAHAAQAIAAAIgDQAHgDAGgFQAGgGADgHQADgHABgIIAAgZIgHgLQgEgFgFgEQgGgEgGgCQgGgCgIAAQgHAAgJAEg");
	this.shape_22.setTransform(37.1,58.7);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#193670").s().p("AgSA0QgKgEgHgHQgIgIgEgKQgEgLAAgMQAAgKAEgKQAEgLAIgIQAHgHAKgFQAKgEAKAAQALAAAJADQAJAFAHAHQAGAHAEAJQAEAKAAAMIAAABQAAACgFAAIhXAAQAAAKAEAIQADAIAGAHQAGAGAIADQAIADAIAAQAIAAAHgCQAGgBAFgDQAIgGAFgJIADAAQADACAAAEQAAAFgHAHQgFAFgKAEQgKAEgNAAQgKAAgLgEgAAogHQAAgIgDgHQgDgHgFgGQgFgFgHgDQgHgCgIAAQgHAAgHACQgHAEgGAEQgGAGgDAHQgEAHgBAIIBPAAIAAAAg");
	this.shape_23.setTransform(25,61);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#193670").s().p("AA8BKQgFAAAAgEIAAiDIguBXQgCAIgHAAQgFAAgEgIIgthXIAACDQAAAEgFAAIgCAAQgEAAAAgEIAAiIQAAgIAIABIADAAQAEAAACACQACABACAFIAsBYIAthYIAEgGQACgCAEAAIADAAQAIgBAAAIIAACIQAAAEgFAAg");
	this.shape_24.setTransform(10.5,59);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#193670").s().p("AgWA3QgEAAAAgFIAAhmIADgBQADAAACACQACADAAAGIAAAOIAEgMQAEgFADgDQAEgDADgCQAEgBAGAAQAHAAAEACQAEADAAAEQAAABAAAAQAAABAAAAQAAABAAAAQgBABAAAAIgCACQgFgFgIAAQgHAAgEAEQgFADgDAHQgEAGgCAJQgBAJgBAJIAAAvQABAFgGAAg");
	this.shape_25.setTransform(103.4,37.9);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#193670").s().p("AgVA0QgIgDgFgHQgGgGgDgJQgCgJAAgLIAAg4QAAgFAFAAIABAAQAFAAAAAFIAAA3QAAAJACAHQACAIAEAFQAEAFAHACQAGADAIAAQAFAAAGgCQAFgBAFgEIAJgIQAEgEACgGIAAhFQAAgFAFAAIACAAQAEAAAAAFIAABmIgEABQgBAAAAAAQgBAAAAgBQgBAAAAAAQgBgBAAAAQgDgDAAgGIAAgKIgGAJIgJAHQgFADgGACIgLABQgKAAgJgDg");
	this.shape_26.setTransform(92.8,38);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#193670").s().p("AgVA0QgKgEgHgIQgIgIgEgKQgEgKAAgMQAAgLAEgKQAEgLAIgHQAHgHAKgFQAKgEALAAQALAAALAEQAKAFAIAHQAHAIAEAKQAEALAAAKQAAAMgEAKQgEAKgHAIQgIAIgKAEQgLAEgLAAQgLAAgKgEgAgQgqQgIAEgGAGQgHAGgCAJQgEAJAAAIQAAAJAEAJQACAIAHAHQAGAGAIAEQAIADAIABQAJgBAIgDQAJgDAGgHQAFgGAEgIQADgJAAgKQAAgIgDgIQgEgKgFgGQgGgGgJgEQgIgEgJAAQgIAAgIAEg");
	this.shape_27.setTransform(80.2,38);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#193670").s().p("AgRBLIgCgBIATgwQgFAAgCgEIgpheQAJgIAEAMIAkBYIAihXQAFgNAJAIIg2CNQgDAIgFAAg");
	this.shape_28.setTransform(68.6,40.1);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#193670").s().p("AAABCQgEgCgEgEQgDgEgBgGQgCgHgBgIIAAhCIgNAAQgFAAAAgEIAAgBQAAgFAFAAIANAAIAAgVQABgFAFAAIABAAQAFAAAAAFIAAAVIAdAAQAFAAABAFIAAABQgBAEgFAAIgdAAIAABBQAAANADAGQADAGAKAAQAFAAAFgCQAEgDADgEIACABQAAAAABABQAAAAAAABQABAAAAABQAAABAAAAQAAAEgEADQgCADgFACQgEABgHAAQgHAAgFgCg");
	this.shape_29.setTransform(55.6,36.7);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#193670").s().p("AgVA0QgIgDgFgHQgGgGgDgJQgCgJAAgLIAAg4QAAgFAFAAIABAAQAFAAAAAFIAAA3QAAAJACAHQACAIAEAFQAEAFAHACQAGADAIAAQAFAAAGgCQAFgBAFgEIAJgIQAEgEACgGIAAhFQAAgFAFAAIACAAQAEAAAAAFIAABmIgEABQAAAAgBAAQgBAAAAgBQgBAAAAAAQgBgBAAAAQgDgDAAgGIAAgKIgGAJIgJAHQgFADgGACIgLABQgKAAgJgDg");
	this.shape_30.setTransform(45.5,38);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#193670").s().p("AgVA0QgKgEgIgIQgHgIgEgKQgEgKAAgMQAAgLAEgKQAEgLAHgHQAIgHAKgFQAKgEALAAQALAAALAEQAKAFAHAHQAIAIAEAKQAEALAAAKQAAAMgEAKQgEAKgIAIQgHAIgKAEQgLAEgLAAQgLAAgKgEgAgQgqQgIAEgHAGQgFAGgEAJQgDAJAAAIQAAAJADAJQAEAIAFAHQAHAGAIAEQAIADAIABQAJgBAJgDQAIgDAFgHQAHgGACgIQAEgJAAgKQAAgIgEgIQgCgKgHgGQgFgGgIgEQgJgEgJAAQgIAAgIAEg");
	this.shape_31.setTransform(32.9,38);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#193670").s().p("AgNBMQgHgBgFgEQgGgDgEgEIgGgJIAAARQAAAFgEAAIgBAAQgFAAAAgFIAAiVIADAAQAEAAABABQADAEAAAFIAAA7QADgGAEgEIAKgIIAMgFQAGgCAGABQAKAAAKADQAJAFAHAHQAIAIADAJQAEAKAAAMQAAAMgEALQgDALgHAHQgIAIgJAEQgKADgLAAQgGAAgHgCgAgNgVQgGACgGAFQgFADgEAGIgHAJIAAAaQAAAIAEAHQADAHAFAFQAGAGAIADQAHADAIAAQAIAAAIgEQAIgCAGgHQAFgHADgIQADgJAAgKQAAgKgDgJQgDgGgGgHQgFgGgIgEQgIgDgIAAQgGAAgHACg");
	this.shape_32.setTransform(20.4,35.7);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#193670").s().p("AgXA2QgGgCgFgEQgFgEgDgGQgCgFAAgGQgBgKAFgGQAEgHALgEQAJgCAPgDQAMgCAVAAIADAAIAAgGQAAgHgDgGQgCgGgEgFQgFgEgGgCQgGgCgIAAQgFAAgGACQgFABgFADQgJAFgFAKQgGgBAAgGQAAgFAGgFQAGgGAIgEQALgEALAAQAKAAAIADQAIADAGAFQAFAGAEAHQADAJAAAJIAABDIgFABQgDAAgBgCQgCgDAAgGIAAgMQgDAGgEAEQgEAEgGADIgNAGIgLABQgJAAgIgCgAABACQgKABgIADQgIAEgFAEQgDAGAAAHQAAAEABAEQACAEAEACIAJAFQAFABAGAAQAHAAAIgDQAHgDAGgEQAGgGADgGQAEgHAAgHIAAgLIgEAAIgeACg");
	this.shape_33.setTransform(7.5,38);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#193670").s().p("AAoA3QgFAAAAgFIAAg3QAAgJgCgHQgCgHgEgGQgFgFgGgCQgGgDgIAAQgFAAgGACQgGACgEADIgJAIIgGAKIAABFQAAAFgFAAIgCAAQgEAAAAgFIAAhmIADgBQAEAAABACQACADAAAGIAAAKIAHgJIAJgHIALgFQAGgBAFAAQAKAAAJADQAIAEAFAGQAGAGACAJQADAJAAALIAAA4QAAAFgFAAg");
	this.shape_34.setTransform(50.8,14.9);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#193670").s().p("AgWA3QgEAAgBgFIAAhmIAEgBQAEAAABACQACADAAAGIAAAOIAEgMQAEgFAEgDQADgDADgCQAFgBAFAAQAGAAAFACQAFADAAAEQAAAAgBABQAAABAAAAQAAABAAAAQgBABAAAAIgCACQgFgFgIAAQgHAAgEAEQgFADgEAHQgDAGgCAJQgBAJAAAJIAAAvQgBAFgFAAg");
	this.shape_35.setTransform(41.5,14.9);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#193670").s().p("AgWA2QgHgCgGgEQgFgEgCgGQgDgFAAgHQAAgJAFgHQAFgGAJgEQAKgCAPgDQAMgCAVAAIACAAIAAgFQAAgJgCgGQgCgFgFgEQgEgEgGgDQgGgCgIAAQgFAAgGABQgGACgEADQgJAGgFAIQgGAAAAgFQAAgGAGgGQAGgFAIgEQALgEALAAQAKAAAIADQAIACAFAGQAHAFACAJQADAHABAKIAABCIgFABQgDAAgBgCQgDgCAAgGIAAgLQgCAEgEAFQgFAEgGAEIgMAEIgLACQgKAAgGgCgAABABQgKACgJAEQgHACgFAGQgDAFAAAGQAAAFACAEQACAEADADIAJADQAFACAGAAQAHAAAIgDQAIgDAFgFQAGgEADgHQAEgHgBgIIAAgKIgCAAIgfABg");
	this.shape_36.setTransform(31,15);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#193670").s().p("AgSA0QgKgEgHgHQgIgIgEgKQgEgLAAgMQAAgKAEgKQAEgLAIgIQAHgHAKgFQAKgEAKAAQALAAAJADQAJAFAHAGQAGAIAEAJQAEAKAAAMIAAABQAAACgFAAIhXAAQAAAKAEAIQADAJAGAGQAGAGAIAEQAIACAIAAQAIAAAHgCQAGgBAFgDQAIgGAFgJIADAAQADADAAADQAAAFgHAHQgFAGgKADQgKAEgNAAQgKAAgLgEgAAogHQAAgIgDgIQgDgHgFgFQgFgFgHgDQgHgCgIAAQgHAAgHACQgHADgGAFQgGAGgDAHQgEAHgBAIIBPAAIAAAAg");
	this.shape_37.setTransform(19.6,15);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#193670").s().p("AglBKQgHAAAAgHIAAiHQAAgFAGAAIABAAQAFAAAAAFIAACEIBHAAQAGAAgBAFIAAAAQABAFgGAAg");
	this.shape_38.setTransform(8.3,12.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,142,119);


(lib.CTA_btn = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#00FFFF").s().p("A6PV3MAAAgruMA0eAAAMAAAArug");
	this.shape.setTransform(168,140);
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(3).to({_off:false},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = null;


(lib.border336x280 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,0,3).p("EgMaguyIY1AAMAAABdlI41AAg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-80.5,-300.5,161,601);


(lib.blocks = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#005A8C").s().p("AjyDwIAAnfIHlAAIAAHfg");
	this.shape.setTransform(6,87.3);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#557C6B").s().p("AjyDqIAAnTIHlAAIAAHTg");
	this.shape_1.setTransform(6,39.7);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#92AF2B").s().p("AjyDzIAAnlIHlAAIAAHlg");
	this.shape_2.setTransform(6,-8.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-18.3,-32.4,48.7,143.8);


(lib.LogoLockkup160x600 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.blocks();
	this.instance.setTransform(147.5,283.9,1,1,90,0,0,150,12.5);

	this.instance_1 = new lib.TEC_logostackrev("synched",0);
	this.instance_1.setTransform(200.6,48.3,0.576,0.576,0,0,0,181.3,32.2);

	this.shape = new cjs.Shape();
	this.shape.graphics.f("#193670").s().p("AxCRYIAAk6IgEAAIAA7ZQAAiRCIgJIAAgBId5AAIAAABQCIAJAACRIAAENQADAUAAAaIAAbYg");
	this.shape.setTransform(109.5,54.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape},{t:this.instance_1},{t:this.instance}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,-57,219,222.4);


// stage content:
(lib.TEC201609_Garden_160x600_AdR = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.clickthru_btn.on("click", function(evt){
		  window.open(clickTag, "_blank");
		});
	}
	this.frame_125 = function() {
		this.stop();
		 
		this.replay_btn.addEventListener("click", fl_ClickToGoToAndPlayFromFrame.bind(this));
		function fl_ClickToGoToAndPlayFromFrame() 
		{
		this.gotoAndPlay(1);
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(125).call(this.frame_125).wait(1));

	// replay btn
	this.replay_btn = new lib.replaybtn();
	this.replay_btn.setTransform(141,396,0.75,0.75);
	this.replay_btn._off = true;
	new cjs.ButtonHelper(this.replay_btn, 0, 1, 2, false, new lib.replaybtn(), 3);

	this.timeline.addTween(cjs.Tween.get(this.replay_btn).wait(125).to({_off:false},0).wait(1));

	// cta btn
	this.clickthru_btn = new lib.CTA_btn();
	this.clickthru_btn.setTransform(0,-0.2,0.476,2.143,0,0,0,-0.1,-0.1);
	new cjs.ButtonHelper(this.clickthru_btn, 0, 1, 2, false, new lib.CTA_btn(), 3);

	this.timeline.addTween(cjs.Tween.get(this.clickthru_btn).wait(126));

	// border
	this.instance = new lib.border336x280();
	this.instance.setTransform(80,300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(126));

	// head1
	this.instance_1 = new lib.head1("synched",0);
	this.instance_1.setTransform(12,186);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1).to({_off:false},0).wait(117).to({startPosition:0},0).to({y:154},5).wait(3));

	// sub1
	this.instance_2 = new lib.sub1("synched",0);
	this.instance_2.setTransform(657,1261.5,5,5,0,0,0,131.4,220.7);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(66).to({_off:false},0).to({scaleX:1,scaleY:1,x:143.4,y:537.7},5).wait(47).to({startPosition:0},0).to({y:503.7},5).wait(3));

	// logo block
	this.instance_3 = new lib.LogoLockkup160x600();
	this.instance_3.setTransform(124.5,641.5,0.83,0.83,0,0,0,150,50);
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(118).to({_off:false},0).to({y:504.5},5).wait(3));

	// pic
	this.instance_4 = new lib.pic();
	this.instance_4.setTransform(-110.9,0,0.85,0.85);

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(118).to({scaleX:0.7,scaleY:0.7,x:-81.9},5).wait(3));

	// bkgd
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("EgMfAu4MAAAhdvIY/AAMAAABdvg");
	this.shape.setTransform(80,300);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(126));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-152.5,300,437.9,600);

})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{});
var lib, images, createjs, ss;